import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {transformSync} from 'esbuild';
import {backgroundImageStamp,cleanBackgroundImagePreferences,validateBackgroundImageBytes,MAX_BACKGROUND_IMAGE_BYTES,type BackgroundImagePreferences} from '../src/background-image';
import {cleanPluginSettings} from '../src/plugin-settings';
const source=readFileSync('src/main.ts','utf8'),start=source.indexOf('  backgroundImageResource('),end=source.indexOf('  openPaperSettings(){',start),saveStart=source.indexOf('  async savePreferences() {'),saveEnd=source.indexOf('  async session(',saveStart);assert.ok(start>=0&&end>start&&saveStart>=0&&saveEnd>saveStart);
const png=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aSf8AAAAASUVORK5CYII=','base64'));
const digest=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const copy=(bytes:Uint8Array)=>Uint8Array.from(bytes).buffer;
function deferred<T=void>(){let resolve!:(value:T)=>void,reject!:(error:Error)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
function fixture(raw:Record<string,unknown>={}){
 const calls={created:0,opened:0,focused:0,applied:0,dock:0,writes:[] as unknown[],files:[] as {path:string;bytes:Uint8Array}[],reads:[] as string[],mkdirs:[] as string[],resources:[] as string[]};
 const files=new Map<string,Uint8Array>(),directories=new Set<string>(),hooks={exists:undefined as undefined|((path:string,result:boolean)=>Promise<boolean>),read:undefined as undefined|((path:string,value:ArrayBuffer)=>Promise<ArrayBuffer>),write:undefined as undefined|((path:string,bytes:ArrayBuffer)=>Promise<void>),save:undefined as undefined|(()=>Promise<void>)};
 class BoardView{applyPreferences(){calls.applied++;}}
 class BackgroundImageModal{modalEl={isConnected:false,querySelector:()=>({focus:()=>calls.focused++})};constructor(_app:unknown,readonly host:{preferences:()=>BackgroundImagePreferences;resource:(path:string)=>string;save:(prefs:BackgroundImagePreferences,file?:unknown)=>Promise<void>}){calls.created++;}open(){this.modalEl.isConnected=true;calls.opened++;}close(){this.modalEl.isConnected=false;}}
 const deps={BackgroundImageModal,BoardView,VIEW:'board',cleanBackgroundImagePreferences,backgroundImageStamp,validateBackgroundImageBytes,MAX_BACKGROUND_IMAGE_BYTES,createHash,normalizePath:(path:string)=>path.replace(/\/+/g,'/')};
 const Plugin=new Function(...Object.keys(deps),transformSync(`class Plugin{${source.slice(start,end)}${source.slice(saveStart,saveEnd)}}return Plugin;`,{loader:'ts'}).code)(...Object.values(deps));
 const plugin=new Plugin(),settings=cleanPluginSettings({canvasBackground:'grid',backgroundImagePath:'assets/old.png',backgroundImageFit:'cover',backgroundImageOpacity:70,accent:'forest',...raw});
 const adapter={exists:async(path:string)=>{const result=files.has(path)||directories.has(path);return hooks.exists?hooks.exists(path,result):result;},mkdir:async(path:string)=>{calls.mkdirs.push(path);directories.add(path);},readBinary:async(path:string)=>{calls.reads.push(path);const bytes=files.get(path);if(!bytes)throw Error('missing file');const value=copy(bytes);return hooks.read?hooks.read(path,value):value;},writeBinary:async(path:string,bytes:ArrayBuffer)=>{await hooks.write?.(path,bytes);calls.files.push({path,bytes:new Uint8Array(bytes)});files.set(path,new Uint8Array(bytes));},getResourcePath:(path:string)=>{calls.resources.push(path);return `app://vault/${encodeURIComponent(path)}`;}};
 Object.assign(plugin,{settings,manifest:{id:'thoughtspace'},backgroundImagesClosed:false,app:{vault:{configDir:'.obsidian-local',adapter},workspace:{getLeavesOfType:(type:string)=>{assert.equal(type,'board');return[{view:new BoardView()},{view:{}},{view:new BoardView()}];}}},saveData:async(value:unknown)=>{calls.writes.push(JSON.parse(JSON.stringify(value)));await hooks.save?.();},refreshDock:()=>calls.dock++});
 const modal=plugin.openBackgroundImageSettings(),path=`.obsidian-local/plugins/thoughtspace/backgrounds/${digest(png)}.png`;files.set('assets/old.png',Uint8Array.from(png));
 return{plugin,settings,calls,hooks,files,directories,modal,host:modal.host,path};
}
function upload(bytes=png){return{name:'../../original.JPG',size:bytes.byteLength,arrayBuffer:async()=>copy(bytes)};}
const prefs=(values:Partial<BackgroundImagePreferences>={})=>cleanBackgroundImagePreferences({backgroundImagePath:'assets/old.png',backgroundImageFit:'tile',backgroundImageOpacity:35,...values});
const tick=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};

test('background settings reuse one open native dialog and preferences are isolated copies',()=>{const f=fixture(),again=f.plugin.openBackgroundImageSettings();assert.equal(again,f.modal);assert.equal(f.calls.created,1);assert.equal(f.calls.focused,1);const read=f.host.preferences();read.backgroundImageOpacity=1;assert.equal(f.settings.backgroundImageOpacity,70);f.modal.close();assert.notEqual(f.plugin.openBackgroundImageSettings(),f.modal);});
test('resources accept only vault-relative raster references and never forward URLs or traversal',()=>{const f=fixture();for(const path of ['../x.png','/x.png','https://example.com/x.png','file:///x.png','assets/x.svg','assets/%2e%2e/x.png','assets/../../x.png','assets/x.png?secret=1','assets/x.png\n'])assert.equal(f.plugin.backgroundImageResource(path),'',path);assert.equal(f.calls.resources.length,0);const path='资料/背景 米黄.png';assert.equal(f.host.resource(path),`app://vault/${encodeURIComponent(path)}`);assert.deepEqual(f.calls.resources,[path]);});
test('image import copies validated bytes into a digest path and never overwrites the selected source path',async()=>{const f=fixture(),original=copy(f.files.get('assets/old.png')!);await f.host.save(prefs(),upload());assert.equal(f.calls.files.length,1);assert.equal(f.calls.files[0].path,f.path);assert.deepEqual(f.calls.files[0].bytes,png);assert.deepEqual(copy(f.files.get('assets/old.png')!),original);assert.equal(f.settings.backgroundImagePath,f.path);assert.equal(f.settings.canvasBackground,'image');assert.equal(f.calls.writes.length,1);assert.equal(f.calls.applied,2);assert.equal(f.calls.dock,1);assert.equal(f.settings.accent,'forest');});
test('identical content reuses the verified digest file regardless of original name without another binary write',async()=>{const f=fixture();f.files.set(f.path,Uint8Array.from(png));await f.host.save(prefs(),upload());assert.equal(f.calls.files.length,0);assert.deepEqual(f.calls.reads,[f.path]);assert.equal(f.settings.backgroundImagePath,f.path);assert.equal(f.calls.writes.length,1);});
test('a corrupted or replaced digest file is rejected and kept intact instead of overwritten or reused',async()=>{const f=fixture(),changed=new Uint8Array([1,2,3]);f.files.set(f.path,changed);const before=JSON.stringify(f.settings);await assert.rejects(f.host.save(prefs(),upload()),/内容发生变化.*未覆盖/);assert.deepEqual(f.files.get(f.path),changed);assert.equal(f.calls.files.length,0);assert.equal(f.calls.writes.length,0);assert.equal(JSON.stringify(f.settings),before);});
test('incomplete imports cannot change settings before their binary copy finishes',async()=>{const f=fixture(),pending=deferred(),before=JSON.stringify(f.settings);f.hooks.write=()=>pending.promise;const save=f.host.save(prefs(),upload());await tick();assert.equal(f.calls.files.length,0);assert.equal(f.calls.writes.length,0);assert.equal(JSON.stringify(f.settings),before);pending.resolve();await save;assert.equal(f.calls.files.length,1);assert.equal(f.settings.backgroundImagePath,f.path);});
test('failed binary imports keep settings and original files untouched',async()=>{const f=fixture(),before=JSON.stringify(f.settings),original=copy(f.files.get('assets/old.png')!);f.hooks.write=async()=>{throw Error('磁盘空间不足');};await assert.rejects(f.host.save(prefs(),upload()),/磁盘空间不足/);assert.equal(JSON.stringify(f.settings),before);assert.equal(f.calls.writes.length,0);assert.deepEqual(copy(f.files.get('assets/old.png')!),original);});
test('empty oversized or disguised non-image uploads fail before files or preferences are written',async()=>{for(const file of [upload(new Uint8Array()),upload(new TextEncoder().encode('<svg onload="alert(1)"></svg>')),{size:MAX_BACKGROUND_IMAGE_BYTES+1,arrayBuffer:()=>{throw Error('should not read');}}]){const f=fixture(),before=JSON.stringify(f.settings);await assert.rejects(f.host.save(prefs(),file));assert.equal(JSON.stringify(f.settings),before);assert.equal(f.calls.files.length,0);assert.equal(f.calls.writes.length,0);}});
test('a saved image path must exist before applying and a missing file leaves the active background unchanged',async()=>{const f=fixture(),before=JSON.stringify(f.settings);await assert.rejects(f.host.save(prefs({backgroundImagePath:'assets/missing.png'})),/已不存在/);assert.equal(JSON.stringify(f.settings),before);assert.equal(f.calls.writes.length,0);});
test('background changes and unloading while bytes are read reject the old preferences',async()=>{for(const change of [(f:ReturnType<typeof fixture>)=>{f.settings.canvasBackground='paper';},(f:ReturnType<typeof fixture>)=>{f.settings.backgroundImageOpacity=12;},(f:ReturnType<typeof fixture>)=>{f.plugin.backgroundImagesClosed=true;}]){const f=fixture(),pending=deferred<ArrayBuffer>(),save=f.host.save(prefs(),{size:png.byteLength,arrayBuffer:()=>pending.promise});change(f);const expected=JSON.stringify(f.settings);pending.resolve(copy(png));await assert.rejects(save,/已关闭|已.*改变/);assert.equal(JSON.stringify(f.settings),expected);assert.equal(f.calls.writes.length,0);}});
test('the final async existence check cannot overwrite a newer background or unload',async()=>{for(const change of [(f:ReturnType<typeof fixture>)=>{f.settings.canvasBackground='plain';},(f:ReturnType<typeof fixture>)=>{f.settings.backgroundImageFit='contain';},(f:ReturnType<typeof fixture>)=>{f.plugin.backgroundImagesClosed=true;}]){const f=fixture(),pending=deferred<boolean>();f.hooks.exists=(path,result)=>path==='assets/old.png'?pending.promise:Promise.resolve(result);const save=f.host.save(prefs());await tick();change(f);const expected=JSON.stringify(f.settings);pending.resolve(true);await assert.rejects(save,/背景已改变/);assert.equal(JSON.stringify(f.settings),expected);assert.equal(f.calls.writes.length,0);}});
test('an unloaded plugin rejects an old dialog save before reading the picked file',async()=>{const f=fixture();f.plugin.backgroundImagesClosed=true;await assert.rejects(f.host.save(prefs(),{size:10,arrayBuffer:()=>{throw Error('must not read');}}),/插件已关闭/);assert.equal(f.calls.writes.length,0);assert.equal(f.calls.files.length,0);});
test('preference persistence failure rolls back only background settings while preserving unrelated newer edits',async()=>{const f=fixture(),before={...cleanBackgroundImagePreferences(f.settings),canvasBackground:f.settings.canvasBackground},pending=deferred();f.hooks.save=()=>pending.promise;const save=f.host.save(prefs());await tick();assert.equal(f.settings.canvasBackground,'image');f.settings.accent='blue';pending.reject(Error('设置写入失败'));await assert.rejects(save,/设置写入失败/);assert.deepEqual({...cleanBackgroundImagePreferences(f.settings),canvasBackground:f.settings.canvasBackground},before);assert.equal(f.settings.accent,'blue');assert.equal(f.calls.applied,2);assert.equal(f.calls.dock,0);});
test('failed old persistence cannot roll back newer image preferences or a newer background mode',async()=>{for(const change of [(f:ReturnType<typeof fixture>)=>{f.settings.backgroundImageOpacity=9;},(f:ReturnType<typeof fixture>)=>{f.settings.canvasBackground='paper';}]){const f=fixture(),pending=deferred();f.hooks.save=()=>pending.promise;const save=f.host.save(prefs());await tick();change(f);const expected=JSON.stringify(f.settings);pending.reject(Error('旧写入失败'));await assert.rejects(save,/旧写入失败/);assert.equal(JSON.stringify(f.settings),expected);assert.equal(f.calls.applied,0);}});
test('clearing the selected background switches to plain and retains asset files for reuse',async()=>{const f=fixture({canvasBackground:'image'}),before=[...f.files.entries()];await f.host.save(prefs({backgroundImagePath:''}));assert.equal(f.settings.backgroundImagePath,'');assert.equal(f.settings.canvasBackground,'plain');assert.deepEqual([...f.files.entries()],before);assert.equal(f.calls.files.length,0);assert.equal(f.calls.writes.length,1);assert.equal(f.calls.applied,2);});
