import test,{TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import {cleanBackgroundImagePreferences,backgroundImageStamp,MAX_BACKGROUND_IMAGE_BYTES,type BackgroundImagePreferences} from '../src/background-image';

type Options={cls?:string;text?:string;attr?:Record<string,string>;type?:string;value?:string};
function deferred(){let resolve!:()=>void,reject!:(error:Error)=>void;const promise=new Promise<void>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
class Document {images:{pending:ReturnType<typeof deferred>;image:{src:string;decoding:string;naturalWidth:number;naturalHeight:number;decode:()=>Promise<void>}}[]=[];createElement(tag:string){assert.equal(tag,'img');const pending=deferred(),image={src:'',decoding:'',naturalWidth:240,naturalHeight:120,decode:()=>pending.promise};this.images.push({pending,image});return image;}}
class Element {
 children:Element[]=[];classes=new Set<string>();attributes:Record<string,string>={};styles:Record<string,string>={};style={setProperty:(key:string,value:string)=>{this.styles[key]=value;}};value='';disabled=false;hidden=false;files?:unknown[];writes=0;private text='';onclick?:()=>void;onchange?:()=>void;oninput?:()=>void;onkeydown?:((event:any)=>void)|null;listeners:Record<string,(event:any)=>void>={};
 constructor(readonly tagName:string,readonly ownerDocument:Document,options:Options|string={}){const opts=typeof options==='string'?{cls:options}:options;this.text=opts.text||'';this.attributes={...opts.attr};this.value=opts.value||'';for(const cls of (opts.cls||'').split(/\s+/).filter(Boolean))this.classes.add(cls);}
 get textContent():string{return this.text+this.children.map(child=>child.textContent).join('');}
 createEl(tag:string,options:Options|string={}){this.writes++;const child=new Element(tag.toUpperCase(),this.ownerDocument,options);this.children.push(child);return child;}createDiv(options:Options|string={}){return this.createEl('div',options);}createSpan(options:Options|string={}){return this.createEl('span',options);}
 setCssProps(props:Record<string,string>){Object.assign(this.styles,props);}
 addClass(...names:string[]){for(const name of names)this.classes.add(name);}setAttribute(name:string,value:string){this.writes++;this.attributes[name]=value;}getAttribute(name:string){return this.attributes[name]??null;}
 setText(text:string){this.writes++;this.text=text;this.children=[];}empty(){this.writes++;this.children=[];this.text='';}click(){if(!this.disabled)this.onclick?.();}addEventListener(type:string,run:(event:any)=>void){this.listeners[type]=run;}
 matches(selector:string){if(selector.startsWith('.'))return this.classes.has(selector.slice(1));const attr=/^\[([^=]+)=([^\]]+)\]$/.exec(selector);return attr?this.getAttribute(attr[1])===attr[2]:this.tagName===selector.toUpperCase();}
 querySelectorAll(selector:string):Element[]{return this.children.flatMap(child=>[...(child.matches(selector)?[child]:[]),...child.querySelectorAll(selector)]);}querySelector(selector:string){return this.querySelectorAll(selector)[0];}
}
class Modal {readonly document=new Document();readonly modalEl=new Element('DIV',this.document);readonly titleEl=this.modalEl.createEl('h2');readonly contentEl=this.modalEl.createDiv();closeCount=0;constructor(readonly app:unknown){}close(){this.closeCount++;(this as unknown as {onClose:()=>void}).onClose();}}
const source=readFileSync('src/background-image-view.ts','utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');
const notices:string[]=[];
const BackgroundImageModal=new Function('Modal','Notice','setIcon','themeSurface','cleanBackgroundImagePreferences','backgroundImageStamp','MAX_BACKGROUND_IMAGE_BYTES',transformSync(source+'\nreturn BackgroundImageModal;',{loader:'ts'}).code)(Modal,class{constructor(message:string){notices.push(message);}},()=>{},()=>{},cleanBackgroundImagePreferences,backgroundImageStamp,MAX_BACKGROUND_IMAGE_BYTES);
function fixture(t:TestContext,initial:Partial<BackgroundImagePreferences>={backgroundImagePath:'Images/paper.png'}){const oldCreate=URL.createObjectURL,oldRevoke=URL.revokeObjectURL,created:string[]=[],revoked:string[]=[];URL.createObjectURL=()=>{const url=`blob:test-${created.length}`;created.push(url);return url;};URL.revokeObjectURL=url=>{revoked.push(url);};t.after(()=>{URL.createObjectURL=oldCreate;URL.revokeObjectURL=oldRevoke;});let prefs=cleanBackgroundImagePreferences(initial),save=(next:BackgroundImagePreferences,_file?:File)=>{prefs={...next};return Promise.resolve();};const writes:{preferences:BackgroundImagePreferences;file?:File}[]=[],host={preferences:()=>prefs,resource:(path:string)=>`app://vault/${path}`,save:(preferences:BackgroundImagePreferences,file?:File)=>{writes.push({preferences:{...preferences},file});return save(preferences,file);}};
 const modal=new BackgroundImageModal({},host);modal.onOpen();const root=modal.contentEl as Element;
 return{modal,root,host,writes,created,revoked,get prefs(){return prefs;},external:(next:Partial<BackgroundImagePreferences>)=>{prefs={...prefs,...next};},setSave:(next:typeof save)=>{save=next;},button:(label:string)=>root.querySelectorAll('button').find(button=>button.getAttribute('aria-label')===label)!,input:()=>root.querySelector('[aria-label=选择本地背景图片]')!,slider:()=>root.querySelector('[aria-label=背景图片浓度]')!,preview:()=>root.querySelector('.ts-background-preview')!,status:()=>root.querySelector('.ts-background-settings-status')!,pick:(name='local.png',size=1024,type='image/png')=>modal.imagePick({name,size,type} as File),image:(index=0)=>modal.document.images[index] as Document['images'][number]};
}
const tick=()=>new Promise<void>(resolve=>setImmediate(resolve));
test('opening uses the stored resource without writes and controls alter only a local preview',t=>{const f=fixture(t),before={...f.prefs};assert.match(f.preview().styles['--ts-background-image'],/app:\/\/vault\/Images\/paper.png/);assert.equal(f.button('应用').disabled,false);f.button('平铺').click();f.slider().value='0';f.slider().oninput?.();assert.equal(f.preview().styles['--ts-background-image-fit'],'auto');assert.equal(f.preview().styles['--ts-background-image-repeat'],'repeat');assert.equal(f.preview().styles['--ts-background-image-opacity'],'0');assert.deepEqual(f.prefs,before);assert.equal(f.writes.length,0);});
test('valid local decoding previews the image and passes its file only on Apply',async t=>{const f=fixture(t),picking=f.pick('summer.webp',2024,'image/webp');assert.equal(f.button('应用').disabled,true);assert.equal(f.created.length,1);f.image().pending.resolve();await picking;assert.match(f.preview().styles['--ts-background-image'],/blob:test-0/);assert.equal(f.writes.length,0);f.button('完整显示').click();f.button('应用').click();await tick();assert.equal(f.writes.length,1);assert.equal(f.writes[0].file?.name,'summer.webp');assert.equal(f.writes[0].preferences.backgroundImageFit,'contain');assert.equal(f.modal.closeCount,1);assert.deepEqual(f.revoked,['blob:test-0']);});
test('cancel after replacing an image does not persist and releases the preview URL',async t=>{const f=fixture(t),before={...f.prefs},picking=f.pick();f.image().pending.resolve();await picking;f.button('取消').click();assert.deepEqual(f.prefs,before);assert.equal(f.writes.length,0);assert.deepEqual(f.revoked,f.created);assert.equal(f.root.children.length,0);});
test('unsupported, oversized and empty files reject before allocating a URL',async t=>{const f=fixture(t);await f.pick('image.svg',10,'image/svg+xml');assert.match(f.status().textContent,/请选择/);await f.pick('image.png',20*1024*1024+1);assert.match(f.status().textContent,/超过/);await f.pick('image.png',0);assert.match(f.status().textContent,/为空/);assert.equal(f.created.length,0);assert.equal(f.writes.length,0);});
test('a failed replacement decode preserves the last valid preview and can be retried',async t=>{const f=fixture(t),first=f.pick('first.png');f.image().pending.resolve();await first;const failing=f.pick('broken.png');f.image(1).pending.reject(Error('decode failed'));await failing;assert.match(f.status().textContent,/无法读取/);assert.match(f.preview().styles['--ts-background-image'],/blob:test-0/);assert.deepEqual(f.revoked,['blob:test-1']);f.button('应用').click();await tick();assert.equal(f.writes[0].file?.name,'first.png');});
test('out of order image decodes cannot overwrite a more recent choice',async t=>{const f=fixture(t),first=f.pick('old.png'),second=f.pick('new.png');f.image(1).pending.resolve();await second;f.image().pending.resolve();await first;assert.match(f.preview().styles['--ts-background-image'],/blob:test-1/);f.button('应用').click();await tick();assert.equal(f.writes[0].file?.name,'new.png');assert.deepEqual(new Set(f.revoked),new Set(f.created));assert.equal(f.revoked.length,2);});
test('removing while decoding invalidates that decode and applies removal without a file',async t=>{const f=fixture(t),picking=f.pick();f.button('移除').click();f.image().pending.resolve();await picking;assert.equal(f.preview().styles['--ts-background-image'],'none');f.button('应用').click();await tick();assert.equal(f.writes.length,1);assert.equal(f.writes[0].preferences.backgroundImagePath,'');assert.equal(f.writes[0].file,undefined);assert.deepEqual(f.revoked,f.created);});
test('closing while decoding revokes pending URLs and never writes detached status',async t=>{const f=fixture(t),picking=f.pick(),status=f.status();f.modal.close();const writes=status.writes;f.image().pending.reject(Error('late decode'));await picking;assert.equal(status.writes,writes);assert.deepEqual(f.revoked,f.created);assert.equal(f.root.children.length,0);assert.equal(f.writes.length,0);});
test('stale preferences block apply; reloading discards local images and accepts current settings',async t=>{const f=fixture(t),picking=f.pick();f.image().pending.resolve();await picking;f.external({backgroundImageOpacity:67});f.button('应用').click();await tick();assert.equal(f.writes.length,0);assert.match(f.status().textContent,/其他窗口/);assert.equal(f.button('应用').disabled,true);f.button('载入当前设置').click();assert.equal(f.slider().value,'67');assert.equal(f.button('应用').disabled,false);assert.deepEqual(f.revoked,f.created);assert.equal(f.status().textContent,'');});
test('pending saves disable mutation and duplicate apply while allowing close',async t=>{const f=fixture(t),wait=deferred();f.setSave(()=>wait.promise);f.button('平铺').click();f.button('应用').click();f.button('应用').click();assert.equal(f.writes.length,1);assert.equal(f.button('平铺').disabled,true);assert.equal(f.slider().disabled,true);const status=f.status();f.button('取消').click();const writes=status.writes;wait.resolve();await tick();assert.equal(status.writes,writes);assert.equal(f.modal.closeCount,1);assert.equal(f.root.children.length,0);});
test('failed saves retain the decoded image for retry instead of leaking or clearing it',async t=>{const f=fixture(t),picking=f.pick();f.image().pending.resolve();await picking;f.setSave(()=>Promise.reject(Error('disk full')));f.button('应用').click();await tick();assert.match(f.status().textContent,/可以重试/);assert.equal(f.button('应用').disabled,false);assert.equal(f.revoked.length,0);f.setSave(()=>Promise.resolve());f.button('应用').click();await tick();assert.equal(f.writes.length,2);assert.equal(f.writes[1].file?.name,'local.png');assert.equal(f.modal.closeCount,1);assert.deepEqual(f.revoked,f.created);});
test('save rejection after closing emits a notice without rebuilding modal content',async t=>{const f=fixture(t),wait=deferred(),before=notices.length;f.setSave(()=>wait.promise);f.button('平铺').click();f.button('应用').click();f.modal.close();wait.reject(Error('lost storage'));await tick();assert.equal(f.root.children.length,0);assert.equal(notices.length,before+1);assert.match(notices.at(-1)!,/lost storage/);});
test('keyboard Apply respects composition and native Modal selection state',async t=>{const f=fixture(t);f.modal.selection={anchorNode:'native editor'};f.button('平铺').click();const key=(composing:boolean)=>{const event={key:'Enter',metaKey:true,ctrlKey:false,altKey:false,shiftKey:false,isComposing:composing,keyCode:composing?229:0,preventDefault(){}};f.root.onkeydown?.(event);};key(true);assert.equal(f.writes.length,0);key(false);await tick();assert.equal(f.writes.length,1);assert.deepEqual(f.modal.selection,{anchorNode:'native editor'});});
test('invalid decoded dimensions reject before replacing the existing source',async t=>{const f=fixture(t),picking=f.pick();f.image().image.naturalWidth=0;f.image().pending.resolve();await picking;assert.match(f.status().textContent,/尺寸无效/);assert.match(f.preview().styles['--ts-background-image'],/Images\/paper.png/);assert.deepEqual(f.revoked,f.created);assert.equal(f.button('应用').disabled,false);});
test('an unchanged stored image can be applied again after another background mode was selected',async t=>{const f=fixture(t),before={...f.prefs};assert.equal(f.button('应用').disabled,false);f.button('应用').click();await tick();assert.equal(f.writes.length,1);assert.deepEqual(f.writes[0].preferences,before);assert.equal(f.writes[0].file,undefined);});
test('without any saved or newly selected image Apply stays disabled until a file is decoded',async t=>{const f=fixture(t,{backgroundImagePath:''});f.button('平铺').click();f.slider().value='80';f.slider().oninput?.();assert.equal(f.button('应用').disabled,true);const picking=f.pick();f.image().pending.resolve();await picking;assert.equal(f.button('应用').disabled,false);f.button('移除').click();assert.equal(f.button('应用').disabled,true);assert.equal(f.writes.length,0);});
test('read failures disable all mutation controls while keeping an explicit reload path',async t=>{const f=fixture(t),read=f.host.preferences;f.host.preferences=()=>{throw Error('unavailable');};f.modal.imageLoad();assert.match(f.status().textContent,/无法读取背景设置/);for(const name of ['选择图片','移除','铺满','完整显示','平铺','应用'])assert.equal(f.button(name).disabled,true,name);assert.equal(f.slider().disabled,true);assert.equal(f.input().disabled,true);assert.equal(f.button('载入当前设置').hidden,false);assert.equal(f.button('载入当前设置').disabled,false);await f.pick();assert.equal(f.created.length,0);f.host.preferences=read;f.button('载入当前设置').click();assert.equal(f.button('平铺').disabled,false);assert.equal(f.button('应用').disabled,false);assert.equal(f.status().textContent,'');});
test('reopening the same modal replaces its key handler and closing removes it',async t=>{const f=fixture(t),old=f.root.onkeydown;assert.ok(old);f.modal.close();assert.equal(f.root.onkeydown,null);f.modal.onOpen();assert.notEqual(f.root.onkeydown,old);(f.root as Element).onkeydown?.({key:'Enter',metaKey:true,ctrlKey:false,altKey:false,shiftKey:false,isComposing:false,keyCode:0,preventDefault(){}});await tick();assert.equal(f.writes.length,1);assert.equal(f.root.onkeydown,null);});
test('large decoded images are rejected before becoming the active preview',async t=>{const f=fixture(t),picking=f.pick();f.image().image.naturalWidth=10000;f.image().image.naturalHeight=5000;f.image().pending.resolve();await picking;assert.match(f.status().textContent,/4000 万像素/);assert.match(f.preview().styles['--ts-background-image'],/Images\/paper.png/);assert.deepEqual(f.revoked,f.created);});
test('stored hashed asset names stay out of the user-facing picker',t=>{const hash='a'.repeat(64),f=fixture(t,{backgroundImagePath:`ThoughtSpace/背景/${hash}.png`});assert.match(f.root.textContent,/已保存的背景图片/);assert.doesNotMatch(f.root.textContent,new RegExp(hash));});
