import {boardHostDeps} from './board-host-deps';
import {SharedOpen} from '../src/view-opening';
import {emptyBoard} from '../src/model';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
const source=readFileSync('src/main.ts','utf8');
const take=(from:string,to:string)=>source.slice(source.indexOf(from),source.indexOf(to,source.indexOf(from)));
function gate<T=void>(){let resolve!:(value:T)=>void,reject!:(error:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
const tick=async()=>{for(let i=0;i<10;i++)await Promise.resolve();};
function fixture(action='locate-native'){
 const doc={defaultView:{closed:false},body:{appendChild(el:any){el.ownerDocument=doc;}}},otherDoc={defaultView:{closed:false},body:{appendChild(el:any){el.ownerDocument=otherDoc;}}},file={path:'Boards/Protected.md'},recovery={path:'Boards/Recovery.md'},files=new Map([[file.path,file],[recovery.path,recovery]]);
 class NativeView {}
 class MarkdownView extends NativeView {file=file;draft='Unsaved native input';saving=true;saveAgain=true;save(){throw Error('Status navigation must not save a native page');}}
 const fileListeners=new Set<(file:any)=>void>();const pickers:any[]=[],focuses:any[]=[],revealed:any[]=[],opens:any[]=[],listeners=new Set<(leaf:any)=>void>(),leaves:any[]=[];
 class FuzzySuggestModal {containerEl={ownerDocument:doc};baseOpens=0;constructor(_app:unknown){pickers.push(this);}onOpen(){this.baseOpens++;if((this as any).hostError)throw (this as any).hostError;if((this as any).hostReject)return Promise.reject((this as any).hostReject);}setPlaceholder(text:string){(this as any).placeholder=text;}open(){}onClose(){}close(){this.onClose();}}
 const module={exports:{} as any};new Function('require','module','exports',transformSync(readFileSync('src/board-save-feedback-native.ts','utf8'),{loader:'ts',format:'cjs'}).code)(()=>({FuzzySuggestModal}),module,module.exports);
 const NativeBoardEditorPicker=module.exports.NativeBoardEditorPicker;
 const nativeBoardEditorLeaves=()=>leaves.filter(leaf=>leaf.getViewState().state.file===file.path);
 const View=new Function('View','nativeBoardEditorLeaves','NativeBoardEditorPicker','report','MarkdownView',transformSync('class BoardView{'+take('  private saveFeedbackSequence=','  private scheduleRender(')+'};return BoardView',{loader:'ts'}).code)(NativeView,nativeBoardEditorLeaves,NativeBoardEditorPicker,()=>{},MarkdownView);
 let active:any,load:(()=>Promise<void>)|undefined,reveal:(()=>Promise<void>)|undefined,open:((...args:any[])=>Promise<any>)|undefined;
 function makeLeaf(view:any,document=doc,deferred=false){const leaf:any={view,isDeferred:deferred,getContainer:()=>({doc:document,win:document.defaultView}),getViewState:()=>({type:view instanceof MarkdownView?'markdown':'thoughtspace-board',state:{file:view.file?.path||''}}),async loadIfDeferred(){await load?.();this.isDeferred=false;}};view.leaf=leaf;return leaf;}
 const workspace={getActiveViewOfType:()=>active?.view,on:(event:string,callback:(leaf:any)=>void)=>{(event==='file-open'?fileListeners:listeners).add(callback);return callback;},offref:(callback:(leaf:any)=>void)=>{listeners.delete(callback);fileListeners.delete(callback);},async revealLeaf(leaf:any){revealed.push(leaf);await reveal?.();},setActiveLeaf(leaf:any){focuses.push(leaf);active=leaf;for(const callback of listeners)callback(leaf);}};
 const app={workspace,vault:{getAbstractFileByPath:(path:string)=>files.get(path)}};
 const Host=new Function('MarkdownView','nativeBoardEditorLeaves',transformSync('class Host{'+take('  async locateNativeBoardEditor(','  nativeBoardEditorStatus(')+'};return Host',{loader:'ts'}).code)(MarkdownView,nativeBoardEditorLeaves);
 const plugin=new Host();Object.assign(plugin,{app,openBoard:async(...args:any[])=>{opens.push(args);return open?.(...args);}});
 const owner={file,blocked:true,recoveryFile:recovery,saveFeedback:{action:{kind:action}}};
 const view=new View();Object.assign(view,{app,plugin,session:owner,contentEl:{ownerDocument:doc},file,renderSaveStatus(){},closed:false,closing:false});const sourceLeaf=makeLeaf(view);active=sourceLeaf;
 const native=makeLeaf(new MarkdownView());leaves.push(native);
 const targetView=new View();Object.assign(targetView,{file:recovery,session:{},containerEl:{isConnected:true},resumeAutomaticGeometry(){}});const recoveryLeaf=makeLeaf(targetView);open=async()=>recoveryLeaf;
 const navigate=(leaf:any)=>{active=leaf;for(const callback of listeners)callback(leaf);};
 return{fileListeners,fireFile:(file:any)=>{for(const callback of fileListeners)callback(file);},NativeBoardEditorPicker,view,plugin,owner,file,recovery,files,doc,otherDoc,sourceLeaf,native,recoveryLeaf,leaves,pickers,focuses,revealed,opens,listeners,MarkdownView,makeLeaf,navigate,run:()=>view.runSaveFeedbackAction(action),load:(fn:()=>Promise<void>)=>load=fn,reveal:(fn:()=>Promise<void>)=>reveal=fn,open:(fn:(...args:any[])=>Promise<any>)=>open=fn};
}
test('locating one native page reveals it without reading, saving, closing or changing its draft',async()=>{const f=fixture(),before={...f.native.view};await f.run();assert.deepEqual(f.focuses,[f.native]);assert.equal(f.native.view.draft,before.draft);assert.equal(f.native.view.saving,true);assert.equal(f.native.view.saveAgain,true);assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);});
test('multiple native windows require a choice; selecting the second preserves both drafts',async()=>{const f=fixture(),other=f.makeLeaf(new f.MarkdownView(),f.otherDoc);f.leaves.push(other);const pending=f.run();await tick();assert.equal(f.pickers.length,1);assert.deepEqual(f.focuses,[]);assert.match(f.pickers[0].getItemText(other),/其他窗口/);f.pickers[0].onChooseItem(other);f.pickers[0].close();await pending;assert.deepEqual(f.focuses,[other]);assert.equal(f.native.view.draft,'Unsaved native input');assert.equal(other.view.draft,'Unsaved native input');assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);});
test('canceling native selection never focuses or changes any native page and a later click works',async()=>{const f=fixture();f.leaves.push(f.makeLeaf(new f.MarkdownView(),f.otherDoc));const first=f.run();await tick();f.pickers[0].close();await first;assert.deepEqual(f.focuses,[]);assert.equal(f.listeners.size,0);const second=f.run();await tick();f.pickers[1].onChooseItem(f.native);await second;assert.deepEqual(f.focuses,[f.native]);});
for(const stale of ['new-navigation','navigate-and-back','source-owner','source-close','window-close','file-rename','native-replaced','native-closed'] as const)test(`native locate cancels ${stale} during deferred load without late focus`,async()=>{const f=fixture(),waiting=gate();f.native.isDeferred=true;f.load(()=>waiting.promise);const pending=f.run();await tick();if(stale==='new-navigation'||stale==='navigate-and-back'){f.navigate(f.makeLeaf({}));if(stale==='navigate-and-back')f.navigate(f.sourceLeaf);}else if(stale==='source-owner')f.view.session={};else if(stale==='source-close')f.view.closed=true;else if(stale==='window-close')f.doc.defaultView.closed=true;else if(stale==='file-rename')f.file.path='Boards/Renamed.md';else if(stale==='native-replaced')f.native.view={file:f.file};else f.leaves.length=0;waiting.resolve();await pending;assert.deepEqual(f.focuses,[]);assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);});
test('new navigation while picker is open closes it, and stale confirmation cannot focus another window',async()=>{const f=fixture();f.leaves.push(f.makeLeaf(new f.MarkdownView(),f.otherDoc));const pending=f.run();await tick();f.navigate(f.makeLeaf({}));await pending;f.pickers[0].onChooseItem(f.native);await tick();assert.deepEqual(f.focuses,[]);assert.equal(f.listeners.size,0);});
test('view unload cancels selection and releases its navigation subscription',async()=>{const f=fixture();f.leaves.push(f.makeLeaf(new f.MarkdownView(),f.otherDoc));const pending=f.run();await tick();f.view.cancelSaveFeedbackNavigation();await pending;assert.equal(f.listeners.size,0);assert.deepEqual(f.focuses,[]);});
test('recovery action opens the exact file in a guarded inactive board before focusing, retaining the original protection',async()=>{const f=fixture('open-recovery');await f.run();assert.equal(f.opens.length,1);assert.equal(f.opens[0][0],f.recovery);assert.equal(f.opens[0][3],true);assert.deepEqual(f.focuses,[f.recoveryLeaf]);assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);});
test('recovery remains accessible when the protected original file was already deleted',async()=>{const f=fixture('open-recovery');f.files.delete(f.file.path);await f.run();assert.deepEqual(f.focuses,[f.recoveryLeaf]);assert.equal(f.owner.blocked,true);});
test('a user-renamed recovery is located by its real identity; same-path replacement or deletion is refused',async()=>{const f=fixture('open-recovery');f.files.delete(f.recovery.path);f.recovery.path='Boards/User renamed recovery.md';f.files.set(f.recovery.path,f.recovery);await f.run();assert.deepEqual(f.focuses,[f.recoveryLeaf]);f.focuses.length=0;f.navigate(f.sourceLeaf);f.files.set(f.recovery.path,{path:f.recovery.path});await assert.rejects(f.run(),/移除|替换/);assert.deepEqual(f.focuses,[]);f.files.delete(f.recovery.path);await assert.rejects(f.run(),/移除|替换/);assert.deepEqual(f.focuses,[]);});
for(const stale of ['navigation','navigate-and-back','cancel','owner','original-rename','original-replace','recovery-rename','recovery-replace','closed'] as const)test(`recovery action cancels ${stale} during opening without late focus or writes`,async()=>{const f=fixture('open-recovery'),waiting=gate<any>();f.open(()=>waiting.promise);const pending=f.run();await tick();if(stale==='navigation'||stale==='navigate-and-back'){f.navigate(f.makeLeaf({}));if(stale==='navigate-and-back')f.navigate(f.sourceLeaf);}else if(stale==='cancel')f.view.cancelSaveFeedbackNavigation();else if(stale==='owner')f.view.session={};else if(stale==='original-rename')f.file.path='Boards/Moved.md';else if(stale==='original-replace')f.files.set(f.file.path,{path:f.file.path});else if(stale==='recovery-rename')f.recovery.path='Boards/Moved recovery.md';else if(stale==='recovery-replace')f.files.set(f.recovery.path,{path:f.recovery.path});else f.view.closed=true;waiting.resolve(f.recoveryLeaf);await pending;assert.deepEqual(f.focuses,[]);assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);});
test('rapid recovery clicks coalesce to one opening and a failed opening releases the busy guard for retry',async()=>{const f=fixture('open-recovery'),waiting=gate<any>();f.open(()=>waiting.promise);const first=f.run();await tick();await f.run();assert.equal(f.opens.length,1);waiting.reject(Error('Read failed'));await assert.rejects(first,/Read failed/);assert.equal(f.listeners.size,0);f.open(async()=>f.recoveryLeaf);await f.run();assert.equal(f.opens.length,2);assert.deepEqual(f.focuses,[f.recoveryLeaf]);assert.equal(f.owner.blocked,true);});
test('navigation arriving during reveal cannot regain focus afterward',async()=>{const f=fixture('open-recovery'),waiting=gate();f.reveal(()=>waiting.promise);const pending=f.run();await tick();assert.equal(f.revealed.length,1);f.navigate(f.makeLeaf({}));waiting.resolve();await pending;assert.deepEqual(f.focuses,[]);assert.equal(f.listeners.size,0);});

test('native picker is placed in its originating popout document before the host opens it',()=>{const f=fixture(),picker=new f.NativeBoardEditorPicker(f.plugin.app,f.leaves,f.otherDoc,()=>{});assert.equal(picker.containerEl.ownerDocument,f.doc);picker.onOpen();assert.equal(picker.containerEl.ownerDocument,f.otherDoc);assert.equal(picker.baseOpens,1);assert.deepEqual(f.focuses,[]);});
for(const cancelled of ['window','request'])test(`native picker ${cancelled} cancellation before opening does not focus or mount it`,async()=>{const f=fixture();let completed=0;const picker=new f.NativeBoardEditorPicker(f.plugin.app,f.leaves,f.otherDoc,()=>completed++,()=>cancelled!=='request');if(cancelled==='window')f.otherDoc.defaultView.closed=true;picker.onOpen();await tick();assert.equal(picker.baseOpens,0);assert.equal(picker.containerEl.ownerDocument,f.doc);assert.equal(completed,1);assert.deepEqual(f.focuses,[]);});

test('recovery opening owns its own synchronous empty-tab activation without canceling itself',async()=>{const f=fixture('open-recovery');f.open(async(...args:any[])=>{const navigation=args[4];const leaf=navigation.acquire(()=>{f.navigate(f.recoveryLeaf);return f.recoveryLeaf;});navigation.target(leaf);return leaf;});await f.run();assert.deepEqual(f.focuses,[f.recoveryLeaf]);assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);});
test('user navigation after expected tab acquisition permanently cancels recovery focus',async()=>{const f=fixture('open-recovery'),waiting=gate();f.open(async(...args:any[])=>{const navigation=args[4];navigation.acquire(()=>{f.navigate(f.recoveryLeaf);return f.recoveryLeaf;});await waiting.promise;return f.recoveryLeaf;});const pending=f.run();await tick();f.navigate(f.makeLeaf({}));f.navigate(f.sourceLeaf);waiting.resolve();await pending;assert.deepEqual(f.focuses,[]);assert.equal(f.listeners.size,0);});
for(const kind of ['closed','closing','detached'])test(`recovery ${kind} destination while loading never receives focus`,async()=>{const f=fixture('open-recovery');if(kind==='detached')f.recoveryLeaf.view.containerEl.isConnected=false;else f.recoveryLeaf.view[kind]=true;await f.run();assert.deepEqual(f.focuses,[]);assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);});

for(const failure of ['throw','reject'])test(`native picker host ${failure} closes safely, reports the cause and leaves retry possible`,async()=>{const f=fixture(),errors:unknown[]=[];let canceled=0;const picker=new f.NativeBoardEditorPicker(f.plugin.app,f.leaves,f.doc,()=>canceled++,()=>true,(error:unknown)=>errors.push(error));const error=Error('Host picker failed');if(failure==='throw')picker.hostError=error;else picker.hostReject=error;picker.onOpen();await tick();assert.equal(canceled,1);assert.deepEqual(errors,[error]);assert.deepEqual(f.focuses,[]);assert.equal(f.owner.blocked,true);});

function productionRecoveryFixture(){
 const f=fixture('open-recovery'),waiting=gate(),BoardView=f.view.constructor,mounts:string[]=[],detached:any[]=[];
 const openBoard=new Function('BoardView','FileView','VIEW',...Object.keys(boardHostDeps),transformSync('class Host{'+take('  async openBoard(','\n  openBoardOrganizer(')+'};return Host.prototype.openBoard;',{loader:'ts'}).code)(BoardView,class FileView{},'thoughtspace-board',...Object.values(boardHostDeps));
 (f.recovery as any).extension='md';Object.assign(f.plugin.app.vault,{read:async()=>boardHostDeps.createMarkdownBoardDocument(emptyBoard(),'Recovery')});f.plugin.boardOpening=new SharedOpen();f.plugin.provisionalBoardGeometry=new WeakMap();f.plugin.readBoard=async()=>{await waiting.promise;return emptyBoard();};
 const initial={},target:any={view:initial,getViewState(){return this.view.file?{type:this.view instanceof BoardView?'thoughtspace-board':'markdown',state:{file:this.view.file.path}}:{type:'empty',state:{}};},getContainer:()=>({doc:f.doc,win:f.doc.defaultView}),detach(){detached.push(this);},async setViewState(state:any){mounts.push(state.state.file);const view=new BoardView();Object.assign(view,{file:f.recovery,session:{},containerEl:{isConnected:true},resumeAutomaticGeometry(){}});view.leaf=this;this.view=view;f.fireFile(f.recovery);}};
 Object.assign(f.plugin.app.workspace,{getLeavesOfType:()=>[],getLeaf:()=>{f.navigate(target);return target;}});f.plugin.openBoard=openBoard;
 return{...f,target,initial,waiting,mounts,detached};
}
for(const change of ['same-view-file','new-native-view','leave-and-return-file','replace-empty-view'])test(`production recovery opening preserves ${change} in its own same target leaf`,async()=>{
 const f=productionRecoveryFixture(),pending=f.run();await tick();const userFile={path:'Notes/Newer user choice.md'};
 if(change==='same-view-file')Object.assign(f.target.view,{file:userFile,leaf:f.target});else if(change==='new-native-view')f.target.view={file:userFile,leaf:f.target};else if(change==='leave-and-return-file'){f.target.view={file:userFile,leaf:f.target};f.fireFile(userFile);f.target.view=f.recoveryLeaf.view;f.target.view.leaf=f.target;}else f.target.view={};
 f.navigate(f.target);const selected=f.target.view;f.waiting.resolve();await pending;assert.equal(f.target.view,selected);assert.deepEqual(f.mounts,[]);assert.deepEqual(f.focuses,[]);assert.deepEqual(f.detached,[]);assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);assert.equal(f.fileListeners.size,0);
});
test('production recovery opening accepts its exact initial placeholder and the mounted recovery board',async()=>{const f=productionRecoveryFixture(),pending=f.run();await tick();f.waiting.resolve();await pending;assert.deepEqual(f.mounts,[f.recovery.path]);assert.deepEqual(f.focuses,[f.target]);assert.equal(f.owner.blocked,true);assert.equal(f.listeners.size,0);assert.equal(f.fileListeners.size,0);});
