import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import * as model from '../src/model';
import * as mindmap from '../src/mindmap';
import * as documents from '../src/board-document';
import * as geometry from '../src/relation-geometry-checkpoint';
import {reflowReadingContent} from '../src/expansion-reading-state';
const parseYaml=(raw:string)=>raw.includes('thoughtspace: board')?{thoughtspace:'board'}:{};
const source=readFileSync('src/main.ts','utf8'),start=source.indexOf('class Session {'),end=source.indexOf('\nexport default class ThoughtSpace',start);
const deps={...model,...mindmap,...documents,...geometry,reflowReadingContent,parseYaml,Notice:class{},EXT:'thoughtspace',report:()=>{},hasNativeBoardEditor:(app:any)=>app.nativeOpen,assertBoardEditorOwnership:(app:any)=>{if(app.nativeOpen)throw Error('Native editor owns this document');}};
const Session=new Function(...Object.keys(deps),transformSync(source.slice(start,end)+';return Session',{loader:'ts'}).code)(...Object.values(deps));
function fixture(format='md'){
 const file={path:'Boards/Example.'+format,extension:format,basename:'Example',parent:{path:'Boards'}};
 let disk=format==='md'?documents.createMarkdownBoardDocument(model.emptyBoard(),'Example'):JSON.stringify(model.emptyBoard(),null,2),writeError:Error|undefined,recoveryError:Error|undefined;
 const files=new Map<string,any>([[file.path,file]]),recovered:any[]=[],events:string[]=[];
 const plugin={nativeBoardTransitions:new Set(),nativeBoardEditorStatus:()=>({open:plugin.app.nativeOpen?1:0,pending:0}),app:{nativeOpen:false,vault:{getAbstractFileByPath:(path:string)=>files.get(path),read:async()=>disk,process:async(_file:any,edit:(raw:string)=>string)=>{if(writeError)throw writeError;disk=edit(disk);}}},createUnique:async(_folder:string,_name:string,extension:string,raw:string)=>{if(recoveryError)throw recoveryError;const recovery={path:'Boards/Example-恢复草稿.'+extension,extension};files.set(recovery.path,recovery);recovered.push({file:recovery,raw});return recovery;}};
 const session=new Session(plugin,file,disk);session.listeners.add((kind:string)=>events.push(kind));
 return{session,plugin,file,files,recovered,events,disk:()=>disk,writeFails:(message:string)=>writeError=Error(message),recoveryFails:(message:string)=>recoveryError=Error(message),external:(value:string)=>disk=value};
}
test('normal saved and queued saving feedback has no navigation action',async()=>{const f=fixture();assert.equal(f.session.saveFeedback.state,'saved');assert.equal(f.session.saveFeedback.action,undefined);f.session.change((b:model.Board)=>b.viewport.x=99);assert.equal(f.session.saveFeedback.state,'saving');await f.session.flush();assert.equal(f.session.saveFeedback.state,'saved');});
test('an observed native owner explains read-only protection and offers locate without saving or closing it',()=>{const f=fixture();f.plugin.app.nativeOpen=true;f.session.refreshNativeEditing();const feedback=f.session.saveFeedback;assert.equal(feedback.state,'paused');assert.match(feedback.text,/原生|仅查看/);assert.equal(feedback.action?.kind,'locate-native');assert.equal(f.recovered.length,0);});
test('an old closed native save explains waiting without presenting a phantom page to locate',()=>{const f=fixture();f.plugin.app.nativeOpen=true;f.plugin.nativeBoardEditorStatus=()=>({open:0,pending:1});f.session.refreshNativeEditing();assert.match(f.session.saveFeedback.text,/旧.*保存|保存.*完成/);assert.equal(f.session.saveFeedback.action,undefined);});
test('a handoff explains waiting; changing reason while still protected emits only status',()=>{const f=fixture();f.plugin.app.nativeOpen=true;f.session.refreshNativeEditing();f.events.length=0;f.plugin.nativeBoardTransitions.add(f.file);f.session.refreshNativeEditing();assert.match(f.session.saveFeedback.text,/交接/);assert.equal(f.session.saveFeedback.action,undefined);assert.deepEqual(f.events,['status']);});
for(const format of ['md','thoughtspace'])test(`${format} save conflict preserves the exact recovery identity and original error`,async()=>{const f=fixture(format),before=f.disk();f.writeFails('Read-only storage is unavailable');f.session.change((b:model.Board)=>b.viewport.x=175);await f.session.flush();assert.equal(f.disk(),before);assert.equal(f.session.blocked,true);assert.equal(f.session.saveFeedback.action?.kind,'open-recovery');assert.equal(f.session.recoveryFile,f.recovered[0].file);assert.match(f.session.saveFeedback.detail,/Read-only storage/);assert.equal(f.session.saveFeedback.recoveryPath,f.recovered[0].file.path);});
test('recovery rename follows the same object while deletion or same-path replacement removes the action',async()=>{const f=fixture();f.writeFails('Conflict');f.session.change((b:model.Board)=>b.viewport.x=175);await f.session.flush();const recovery=f.session.recoveryFile,old=recovery.path;f.files.delete(old);recovery.path='Boards/User recovery.md';f.files.set(recovery.path,recovery);assert.equal(f.session.saveFeedback.recoveryPath,recovery.path);assert.equal(f.session.saveFeedback.action?.kind,'open-recovery');f.files.set(recovery.path,{...recovery});assert.equal(f.session.saveFeedback.action,undefined);assert.match(f.session.saveFeedback.detail,/移除|替换/);f.files.delete(recovery.path);assert.equal(f.session.saveFeedback.action,undefined);assert.equal(f.session.blocked,true);});
test('failed recovery creation explains both errors and does not pretend a saved draft exists',async()=>{const f=fixture();f.writeFails('Permission denied');f.recoveryFails('Disk full');f.session.change((b:model.Board)=>b.viewport.x=175);await f.session.flush();assert.equal(f.session.recoveryFile,undefined);assert.equal(f.session.saveFeedback.action,undefined);assert.match(f.session.saveFeedback.detail,/Permission denied/);assert.match(f.session.saveFeedback.detail,/Disk full/);assert.match(f.session.saveFeedback.text,/导出/);assert.equal(f.session.blocked,true);});
test('external layout conflict with failed draft creation remains a conflict, not an invalid-format report',async()=>{const f=fixture();f.session.board.viewport.x=175;f.session.board.nodes.push({id:'local',kind:'text',text:'Local unsaved thought',x:0,y:0,width:200,height:100,color:'slate'});const incoming=model.emptyBoard();incoming.viewport.x=900;f.external(documents.replaceBoardDocumentLayout(f.disk(),documents.readBoardDocument(f.disk(),'md',parseYaml),incoming,parseYaml).source);f.recoveryFails('Recovery folder unavailable');await f.session.externalUpdate();assert.match(f.session.saveFeedback.text,/冲突/);assert.match(f.session.saveFeedback.detail,/Recovery folder unavailable/);assert.doesNotMatch(f.session.saveFeedback.text,/格式错误/);assert.equal(f.session.saveFeedback.action,undefined);assert.equal(f.session.board.viewport.x,175);});

test('a failed external read preserves its storage reason rather than reporting invalid document format',async()=>{const f=fixture();f.plugin.app.vault.read=async()=>{throw Error('Storage temporarily offline');};await f.session.externalUpdate();assert.match(f.session.saveFeedback.text,/读取失败/);assert.doesNotMatch(f.session.saveFeedback.text,/格式错误/);assert.match(f.session.saveFeedback.detail,/Storage temporarily offline/);assert.equal(f.session.blocked,true);assert.equal(f.session.saveFeedback.action,undefined);});
