import test from 'node:test';import assert from 'node:assert/strict';
import {BoardSearchSync,boardSearchDocument,isManagedSearchIndex,searchIndexPath} from '../src/native-search';
import {emptyBoard,parseBoard,clone,type Board} from '../src/model';
import {branchState} from '../src/mindmap';
import {discloseBranches,makeChildConnection} from '../src/branch-disclosure';
import {foldCards} from '../src/board-tools';
import {pdfCard,pdfPageKey} from '../src/pdf-card';
import {PdfDocumentPool,type PdfApi} from '../src/pdf-document-pool';
function tree(){const b=emptyBoard();b.version=3;b.nodes=['a','b','c','d'].map((id,i)=>({id,kind:'text',text:id,x:i*200,y:0,width:150,height:80,color:'green'}));b.edges=[{id:'ab',from:'a',to:'b',label:'',kind:'branch'},{id:'bc',from:'b',to:'c',label:'',kind:'branch'},{id:'cd',from:'c',to:'d',label:'',kind:'branch'}];return b;}
test('native search preserves literal syntax, hidden node text, labels and source locators',()=>{const b=tree();b.nodes[0].text='中文 a_b #tag ``` ![[file]]\n- [ ] task';b.nodes[0].branchFolded=true;b.edges[0].label='支持证据';const s=boardSearchDocument(b,'资料/图.thoughtspace','库');assert.ok(s.includes(b.nodes[0].text!));assert.ok(s.includes('支持证据'));assert.ok(s.includes('node=d'));assert.ok(isManagedSearchIndex(s));assert.equal(isManagedSearchIndex(s+'edited'),false);const moved=clone(b);moved.nodes[0].x+=200;assert.equal(boardSearchDocument(moved,'资料/图.thoughtspace','库'),s);});
function indexFixture(){const b=tree(),files=new Map<string,string>();let writes=0;const errors:unknown[]=[];let board:Board|undefined=b;const sync=new BoardSearchSync({board:async()=>board,read:async p=>files.get(p),write:async(p,s,old)=>{assert.equal(files.get(p),old);files.set(p,s);writes++;},remove:async(p,old)=>{assert.equal(files.get(p),old);files.delete(p);}},'vault',(_,e)=>errors.push(e));return{sync,b,files,errors,writes:()=>writes,remove:()=>board=undefined};}
test('index queue coalesces rapid saves, skips identical content and removes generated orphans',async()=>{const f=indexFixture();for(let i=0;i<100;i++)f.sync.enqueue('a.thoughtspace');await f.sync.flush();assert.equal(f.writes(),1);f.sync.enqueue('a.thoughtspace');await f.sync.flush();assert.equal(f.writes(),1);f.remove();f.sync.enqueue('a.thoughtspace');await f.sync.flush();assert.equal(f.files.size,0);});
test('index never overwrites or deletes manually edited files',async()=>{const f=indexFixture();const p=searchIndexPath('a.thoughtspace');f.files.set(p,'user note');f.sync.enqueue('a.thoughtspace');await f.sync.flush();f.remove();f.sync.enqueue('a.thoughtspace');await f.sync.flush();assert.equal(f.files.get(p),'user note');assert.equal(f.errors.length,2);});
test('stopping indexing during async read performs no writes',async()=>{let done!:(b:Board)=>void;let writes=0;const sync=new BoardSearchSync({board:()=>new Promise(r=>done=r),read:async()=>undefined,write:async()=>{writes++;},remove:async()=>{}},'vault',()=>{});sync.enqueue('a');const p=sync.flush();sync.stop();done(tree());await p;assert.equal(writes,0);});
test('PDF collapse persists page, restores exact height and respects locks',()=>{const b=emptyBoard();b.version=3;b.nodes=[pdfCard('p','a.pdf',0,0)];b.nodes[0].pdfPage=3;foldCards(b,new Set(['p']),true);assert.equal(b.nodes[0].height,72);assert.equal(parseBoard(JSON.stringify(b)).nodes[0].pdfPage,3);foldCards(b,new Set(['p']),false);assert.equal(b.nodes[0].height,400);b.nodes[0].locked=true;foldCards(b,new Set(['p']),true);assert.equal(b.nodes[0].collapsed,undefined);});
test('PDF keys clamp page bounds and wait for page count before moving forward',()=>{assert.equal(pdfPageKey('PageUp',1,4),1);assert.equal(pdfPageKey('PageDown',4,4),4);assert.equal(pdfPageKey('End',1,4),4);assert.equal(pdfPageKey('Home',4,4),1);assert.equal(pdfPageKey('PageDown',1),undefined);assert.equal(pdfPageKey('ArrowRight',1,4),undefined);});
test('branch expansion reveals one level per action and roundtrips',()=>{const b=tree();discloseBranches(b,new Set(['a']),'collapse');assert.deepEqual([...branchState(b).hidden].sort(),['b','c','d']);discloseBranches(b,new Set(['a']),'level');assert.deepEqual([...branchState(b).hidden].sort(),['c','d']);discloseBranches(b,new Set(['a']),'level');assert.deepEqual([...branchState(b).hidden],['d']);discloseBranches(b,new Set(['a']),'all');assert.equal(branchState(b).hidden.size,0);assert.deepEqual(parseBoard(JSON.stringify(b)),b);});
test('converting a plain connection rejects cycles and multiple parents atomically',()=>{const b=tree();b.edges.push({id:'loop',from:'d',to:'a',label:''});const before=clone(b);assert.throws(()=>makeChildConnection(b,'loop'));assert.deepEqual(b,before);b.edges.push({id:'multiple',from:'d',to:'b',label:''});assert.throws(()=>makeChildConnection(b,'multiple'));const plain=tree();delete plain.edges[0].kind;makeChildConnection(plain,'ab');assert.equal(plain.edges[0].kind,'branch');});
test('large folded tree uses iterative disclosure without recursion limits',()=>{const b=tree();for(let i=0;i<5000;i++){const id='x'+i;b.nodes.push({...b.nodes[0],id});b.edges.push({id:'e'+i,from:i?'x'+(i-1):'d',to:id,label:'',kind:'branch'});}discloseBranches(b,new Set(['a']),'collapse');discloseBranches(b,new Set(['a']),'level');assert.equal(branchState(b).hidden.size,5002);discloseBranches(b,new Set(['a']),'all');assert.equal(branchState(b).hidden.size,0);});
function poolFixture(){let loads=0,destroyed=0,created=0,clock=0;const timers=new Map<number,()=>void>();const api={getDocument:()=>{created++;return{promise:Promise.resolve({numPages:10,getPage:async()=>{throw Error('unused');}}),destroy:async()=>{destroyed++;}};}} satisfies PdfApi;const pool=new PdfDocumentPool(async()=>{loads++;return api;},{set:fn=>{timers.set(++clock,fn);return clock;},clear:id=>{timers.delete(id);}},2);return{pool,timers,stats:()=>({loads,destroyed,created})};}
test('PDF document leases share parsing, survive one card closing and expire',async()=>{const f=poolFixture();const a=f.pool.acquire('a'),b=f.pool.acquire('a');await Promise.all([a.document,b.document]);a.release();assert.equal(f.timers.size,0);b.release();assert.equal(f.stats().created,1);const c=f.pool.acquire('a');await c.document;assert.equal(f.timers.size,0);c.release();for(const run of [...f.timers.values()])run();assert.equal(f.stats().destroyed,1);f.pool.clear();assert.equal(f.stats().destroyed,1);});
test('PDF pool evicts idle documents and unload cancels retained workers',async()=>{const f=poolFixture();for(const key of ['a','b','c']){const lease=f.pool.acquire(key);await lease.document;lease.release();}assert.equal(f.stats().destroyed,1);f.pool.clear();assert.equal(f.stats().destroyed,3);assert.equal(f.timers.size,0);assert.throws(()=>f.pool.acquire('d'));});
test('large text indexes avoid argument-stack overflow',()=>{const b=tree();b.nodes[0].text='` x '.repeat(150000);assert.ok(isManagedSearchIndex(boardSearchDocument(b,'large.thoughtspace','库')));});
test('overlapping selected branches reveal only one new level',()=>{const b=tree();discloseBranches(b,new Set(['a']),'collapse');discloseBranches(b,new Set(['a','b','c']),'level');assert.deepEqual([...branchState(b).hidden].sort(),['c','d']);});
test('index worker drains a save queued while writing without losing the latest edit',async()=>{const b=tree();let sync!:BoardSearchSync;const values:string[]=[];let stored:string|undefined;sync=new BoardSearchSync({board:async()=>b,read:async()=>stored,write:async(_p,s)=>{stored=s;values.push(s);if(values.length===1){b.nodes[0].text='latest edit';sync.enqueue('a');}},remove:async()=>{}},'vault',e=>assert.fail(e));sync.enqueue('a');await sync.flush();assert.equal(values.length,2);assert.ok(values[1].includes('latest edit'));});
test('PDF worker loading failures are evicted and can be retried',async()=>{let attempts=0,destroyed=0;const pool=new PdfDocumentPool(async()=>({getDocument:()=>({promise:++attempts===1?Promise.reject(Error('bad PDF')):Promise.resolve({numPages:2,getPage:async()=>{throw Error('unused');}}),destroy:async()=>{destroyed++;}})}),{set:()=>1,clear:()=>{}});const a=pool.acquire('a');await assert.rejects(a.document,/bad PDF/);a.release();const b=pool.acquire('a');assert.equal((await b.document).numPages,2);b.release();pool.clear();assert.equal(destroyed,2);});
test('unloading PDF pool before API resolves never creates a late worker',async()=>{let ready!:(v:PdfApi)=>void;let created=0;const pool=new PdfDocumentPool(()=>new Promise(r=>ready=r),{set:()=>1,clear:()=>{}});const a=pool.acquire('a');pool.clear();ready({getDocument:()=>{created++;throw Error('late');}});await assert.rejects(a.document,/取消/);a.release();assert.equal(created,0);});
