import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import * as state from '../src/board-mindmap';
import * as relations from '../src/local-relations';
import * as motion from '../src/local-relations-motion';
import {emptyBoard,clone,type Board,type Card} from '../src/model';

class Doc {
 activeElement:El|null=null;frames=new Map<number,()=>void>();counter=0;
 defaultView={closed:false,matchMedia:()=>({matches:false}),requestAnimationFrame:(fn:()=>void)=>{const id=++this.counter;this.frames.set(id,fn);return id;},cancelAnimationFrame:(id:number)=>this.frames.delete(id)};
 tick(){const frames=[...this.frames.values()];this.frames.clear();for(const fn of frames)fn();}
}
class El {
 children:El[]=[];parentElement:El|null=null;dataset:Record<string,string>={};attrs:Record<string,string>={};classes=new Set<string>();listeners=new Map<string,Set<(e:any)=>void>>();hidden=false;disabled=false;visible=true;title='';text='';value='';style:Record<string,string>={};scrollTop=0;scrollLeft=0;clientHeight=400;clientWidth=600;scrollHeight=400;scrollWidth=600;
 onclick:((event:any)=>void)|null=null;onpointerdown:((event:any)=>void)|null=null;oninput:((event:any)=>void)|null=null;onkeydown:((event:any)=>void)|null=null;
 classList={add:(...values:string[])=>values.forEach(value=>this.classes.add(value)),remove:(...values:string[])=>values.forEach(value=>this.classes.delete(value)),contains:(value:string)=>this.classes.has(value),toggle:(value:string,force?:boolean)=>{const on=force??!this.classes.has(value);if(on)this.classes.add(value);else this.classes.delete(value);return on;}};
 constructor(readonly tagName:string,public ownerDocument:Doc,options:any={}){if(typeof options==='string')options={cls:options};this.text=options.text||'';for(const cls of (options.cls||'').split(' ').filter(Boolean))this.classes.add(cls);for(const [key,value]of Object.entries(options.attr||{}))this.setAttribute(key,String(value));}
 get isConnected():boolean{return this.tagName==='ROOT'||!!this.parentElement?.isConnected;}
 get textContent():string{return this.text+this.children.map(child=>child.textContent).join('');}
 createEl(tag:string,options:any={}){return this.appendChild(new El(tag.toUpperCase(),this.ownerDocument,options));}createDiv(options:any={}){return this.createEl('div',options);}createSpan(options:any={}){return this.createEl('span',options);}createSvg(tag:string,options:any={}){return this.createEl(tag,options);}
 appendChild(child:El){return this.insertBefore(child,null);}insertBefore(child:El,before:El|null){child.remove();const index=before?this.children.indexOf(before):-1;if(index<0)this.children.push(child);else this.children.splice(index,0,child);child.parentElement=this;return child;}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(child=>child!==this);this.parentElement=null;}
 replaceChildren(...children:El[]){this.empty();for(const child of children)this.appendChild(child);}empty(){for(const child of this.children)child.parentElement=null;this.children=[];this.text='';}setText(value:string){this.empty();this.text=value;}
 setAttribute(key:string,value:string){this.attrs[key]=value;if(key==='title')this.title=value;if(key.startsWith('data-'))this.dataset[this.dataKey(key)]=value;}getAttribute(key:string){return key.startsWith('data-')?this.dataset[this.dataKey(key)]??null:this.attrs[key]??null;}private dataKey(key:string){return key.slice(5).replace(/-([a-z])/g,(_match,letter)=>letter.toUpperCase());}
 contains(child:El|null):boolean{return !!child&&(child===this||this.children.some(item=>item.contains(child)));}
 matches(selector:string):boolean{if(selector.includes(','))return selector.split(',').some(part=>this.matches(part.trim()));if(selector.startsWith('.'))return this.classes.has(selector.slice(1));if(selector.startsWith('[')){const found=selector.match(/^\[([^=\]]+)(?:="([^"]*)")?\]$/)!;return this.getAttribute(found[1])!==null&&(found[2]===undefined||this.getAttribute(found[1])===found[2]);}return this.tagName===selector.toUpperCase();}
 closest(selector:string):El|null{return this.matches(selector)?this:this.parentElement?.closest(selector)||null;}
 querySelectorAll(selector:string):El[]{return this.children.flatMap(child=>[...(child.matches(selector)?[child]:[]),...child.querySelectorAll(selector)]);}querySelector(selector:string){return this.querySelectorAll(selector)[0];}
 getClientRects(){return this.isConnected&&this.visible&&!this.hidden&&!this.ancestors().some(parent=>!parent.visible||parent.hidden)?[this.getBoundingClientRect()]:[];}
 getBoundingClientRect(){const offset=this.dataset.mindmapRole==='center'?300:this.parentElement?.dataset.side==='left'?20:500;return{left:offset,top:50,right:offset+120,bottom:90,width:this.clientWidth,height:40};}
 ancestors():El[]{return this.parentElement?[this.parentElement,...this.parentElement.ancestors()]:[];}
 focus(){if(this.isConnected&&!this.disabled)this.ownerDocument.activeElement=this;}
 dispatch(type:string,extra:any={}){const event={type,target:this,button:0,key:'',shiftKey:false,ctrlKey:false,metaKey:false,isComposing:false,deltaY:0,deltaX:0,defaultPrevented:false,stopped:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;},...extra};let current:El|null=this;while(current){const fn=(current as any)['on'+type];fn?.(event);for(const listener of current.listeners.get(type)||[])listener(event);if(event.stopped)break;current=current.parentElement;}return event;}
 click(){if(!this.disabled)this.dispatch('click');}
}
class Component {
 children:Component[]=[];callbacks:(()=>void)[]=[];loaded=false;
 load(){this.loaded=true;(this as any).onload?.();for(const child of this.children)if(!child.loaded)child.load();}
 unload(){(this as any).onunload?.();for(const child of [...this.children])child.unload();this.children=[];for(const callback of this.callbacks.splice(0))callback();this.loaded=false;}
 addChild<T extends Component>(child:T):T {this.children.push(child);if(this.loaded)child.load();return child;}
 removeChild(child:Component){this.children=this.children.filter(value=>value!==child);child.unload();return child;}
 register(callback:()=>void){this.callbacks.push(callback);}
 registerDomEvent(el:El,type:string,callback:(event:any)=>void){let events=el.listeners.get(type);if(!events){events=new Set();el.listeners.set(type,events);}events.add(callback);this.register(()=>events!.delete(callback));}
}
class MenuItem {title='';icon='';disabled=false;callback=()=>{};setTitle(value:string){this.title=value;return this;}setIcon(value:string){this.icon=value;return this;}setDisabled(value:boolean){this.disabled=value;return this;}onClick(fn:()=>void){this.callback=fn;return this;}click(){if(!this.disabled)this.callback();}}
class Menu {static last:Menu;items:MenuItem[]=[];native=true;shown?:string;doc?:Doc;hidden=false;private onHidden=()=>{};constructor(){Menu.last=this;}setUseNativeMenu(value:boolean){this.native=value;return this;}addItem(fn:(item:MenuItem)=>void){const item=new MenuItem();fn(item);this.items.push(item);return this;}addSeparator(){}showAtMouseEvent(){this.shown='mouse';}showAtPosition(_position:any,doc:Doc){this.shown='keyboard';this.doc=doc;}onHide(fn:()=>void){this.onHidden=fn;}hide(){this.hidden=true;this.onHidden();}}
const source=readFileSync('src/board-mindmap-view.ts','utf8').replace(/^import[^\n]*\n/gm,'').replace(/\bexport /g,'');
const deps={...state,...relations,...motion,Component,Menu,setIcon(el:El,icon:string){el.dataset.icon=icon;}};
const View=new Function(...Object.keys(deps),transformSync(source+'\nreturn BoardMindmapView;',{loader:'ts'}).code)(...Object.values(deps));
const card=(id:string,kind:Card['kind']='card'):Card=>({id,kind,title:'标题 '+id,file:kind==='card'?`Notes/${id}.md`:kind==='board'?`Boards/${id}.thoughtspace`:undefined,x:10,y:20,width:120,height:80,color:'slate'});
function fixture(){
 const doc=new Doc(),root=new El('ROOT',doc),el=root.createDiv();el.classList.add('ts-node');
 const container:Card={...card('map','mindmap'),mindmap:state.createBoardMindmapState('b')};
 const board:Board={...emptyBoard(),version:3,nodes:[...['a','b','c','d'].map(id=>card(id)),card('group','section'),card('sub','board'),{...card('text','text'),text:'独立文本'},container],edges:[{id:'ab',from:'a',to:'b',label:'父级',kind:'branch'},{id:'bc',from:'b',to:'c',label:'子级',kind:'branch'},{id:'bd',from:'b',to:'d',label:'引用'},{id:'bs',from:'b',to:'sub',label:'子板',direction:'both'},{id:'bg',from:'b',to:'group',label:'分组',direction:'both'},{id:'bt',from:'b',to:'text',label:'不可用'}]};
 let snapshot:any={board,container,path:'Board.thoughtspace',key:{}},selected=0,folded=0;const saves:any[]=[],opens:{id:string;current:()=>boolean;edit:boolean}[]=[],previews:{id:string;body:El;scope:Component;current:()=>boolean}[]=[],missing=new Set<string>(),stamps=new Map<string,string>();
 const host:any={snapshot:()=>snapshot,change:(next:any)=>{saves.push(clone(next));snapshot.container.mindmap=next;},source:(id:string)=>{const node=board.nodes.find(item=>item.id===id);return{label:'来源 '+id,path:node?.file,available:!!node&&!missing.has(id),reason:'来源文件缺失',canEdit:node?.kind==='card',stamp:stamps.get(id)||'1'};},open:async(id:string,current:()=>boolean,edit:boolean)=>{opens.push({id,current,edit});},preview:(id:string,body:El,scope:Component,current:()=>boolean)=>{previews.push({id,body,scope,current});if(current())body.createEl('p',{text:`真实正文 ${id} 很长的正文不会被改成标题。`});},select:()=>{selected++;},fold:()=>{folded++;snapshot.container.collapsed=!snapshot.container.collapsed;},relate:()=>{},fileMenu:()=>{}};
 const view=new View({},el,host);view.load();
 return{view,doc,root,el,board,container,host,saves,opens,previews,missing,stamps,get snapshot(){return snapshot;},setSnapshot:(value:any)=>{snapshot=value;},get selected(){return selected;},get folded(){return folded;}};
}
const node=(f:ReturnType<typeof fixture>,id:string,role?:string)=>f.el.querySelectorAll('.ts-mindmap-item').find(item=>item.dataset.mindmapNodeId===id&&(!role||item.dataset.mindmapRole===role))!;
const action=(root:El,key:string)=>root.querySelector(`[data-mindmap-action="${key}"]`)!;
const title=(f:ReturnType<typeof fixture>,id:string,role?:string)=>node(f,id,role).querySelector('.ts-mindmap-title')!;
const menuItem=(title:string)=>Menu.last.items.find(item=>item.title===title)!;

test('mount is read-only and projects actual eligible nodes without nested board drag targets',()=>{const f=fixture();assert.equal(f.saves.length,0);assert.equal(f.opens.length,0);assert.equal(f.previews.length,0);assert.equal(f.el.querySelectorAll('.ts-node').length,0);assert.equal(f.el.querySelectorAll('[data-id]').length,0);assert.equal(node(f,'text'),undefined);assert.ok(node(f,'group'));assert.ok(node(f,'sub'));assert.equal(f.el.querySelectorAll('.ts-mindmap-links')[0].children.length,5);});
test('single title click changes persisted center only and native source stays unopened',()=>{const f=fixture(),before=clone(f.board);title(f,'a').click();assert.equal(f.container.mindmap!.centerId,'a');assert.deepEqual(f.container.mindmap!.history,{entries:['b','a'],index:1});assert.equal(f.opens.length,0);assert.deepEqual(f.board.edges,before.edges);assert.deepEqual(f.board.viewport,before.viewport);assert.deepEqual(clone(f.board.nodes.filter(n=>n.id!=='map')),before.nodes.filter(n=>n.id!=='map'));assert.equal(title(f,'a','center').getAttribute('aria-current'),'true');});
test('node title double click has no second navigation or open behavior',()=>{const f=fixture(),button=title(f,'a');button.click();button.dispatch('dblclick');assert.equal(f.saves.length,1);assert.equal(f.opens.length,0);});
test('back and forward use saved stack including nonconsecutive repeated centers',()=>{const f=fixture();title(f,'a').click();title(f,'b').click();action(f.el,'back').click();assert.equal(f.container.mindmap!.centerId,'a');action(f.el,'back').click();assert.equal(f.container.mindmap!.centerId,'b');action(f.el,'forward').click();assert.equal(f.container.mindmap!.centerId,'a');});
test('independent expand renders actual body without changing center or navigation history',()=>{const f=fixture(),history=clone(f.container.mindmap!.history);action(node(f,'a'),'expand').click();assert.equal(f.container.mindmap!.centerId,'b');assert.deepEqual(f.container.mindmap!.history,history);assert.deepEqual(f.container.mindmap!.expandedIds,['a']);assert.match(node(f,'a').textContent,/真实正文 a/);assert.equal(f.previews.length,1);});
test('same-center refresh preserves body element, source read count, scroll and native input focus',()=>{const f=fixture();action(node(f,'a'),'expand').click();const body=f.previews[0].body,input=body.createEl('input'),stage=f.el.querySelector('.ts-mindmap-stage')!;body.scrollTop=81;stage.scrollTop=154;input.focus();for(let i=0;i<5;i++)f.view.refresh();assert.equal(f.previews.length,1);assert.equal(f.previews[0].current(),true);assert.equal(body.scrollTop,81);assert.equal(stage.scrollTop,154);assert.equal(f.doc.activeElement,input);assert.equal(node(f,'a').querySelector('.ts-mindmap-preview'),body);});
test('expanded neighbor body is reused when that node becomes center',()=>{const f=fixture();action(node(f,'a'),'expand').click();const body=f.previews[0].body;title(f,'a').click();assert.equal(f.previews.length,1);assert.equal(node(f,'a','center').querySelector('.ts-mindmap-preview'),body);assert.equal(f.previews[0].current(),true);});
test('same object with multiple relationships has one actionable card and retains its other roles',()=>{const f=fixture();f.board.edges.push({id:'ba',from:'b',to:'a',label:'extra'});const edges=clone(f.board.edges);f.view.refresh();action(node(f,'a'),'expand').click();assert.equal(f.el.querySelectorAll('.ts-mindmap-item').filter(item=>item.dataset.mindmapNodeId==='a').length,1);assert.match(title(f,'a').title,/父级、此对象引用/);assert.match(title(f,'a').getAttribute('aria-description')!,/父级、此对象引用/);action(node(f,'a'),'menu').click();assert.ok(Menu.last.items.some(item=>item.title==='关系：父级、此对象引用'&&item.disabled));assert.equal(f.previews.filter(row=>row.id==='a').length,1);assert.equal(f.el.querySelectorAll('.ts-mindmap-preview').length,1);assert.deepEqual(f.board.edges,edges);});
test('visible nodes retain roles whose category evidence is on another page',()=>{const f=fixture();f.board.edges.push({id:'ba-extra',from:'b',to:'a',label:'extra'});for(let i=0;i<24;i++){const id=`extra-${i}`;f.board.nodes.push(card(id));f.board.edges.push({id:`edge-${i}`,from:'b',to:id,label:''});}f.view.pages.outgoing=1;const before=clone(f.board);f.view.refresh();assert.equal(f.el.querySelectorAll('.ts-mindmap-item').filter(item=>item.dataset.mindmapNodeId==='a').length,1);assert.match(title(f,'a').getAttribute('aria-description')!,/父级、此对象引用/);action(node(f,'a'),'menu').click();assert.ok(Menu.last.items.some(item=>item.title==='关系：父级、此对象引用'&&item.disabled));assert.deepEqual(clone(f.board),before);});
test('an off-page preferred role cannot hide a node from its visible category',()=>{const f=fixture();const extra=Array.from({length:12},(_,i)=>card(`associate-${i}`));f.board.nodes.unshift(...extra);f.board.edges.push(...extra.map(item=>({id:`edge-${item.id}`,from:'b',to:item.id,label:'',direction:'both' as const})),{id:'d-associate',from:'b',to:'d',label:'',direction:'both'});const before=clone(f.board);f.view.refresh();assert.equal(node(f,'d').dataset.mindmapRole,'outgoing');assert.equal(f.el.querySelectorAll('.ts-mindmap-item').filter(item=>item.dataset.mindmapNodeId==='d').length,1);assert.match(title(f,'d').getAttribute('aria-description')!,/关联、此对象引用/);f.view.pages.associated=1;f.view.refresh();assert.equal(node(f,'d').dataset.mindmapRole,'associated');assert.equal(f.el.querySelectorAll('.ts-mindmap-item').filter(item=>item.dataset.mindmapNodeId==='d').length,1);assert.match(title(f,'d').getAttribute('aria-description')!,/关联、此对象引用/);assert.deepEqual(clone(f.board),before);});
test('source stamp changes invalidate old body and guard without losing expanded state',()=>{const f=fixture();action(node(f,'a'),'expand').click();const old=f.previews[0];f.stamps.set('a','2');assert.equal(old.current(),false);f.view.refresh();assert.equal(f.previews.length,2);assert.equal(old.scope.loaded,false);assert.notEqual(f.previews[1].body,old.body);assert.deepEqual(f.container.mindmap!.expandedIds,['a']);});
test('source loss remains visible, unloads preview and disables open without deleting reference',()=>{const f=fixture();action(node(f,'a'),'expand').click();const old=f.previews[0];f.missing.add('a');f.view.refresh();assert.match(node(f,'a').textContent,/来源文件缺失/);assert.equal(action(node(f,'a'),'open').disabled,true);assert.equal(action(node(f,'a'),'expand').disabled,false);assert.deepEqual(f.container.mindmap!.expandedIds,['a']);assert.equal(old.scope.loaded,false);});
test('explicit collapse unloads native scope and reexpand mounts a fresh body',()=>{const f=fixture();action(node(f,'a'),'expand').click();const old=f.previews[0];action(node(f,'a'),'expand').click();assert.equal(old.current(),false);assert.equal(old.scope.loaded,false);assert.deepEqual(f.container.mindmap!.expandedIds,[]);action(node(f,'a'),'expand').click();assert.equal(f.previews.length,2);});
test('open button opens specific actual source without changing center or persisted state',()=>{const f=fixture();action(node(f,'a'),'open').click();assert.equal(f.opens.length,1);assert.equal(f.opens[0].id,'a');assert.equal(f.opens[0].edit,false);assert.equal(f.opens[0].current(),true);assert.equal(f.container.mindmap!.centerId,'b');assert.equal(f.saves.length,0);});
for(const reason of ['center','board','path','deleted','document','closed-window','collapsed','hidden','unloaded'])test(`source action guard cancels after ${reason}`,()=>{const f=fixture();action(node(f,'a'),'open').click();const guard=f.opens[0].current;if(reason==='center')title(f,'a').click();if(reason==='board')f.setSnapshot({...f.snapshot,key:{}});if(reason==='path')f.snapshot.path='Renamed.thoughtspace';if(reason==='deleted')f.board.nodes=f.board.nodes.filter(n=>n.id!=='a');if(reason==='document')f.el.ownerDocument=new Doc();if(reason==='closed-window')f.doc.defaultView.closed=true;if(reason==='collapsed')f.container.collapsed=true;if(reason==='hidden')f.el.visible=false;if(reason==='unloaded')f.view.unload();assert.equal(guard(),false);if(reason==='hidden'){f.el.visible=true;assert.equal(guard(),false);}});
test('native themed menu provides independent center preview open edit pin and relationships',()=>{const f=fixture();action(node(f,'a'),'menu').click();assert.equal(Menu.last.native,false);assert.equal(Menu.last.shown,'mouse');assert.deepEqual(Menu.last.items.map(item=>item.title),['设为中心','展开正文','打开 来源 a','编辑实际笔记','固定对象','添加子级关系','添加父级关系','添加关联','移除本板关系']);menuItem('编辑实际笔记').click();assert.equal(f.opens[0].id,'a');assert.equal(f.opens[0].edit,true);assert.equal(f.saves.length,0);});
test('Shift F10 uses native menu in the exact owning document',()=>{const f=fixture(),event=title(f,'group').dispatch('keydown',{key:'F10',shiftKey:true});assert.equal(event.defaultPrevented,true);assert.equal(Menu.last.shown,'keyboard');assert.equal(Menu.last.doc,f.doc);assert.ok(menuItem('定位原分组'));assert.equal(Menu.last.items.find(item=>item.title.startsWith('编辑实际笔记'))!.disabled,true);assert.match(Menu.last.items.find(item=>item.title.startsWith('编辑实际笔记'))!.title,/没有独立笔记正文/);});
test('context menu cancellation makes no board or native source changes',()=>{const f=fixture(),before=JSON.stringify(f.board),event=node(f,'a').dispatch('contextmenu');assert.equal(event.defaultPrevented,true);assert.equal(event.stopped,true);assert.equal(JSON.stringify(f.board),before);assert.equal(f.opens.length,0);assert.equal(f.previews.length,0);});
test('stale node menu cannot apply after center changes',()=>{const f=fixture();action(node(f,'a'),'menu').click();const pending=menuItem('固定对象');title(f,'a').click();pending.click();assert.deepEqual(f.container.mindmap!.pins,[]);});
test('pin is persisted and can select a disconnected object after center changes',()=>{const f=fixture();action(node(f,'d'),'menu').click();menuItem('固定对象').click();assert.deepEqual(f.container.mindmap!.pins,['d']);title(f,'a').click();const pin=f.el.querySelector('[data-mindmap-pinned-id="d"]')!;pin.click();assert.equal(f.container.mindmap!.centerId,'d');assert.equal(f.opens.length,0);});
test('missing center and history entries remain explicit and mounting never rewrites them',()=>{const f=fixture();title(f,'a').click();f.board.nodes=f.board.nodes.filter(n=>n.id!=='a');const count=f.saves.length;f.view.refresh();assert.equal(f.saves.length,count);assert.equal(f.container.mindmap!.centerId,'a');assert.match(f.el.textContent,/中心对象已移除/);action(f.el,'back').click();assert.equal(f.container.mindmap!.centerId,'b');action(f.el,'forward').click();assert.equal(f.container.mindmap!.centerId,'a');});
test('dangling expanded and pinned IDs can be explicitly cleared without selecting a replacement',()=>{const f=fixture();f.container.mindmap!.expandedIds=['gone'];f.container.mindmap!.pins=['gone'];f.view.refresh();const cleanup=f.el.querySelectorAll('button').find(button=>button.title==='清理失效展开 gone')!;cleanup.click();assert.deepEqual(f.container.mindmap!.expandedIds,[]);f.el.querySelector('[data-mindmap-pinned-id="gone"]')!.click();assert.deepEqual(f.container.mindmap!.pins,[]);assert.equal(f.container.mindmap!.centerId,'b');});
test('read-only container disables persistent controls and still allows actual-source viewing',()=>{const f=fixture();f.snapshot.readOnly=true;f.view.refresh();title(f,'a').click();action(node(f,'a'),'expand').click();action(node(f,'a'),'open').click();assert.equal(f.saves.length,0);assert.equal(f.previews.length,0);assert.equal(f.opens.length,1);assert.match(f.el.textContent,/只读/);});
test('global center search preserves input focus and excludes text and mindmap containers',()=>{const f=fixture();action(f.el,'search').click();const input=f.el.querySelector('input')!;assert.equal(f.doc.activeElement,input);assert.equal(f.el.querySelectorAll('.ts-mindmap-search-result').length,6);input.value='标题 a';input.dispatch('input');assert.equal(f.el.querySelectorAll('.ts-mindmap-search-result').length,1);assert.equal(f.doc.activeElement,input);assert.equal(f.saves.length,0);input.dispatch('keydown',{key:'Enter'});assert.equal(f.container.mindmap!.centerId,'a');});
test('Escape from embedded search restores focus to its visible trigger without saving',()=>{const f=fixture(),search=action(f.el,'search');search.click();const input=f.el.querySelector('input')!;assert.equal(f.doc.activeElement,input);const event=input.dispatch('keydown',{key:'Escape'});assert.equal(event.defaultPrevented,true);assert.equal(f.doc.activeElement,search);assert.equal(search.getAttribute('aria-expanded'),'false');assert.equal(f.el.querySelector('.ts-mindmap-search')!.hidden,true);assert.equal(f.saves.length,0);});
test('inline search keeps one header input across refresh and leaves no hidden input focus',()=>{const f=fixture(),input=f.el.querySelector('input')!,heading=f.el.querySelector('.ts-mindmap-heading')!;assert.equal(input.hidden,true);assert.equal(heading.hidden,false);action(f.el,'search').click();assert.equal(input.parentElement,f.el.querySelector('.ts-mindmap-header'));assert.equal(input.dataset.mindmapInteractive,'true');assert.equal(heading.hidden,true);input.value='标题 a';input.dispatch('input');f.view.refresh();assert.equal(f.el.querySelector('input'),input);assert.equal(f.doc.activeElement,input);assert.equal(input.value,'标题 a');input.dispatch('keydown',{key:'Escape'});assert.equal(input.hidden,true);assert.equal(heading.hidden,false);assert.equal(f.doc.activeElement,action(f.el,'search'));action(f.el,'search').click();assert.equal(input.value,'标题 a');assert.equal(f.saves.length,0);});
test('relationship groups and search are bounded with explicit pages',()=>{const f=fixture();for(let i=0;i<33;i++){f.board.nodes.push(card(`extra${i}`));f.board.edges.push({id:`e${i}`,from:'b',to:`extra${i}`,label:''});}f.view.refresh();const outgoing=f.el.querySelector('[data-relation-kind="outgoing"]')!;assert.equal(outgoing.querySelectorAll('.ts-mindmap-item').length,10);const next=outgoing.querySelectorAll('button').find(button=>button.title==='此对象引用下一页')!;next.click();assert.equal(outgoing.querySelectorAll('.ts-mindmap-item').length,10);assert.match(outgoing.textContent,/2 \/ 4/);assert.equal(f.saves.length,0);action(f.el,'search').click();assert.equal(f.el.querySelectorAll('.ts-mindmap-search-result').length,10);});
test('body pointer selects only container while header blank remains available to canvas dragging',()=>{const f=fixture();const before=f.selected,bodyEvent=node(f,'a').dispatch('pointerdown');assert.equal(bodyEvent.stopped,true);assert.equal(f.selected,before+1);const heading=f.el.querySelector('.ts-mindmap-heading')!,headerEvent=heading.dispatch('pointerdown');assert.equal(headerEvent.stopped,false);assert.equal(f.doc.activeElement,null);});
test('scrollable body consumes ordinary wheel while ctrl/meta zoom and scroll edges reach board',()=>{const f=fixture(),stage=f.el.querySelector('.ts-mindmap-stage')!;stage.scrollHeight=900;stage.scrollTop=20;assert.equal(stage.dispatch('wheel',{deltaY:40}).stopped,true);assert.equal(stage.dispatch('wheel',{deltaY:40,ctrlKey:true}).stopped,false);assert.equal(stage.dispatch('wheel',{deltaY:40,metaKey:true}).stopped,false);stage.scrollTop=0;assert.equal(stage.dispatch('wheel',{deltaY:-40}).stopped,false);assert.equal(f.saves.length,0);});
test('search overlay contains ordinary wheel for short lists scroll boundaries and horizontal movement without canceling native scroll',()=>{const f=fixture();action(f.el,'search').click();const popup=f.el.querySelector('.ts-mindmap-search')!,result=f.el.querySelector('.ts-mindmap-search-result')!,before=JSON.stringify(f.board);let outerWheels=0;f.root.listeners.set('wheel',new Set([()=>outerWheels++]));for(const state of [{name:'short',top:0,height:80,dx:0,dy:160},{name:'top',top:0,height:300,dx:0,dy:-80},{name:'bottom',top:220,height:300,dx:0,dy:80},{name:'scrollable',top:80,height:300,dx:0,dy:40},{name:'horizontal',top:80,height:300,dx:80,dy:0}]){popup.clientHeight=80;popup.scrollHeight=state.height;popup.scrollTop=state.top;popup.scrollWidth=900;popup.clientWidth=600;popup.scrollLeft=300;for(const target of [result,popup]){const event=target.dispatch('wheel',{deltaX:state.dx,deltaY:state.dy});assert.equal(event.stopped,true,state.name);assert.equal(event.defaultPrevented,false,state.name);assert.equal(popup.scrollTop,state.top,state.name);}}assert.equal(outerWheels,0);assert.equal(JSON.stringify(f.board),before);assert.equal(f.saves.length,0);});
test('search overlay preserves explicit ctrl and meta zoom gestures for the outer board',()=>{const f=fixture();action(f.el,'search').click();const popup=f.el.querySelector('.ts-mindmap-search')!,result=f.el.querySelector('.ts-mindmap-search-result')!;let outerWheels=0;f.root.listeners.set('wheel',new Set([()=>outerWheels++]));for(const modifier of ['ctrlKey','metaKey'])for(const target of [result,popup]){const event=target.dispatch('wheel',{deltaY:80,[modifier]:true});assert.equal(event.stopped,false);assert.equal(event.defaultPrevented,false);}assert.equal(outerWheels,4);assert.equal(f.saves.length,0);});
test('hidden mount never starts native previews and visibility refresh safely resumes',()=>{const f=fixture();f.el.visible=false;f.container.mindmap!.expandedIds=['a'];f.view.refresh();assert.equal(f.previews.length,0);f.el.visible=true;f.view.refresh();assert.equal(f.previews.length,1);assert.equal(f.previews[0].current(),true);});
test('folded container shows center summary and does not initiate source reads',()=>{const f=fixture();f.container.mindmap!.expandedIds=['a'];f.container.collapsed=true;f.view.refresh();assert.equal(f.previews.length,0);assert.equal(f.el.querySelector('.ts-mindmap-stage')!.hidden,true);assert.match(f.el.querySelector('.ts-mindmap-status')!.textContent,/标题 b/);f.el.querySelector('.ts-mindmap-heading')!.click();assert.equal(f.folded,1);assert.equal(f.container.collapsed,false);});
test('unload cancels queued line rendering and native scopes without external focus',()=>{const f=fixture();action(node(f,'a'),'expand').click();const record=f.previews[0];f.el.querySelector('.ts-mindmap-stage')!.dispatch('scroll');assert.equal(f.doc.frames.size,1);const external=f.root.createEl('input');external.focus();f.view.unload();f.doc.tick();assert.equal(f.doc.frames.size,0);assert.equal(record.scope.loaded,false);assert.equal(record.current(),false);assert.equal(f.el.querySelector('.ts-mindmap-shell'),undefined);assert.equal(f.doc.activeElement,external);});
test('multiple containers keep center, history, preview and local search independent',()=>{const a=fixture(),b=fixture();title(a,'a').click();action(node(a,'a'),'expand').click();action(a.el,'search').click();assert.equal(b.container.mindmap!.centerId,'b');assert.deepEqual(b.container.mindmap!.expandedIds,[]);assert.equal(b.saves.length,0);assert.equal(b.previews.length,0);assert.equal(b.el.querySelector('.ts-mindmap-search')!.hidden,true);});
test('preview guard rejects owner replacement even before next render',()=>{const f=fixture();action(node(f,'a'),'expand').click();const guard=f.previews[0].current;f.setSnapshot({...f.snapshot,key:{}});assert.equal(guard(),false);});
test('row lifecycle listener registrations stay bounded during repeated browsing',()=>{const f=fixture();for(let i=0;i<80;i++){title(f,i%2?'b':'a').click();}assert.ok(f.view.children.length<25);assert.ok(f.view.items.size<15);});
test('synchronous host render and queued selection refresh preserve one running center transition',()=>{const f=fixture(),calls:string[]=[];let finish=()=>{};f.view.motion={capture:()=>{calls.push('capture');return{};},play:(_root:any,_snapshot:any,done:()=>void)=>{calls.push('play');finish=done;},cancel:()=>calls.push('cancel')};f.host.change=(next:any)=>{f.container.mindmap=next;f.view.refresh();};f.host.select=()=>{f.doc.defaultView.requestAnimationFrame(()=>f.view.refresh());};const before=f.view.renders;title(f,'a').click();assert.equal(f.view.renders,before+1);assert.deepEqual(calls,['capture','play']);assert.equal(f.view.motionActive,true);f.doc.tick();assert.deepEqual(calls,['capture','play']);assert.equal(f.view.motionActive,true);assert.equal(f.el.querySelector('.ts-mindmap-links')!.classList.contains('is-transitioning'),true);finish();assert.equal(f.view.motionActive,false);assert.equal(f.el.querySelector('.ts-mindmap-links')!.classList.contains('is-transitioning'),false);});
test('a new center cancels old menu and unload closes the remaining native menu',()=>{const f=fixture();action(node(f,'a'),'menu').click();const old=Menu.last;title(f,'a').click();assert.equal(old.hidden,true);action(node(f,'b'),'menu').click();const active=Menu.last;f.view.unload();assert.equal(active.hidden,true);});
test('native action labels do not duplicate open and disclose real content type',()=>{const f=fixture(),source=f.host.source;f.host.source=(id:string)=>({...source(id),label:id==='sub'?'打开子白板':'打开笔记'});f.view.refresh();assert.equal(action(node(f,'a'),'open').title,'打开笔记');assert.equal(action(node(f,'sub'),'open').title,'打开子白板');assert.equal(action(node(f,'sub'),'expand').title,'展开子白板概览');assert.equal(action(node(f,'group'),'expand').title,'展开分组内容');});
test('host canvas gesture passes Space pointer drag through body and buttons without selecting',()=>{const f=fixture();f.host.canvasGesture=()=>true;const before=f.selected;assert.equal(node(f,'a').dispatch('pointerdown').stopped,false);assert.equal(action(node(f,'a'),'open').dispatch('pointerdown').stopped,false);assert.equal(f.selected,before);assert.equal(node(f,'a').dispatch('keydown',{key:' '}).stopped,false);assert.equal(title(f,'a').dispatch('keydown',{key:' '}).stopped,true);});
test('board undo shortcut delegates only outside editing controls and composition',()=>{const f=fixture();let shortcuts=0;f.host.shortcut=()=>{shortcuts++;return true;};const event=title(f,'a').dispatch('keydown',{key:'z',metaKey:true});assert.equal(shortcuts,1);assert.equal(event.defaultPrevented,true);action(f.el,'search').click();f.el.querySelector('input')!.dispatch('keydown',{key:'z',metaKey:true});assert.equal(shortcuts,1);title(f,'a').dispatch('keydown',{key:'z',metaKey:true,isComposing:true});assert.equal(shortcuts,1);});
test('without a shortcut host, non-input Cmd Z and Ctrl Y reach normal board handling',()=>{const f=fixture();assert.equal(title(f,'a').dispatch('keydown',{key:'z',metaKey:true}).stopped,false);assert.equal(title(f,'a').dispatch('keydown',{key:'y',ctrlKey:true}).stopped,false);});
test('save failures preserve original center and expose failure without opening native sources',()=>{const f=fixture();f.host.change=()=>{throw Error('只读存储未修改');};title(f,'a').click();assert.equal(f.container.mindmap!.centerId,'b');assert.equal(f.opens.length,0);assert.match(f.el.querySelector('.ts-mindmap-status')!.textContent,/只读存储未修改/);});
test('native source open failure cannot write error into another center after cancellation',async()=>{const f=fixture();let reject!:(error:Error)=>void;f.host.open=()=>new Promise((_resolve,no)=>{reject=no;});action(node(f,'a'),'open').click();title(f,'a').click();reject(Error('旧请求失败'));await Promise.resolve();await Promise.resolve();assert.doesNotMatch(f.el.querySelector('.ts-mindmap-status')!.textContent,/旧请求失败/);});
test('queued lines are canceled when the container adopts another window',()=>{const f=fixture();f.el.querySelector('.ts-mindmap-stage')!.dispatch('scroll');const next=new Doc();const adopt=(el:El)=>{el.ownerDocument=next;for(const child of el.children)adopt(child);};adopt(f.el);f.view.refresh();assert.equal(f.doc.frames.size,0);f.el.querySelector('.ts-mindmap-stage')!.dispatch('scroll');assert.equal(next.frames.size,1);f.doc.tick();assert.equal(next.frames.size,1);next.tick();assert.equal(next.frames.size,0);});
test('owning board rename rebuilds a pending preview with new path while keeping center history',()=>{const f=fixture();action(node(f,'a'),'expand').click();const old=f.previews[0],history=clone(f.container.mindmap!.history);f.snapshot.path='Renamed.thoughtspace';assert.equal(old.current(),false);f.view.refresh();assert.equal(f.previews.length,2);assert.equal(old.scope.loaded,false);assert.equal(f.previews[1].current(),true);assert.deepEqual(f.container.mindmap!.history,history);assert.equal(f.container.mindmap!.centerId,'b');});
