import test from 'node:test';
import assert from 'node:assert/strict';
import {createBrainBoard} from '../src/brain-board';
import {brainIdeaNode,brainIdeaToNote,brainNoteFolder} from '../src/brain-board-idea';
import {brainAssociationSides} from '../src/brain-board-create';
import {BrainBranchIndex,BrainDescendantPager,BRAIN_DESCENDANT_NODES,BRAIN_DESCENDANT_WORK,BRAIN_RENDER_EDGES,BRAIN_RENDER_NODES} from '../src/brain-board-descendants';
import {brainBoardLayout,brainBoardDescendantLayout} from '../src/brain-board-layout';
import {localRelationMatches,supportsLocalRelations} from '../src/local-relations';
import {updateBoardMindmapState,validBoardMindmapState} from '../src/board-mindmap';
import {clone,parseBoard,type Board} from '../src/model';
function graph(count:number,fanout:number){const board=createBrainBoard('0');for(let i=0;i<count;i++){board.nodes.push(brainIdeaNode(String(i),'想法 '+i,i*400));if(i)board.edges.push({id:'e'+i,from:String(Math.floor((i-1)/fanout)),to:String(i),kind:'branch',label:''});}return board;}
test('old state defaults to one layer; depth preference validates, copies and serializes without graph edits',()=>{const board=graph(8,1),before=clone(board);assert.equal(board.brain.descendantDepth,undefined);for(const value of [1,2,3,4,5]){const next=updateBoardMindmapState(board.brain,{type:'depth',value},board.nodes);assert(validBoardMindmapState(next));assert.equal(next.descendantDepth??1,value);board.brain=next;assert.equal(parseBoard(JSON.stringify(board)).brain?.descendantDepth??1,value);}assert.deepEqual(board.nodes,before.nodes);assert.deepEqual(board.edges,before.edges);for(const value of [0,6,1.5,NaN,Infinity])assert.throws(()=>updateBoardMindmapState(board.brain,{type:'depth',value},board.nodes));});
for(const depth of [1,2,3,4,5])test('chain displays exact descendants 0–'+depth,()=>{const b=graph(10000,1),index=new BrainBranchIndex(b),pager=new BrainDescendantPager(index,'0',depth);assert.deepEqual(pager.current.ids.sort(),Array.from({length:depth+1},(_,i)=>String(i)));assert.equal(pager.current.hasNext,false);assert.equal(pager.current.links.length,depth);});
for(const count of [100,500,1000,10000])for(const fanout of [4,10000])test(`all eligible sources remain reachable: ${count} nodes / fanout ${fanout}`,()=>{
 const b=graph(count,fanout),before=JSON.stringify(b),pager=new BrainDescendantPager(new BrainBranchIndex(b),'0',5),ids=new Set<string>();let pages=0;
 do{const p=pager.current;assert(p.ids.length<=BRAIN_DESCENDANT_NODES);assert(p.work<=BRAIN_DESCENDANT_WORK);assert(p.links.length<=BRAIN_RENDER_EDGES);for(const id of p.ids)ids.add(id);assert(p.ids.every(id=>p.depths.get(id)!<=5));for(const id of p.ids)if(id!=='0')assert(p.links.some(edge=>edge.to===id),'path to '+id);pages++;if(!p.hasNext)break;pager.next();assert(pages<2000);}while(true);
 const expected=new Set(['0']);for(let depth=0;depth<5;depth++)for(const edge of b.edges)if(expected.has(edge.from))expected.add(edge.to);
 // Compute shortest depths independently (iteration uses a frozen frontier).
 const reachable=new Set(['0']);let frontier=['0'];for(let d=0;d<5;d++){const next=b.edges.filter(e=>frontier.includes(e.from)).map(e=>e.to);next.forEach(id=>reachable.add(id));frontier=next;}
 assert.deepEqual(ids,reachable);assert.equal(JSON.stringify(b),before);assert(pager.current.firstPage>=Math.max(0,pages-16));assert((pager as any).pages.length<=16);
});
test('ordinary links and unsupported text never become descendants',()=>{const b=graph(3,1);b.nodes.push({...brainIdeaNode('text','独立文本'),brainIdea:undefined});b.edges.push({id:'ordinary',from:'0',to:'text',label:''},{id:'not-idea',from:'0',to:'text',label:'',kind:'branch'});const p=new BrainDescendantPager(new BrainBranchIndex(b),'0',5).current;assert(!p.ids.includes('text'));assert(!supportsLocalRelations(b.nodes.at(-1)!));});
test('cycle, repeated evidence and shared descendants deduplicate traversal and preserve original endpoints',()=>{const b=graph(4,2);b.edges.push({id:'shared',from:'2',to:'3',kind:'branch',label:''},{id:'cycle',from:'3',to:'0',kind:'branch',label:''},{id:'parallel',from:'0',to:'1',kind:'branch',label:''});const before=JSON.stringify(b),p=new BrainDescendantPager(new BrainBranchIndex(b),'0',5).current;assert.equal(new Set(p.ids).size,4);assert.equal(p.links.length,6);assert(p.links.some(e=>e.id==='cycle'));assert(p.links.some(e=>e.id==='shared'));assert.throws(()=>parseBoard(JSON.stringify(b)));assert.equal(JSON.stringify(b),before);});
test('dense shared edges stop each request at a work budget and eventually finish',()=>{const b=graph(40,100);for(let from=1;from<40;from++)for(let to=1;to<40;to++)b.edges.push({id:`s${from}-${to}`,from:String(from),to:String(to),kind:'branch',label:''});const p=new BrainDescendantPager(new BrainBranchIndex(b),'0',5);let requests=0;do{assert(p.current.work<=BRAIN_DESCENDANT_WORK);assert(p.current.links.length<=BRAIN_RENDER_EDGES);if(!p.current.hasNext)break;p.next();assert(++requests<5);}while(true);assert.equal(p.current.visited,39);});
test('multi-level layout budgets keep previews separate and branch endpoints exact',()=>{const b=graph(1000,4),p=new BrainDescendantPager(new BrainBranchIndex(b),'0',5).current,l=brainBoardDescendantLayout(brainBoardLayout(localRelationMatches(b,'0'),{width:1900}),p,['1','2','3']);assert(l.nodes.length<=BRAIN_RENDER_NODES);assert(l.links.length<=BRAIN_RENDER_EDGES);for(const a of l.nodes)for(const other of l.nodes)if(a!==other){const aw=a.previewWidth??a.width,ah=a.height+(a.previewWidth?212:0),bw=other.previewWidth??other.width,bh=other.height+(other.previewWidth?212:0);const ax=a.x+a.width/2-aw/2,bx=other.x+other.width/2-bw/2;assert(!(ax<bx+bw&&bx<ax+aw&&a.y<other.y+bh&&other.y<a.y+ah),`${a.id} overlaps ${other.id}`);}for(const link of l.links)assert(b.edges.some(e=>e.from===link.from&&e.to===link.to));});
test('idea conversion preserves identity, all geometry and content until native file confirmation',()=>{const idea=brainIdeaNode('id','先记录'),note=brainIdeaToNote(idea,'Notes/整理.md');assert.equal(note.id,idea.id);for(const k of ['x','y','width','height','color','title'] as const)assert.equal(note[k],idea[k]);assert.equal(note.kind,'card');assert.equal(note.brainIdea,undefined);assert.equal(idea.kind,'text');assert.throws(()=>brainIdeaToNote({...idea,locked:true},'Notes/A.md'));assert.equal(brainNoteFolder('Notes/想法/'),'Notes/想法');for(const path of ['/etc','../bad','A/../B','A\\B',''])assert.throws(()=>brainNoteFolder(path));});

function associated(count:number,star=false){const b=graph(count,1);b.edges=b.edges.map((e,i)=>({id:e.id,from:star?'0':String(i),to:e.to,label:'关联',direction:'both' as const,fromSide:'right' as const,toSide:'left' as const}));return b;}
for(const depth of [1,2,3,4,5])test(`associated chain uses shortest hop depths through ${depth} and retains dashed original links`,()=>{
 const b=associated(9),before=JSON.stringify(b),p=new BrainDescendantPager(new BrainBranchIndex(b),'0',depth).current;
 assert.deepEqual(p.ids,Array.from({length:depth+1},(_,i)=>String(i)));for(const id of p.ids)assert.equal(p.depths.get(id),Number(id));assert.equal(p.hasNext,false);
 const l=brainBoardDescendantLayout(brainBoardLayout(localRelationMatches(b,'0'),{associationSides:brainAssociationSides(b,'0')}),p,[]);assert.equal(l.nodes.length,depth+1);assert(l.links.every(e=>e.role==='associated'&&e.dashed));for(let i=1;i<=depth;i++)assert(l.nodes.find(n=>n.id===String(i))!.x>l.nodes.find(n=>n.id===String(i-1))!.x);assert.equal(JSON.stringify(b),before);
});
test('association cycles, shared nodes and mixed branch paths never duplicate nodes or convert links into a tree',()=>{
 const b=associated(7);b.edges.push({id:'cycle',from:'6',to:'0',direction:'both',label:''},{id:'shortcut',from:'0',to:'3',direction:'both',label:''},{id:'branch',from:'1',to:'5',kind:'branch',label:''});
 const before=JSON.stringify(b),p=new BrainDescendantPager(new BrainBranchIndex(b),'0',5).current,l=brainBoardDescendantLayout(brainBoardLayout(localRelationMatches(b,'0')),p,['1','5']);assert.equal(new Set(p.ids).size,7);assert.equal(p.depths.get('3'),1);assert.equal(p.depths.get('5'),2);assert.equal(p.hasNext,false);assert.equal(l.nodes.length,7);assert(l.links.some(e=>e.from==='1'&&e.to==='5'&&!e.dashed&&e.role==='children'));assert(l.links.some(e=>e.from==='6'&&e.to==='0'&&e.dashed));assert.equal(JSON.stringify(b),before);
 for(const a of l.nodes)for(const c of l.nodes)if(a!==c){const aw=a.previewWidth??a.width,cw=c.previewWidth??c.width,ax=a.x+a.width/2-aw/2,cx=c.x+c.width/2-cw/2;assert(!(ax<cx+cw&&cx<ax+aw&&a.y<c.y+c.height+(c.previewWidth?212:0)&&c.y<a.y+a.height+(a.previewWidth?212:0)),`${a.id}/${c.id}`);}
});
for(const count of [100,500,1000])test(`${count} associated fanout is budgeted, paged and completely reachable`,()=>{
 const b=associated(count,true),before=JSON.stringify(b),p=new BrainDescendantPager(new BrainBranchIndex(b),'0',5),all=new Set<string>();let pages=0;
 do{assert(p.current.ids.length<=48);assert(p.current.work<=BRAIN_DESCENDANT_WORK);assert(p.current.links.length<=128);p.current.ids.forEach(id=>all.add(id));pages++;if(!p.current.hasNext)break;p.next();assert(pages<50);}while(true);
 assert.equal(all.size,count);assert.equal(JSON.stringify(b),before);p.reset();assert(p.current.ids.includes('1'));assert.equal(p.current.page,0);
});
