import test from 'node:test';import assert from 'node:assert/strict';import {excerptPresentation,sourceLinkTarget,conceptDocument} from '../src/excerpt-sources';import {emptyBoard,parseBoard,validCardFill} from '../src/model';import {applyNodeStyle,readNodeStyle} from '../src/board-experience';
test('source presentation extracts Markdown line and PDF page citations, preserving evidence',()=>{const raw='# 概念\n\n> 来源：[[原文|书]] · 第 3–5 行 · 章节\n\n原文证据\n\n来源：[[file.pdf#page=2]] · PDF 第 2–3 页\n\n> PDF 正文';const p=excerptPresentation(raw);assert.equal(p.sources.length,2);assert.deepEqual([p.sources[0].line,p.sources[1].page],[3,2]);assert.ok(p.body.includes('原文证据'));assert.ok(p.body.includes('> PDF 正文'));assert.ok(!p.body.includes('来源：'));assert.ok(raw.includes('来源：'));});
test('ordinary prose, fenced code, indented code and frontmatter stay visible',()=>{const cite='来源：[[a.pdf#page=1]] · PDF 第 1 页';for(const raw of ['来源：[[普通引用]]','这句来源：[[a]] · 第 1–2 行',`\`\`\`md\n${cite}\n\`\`\``,`    ${cite}`,`---\n${cite}\n---\n正文`])assert.equal(excerptPresentation(raw).body,raw);});
test('native and Markdown source links keep subpaths and aliases',()=>{assert.equal(sourceLinkTarget('[[folder/note#h|alias]]'),'folder/note#h');assert.equal(sourceLinkTarget('[source](folder/file%20one.pdf#page=3)'),'folder/file one.pdf#page=3');assert.equal(sourceLinkTarget('invalid'),'');});
test('repeated source records are retained so separate page locations remain accessible',()=>{const p=excerptPresentation('来源：[[a.pdf#page=1]] · PDF 第 1 页\n\n来源：[[a.pdf#page=2]] · PDF 第 2 页');assert.equal(p.sources.length,2);});
test('card background serialization allows presets and hex, rejects unsafe CSS',()=>{const b=emptyBoard();b.nodes.push({id:'a',kind:'card',file:'a.md',x:0,y:0,width:300,height:200,color:'blue',fillColor:'#aabbcc'});assert.equal(parseBoard(JSON.stringify(b)).nodes[0].fillColor,'#aabbcc');for(const invalid of ['url(x)','red; color: blue','#abc',123])assert.equal(validCardFill(invalid),false);b.nodes[0].fillColor='teal';assert.doesNotThrow(()=>parseBoard(JSON.stringify(b)));});
test('pasting a card fill styles text while preserving locked cards',()=>{const b=emptyBoard();b.version=3;b.nodes=[{id:'c',kind:'card',file:'c.md',x:0,y:0,width:300,height:200,color:'blue',fillColor:'rose'},{id:'t',kind:'text',text:'x',x:0,y:0,width:100,height:100,color:'green'},{id:'l',kind:'card',file:'l.md',locked:true,x:0,y:0,width:300,height:200,color:'blue'}];const style=readNodeStyle(b.nodes[0]);applyNodeStyle(b,new Set(['t','l']),style);assert.equal(b.nodes[1].fillColor,'rose');assert.equal(b.nodes[2].fillColor,undefined);assert.doesNotThrow(()=>parseBoard(JSON.stringify(b)));});
test('concept merge keeps evidence citations and a separate interpretation section',()=>{const text=conceptDocument('共同概念',[{title:'甲',link:'[[甲]]',body:'# 甲\n\n来源：[[a.pdf#page=1]] · PDF 第 1 页\n\n> 证据'},{title:'乙',link:'[[乙]]',body:'---\ntags: [tag]\n---\n# 乙\n\n更多证据'}]);assert.ok(text.includes('## 我的理解'));assert.ok(text.includes('[[甲]]'));assert.ok(text.includes('更多证据'));assert.ok(!text.includes('tags:'));assert.equal(excerptPresentation(text).sources.length,1);});
test('concept merge validates title and note count',()=>{assert.throws(()=>conceptDocument('',[]));assert.throws(()=>conceptDocument('概念',[{title:'单篇',link:'[[a]]',body:'正文'}]));});

test('transparent cards serialize independently of their preserved fill color',()=>{const b=emptyBoard();b.nodes=[{id:'c',kind:'card',file:'c.md',x:0,y:0,width:300,height:200,color:'blue',fillColor:'rose',transparent:true}];const restored=parseBoard(JSON.stringify(b));assert.equal(restored.nodes[0].transparent,true);assert.equal(restored.nodes[0].fillColor,'rose');delete restored.nodes[0].transparent;assert.equal(parseBoard(JSON.stringify(restored)).nodes[0].fillColor,'rose');});
test('transparent card style copying includes text and respects locks',()=>{const b=emptyBoard();b.version=3;b.nodes=[{id:'c',kind:'card',file:'c.md',x:0,y:0,width:300,height:200,color:'blue',transparent:true},{id:'d',kind:'card',file:'d.md',x:0,y:0,width:300,height:200,color:'blue'},{id:'t',kind:'text',text:'x',x:0,y:0,width:100,height:100,color:'green'},{id:'l',kind:'card',file:'l.md',locked:true,x:0,y:0,width:300,height:200,color:'blue'}];applyNodeStyle(b,new Set(['d','t','l']),readNodeStyle(b.nodes[0]));assert.equal(b.nodes[1].transparent,true);assert.equal(b.nodes[2].transparent,true);assert.equal(b.nodes[3].transparent,undefined);assert.doesNotThrow(()=>parseBoard(JSON.stringify(b)));});
