import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import {Board,Card,cardFillHex,emptyBoard} from '../src/model';
import {applyGroupMove,groupNodeName,outlineTree,planGroupMove} from '../src/group-organizer';
import {sectionContains} from '../src/sections';
type Options={cls?:string;text?:string;attr?:Record<string,string>;type?:string;value?:string};
class Document {activeElement?:Element;createElementNS(_ns:string,tag:string){return new Element(tag.toUpperCase(),this);}}
class Element {
 children:Element[]=[];classes=new Set<string>();attributes:Record<string,string>={};value='';disabled=false;title='';private text='';onclick?:()=>void;oninput?:()=>void;onchange?:()=>void;listeners=new Map<string,(event:any)=>void>();
 constructor(readonly tagName:string,readonly ownerDocument:Document,options:Options|string={}){const opts=typeof options==='string'?{cls:options}:options;this.text=opts.text||'';this.attributes={...opts.attr};this.value=opts.value||'';for(const cls of (opts.cls||'').split(/\s+/).filter(Boolean))this.classes.add(cls);}
 get textContent():string{return this.text+this.children.map(child=>child.textContent).join('');}set textContent(value:string){this.text=value;}
 createEl(tag:string,options:Options|string={}){const child=new Element(tag.toUpperCase(),this.ownerDocument,options);this.children.push(child);return child;}
 createDiv(options:Options|string={}){return this.createEl('div',options);}createSpan(options:Options|string={}){return this.createEl('span',options);}
 addClass(...names:string[]){for(const name of names)this.classes.add(name);}removeClass(name:string){this.classes.delete(name);}
 setAttribute(name:string,value:string){this.attributes[name]=value;if(name==='class')this.classes=new Set(value.split(/\s+/));}getAttribute(name:string){return this.attributes[name]??null;}
 setText(text:string){this.text=text;this.children=[];}empty(){this.children=[];this.text='';}appendChild(child:Element){this.children.push(child);}
 addEventListener(type:string,listener:(event:any)=>void){this.listeners.set(type,listener);}focus(){this.ownerDocument.activeElement=this;}click(){if(!this.disabled)this.onclick?.();}
 matches(selector:string){return selector.startsWith('.')?this.classes.has(selector.slice(1)):this.tagName===selector.toUpperCase();}
 querySelectorAll(selector:string):Element[]{return this.children.flatMap(child=>[...(child.matches(selector)?[child]:[]),...child.querySelectorAll(selector)]);}querySelector(selector:string){return this.querySelectorAll(selector)[0];}
}
class Modal {readonly document=new Document();readonly modalEl=new Element('DIV',this.document);readonly titleEl=this.modalEl.createEl('h2');readonly contentEl=this.modalEl.createDiv();selection:unknown;closeCount=0;constructor(readonly app:unknown){}open(){this.selection={win:{document:this.document},range:null,focusEl:null};(this as unknown as {onOpen:()=>void}).onOpen();}close(){this.closeCount++;(this as unknown as {onClose:()=>void}).onClose();}}
const source=readFileSync('src/group-organizer-view.ts','utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');
const GroupOrganizerModal=new Function('Modal','setIcon','themeSurface','cardFillHex','applyGroupMove','groupNodeName','outlineTree','planGroupMove','sectionContains',transformSync(source+'\nreturn GroupOrganizerModal;',{loader:'ts'}).code)(Modal,()=>{},()=>{},cardFillHex,applyGroupMove,groupNodeName,outlineTree,planGroupMove,sectionContains);
const n=(id:string,x=0,y=0):Card=>({id,kind:'text',text:id,x,y,width:120,height:80,color:'green'});
const g=(id:string,x=1000):Card=>({...n(id,x,1000),kind:'section',title:id,width:400,height:320});
function fixture(){let board:Board={...emptyBoard(),version:3,nodes:[n('selected'),g('甲组'),g('乙组',1800)]},commits=0;const host={board:()=>board,ids:new Set(['selected']),commit:(edit:(board:Board)=>void)=>{commits++;edit(board);}};const modal=new GroupOrganizerModal({},host);modal.open();const buttons=modal.contentEl.querySelectorAll('button') as Element[];return{modal,host,get board(){return board;},replace:(next:Board)=>{board=next;},get commits(){return commits;},input:modal.contentEl.querySelector('input') as Element,targets:modal.contentEl.querySelector('select') as Element,apply:buttons.find(button=>button.getAttribute('aria-label')==='移入分组')!,refresh:buttons.find(button=>button.getAttribute('aria-label')==='刷新预览')!,status:modal.contentEl.querySelector('.ts-group-status') as Element};}
function key(modal:InstanceType<typeof GroupOrganizerModal>,overrides:Record<string,unknown>={}){const event={key:'Enter',ctrlKey:true,metaKey:false,altKey:false,shiftKey:false,isComposing:false,keyCode:0,prevented:false,stopped:false,preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;},...overrides};modal.contentEl.listeners.get('keydown')?.(event);return event;}
test('opening previews without a write; one apply commits once and preserves the camera',()=>{const f=fixture(),camera={...f.board.viewport};assert.equal(f.commits,0);assert.equal(f.apply.disabled,false);assert.equal(f.modal.contentEl.querySelectorAll('svg').length,1);f.apply.click();f.apply.click();assert.equal(f.commits,1);assert.equal(f.modal.closeCount,1);assert.deepEqual(f.board.viewport,camera);assert.ok(sectionContains(f.board.nodes[1],f.board.nodes[0]));});
test('native Modal.open text selection cannot replace the selected board node ids',()=>{const f=fixture();assert.deepEqual(f.modal.selection,{win:{document:f.modal.document},range:null,focusEl:null});assert.deepEqual(f.targets.children.map(option=>option.value),['甲组','乙组']);assert.match(f.status.textContent,/移入 1 项/);f.host.ids.clear();f.modal.selection=null;f.refresh.click();assert.equal(f.apply.disabled,false);f.apply.click();assert.ok(sectionContains(f.board.nodes[1],f.board.nodes[0]));});
test('search and native target changes update preview and chosen destination',()=>{const f=fixture();f.input.value='乙';f.input.oninput?.();assert.equal(f.targets.children.length,1);assert.equal(f.targets.value,'乙组');f.apply.click();assert.ok(sectionContains(f.board.nodes[2],f.board.nodes[0]));const another=fixture();another.targets.value='乙组';another.targets.onchange?.();another.apply.click();assert.ok(sectionContains(another.board.nodes[2],another.board.nodes[0]));});
test('empty searches disable apply and clearing the filter restores a usable preview',()=>{const f=fixture();f.input.value='不存在';f.input.oninput?.();assert.equal(f.apply.disabled,true);key(f.modal);assert.equal(f.commits,0);f.input.value='';f.input.oninput?.();assert.equal(f.apply.disabled,false);assert.match(f.status.textContent,/移入 1 项/);});
test('Ctrl and Cmd Enter apply, composition and modified keys remain untouched',()=>{for(const overrides of [{},{ctrlKey:false,metaKey:true}]){const f=fixture();assert.equal(key(f.modal,overrides).prevented,true);assert.equal(f.commits,1);}for(const overrides of [{isComposing:true},{keyCode:229},{altKey:true},{shiftKey:true},{ctrlKey:false}]){const f=fixture();assert.equal(key(f.modal,overrides).prevented,false);assert.equal(f.commits,0);}});
test('stale geometry fails before moving, keeps dialog open and refresh makes it reviewable',()=>{const f=fixture();f.board.nodes[0].width=150;const before=JSON.stringify(f.board);f.apply.click();assert.equal(JSON.stringify(f.board),before);assert.equal(f.modal.closeCount,0);assert.equal(f.apply.disabled,true);assert.match(f.status.textContent,/已变化/);f.refresh.click();assert.equal(f.apply.disabled,false);f.apply.click();assert.equal(f.modal.closeCount,1);});
test('a removed target or newly locked member is rejected at commit time',()=>{for(const mutate of [(board:Board)=>{board.nodes=board.nodes.filter(node=>node.id!=='甲组');},(board:Board)=>{board.nodes[0].locked=true;}]){const f=fixture();mutate(f.board);const before=JSON.stringify(f.board);f.apply.click();assert.equal(JSON.stringify(f.board),before);assert.equal(f.modal.closeCount,0);assert.equal(f.apply.disabled,true);}});
test('a replaced board snapshot is read again, and a closed modal cannot write',()=>{const f=fixture(),next={...f.board,nodes:f.board.nodes.map(node=>({...node,width:node.width+10}))};f.replace(next);f.apply.click();assert.match(f.status.textContent,/已变化/);const closed=fixture();closed.modal.close();closed.apply.click();key(closed.modal);assert.equal(closed.commits,0);});
test('locked targets remain visible but cannot be chosen as automatic fallback',()=>{const f=fixture();f.board.nodes[1].locked=true;f.refresh.click();assert.equal(f.targets.children[0].disabled,true);assert.equal(f.targets.value,'乙组');f.apply.click();assert.ok(sectionContains(f.board.nodes[2],f.board.nodes[0]));});
test('SVG preview exposes a linked accessible title and contains both old and proposed bounds',()=>{const f=fixture(),svg=f.modal.contentEl.querySelector('svg') as Element,title=svg.querySelector('title')!;assert.equal(svg.getAttribute('aria-labelledby'),title.getAttribute('id'));assert.equal(svg.querySelectorAll('.ts-group-frame').length,1);assert.equal(svg.querySelectorAll('.ts-group-original-frame').length,1);});
