import test from 'node:test';
import assert from 'node:assert/strict';
import {Board,Card,History,emptyBoard} from '../src/model';
import {applyGroupMove,outlineTree,planGroupMove} from '../src/group-organizer';
import {sectionContains} from '../src/sections';
const n=(id:string,x=0,y=0,width=120,height=80):Card=>({id,kind:'text',text:id,x,y,width,height,color:'green'});
const g=(id:string,x=1000,y=1000,width=400,height=320):Card=>({...n(id,x,y,width,height),kind:'section',title:id});
const b=(nodes:Card[]):Board=>({...emptyBoard(),version:3,nodes});
const ids=(...names:string[])=>new Set(names);
const byId=(board:Board,id:string)=>board.nodes.find(node=>node.id===id)!;

test('move proposal preserves source, relative arrangement, all content types, edges and camera',()=>{
 const nodes:Card[]=(['text','card','image','pdf','board'] as const).map((kind,i)=>({...n(String(i),i*150,i*20),kind,...(kind==='card'?{file:'note.md'}:kind==='image'?{file:'image.png'}:kind==='pdf'?{file:'paper.pdf'}:kind==='board'?{file:'child.thoughtspace'}:{})}));const board=b([...nodes,g('target',1800,1200)]);board.edges=[{id:'e',from:'0',to:'4',label:'关联'}];const before=JSON.stringify(board),plan=planGroupMove(board,ids('0','1','2','3','4'),'target');assert.equal(JSON.stringify(board),before);applyGroupMove(board,plan);
 for(const node of nodes){assert.equal(node.x-JSON.parse(before).nodes[Number(node.id)].x,plan.delta.x);assert.equal(node.y-JSON.parse(before).nodes[Number(node.id)].y,plan.delta.y);assert.ok(sectionContains(byId(board,'target'),node));}assert.deepEqual(board.edges,JSON.parse(before).edges);assert.deepEqual(board.viewport,JSON.parse(before).viewport);
});
test('moving an open group includes nested frames and contents, never unrelated nodes',()=>{const board=b([g('source',0,0,500,500),g('inner',30,60,250,250),n('child',50,90),n('direct',320,100),n('outside',600,10),g('target',1200,100)]),before=JSON.stringify(board),plan=planGroupMove(board,ids('source','child'),'target');assert.deepEqual(new Set(plan.ids),ids('source','inner','child','direct'));applyGroupMove(board,plan);assert.deepEqual(byId(board,'outside'),JSON.parse(before).nodes[4]);assert.ok(sectionContains(byId(board,'source'),byId(board,'inner')));assert.ok(sectionContains(byId(board,'inner'),byId(board,'child')));});
test('a folded content branch carries external hidden descendants exactly once',()=>{const board=b([{...n('root'),branchFolded:true},n('child',200,30),n('grandchild',420,80),g('target')]);board.edges=[{id:'a',from:'root',to:'child',label:'',kind:'branch'},{id:'b',from:'child',to:'grandchild',label:'',kind:'branch'}];const plan=planGroupMove(board,ids('root','child'),'target');assert.equal(plan.ids.length,3);applyGroupMove(board,plan);assert.equal(byId(board,'child').x-byId(board,'root').x,200);assert.equal(byId(board,'grandchild').x-byId(board,'root').x,420);assert.equal(byId(board,'root').branchFolded,true);});
test('folded groups carry nested hidden group branches and material outside their bounds',()=>{const board=b([{...g('source',0,0,500,500),sectionFolded:true},g('inner',30,60,250,250),n('child',50,90),g('linked',600,0,250,200),n('linked-material',630,60),g('target',1600,1000)]);board.edges=[{id:'e',from:'inner',to:'linked',kind:'branch',label:''}];const plan=planGroupMove(board,ids('source'),'target');assert.deepEqual(new Set(plan.ids),ids('source','inner','child','linked','linked-material'));applyGroupMove(board,plan);assert.equal(byId(board,'source').sectionFolded,true);});
test('hidden content cannot be moved independently of its collapsed owner',()=>{for(const board of [b([{...g('source',0,0),sectionFolded:true},n('child',40,70),g('target')]),b([{...n('root'),branchFolded:true},n('child',300,0),g('target')])]){if(byId(board,'root'))board.edges=[{id:'e',from:'root',to:'child',kind:'branch',label:''}];assert.throws(()=>planGroupMove(board,ids('child'),'target'),/已隐藏/);}});
test('an overlapping open frame cannot split somebody else\'s folded movement unit',()=>{const board=b([g('source',250,0,400,400),{...n('root'),branchFolded:true},n('child',300,90),g('target')]);board.edges=[{id:'e',from:'root',to:'child',kind:'branch',label:''}];assert.throws(()=>planGroupMove(board,ids('source'),'target'),/其他折叠分支/);});
test('locked selected objects, nested members, folded descendants and targets block the whole move',()=>{
 const boards=[b([{...n('a'),locked:true},g('target')]),b([g('source',0,0),{...n('a',30,60),locked:true},g('target')]),b([n('a'),{...g('target'),locked:true}]),b([{...n('a'),branchFolded:true},{...n('descendant',300,0),locked:true},g('target')])];boards[3].edges=[{id:'e',from:'a',to:'descendant',kind:'branch',label:''}];for(const board of boards){const before=JSON.stringify(board);assert.throws(()=>planGroupMove(board,ids(board.nodes[0].id),'target'),/锁定/);assert.equal(JSON.stringify(board),before);}
});
test('self and geometric descendant destinations are rejected',()=>{const board=b([g('source',0,0,600,600),g('inner',50,80,300,300),n('child',90,120)]);for(const target of ['source','inner'])assert.throws(()=>planGroupMove(board,ids('source'),target),/自身或自己的子分组/);});
test('moving a branch ancestor into its linked child group rejects combined containment cycles',()=>{const board=b([g('parent',0,0),g('child',1000,1000)]);board.edges=[{id:'e',from:'parent',to:'child',kind:'branch',label:''}];assert.throws(()=>planGroupMove(board,ids('parent'),'child'),/循环/);});
test('existing target members never move and target expands only when needed',()=>{const board=b([n('a'),g('target',1000,1000,200,180),n('existing',1030,1060)]),old={...byId(board,'existing')},plan=planGroupMove(board,ids('a'),'target');assert.equal(plan.expanded,true);applyGroupMove(board,plan);assert.deepEqual(byId(board,'existing'),old);assert.ok(!sectionContains(byId(board,'a'),old));assert.equal(byId(board,'target').x,1000);assert.equal(byId(board,'target').y,1000);});
test('an obstacle below the frame selects a safe right-side placement',()=>{const board=b([n('a'),g('target',1000,1000,200,180),n('existing',1030,1060),n('below',1030,1180)]),plan=planGroupMove(board,ids('a'),'target');assert.ok(plan.items[0].x>=1182);assert.equal(plan.items[0].y,1060);applyGroupMove(board,plan);assert.equal(sectionContains(byId(board,'target'),byId(board,'below')),false);});
test('expansion never silently acquires unrelated objects on either side',()=>{const board=b([n('a'),g('target',1000,1000,200,180),n('existing',1030,1060),n('below',1030,1180),n('right',1190,1060)]);assert.throws(()=>planGroupMove(board,ids('a'),'target'),/其他对象/);});
test('nested destinations cannot grow beyond their enclosing frame',()=>{const board=b([n('a'),g('outer',980,980,240,220),g('target',1000,1000,200,180),n('existing',1030,1060)]);assert.throws(()=>planGroupMove(board,ids('a'),'target'),/上级分组/);});
test('full-target duplicates and missing selection have clear errors',()=>{const board=b([g('target'),n('inside',1030,1060)]);assert.throws(()=>planGroupMove(board,ids('inside'),'target'),/已在/);assert.throws(()=>planGroupMove(board,ids(),'target'),/先选择/);assert.throws(()=>planGroupMove(board,ids('gone'),'target'),/删除/);});
test('stale source, target, outside obstacles, folds and branch topology reject atomically',()=>{
 const mutations=[(board:Board)=>byId(board,'a').width++,(board:Board)=>byId(board,'target').locked=true,(board:Board)=>byId(board,'outside').x++,(board:Board)=>board.nodes.push(n('new',9000,9000)),(board:Board)=>{byId(board,'a').branchFolded=true;},(board:Board)=>board.edges.push({id:'b',from:'a',to:'outside',kind:'branch',label:''})];
 for(const mutate of mutations){const board=b([n('a'),g('target'),n('outside',8000,8000)]),plan=planGroupMove(board,ids('a'),'target');mutate(board);const before=JSON.stringify(board);assert.throws(()=>applyGroupMove(board,plan),/变化/);assert.equal(JSON.stringify(board),before);}
});
test('style and content changes survive an otherwise valid geometry preview',()=>{const board=b([n('a'),g('target')]),plan=planGroupMove(board,ids('a'),'target');byId(board,'a').text='edited';byId(board,'a').color='blue';byId(board,'target').title='renamed';applyGroupMove(board,plan);assert.equal(byId(board,'a').text,'edited');assert.equal(byId(board,'a').color,'blue');assert.equal(byId(board,'target').title,'renamed');});
test('tampered positions and invalid dimensions never partially write',()=>{for(const mutate of [(plan:ReturnType<typeof planGroupMove>)=>plan.items[0].x=NaN,(plan:ReturnType<typeof planGroupMove>)=>plan.target.next.width=Infinity,(plan:ReturnType<typeof planGroupMove>)=>plan.ids.push('unknown')]){const board=b([n('a'),g('target')]),plan=planGroupMove(board,ids('a'),'target'),before=JSON.stringify(board);mutate(plan);assert.throws(()=>applyGroupMove(board,plan),/无效/);assert.equal(JSON.stringify(board),before);}});
test('moving a group and target expansion undo in one history step',()=>{const board=b([g('source',0,0),n('a',50,90),g('target')]),before=JSON.stringify(board),history=new History(),plan=planGroupMove(board,ids('source'),'target');history.push(board);applyGroupMove(board,plan);assert.equal(JSON.stringify(history.undo(board)),before);});

test('outline uses the smallest enclosing group, stable spatial order and unique rows',()=>{const board=b([n('loose',0,700),g('outer',0,0,800,600),g('inner',40,70,250,250),n('a',60,100),n('direct',400,100)]),rows=outlineTree(board);assert.deepEqual(rows.map(row=>[row.node.id,row.depth,row.parentId]),[['outer',0,undefined],['inner',1,'outer'],['a',2,'inner'],['direct',1,'outer'],['loose',0,undefined]]);assert.equal(rows[0].childCount,2);assert.equal(rows[0].descendantCount,3);});
test('outline collapse hides only descendants, filtering retains and opens ancestors',()=>{const board=b([g('outer',0,0,800,600),g('inner',40,70,250,250),{...n('a',60,100),text:'重点结论'},n('other',400,100)]);assert.deepEqual(outlineTree(board,{collapsed:ids('outer')}).map(row=>row.node.id),['outer']);const rows=outlineTree(board,{query:'重点',collapsed:ids('outer','inner')});assert.deepEqual(rows.map(row=>row.node.id),['outer','inner','a']);assert.deepEqual(rows.map(row=>row.matched),[false,false,true]);assert.equal(rows[0].expanded,true);assert.equal(rows[1].expanded,true);});
test('kind and token filters intersect, custom names and Unicode search are normalized',()=>{const board=b([g('outer',0,0,900,900),{...n('file',50,100),kind:'card',file:'notes/ＡＢＣ.md'},n('text',400,100)]);assert.deepEqual(outlineTree(board,{kind:'card',query:'abc title',name:()=> 'TITLE'}).map(row=>row.node.id),['outer','file']);assert.deepEqual(outlineTree(board,{kind:'image'}),[]);});
test('overlapping and coincident frames have deterministic ownership without cycles',()=>{const board=b([g('z',0,0,400,400),g('a',0,0,400,400),g('overlap',100,0,400,400),n('child',150,80)]),rows=outlineTree(board);assert.equal(rows.find(row=>row.node.id==='child')?.parentId,'a');assert.equal(rows.filter(row=>row.node.kind==='section').every(row=>row.depth===0),true);const reverse=outlineTree({...board,nodes:[...board.nodes].reverse()});assert.deepEqual(rows.map(row=>[row.node.id,row.depth]),reverse.map(row=>[row.node.id,row.depth]));});
test('deeply nested outlines and broad large boards are iterative',()=>{const count=12000,board=b(Array.from({length:count},(_,i)=>g(String(i),i,i,(count-i)*2+100,(count-i)*2+100))),rows=outlineTree(board,{query:String(count-1),name:node=>node.id});assert.equal(rows.length,count);assert.equal(rows.at(-1)?.depth,count-1);assert.equal(rows[0].descendantCount,count-1);const loose=b(Array.from({length:30000},(_,i)=>n(`n${i}`,i*150)));assert.equal(outlineTree(loose).length,30000);});
