import {test} from 'node:test';import {strict as assert} from 'node:assert';
import {createdNoteDay,createdNoteLink,syncCreatedNotes,CREATED_START,CREATED_END} from '../src/journal-links-model';
import {localDay} from '../src/filing';
test('Creation day follows local creation time, not modified time',()=>{const time=new Date(2026,8,8,0,1).getTime();assert.equal(createdNoteDay({path:'项目/笔记.md',stat:{ctime:time}},'日记'),localDay(new Date(time)));assert.equal(createdNoteDay({path:'a.md',stat:{ctime:0}},'日记'),undefined);});
test('Daily and period journals, installation backups and attachments cannot self-index',()=>{for(const path of ['日记/2026/09/2026-09-08.md','日记/周期/2026/2026-W37 周记.md','ThoughtSpace-plugin-backups/v1/old.md','image.png'])assert.equal(createdNoteDay({path,stat:{ctime:Date.now()}},'日记'),undefined);assert.ok(createdNoteDay({path:'日记研究/材料.md',stat:{ctime:Date.now()}},'日记'));});
test('Auto links preserve exact user frontmatter, text and suffix while removing stale paths',()=>{const original='---\r\ntags: [日记]\r\n---\r\n# 我的正文\r\n\r\n';const withLinks=syncCreatedNotes(original,['材料/A.md','材料/A.md','材料/B.md'])+'\n人工追加保留';assert.ok(withLinks.startsWith(original));assert.equal(withLinks.split('[[材料/A.md|A]]').length,2);const renamed=syncCreatedNotes(withLinks,['材料/A新名.md']);assert.ok(renamed.startsWith(original));assert.ok(renamed.endsWith('\n人工追加保留'));assert.ok(!renamed.includes('[[材料/B.md'));assert.ok(renamed.includes('[[材料/A新名.md|A新名]]'));assert.equal(syncCreatedNotes(renamed,['材料/A新名.md']),renamed);});
test('No-note sync does not change pristine diary; deleting last indexed note clears only managed links',()=>{assert.equal(syncCreatedNotes('保留\n',[]),'保留\n');const text=syncCreatedNotes(syncCreatedNotes('保留\n',['a.md']),[]);assert.ok(text.startsWith('保留\n'));assert.ok(!text.includes('[[a.md'));assert.ok(text.includes('当天还没有新建笔记'));});
test('Broken or duplicate managed markers fail without overwriting prose',()=>{for(const text of [CREATED_START+'保留',CREATED_END,CREATED_END+CREATED_START,CREATED_START+CREATED_START+CREATED_END,CREATED_START+CREATED_END+CREATED_END])assert.throws(()=>syncCreatedNotes(text,['a.md']));});
test('File links disambiguate same titles by full path and escape special filenames',()=>{assert.equal(createdNoteLink('A/同名.md'),'[[A/同名.md|同名]]');assert.equal(createdNoteLink('B/同名.md'),'[[B/同名.md|同名]]');const link=createdNoteLink('材料/问题 #1 [初稿].md');assert.ok(link.includes('%23'));assert.ok(link.toLowerCase().includes('%5b'));assert.ok(!link.includes('[['));});
