import {test} from 'node:test';import assert from 'node:assert/strict';
import {Board,Card} from '../src/model';
import {planLayout,resolveLayoutScope,layoutChanges,applyLayout,LayoutOptions,planSectionLayout} from '../src/layout-planner';
const n=(id:string,x:number,y:number,w=100,h=80):Card=>({id,kind:'text',text:id,x,y,width:w,height:h,color:'green'});
const board=():Board=>({version:3,viewport:{x:0,y:0,zoom:1},nodes:[{...n('frame',0,0,500,500),kind:'section',title:'Topic'},n('inside',40,80),n('inside2',260,180),n('outside',600,0),n('partial',480,480),{...n('locked',900,300),locked:true}],edges:[]});
const options:LayoutOptions={mode:'grid',columns:2,gap:40,sort:'position',anchor:'center'};
test('broad layout scopes preserve framed content and do not mutate selection',()=>{const b=board(),selected=new Set(['inside']),before=JSON.stringify(b),s=resolveLayoutScope(b,'loose',selected);assert.deepEqual([...s.ids],['outside','partial','locked']);assert.deepEqual([...selected],['inside']);assert.equal(JSON.stringify(b),before);});
test('visible scope intersects viewport in world coordinates and excludes framed content',()=>{const s=resolveLayoutScope(board(),'visible',new Set(),{x:550,y:0,width:150,height:200});assert.deepEqual([...s.ids],['outside']);assert.equal(resolveLayoutScope(board(),'visible',new Set()).ids.size,0);});
test('explicit frame and selected frame use section layout; deleted frames fail safely',()=>{const b=board();assert.equal(resolveLayoutScope(b,'section:frame',new Set()).sectionId,'frame');assert.equal(resolveLayoutScope(b,'selection',new Set(['frame'])).sectionId,'frame');assert.throws(()=>resolveLayoutScope(b,'section:missing',new Set()),/删除/);assert.deepEqual([...resolveLayoutScope(b,'selection',new Set(['inside','missing'])).ids],['inside']);});
test('loose layout application leaves frame, members and locked objects unchanged',()=>{const b=board(),before=structuredClone(b),scope=resolveLayoutScope(b,'loose',new Set()),p=planLayout(b,scope.ids,options);applyLayout(b,p);for(const id of ['frame','inside','inside2','locked'])assert.deepEqual(b.nodes.find(n=>n.id===id),before.nodes.find(n=>n.id===id));});
test('six alignments preserve perpendicular positions and align exact edges or centers',()=>{for(const mode of ['alignLeft','alignCenter','alignRight','alignTop','alignMiddle','alignBottom'] as const){const b:Board={...board(),nodes:[n('a',0,0,100,80),n('b',240,160,160,120),n('c',520,400,80,60)]};const p=planLayout(b,new Set(b.nodes.map(n=>n.id)),{...options,mode});const horizontal=['alignLeft','alignCenter','alignRight'].includes(mode);const values=p.items.map(n=>mode==='alignLeft'?n.x:mode==='alignRight'?n.x+n.width:mode==='alignCenter'?n.x+n.width/2:mode==='alignTop'?n.y:mode==='alignBottom'?n.y+n.height:n.y+n.height/2);assert.ok(values.every(x=>x===values[0]));for(const node of p.items){const old=b.nodes.find(n=>n.id===node.id)!;assert.equal(horizontal?node.y:node.x,horizontal?old.y:old.x);assert.equal(node.width,old.width);assert.equal(node.height,old.height);}}});
test('distribution handles mixed sizes, preserves cross-axis coordinates, and exact equal gaps',()=>{for(const mode of ['distributeX','distributeY'] as const){const b={...board(),nodes:[n('c',500,600,80,60),n('a',0,0,100,80),n('b',210,200,160,120)]};const p=planLayout(b,new Set(b.nodes.map(n=>n.id)),{...options,mode,anchor:'corner'}),horizontal=mode==='distributeX';assert.deepEqual(p.items.map(n=>n.id),['a','b','c']);p.items.forEach((node,i)=>{const old=b.nodes.find(n=>n.id===node.id)!;assert.equal(horizontal?node.y:node.x,horizontal?old.y:old.x);if(i){const prev=p.items[i-1];assert.equal(horizontal?node.x-prev.x-prev.width:node.y-prev.y-prev.height,40);}});}});
test('alignment ignores unused gap while ordinary layouts still validate gap',()=>{const b=board(),ids=new Set(['outside','partial']);assert.doesNotThrow(()=>planLayout(b,ids,{...options,mode:'alignLeft',gap:NaN}));assert.throws(()=>planLayout(b,ids,{...options,gap:NaN}));});
test('changed count identifies no-op plans and alignment snapshots reject stale source',()=>{const b={...board(),nodes:[n('a',0,0),n('b',0,200)]},ids=new Set(['a','b']),p=planLayout(b,ids,{...options,mode:'alignLeft'});assert.equal(layoutChanges(p),0);b.nodes[1].x=100;assert.throws(()=>applyLayout(b,p),/变化/);});
test('section alignment refits frame and keeps unrelated content',()=>{const b=board(),outside=structuredClone(b.nodes.find(n=>n.id==='outside'));const p=planSectionLayout(b,'frame',{...options,mode:'alignLeft'});applyLayout(b,p);assert.equal(b.nodes.find(n=>n.id==='inside')!.x,b.nodes.find(n=>n.id==='inside2')!.x);assert.deepEqual(b.nodes.find(n=>n.id==='outside'),outside);});

import {layoutHasChanges} from '../src/layout-planner';
test('no-op layout has no write while changed node positions are detected',()=>{const b={...board(),nodes:[n('a',0,0),n('b',0,200)]},ids=new Set(['a','b']);assert.equal(layoutHasChanges(planLayout(b,ids,{...options,mode:'alignLeft'})),false);assert.equal(layoutHasChanges(planLayout(b,ids,{...options,mode:'row'})),true);});
test('frame-only resizing still counts as an applicable layout change',()=>{const b={...board(),nodes:[{...n('frame',0,0,900,900),kind:'section' as const},n('a',30,60),n('b',30,200)]};const p=planSectionLayout(b,'frame',{...options,mode:'alignLeft'});assert.equal(layoutChanges(p),0);assert.equal(layoutHasChanges(p),true);});
