import {test} from 'node:test';import assert from 'node:assert/strict';import {Board,Card,emptyBoard,History} from '../src/model';import{planLayout,planSectionLayout,applyLayout,layoutBounds,LayoutOptions}from'../src/layout-planner';
const n=(id:string,x:number,y:number,w=160,h=100):Card=>({id,kind:'text',text:id,x,y,width:w,height:h,color:'green'});const b=():Board=>({...emptyBoard(),version:3,nodes:[n('C',80,20,250,120),n('A',500,200,120,300),n('B',300,500,190,80)],edges:[{id:'e',from:'C',to:'A',label:'依据'}]});const opts:LayoutOptions={mode:'grid',columns:2,gap:40,sort:'title',anchor:'corner'};const ids=(b:Board)=>new Set(b.nodes.map(n=>n.id));const overlap=(a:Card,b:Card)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
test('layout planning never mutates source geometry or edges',()=>{const board=b(),before=JSON.stringify(board);const p=planLayout(board,ids(board),opts);assert.equal(JSON.stringify(board),before);assert.deepEqual(p.items.map(n=>n.id),['A','B','C']);assert.equal(p.items[1].x-p.items[0].x,290);});
test('grid respects tallest row and varying sizes',()=>{const board=b(),p=planLayout(board,ids(board),opts);assert.equal(p.items[2].y,p.items[0].y+340);assert.ok(p.items.every((a,i)=>p.items.slice(i+1).every(b=>!overlap(a,b))));});
test('masonry chooses shortest column while preserving sizes',()=>{const board=b(),p=planLayout(board,ids(board),{...opts,mode:'masonry'});assert.equal(p.items[2].x,p.items[1].x);assert.equal(p.items[2].y,p.items[1].y+120);assert.deepEqual(p.items.map(n=>n.width),[120,190,250]);});
test('center anchor preserves selection bounding center',()=>{const board=b(),a=layoutBounds(board.nodes),p=planLayout(board,ids(board),{...opts,anchor:'center'}).bounds;assert.equal(a.x+a.width/2,p.x+p.width/2);assert.equal(a.y+a.height/2,p.y+p.height/2);});
test('color type and review lanes use actual object metadata',()=>{const board=b();board.nodes[1].color='blue';board.nodes[1].review='done';board.nodes[2]={...board.nodes[2],kind:'image',file:'photo.png'};assert.equal(planLayout(board,ids(board),{...opts,mode:'color'}).lanes.length,2);assert.deepEqual(planLayout(board,ids(board),{...opts,mode:'kind'}).lanes.map(l=>l.label),['文本','图片']);assert.equal(planLayout(board,ids(board),{...opts,mode:'review'}).lanes.length,2);});
test('locked and section objects are excluded and remain unchanged on apply',()=>{const board=b();board.nodes.push({...n('locked',0,0),locked:true},{...n('group',0,0),kind:'section',title:'组'});const before=JSON.stringify(board.nodes.slice(3));const p=planLayout(board,ids(board),opts);assert.equal(p.skipped,2);applyLayout(board,p);assert.equal(JSON.stringify(board.nodes.slice(3)),before);});
test('applying moves only coordinates and history restores them',()=>{const board=b(),old=JSON.stringify(board),history=new History(),p=planLayout(board,ids(board),opts);history.push(board);applyLayout(board,p);assert.deepEqual(board.edges,JSON.parse(old).edges);assert.equal(JSON.stringify(history.undo(board)),old);});
test('stale geometry and newly locked nodes are rejected atomically',()=>{for(const change of [(n:Card)=>n.width++,(n:Card)=>n.locked=true]){const board=b(),p=planLayout(board,ids(board),opts);change(board.nodes[2]);const before=JSON.stringify(board);assert.throws(()=>applyLayout(board,p),/已变化/);assert.equal(JSON.stringify(board),before);}});
test('invalid input and too few eligible objects have clear errors',()=>{const board=b();for(const values of [{gap:0},{columns:0},{columns:2.5},{gap:NaN}])assert.throws(()=>planLayout(board,ids(board),{...opts,...values}));assert.throws(()=>planLayout(board,new Set(['C']),opts));});
test('1000-object proposals are bounded and deterministic',()=>{const board={...b(),nodes:Array.from({length:1000},(_,i)=>n(String(i),i%20*170,Math.floor(i/20)*110))};const p=planLayout(board,ids(board),{...opts,mode:'masonry',columns:10});assert.equal(p.items.length,1000);assert.deepEqual(p,planLayout(board,ids(board),{...opts,mode:'masonry',columns:10}));});

test('row and column pack varying dimensions without overlaps',()=>{for(const mode of ['row','column'] as const){const board=b(),p=planLayout(board,ids(board),{...opts,mode});assert.ok(p.items.every((a,i)=>p.items.slice(i+1).every(b=>!overlap(a,b))));for(let i=1;i<p.items.length;i++){const a=p.items[i-1],next=p.items[i];assert.equal(mode==='row'?next.x-a.x-a.width:next.y-a.y-a.height,40);}}});
const grouped=():Board=>{const board=b();board.nodes.unshift({...n('section',0,0,1200,900),kind:'section',title:'研究材料'});board.nodes.push(n('outside',2400,0));return board;};
test('section layout fits its frame and leaves outside objects and connections unchanged',()=>{const board=grouped(),before=JSON.stringify(board),p=planSectionLayout(board,'section',opts);assert.equal(JSON.stringify(board),before);assert.equal(p.items.length,3);assert.equal(p.section!.next.x,0);assert.equal(p.section!.next.y,0);applyLayout(board,p);const frame=board.nodes[0];assert.ok(p.items.every(n=>n.x>=frame.x+30&&n.y>=frame.y+60&&n.x+n.width<=frame.x+frame.width-30&&n.y+n.height<=frame.y+frame.height-30));assert.deepEqual(board.nodes.at(-1),JSON.parse(before).nodes.at(-1));assert.deepEqual(board.edges,JSON.parse(before).edges);});
test('section layout is restored in one history operation',()=>{const board=grouped(),before=JSON.stringify(board),h=new History(),p=planSectionLayout(board,'section',{...opts,mode:'column'});h.push(board);applyLayout(board,p);assert.equal(JSON.stringify(h.undo(board)),before);});
test('locked members and nested sections block section layout',()=>{for(const mutate of [(b:Board)=>{b.nodes[1].locked=true;},(b:Board)=>{b.nodes.push({...n('nested',40,40,800,600),kind:'section'});},(b:Board)=>{b.nodes[0].locked=true;}]){const board=grouped();mutate(board);assert.throws(()=>planSectionLayout(board,'section',opts));}});
test('new or removed section members invalidate the entire proposal',()=>{for(const mutate of [(b:Board)=>{b.nodes.push(n('new',600,500));},(b:Board)=>{b.nodes[1].x=3000;},(b:Board)=>{b.nodes[0].width++;}]){const board=grouped(),p=planSectionLayout(board,'section',opts);mutate(board);const before=JSON.stringify(board);assert.throws(()=>applyLayout(board,p),/变化/);assert.equal(JSON.stringify(board),before);}});
test('invalid frame geometry cannot partially apply content positions',()=>{const board=grouped(),p=planSectionLayout(board,'section',opts),before=JSON.stringify(board);p.section!.next.width=NaN;assert.throws(()=>applyLayout(board,p),/无效/);assert.equal(JSON.stringify(board),before);});

test('modes without columns do not inherit an invalid disabled column field',()=>{const board=b();for(const mode of ['row','column','kind','color','review'] as const)assert.equal(planLayout(board,ids(board),{...opts,mode,columns:NaN}).items.length,3);});

test('connection layout keeps transitive and cyclic relations together, isolates unlinked content',()=>{const board={...b(),nodes:[n('A',0,0),n('B',400,0),n('C',800,0),n('D',0,400),n('E',400,400),n('F',800,400)],edges:[{id:'ab',from:'A',to:'B',label:''},{id:'bc',from:'B',to:'C',label:''},{id:'ca',from:'C',to:'A',label:''},{id:'de',from:'D',to:'E',label:''}]};const before=JSON.stringify(board),p=planLayout(board,ids(board),{...opts,mode:'connections'});assert.equal(p.lanes.length,3);assert.match(p.lanes[0].label,/3 项/);assert.match(p.lanes[1].label,/2 项/);assert.match(p.lanes[2].label,/未连接/);assert.ok(p.items.every((a,i)=>p.items.slice(i+1).every(b=>!overlap(a,b))));assert.equal(JSON.stringify(board),before);applyLayout(board,p);assert.deepEqual(board.edges,JSON.parse(before).edges);});
test('clustering ignores edge direction, duplicates, self loops and paths outside selection',()=>{const board=b();board.nodes.push(n('external',900,900));board.edges.push({id:'cx',from:'C',to:'external',label:''},{id:'xb',from:'external',to:'B',label:''});const selected=new Set(['A','B','C']),p=planLayout(board,selected,{...opts,mode:'connections'});assert.equal(p.lanes.length,2);board.edges.reverse();board.edges.push({id:'duplicate',from:'A',to:'C',label:''},{id:'self',from:'B',to:'B',label:''});const q=planLayout(board,selected,{...opts,mode:'connections'});assert.deepEqual(q,p);applyLayout(board,p);});
test('new internal relations reject a clustered preview before any geometry changes',()=>{const board=b(),p=planLayout(board,ids(board),{...opts,mode:'connections'});board.edges.push({id:'new',from:'B',to:'C',label:''});const before=JSON.stringify(board);assert.throws(()=>applyLayout(board,p),/连线关系已变化/);assert.equal(JSON.stringify(board),before);});
test('removing a relation invalidates clustering but not a geometry-only grid proposal',()=>{const board=b(),p=planLayout(board,ids(board),{...opts,mode:'connections'}),grid=planLayout(board,ids(board),opts);board.edges=[];assert.throws(()=>applyLayout(board,p),/连线关系已变化/);applyLayout(board,grid);});
test('locked bridge nodes do not connect separate movable clusters',()=>{const board=b();board.nodes[1].locked=true;board.edges.push({id:'ab',from:'A',to:'B',label:''});const p=planLayout(board,ids(board),{...opts,mode:'connections'});assert.equal(p.items.length,2);assert.equal(p.lanes.length,1);assert.match(p.lanes[0].label,/未连接 · 2/);});
test('section clustering offsets labels with members and preserves an atomic undo',()=>{const board=grouped(),p=planSectionLayout(board,'section',{...opts,mode:'connections'}),before=JSON.stringify(board),h=new History();assert.ok(p.lanes.every(l=>l.y!>=60));h.push(board);applyLayout(board,p);assert.equal(JSON.stringify(h.undo(board)),before);});
test('1000 nodes with 500 components use a two-dimensional packing without overlap',()=>{const board={...b(),nodes:Array.from({length:1000},(_,i)=>n(String(i),i*20,i*10,80+i%4*30,60+i%3*20)),edges:Array.from({length:500},(_,i)=>({id:String(i),from:String(i*2),to:String(i*2+1),label:''}))};const p=planLayout(board,ids(board),{...opts,mode:'connections'});assert.equal(p.items.length,1000);assert.equal(p.lanes.length,500);assert.ok(p.items.every((a,i)=>p.items.slice(i+1).every(b=>!overlap(a,b))));assert.ok(p.bounds.width/p.bounds.height<5);assert.deepEqual(planLayout(board,ids(board),{...opts,mode:'connections'}),p);});
