import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import {cleanLayoutPresets,saveLayoutPreset,renameLayoutPreset,removeLayoutPreset,LayoutPreset} from '../src/layout-presets';
import {LayoutOptions} from '../src/layout-planner';
const options:LayoutOptions={mode:'grid',columns:3,gap:40,sort:'position',anchor:'center'};
function harness(){const source=readFileSync('src/layout-planner-view.ts','utf8'),start=source.indexOf(' private async persistPreset('),end=source.indexOf(' /** Coalesce input events',start);assert.ok(start>0&&end>start);const deps={cleanLayoutPresets,saveLayoutPreset,renameLayoutPreset,removeLayoutPreset,Notice:class{}};const View=new Function(...Object.keys(deps),transformSync(`class View{${source.slice(start,end)}}return View;`,{loader:'ts'}).code)(...Object.values(deps));const view=new View();let items:LayoutPreset[]=[],status='',fail=false;Object.assign(view,{host:{presets:()=>items,savePresets:async(next:LayoutPreset[])=>{if(fail)throw Error('disk unavailable');items=next;}},presetName:{value:'Grid'},selectedPreset:'',presetBusy:false,presetStamp:'[]',closed:false,options,presetStatus:{setText:(value:string)=>status=value},renderPresets(){view.presetStamp=JSON.stringify(cleanLayoutPresets(items));}});return{view,get items(){return items;},set items(next:LayoutPreset[]){items=next;},get status(){return status;},set fail(value:boolean){fail=value;}};}
test('save failures keep the editable layout and name and allow retry without closing the modal',async()=>{const h=harness();h.fail=true;await h.view.persistPreset('create');assert.match(h.status,/保存失败.*disk unavailable.*重试/);assert.equal(h.view.presetBusy,false);assert.equal(h.view.closed,false);assert.equal(h.view.presetName.value,'Grid');assert.deepEqual(h.items,[]);h.fail=false;await h.view.persistPreset('create');assert.equal(h.items.length,1);assert.equal(h.view.selectedPreset,cleanLayoutPresets(h.items)[0].id);assert.equal(h.status,'布局预设已保存');});
test('another window changing the list requires a refreshed choice before overwrite',async()=>{const h=harness();h.items=saveLayoutPreset([],'Original',options);h.view.selectedPreset=h.items[0].id;h.view.renderPresets();h.items=renameLayoutPreset(h.items,h.items[0].id,'Changed elsewhere');const before=JSON.stringify(h.items);await assert.rejects(()=>h.view.persistPreset('replace'),/其他窗口更新/);assert.equal(JSON.stringify(h.items),before);assert.equal(h.view.presetStamp,before);});
test('pending preset saves reject duplicate button activation',async()=>{const h=harness();let resolve!:()=>void,calls=0;h.view.host.savePresets=async()=>{calls++;await new Promise<void>(done=>resolve=done);};const pending=h.view.persistPreset('create');assert.equal(h.view.presetBusy,true);await h.view.persistPreset('create');assert.equal(calls,1);resolve();await pending;assert.equal(h.view.presetBusy,false);});
