import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';import {emptyBoard,uid,type Card} from '../src/model';
const source=readFileSync('src/main.ts','utf8'),start=source.indexOf('  private async createLinkedContent('),end=source.indexOf('  private createConnection(',start);
let current:Menu|undefined,picker:NotePicker|undefined;
class Menu{hidden=false;callback?:()=>void;onHide(fn:()=>void){this.callback=fn;}hide(){this.hidden=true;this.callback?.();}setUseNativeMenu(){return this;}items:{title:string;run:()=>void}[]=[];addItem(fn:(i:any)=>void){const row={title:'',run:()=>{},setTitle(t:string){this.title=t;return this;},setIcon(){return this;},onClick(run:()=>void){this.run=run;return this;}};fn(row);this.items.push(row);}showAtPosition(){current=this;}}
class NotePicker{constructor(_app:unknown,readonly pick:(f:any)=>unknown){}open(){picker=this;}}
const pending:Promise<unknown>[]=[];const deps={Menu,NotePicker,uid,isPdfFile:(p:string)=>p.endsWith('.pdf'),act:(fn:()=>unknown)=>pending.push(Promise.resolve().then(fn))};
const View=new Function(...Object.keys(deps),transformSync(`class View{${source.slice(start,end)}};return View`,{loader:'ts'}).code)(...Object.values(deps));
function fixture(){current=undefined;picker=undefined;pending.length=0;const node:Card={id:'source',kind:'text',text:'source',x:0,y:0,width:100,height:100,color:'sand'},board={...emptyBoard(),nodes:[node]},files=new Map<string,any>(),edited:string[]=[],v=new View();const owner={board,blocked:false,change(fn:(b:typeof board)=>void){fn(board);}};Object.assign(v,{session:owner,app:{vault:{getAbstractFileByPath:(p:string)=>files.get(p)}},requireOwner(o:unknown){if(o!==v.session||owner.blocked)throw Error('stale');return owner;},plugin:{settings:{defaultTextSize:16,defaultEdgeStyle:'curve',defaultEdgeDirection:'forward'}},updateSelection(){},startInlineEdit:async(id:string)=>edited.push(id)});return{v,board,owner,files,edited,open:()=>v.chooseLinkedContent(owner,'source','right',{x:400,y:200},{x:400,y:200})};}
test('closing the type menu or file picker creates neither nodes nor edges',async()=>{const f=fixture();f.open();assert.equal(f.board.nodes.length,1);assert.equal(f.board.edges.length,0);current!.items[2].run();await Promise.all(pending);assert.ok(picker);assert.equal(f.board.nodes.length,1);assert.equal(f.board.edges.length,0);});
test('text and table choices create one node and its edge together, and duplicate activation is ignored',async()=>{for(const choice of [0,1]){const f=fixture();f.open();current!.items[choice].run();current!.items[choice].run();await Promise.all(pending);assert.equal(f.board.nodes.length,2);assert.equal(f.board.edges.length,1);assert.equal(f.board.edges[0].to,f.board.nodes[1].id);assert.equal(f.board.edges[0].fromSide,'right');assert.equal(f.edited.length,1);assert.equal(f.board.nodes[1].text?.includes('|'),choice===1);}});
test('existing Markdown and PDF remain references with no new vault file or inline edit',async()=>{for(const path of ['现有 笔记.md','资料.pdf']){const f=fixture(),file={path};f.files.set(path,file);f.open();current!.items[2].run();await Promise.all(pending);await picker!.pick(file);await picker!.pick(file);assert.equal(f.board.nodes.length,2);assert.equal(f.board.nodes[1].file,path);assert.equal(f.board.nodes[1].kind,path.endsWith('.pdf')?'pdf':'card');assert.equal(f.edited.length,0);assert.equal(f.files.size,1);}});
test('stale source, failed editor commit and moved file cannot leave a partial connection',async()=>{
 const f=fixture();f.board.nodes=[];await assert.rejects(()=>f.v.createLinkedContent(f.owner,'source','right',{x:0,y:0}));assert.equal(f.board.edges.length,0);
 const g=fixture();g.v.inline={commit:async()=>false};await g.v.createLinkedContent(g.owner,'source','right',{x:0,y:0});assert.equal(g.board.nodes.length,1);
 const h=fixture();await assert.rejects(()=>h.v.createLinkedContent(h.owner,'source','right',{x:0,y:0},'',{path:'gone.md'}));assert.equal(h.board.nodes.length,1);assert.equal(h.board.edges.length,0);
});

test('reopening the menu hides the previous instance without creating content',()=>{const f=fixture();f.open();const previous=current!;f.open();assert.equal(previous.hidden,true);assert.notEqual(current,previous);assert.equal(f.board.nodes.length,1);});
