import{test}from'node:test';import assert from'node:assert/strict';import{extractFragments,excerptDocuments,MaterialProgress,materialKey,MaterialImportResult}from'../src/materials';
const fragments=extractFragments('# H\n\nFirst **idea**.\n\n> Quote\n\n- [ ] task').fragments;
const result:MaterialImportResult={ids:['n1'],files:['one.md'],boardPath:'one.thoughtspace',groupId:'g'};
test('individual excerpts retain one source citation per note',()=>{const notes=excerptDocuments(fragments,'[[Source]]');assert.equal(notes.length,3);assert.ok(notes.every(n=>n.body.includes('来源：[[Source]]')));assert.ok(notes[0].body.includes('**idea**'));assert.ok(notes[2].body.includes('- [ ] task'));});
test('merge produces one named note containing every original passage and its own location',()=>{const [note]=excerptDocuments(fragments,'[[Source]]',{mergeTitle:'My concept'});assert.equal(note.title,'My concept');assert.equal(note.body.match(/来源：/g)?.length,3);assert.ok(note.body.indexOf('First')<note.body.indexOf('Quote'));assert.ok(note.body.includes('第 3–3 行'));assert.ok(note.body.includes('第 7–7 行'));});
test('merged title must be explicit and cannot inject a new heading line',()=>{assert.throws(()=>excerptDocuments(fragments,'[[S]]',{mergeTitle:' '}));assert.equal(excerptDocuments(fragments,'[[S]]',{mergeTitle:'One\nTwo'})[0].title,'One Two');});
test('custom title applies to a single excerpt without changing its body',()=>{const [note]=excerptDocuments([fragments[0]],'[[S]]',{title:'My title'});assert.equal(note.title,'My title');assert.ok(note.body.includes(fragments[0].body+'\n\n> 来源：'));assert.match(note.body.trimEnd().split('\n').at(-1)!,/^> 来源：/);assert.notEqual(excerptDocuments(fragments,'[[S]]',{title:'Wrong batch title'})[0].title,'Wrong batch title');});
test('progress identifies same content after line offsets change',()=>{const progress=new MaterialProgress(),source={};progress.record(source,[fragments[0]],result);assert.equal(progress.get(source,{...fragments[0],id:'10:10',start:10,end:10},result.boardPath),result);});
test('modified text, another source, or another board is not silently deduplicated',()=>{const progress=new MaterialProgress(),source={};progress.record(source,fragments,result);assert.equal(progress.get(source,{...fragments[0],body:'new'},result.boardPath),undefined);assert.equal(progress.get({},fragments[0],result.boardPath),undefined);assert.equal(progress.get(source,fragments[0],'other.thoughtspace'),undefined);});
test('merged result lets every selected fragment locate its concept note',()=>{const p=new MaterialProgress(),source={};p.record(source,fragments,result);for(const f of fragments)assert.deepEqual(p.get(source,f,result.boardPath)?.ids,['n1']);});
test('material source identity survives file path changes',()=>{const p=new MaterialProgress(),source={path:'old.md'};p.record(source,fragments,result);source.path='new.md';assert.equal(p.get(source,fragments[1],result.boardPath),result);});
test('progress evicts old sources instead of retaining an unbounded vault index',()=>{const p=new MaterialProgress(2),a={},b={},c={};p.record(a,fragments,result);p.record(b,fragments,result);p.record(c,fragments,result);assert.equal(p.size,2);assert.equal(p.get(a,fragments[0],result.boardPath),undefined);p.clear();assert.equal(p.size,0);});
test('identical passages in distinct chapters keep independent progress',()=>assert.notEqual(materialKey(fragments[0]),materialKey({...fragments[0],heading:'Other'})));

test('concept notes distinguish personal interpretation from source excerpts',()=>{const [n]=excerptDocuments(fragments,'[[Source]]',{mergeTitle:'Concept',insight:'My own **interpretation**.'});assert.ok(n.body.includes('## 我的理解\n\nMy own **interpretation**.'));assert.ok(n.body.indexOf('## 我的理解')<n.body.indexOf('## 来源摘录'));assert.equal(n.body.match(/来源：/g)?.length,3);assert.ok(!excerptDocuments(fragments,'[[S]]',{insight:'  '})[0].body.includes('## 我的理解'));});

test('merged excerpt sources follow all selected passages',()=>{const [note]=excerptDocuments(fragments,'[[Source]]',{mergeTitle:'Concept'});for(const f of fragments)assert.ok(note.body.indexOf(f.body)<note.body.indexOf('> 来源：'));});
