import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';import * as model from '../src/model';import * as mindmap from '../src/mindmap';import {presetMindmap,insertPreset} from '../src/mindmap-presets';import {editTopic} from '../src/mindmap-editor';
// Execute the actual Session.change method; fake only persistence and notifications.
function session(board:model.Board){const source=readFileSync('src/main.ts','utf8'),start=source.indexOf('  change(fn:'),end=source.indexOf('\n  undo(',start),body=source.slice(start,end),exports={...model,...mindmap,Notice:class{}};const Session=new Function(...Object.keys(exports),transformSync('class Session{'+body+'};return Session',{loader:'ts'}).code)(...Object.values(exports));const s=new Session();Object.assign(s,{board,blocked:false,history:{push:()=>{}},persist:()=>{},emit:()=>{}});return s;}
test('template text nodes are automatically sized, not frozen at import width',()=>{const b=presetMindmap('project');assert(b.nodes.every(n=>n.kind!=='text'||n.autoSize===true));assert(b.nodes[1].width<240);});
test('growing a template topic through Session.change separates following topics automatically',()=>{const b=presetMindmap('project'),s=session(b),id=b.nodes[2].id,next=b.nodes[3].id;s.change((draft:model.Board)=>{draft.nodes.find(n=>n.id===id)!.height=900;});const a=s.board.nodes.find((n:model.Card)=>n.id===id)!,c=s.board.nodes.find((n:model.Card)=>n.id===next)!;assert(c.y>=a.y+a.height+12,'editing a growing topic must move its sibling below it');});
test('imported organization preset keeps its downward structure after adding a child',()=>{const b=presetMindmap('project'),p=presetMindmap('organization'),r=insertPreset(b,p),edited=editTopic(r.board,r.root,'child',['新职责']),root=edited.board.nodes.find(n=>n.id===r.root)!,child=edited.board.nodes.find(n=>n.id===edited.selected)!;assert.equal(edited.board.edges.find(e=>e.to===child.id&&e.kind==='branch')?.fromSide,'bottom','imported template must not adopt another tree layout');});

import {inlineDisplayBoard} from '../src/inline-geometry';import {configureAutomaticTree} from '../src/mindmap-auto';import {appendTopicOutline,parseTopicOutline} from '../src/mindmap-content';
test('inline typing previews sibling layout, preserves source, and cancellation restores it',()=>{const b=presetMindmap('project'),before=model.clone(b),a=b.nodes[2],sibling=b.nodes[3];const view=inlineDisplayBoard(b,{id:a.id,width:a.width,height:900});assert(view.nodes[3].y>=view.nodes[2].y+900+12);assert.notEqual(view.nodes[3].y,sibling.y);assert.deepEqual(b,before);assert.equal(inlineDisplayBoard(b),b);});
test('automatic reflow ignores normal movement and does not touch another template tree',()=>{const p=presetMindmap('project'),other=presetMindmap('organization'),b=insertPreset(p,other).board,s=session(b),initial=model.clone(b);s.change((d:model.Board)=>{d.nodes[2].x+=300;});assert.equal(s.board.nodes[2].x,initial.nodes[2].x+300);const untouched=model.clone(s.board.nodes.slice(p.nodes.length));s.change((d:model.Board)=>{d.nodes[2].height=900;});assert.deepEqual(s.board.nodes.slice(p.nodes.length),untouched);});
test('turning off automatic layout keeps later dimension changes in place',()=>{const b=presetMindmap('project'),r=configureAutomaticTree(b,b.nodes[0].id,false),s=session(r.board),positions=r.board.nodes.map(n=>[n.x,n.y]);s.change((d:model.Board)=>{d.nodes[2].height=900;});assert.deepEqual(s.board.nodes.map((n:model.Card)=>[n.x,n.y]),positions);});
test('locked trees stay in place and reject explicit repair without modifying source',()=>{const b=presetMindmap('project');b.nodes[1].locked=true;const before=model.clone(b),s=session(b);assert.throws(()=>configureAutomaticTree(b,b.nodes[0].id,true),/锁定/);assert.deepEqual(b,before);s.change((d:model.Board)=>{d.nodes[2].height=900;});assert.deepEqual(s.board.nodes.map((n:model.Card)=>[n.x,n.y]),before.nodes.map(n=>[n.x,n.y]));});
test('one-click repair upgrades legacy fixed-size topics without changing text or references',()=>{const b=presetMindmap('project');delete b.nodes[0].mindmapRules;for(const n of b.nodes){n.autoSize=false;n.width=500;}const before=model.clone(b),r=configureAutomaticTree(b,b.nodes[0].id,true);assert.deepEqual(b,before);assert(r.board.nodes.every(n=>n.autoSize&&n.width<=360));assert.deepEqual(r.board.nodes.map(n=>n.text),b.nodes.map(n=>n.text));});
test('new parent of an automatic tree inherits its template settings',()=>{const b=presetMindmap('organization'),r=editTopic(b,b.nodes[0].id,'parent',['上级']);assert.deepEqual(r.board.nodes.find(n=>n.id===r.root)?.mindmapRules,b.nodes[0].mindmapRules);assert.equal(r.board.edges.find(e=>e.to===b.nodes[0].id)?.fromSide,'bottom');assert.equal(r.board.nodes.find(n=>n.id===b.nodes[0].id)?.mindmapRules,undefined);});
test('automatic templates keep bilateral branch sides stable while a subtree grows',()=>{const b=presetMindmap('brainstorm'),before=model.clone(b),s=session(b);s.change((d:model.Board)=>{d.nodes[2].height=2000;});assert.deepEqual(s.board.edges.map((e:model.Edge)=>[e.fromSide,e.toSide]),before.edges.map(e=>[e.fromSide,e.toSide]));});
test('new topics and imported outlines inherit automatic sizing',()=>{const b=presetMindmap('organization'),r=editTopic(b,b.nodes[0].id,'child',['说明'.repeat(80)]),n=r.board.nodes.find(n=>n.id===r.selected)!;assert(n.autoSize);assert(n.width<=280);assert(n.height>70);const imported=appendTopicOutline(b,b.nodes[0].id,parseTopicOutline('# 额外工作\n- 处理事项'));assert(imported.board.nodes.slice(b.nodes.length).every(n=>n.autoSize&&n.width<=280));});
test('invalid template rules and text width constraints are rejected when opening a board',()=>{for(const value of [{layout:'fish',density:'standard',automatic:true},{layout:'down',density:'tiny',automatic:true},{layout:'right',density:'standard',automatic:'yes'}]){const b=presetMindmap('project');(b.nodes[0] as any).mindmapRules=value;assert.throws(()=>model.parseBoard(JSON.stringify(b)));}const b=presetMindmap('project');b.nodes[1].textMaxWidth=0;assert.throws(()=>model.parseBoard(JSON.stringify(b)));});
