import test from 'node:test';
import assert from 'node:assert/strict';
import {clone,parseBoard,Board} from '../src/model';
import {layoutMindmap,previewMindmapSize,reflowAutomaticMindmaps,branchState} from '../src/mindmap';
import {starterMindmap,mindmapPlan,mindmapLayouts} from '../src/mindmap-studio';
import {editTopic} from '../src/mindmap-editor';
import {appendTopicOutline,parseTopicOutline} from '../src/mindmap-content';
import {branchOutline} from '../src/mindmap-flow';
import {mindmapNavigation} from '../src/mindmap-navigation';
import {configureAutomaticTree} from '../src/mindmap-auto';

function fixture(){let i=0;const b=starterMindmap('根主题',()=>String(++i));b.nodes[0].x=120;b.nodes[0].y=400;b.nodes[0].mindmapRules={automatic:true,layout:'up',density:'standard'};return b;}
function upwards(b:Board){const byId=new Map(b.nodes.map(n=>[n.id,n])),hidden=branchState(b).hidden;for(const e of b.edges.filter(e=>e.kind==='branch'&&!hidden.has(e.from)&&!hidden.has(e.to))){const parent=byId.get(e.from)!,child=byId.get(e.to)!;assert(child.y+child.height<parent.y,`${child.id} must be above ${parent.id}`);assert.equal(e.fromSide,'top');assert.equal(e.toSide,'bottom');}}
function noOverlap(b:Board){const visible=b.nodes.filter(n=>!branchState(b).hidden.has(n.id));for(let i=0;i<visible.length;i++)for(let j=i+1;j<visible.length;j++){const a=visible[i],z=visible[j];assert(a.x+a.width<=z.x||z.x+z.width<=a.x||a.y+a.height<=z.y||z.y+z.height<=a.y,`${a.id} overlaps ${z.id}`);}}

test('upward layout preserves root anchor, places mixed-sized descendants above, and routes top to bottom',()=>{const b=fixture(),root={x:b.nodes[0].x,y:b.nodes[0].y};b.nodes[2].width=610;b.nodes[2].height=330;b.nodes[4].height=510;layoutMindmap(b,b.nodes[0].id,'up');assert.deepEqual({x:b.nodes[0].x,y:b.nodes[0].y},root);upwards(b);noOverlap(b);assert.equal(b.mindmapLayout,'up');assert.equal(b.mindmapDirection,'up');assert.deepEqual(parseBoard(JSON.stringify(b)),b);});
test('upward layout is offered in studio and applied as an isolated preview',()=>{const b=fixture(),before=clone(b),plan=mindmapPlan(b,b.nodes[2].id,{layout:'up',density:'compact',depth:'all',rainbow:false});assert.equal(mindmapLayouts.up,'向上组织图');assert.deepEqual(b,before);assert.equal(plan.rootId,b.nodes[0].id);assert.equal(plan.board.nodes[0].y,b.nodes[0].y);upwards(plan.board);});
test('upward child and sibling creation uses final dimensions on first layout',()=>{const b=fixture();layoutMindmap(b,b.nodes[0].id);let i=0;const child=editTopic(b,b.nodes[1].id,'child',['向上子主题'],()=>`child-${++i}`,{prepareNode:n=>{n.width=420;n.height=300;}});upwards(child.board);noOverlap(child.board);const sibling=editTopic(child.board,child.selected,'sibling',['向上同级主题'],()=>`sibling-${++i}`,{prepareNode:n=>{n.width=550;n.height=210;}});upwards(sibling.board);noOverlap(sibling.board);assert.equal(sibling.board.nodes.find(n=>n.id===sibling.selected)!.width,550);});
test('deferred upward creation matches immediate layout without moving original tree first',()=>{const b=fixture();layoutMindmap(b,b.nodes[0].id);b.nodes[1].branchFolded=true;let i=0,j=0;const prepareNode=(n:any)=>{n.width=320;n.height=270;};const direct=editTopic(b,b.nodes[1].id,'child',['child'],()=>`n${++i}`,{prepareNode});const deferred=editTopic(b,b.nodes[1].id,'child',['child'],()=>`n${++j}`,{prepareNode,deferAutomaticLayout:true});assert.deepEqual(deferred.board.nodes.slice(0,b.nodes.length).map(({id,x,y,width,height})=>({id,x,y,width,height})),b.nodes.map(({id,x,y,width,height})=>({id,x,y,width,height})));reflowAutomaticMindmaps(deferred.board,b);assert.deepEqual(deferred.board,direct.board);upwards(deferred.board);});
test('upward inline size preview reflows adjacent topics and leaves source board untouched',()=>{const b=fixture();layoutMindmap(b,b.nodes[0].id);const before=clone(b),target=b.nodes[2],preview=previewMindmapSize(b,target.id,740,420)!;assert(preview);assert.deepEqual(b,before);assert.equal(preview.nodes.find(n=>n.id===target.id)!.width,740);assert.equal(preview.nodes[0].x,b.nodes[0].x);assert.equal(preview.nodes[0].y,b.nodes[0].y);upwards(preview);noOverlap(preview);});
test('folded upward descendants follow their parent once and expand with correct routing',()=>{const b=fixture();layoutMindmap(b,b.nodes[0].id);const parent=b.nodes[1],leaf=b.nodes[2],relative={x:leaf.x-parent.x,y:leaf.y-parent.y};parent.branchFolded=true;b.nodes[3].width=900;layoutMindmap(b,b.nodes[0].id);assert.deepEqual({x:leaf.x-parent.x,y:leaf.y-parent.y},relative);assert(branchState(b).hidden.has(leaf.id));delete parent.branchFolded;layoutMindmap(b,b.nodes[0].id);upwards(b);noOverlap(b);});
test('upward rules survive saved reload, automatic repair and outline import',()=>{const b=fixture();layoutMindmap(b,b.nodes[0].id);const restored=parseBoard(JSON.stringify(b)),configured=configureAutomaticTree(restored,restored.nodes[0].id,true);const imported=appendTopicOutline(configured.board,configured.root,parseTopicOutline('## 新材料\n- 事实\n- 证据'));assert.equal(imported.board.nodes[0].mindmapRules?.layout,'up');assert.equal(imported.board.mindmapLayout,'up');upwards(imported.board);noOverlap(imported.board);});
test('legacy upward boards export siblings left to right without explicit layout field',()=>{const b=fixture();layoutMindmap(b,b.nodes[0].id);delete b.mindmapLayout;const root=b.nodes[0].id,children=b.edges.filter(e=>e.from===root);children.forEach((e,i)=>{const n=b.nodes.find(n=>n.id===e.to)!;n.x=i*300;n.y=[600,100,400,200][i];});b.edges=[...children].reverse().concat(b.edges.filter(e=>e.from!==root));const expected=children.map(e=>b.nodes.find(n=>n.id===e.to)!).sort((a,z)=>a.x-z.x).map(n=>n.id);assert.deepEqual(branchOutline(b,root).filter(r=>r.depth===1).map(r=>r.node.id),expected);});
test('arrow navigation follows upward children and returns downward to root',()=>{const b=fixture();b.nodes=b.nodes.slice(0,3);b.edges=b.edges.filter(e=>b.nodes.some(n=>n.id===e.from)&&b.nodes.some(n=>n.id===e.to));layoutMindmap(b,b.nodes[0].id);assert.equal(mindmapNavigation(b,b.nodes[0].id,'up'),b.nodes[1].id);assert.equal(mindmapNavigation(b,b.nodes[1].id,'down'),b.nodes[0].id);});
test('upward layout keeps unrelated nodes and relationship geometry unchanged',()=>{const b=fixture();b.nodes.push({id:'other',kind:'text',text:'独立',x:9000,y:8000,width:200,height:80,color:'slate'});b.edges.push({id:'relation',from:b.nodes[0].id,to:'other',label:'引用',style:'elbow',fromSide:'right',toSide:'left'});const node=clone(b.nodes.at(-1)!),edge=clone(b.edges.at(-1)!);layoutMindmap(b,b.nodes[0].id);assert.deepEqual(b.nodes.at(-1),node);assert.deepEqual(b.edges.at(-1),edge);});
test('upward density preserves vertical gaps and changing back to downward restores ports',()=>{const b=fixture(),compact=mindmapPlan(b,b.nodes[0].id,{layout:'up',density:'compact',depth:'all',rainbow:false}).board,relaxed=mindmapPlan(b,b.nodes[0].id,{layout:'up',density:'relaxed',depth:'all',rainbow:false}).board;assert(compact.nodes[1].y>relaxed.nodes[1].y);layoutMindmap(compact,compact.nodes[0].id,'down');const byId=new Map(compact.nodes.map(n=>[n.id,n]));for(const e of compact.edges){assert(byId.get(e.to)!.y>byId.get(e.from)!.y+byId.get(e.from)!.height);assert.equal(e.fromSide,'bottom');assert.equal(e.toSide,'top');}});
