import test from 'node:test';
import assert from 'node:assert/strict';
import {clone,parseBoard} from '../src/model';
import {sizeTemplateTopic} from '../src/mindmap-sizing';
import {configureAutomaticTree} from '../src/mindmap-auto';
import {starterMindmap} from '../src/mindmap-studio';

function fixture(){let i=0;const b=starterMindmap('中心主题',()=>String(++i));const text=b.nodes[1];Object.assign(text,{text:'保留完整正文\n'.repeat(10),autoSize:false,collapsed:true,expandedHeight:450,height:72,width:320});return{b,text};}
test('fallback template sizing preserves collapsed text geometry and stored expanded height',()=>{const{b,text}=fixture(),before=clone(text);sizeTemplateTopic(text);assert.deepEqual([text.width,text.height,text.expandedHeight,text.collapsed],[before.width,72,450,true]);assert.equal(text.text,before.text);assert.equal(text.autoSize,true);assert.equal(text.textMaxWidth,280);parseBoard(JSON.stringify(b));});
test('automatic repair skips measuring collapsed text while keeping its future sizing rule',()=>{const{b,text}=fixture(),before=clone(b),measured:string[]=[];const result=configureAutomaticTree(b,b.nodes[0].id,true,n=>{measured.push(n.id);n.height=120;});const folded=result.board.nodes.find(n=>n.id===text.id)!;assert.deepEqual(b,before);assert.deepEqual([folded.height,folded.width,folded.expandedHeight,folded.collapsed],[72,320,450,true]);assert.equal(folded.text,text.text);assert.equal(folded.autoSize,true);assert(!measured.includes(text.id));assert(measured.length>0);parseBoard(JSON.stringify(result.board));});
test('automatic repair preserves collapsed note cards and their file references',()=>{const{b,text}=fixture();Object.assign(text,{kind:'card',file:'notes/source.md'});delete text.autoSize;delete text.text;const before=clone(text),result=configureAutomaticTree(b,b.nodes[0].id,true),card=result.board.nodes.find(n=>n.id===text.id)!;assert.deepEqual([card.kind,card.file,card.width,card.height,card.expandedHeight,card.collapsed],[before.kind,before.file,before.width,before.height,before.expandedHeight,before.collapsed]);parseBoard(JSON.stringify(result.board));});

test('reopening a repaired text restores expanded content and resumes automatic reflow',async()=>{const{foldCards}=await import('../src/board-tools'),{reflowAutomaticMindmaps}=await import('../src/mindmap');const{b,text}=fixture(),result=configureAutomaticTree(b,b.nodes[0].id,true).board;foldCards(result,new Set([text.id]),false);const expanded=result.nodes.find(n=>n.id===text.id)!;assert.equal(expanded.height,450);assert.equal(expanded.expandedHeight,undefined);assert.equal(expanded.collapsed,undefined);const before=clone(result);sizeTemplateTopic(expanded);reflowAutomaticMindmaps(result,before);assert.equal(expanded.autoSize,true);assert.notEqual(expanded.height,72);assert.equal(expanded.text,text.text);assert.equal(result.nodes[0].mindmapRules?.automatic,true);parseBoard(JSON.stringify(result));});
