import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';import {noteRenamePath} from '../src/note-rename';
const source=readFileSync('src/main.ts','utf8'),method=source.slice(source.indexOf('  async renameNote('),source.indexOf('  promptRenameNote('));
const Rename=new Function('noteRenamePath',transformSync('class Rename{'+method+'}\nreturn Rename;',{loader:'ts'}).code)(noteRenamePath);
function fixture(){const f={path:'目录/原名.md'},calls:string[]=[],files=new Map<string,unknown>([[f.path,f]]);const plugin=new Rename();plugin.referenceQueue=Promise.resolve();plugin.app={vault:{getAbstractFileByPath:(p:string)=>files.get(p)},fileManager:{renameFile:async(file:typeof f,path:string)=>{calls.push(path);files.delete(file.path);file.path=path;files.set(path,file)}}};return{f,plugin,files,calls};}
test('note rename keeps folder, supports root and unicode titles',()=>{assert.equal(noteRenamePath('目录/原名.md',' 新标题 '),'目录/新标题.md');assert.equal(noteRenamePath('原名.md','中文标题'),'中文标题.md');});
test('empty, path traversal and invalid filename do not become a sanitized unexpected title',()=>{for(const name of ['',' ','../位置','a/b','a\\b','..','a:路径','结尾.'])assert.throws(()=>noteRenamePath('原名.md',name));});
test('actual plugin rename uses native fileManager and preserves file identity',async()=>{const f=fixture();await f.plugin.renameNote(f.f,'新标题','目录/原名.md');assert.deepEqual(f.calls,['目录/新标题.md']);assert.equal(f.files.get('目录/新标题.md'),f.f);});
test('actual rename rejects stale file identity and collisions without file writes',async()=>{const f=fixture();f.files.set('目录/冲突.md',{});await assert.rejects(f.plugin.renameNote(f.f,'冲突'),/同名/);f.files.set(f.f.path,{});await assert.rejects(f.plugin.renameNote(f.f,'新标题'),/移动或删除/);assert.equal(f.calls.length,0);});
test('unchanged title is a no-op and reference updates are awaited after native rename',async()=>{const f=fixture();await f.plugin.renameNote(f.f,'原名');assert.equal(f.calls.length,0);let resolve!:()=>void,done=false;f.plugin.referenceQueue=new Promise<void>(r=>resolve=r);const job=f.plugin.renameNote(f.f,'新标题').then(()=>done=true);await new Promise(r=>setImmediate(r));assert.equal(done,false);resolve();await job;assert.equal(done,true);});
