import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import {cleanPaperPreferences,paperAppearanceStamp,paperBaseColor,paperPresets,type PaperPreferences} from '../src/paper-appearance';
type Options={cls?:string;text?:string;attr?:Record<string,string>;type?:string;value?:string};
class Element {
 children:Element[]=[];attributes:Record<string,string>={};classes=new Set<string>();value='';disabled=false;hidden=false;writes=0;private text='';onclick?:()=>void;oninput?:()=>void;onkeydown:((event:any)=>void)|null=null;style={values:{} as Record<string,string>,setProperty(name:string,value:string){this.values[name]=value;}};
 constructor(readonly tagName:string,options:Options|string={}){const opts=typeof options==='string'?{cls:options}:options;this.text=opts.text||'';this.attributes={...opts.attr};this.value=opts.value||'';if(opts.type)this.attributes.type=opts.type;for(const cls of (opts.cls||'').split(/\s+/).filter(Boolean))this.classes.add(cls);}
 get textContent():string{return this.text+this.children.map(child=>child.textContent).join('');}
 createEl(tag:string,options:Options|string={}){this.writes++;const child=new Element(tag.toUpperCase(),options);this.children.push(child);return child;}createDiv(options:Options|string={}){return this.createEl('div',options);}createSpan(options:Options|string={}){return this.createEl('span',options);}
 addClass(...names:string[]){for(const name of names)this.classes.add(name);}setAttribute(name:string,value:string){this.writes++;this.attributes[name]=value;}getAttribute(name:string){return this.attributes[name]??null;}setText(text:string){this.writes++;this.text=text;this.children=[];}empty(){this.writes++;this.children=[];this.text='';}prepend(child:Element){this.children=this.children.filter(item=>item!==child);this.children.unshift(child);}click(){if(!this.disabled)this.onclick?.();}
 matches(selector:string){if(selector.startsWith('.'))return this.classes.has(selector.slice(1));const attr=/^\[([^=]+)=([^\]]+)\]$/.exec(selector);return attr?this.getAttribute(attr[1])===attr[2]:this.tagName===selector.toUpperCase();}querySelectorAll(selector:string):Element[]{return this.children.flatMap(child=>[...(child.matches(selector)?[child]:[]),...child.querySelectorAll(selector)]);}querySelector(selector:string){return this.querySelectorAll(selector)[0];}
}
class Modal {readonly modalEl=new Element('DIV');readonly titleEl=this.modalEl.createEl('h2');readonly contentEl=this.modalEl.createDiv();selection:unknown;closeCount=0;constructor(readonly app:unknown){}open(){this.selection={win:{document:{}},range:null,focusEl:null};(this as unknown as {onOpen:()=>void}).onOpen();}close(){this.closeCount++;(this as unknown as {onClose:()=>void}).onClose();}}
const notices:string[]=[];
class Notice {constructor(message:string){notices.push(message);}}
const source=readFileSync('src/paper-settings-view.ts','utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');
const deps={Modal,Notice,setIcon:()=>{},themeSurface:()=>{},cleanPaperPreferences,paperAppearanceStamp,paperBaseColor,paperPresets};
const PaperSettingsModal=new Function(...Object.keys(deps),transformSync(source+'\nreturn PaperSettingsModal;',{loader:'ts'}).code)(...Object.values(deps));
function deferred(){let resolve!:()=>void,reject!:(error:Error)=>void;const promise=new Promise<void>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
function fixture(raw:unknown={},initialError=false){let current=cleanPaperPreferences(raw),readError=initialError;const saves:PaperPreferences[]=[],pending:ReturnType<typeof deferred>[]=[];const host={preferences:()=>{if(readError)throw Error('暂时无法读取设置');return current;},save:(prefs:PaperPreferences)=>{saves.push({...prefs});const save=deferred();pending.push(save);return save.promise;}};const modal=new PaperSettingsModal({},host);modal.open();const root=modal.contentEl as Element;return{modal,root,saves,pending,get current(){return current;},setCurrent:(prefs:Partial<PaperPreferences>)=>{current={...current,...prefs};},readError:(fail:boolean)=>{readError=fail;},button:(label:string)=>root.querySelectorAll('button').find(button=>button.getAttribute('aria-label')===label||button.textContent===label)!,input:(label:string)=>root.querySelectorAll('input').find(input=>input.getAttribute('aria-label')===label)!,get preview(){return root.querySelector('.ts-paper-preview')!;},get status(){return root.querySelector('.ts-paper-settings-status')!;}};}
const input=(el:Element,value:string)=>{el.value=value;el.oninput?.();};
function key(f:ReturnType<typeof fixture>,overrides:Record<string,unknown>={}){const event={key:'Enter',ctrlKey:true,metaKey:false,altKey:false,shiftKey:false,isComposing:false,keyCode:0,prevented:false,preventDefault(){this.prevented=true;},...overrides};f.root.onkeydown?.(event);return event;}
const tick=async()=>{await Promise.resolve();await Promise.resolve();};

test('opening default paper preferences leaves Apply available so another background can become paper',async()=>{const f=fixture();assert.equal(f.saves.length,0);assert.equal(f.button('应用').disabled,false);f.button('应用').click();assert.deepEqual(f.saves,[cleanPaperPreferences({})]);f.pending[0].resolve();await tick();assert.equal(f.modal.closeCount,1);});
test('preset, custom color and texture preview are local until Apply, and Cancel discards them',()=>{const f=fixture(),before={...f.current};f.button('纯白纸').click();assert.equal(f.preview.style.values['--ts-paper-color'],'#ffffff');input(f.input('自定义纸色十六进制代码'),'#A0B1C2');input(f.input('纸张纹理强度'),'0');assert.equal(f.preview.style.values['--ts-paper-color'],'#a0b1c2');assert.equal(f.preview.style.values['--ts-paper-texture'],'0');assert.deepEqual(f.current,before);f.button('取消').click();assert.equal(f.saves.length,0);assert.equal(f.root.children.length,0);});
test('native Modal selection state remains independent of paper choices',()=>{const f=fixture();assert.deepEqual(f.modal.selection,{win:{document:{}},range:null,focusEl:null});f.button('牛皮纸').click();f.modal.selection=null;f.button('应用').click();assert.equal(f.saves[0].paperPreset,'kraft');});
test('invalid color input blocks Apply and an explicit preset recovers without persisting invalid CSS',()=>{const f=fixture();const hex=f.input('自定义纸色十六进制代码');input(hex,'#ff');assert.equal(hex.getAttribute('aria-invalid'),'true');assert.equal(f.button('应用').disabled,true);assert.match(f.status.textContent,/完整的颜色/);key(f);assert.equal(f.saves.length,0);f.button('纯白纸').click();assert.equal(hex.getAttribute('aria-invalid'),'false');assert.equal(f.button('应用').disabled,false);assert.equal(f.preview.style.values['--ts-paper-color'],'#ffffff');f.button('应用').click();assert.equal(f.saves[0].paperColor,'#f3e9d4');});
test('color picker normalizes custom color and dark custom paper uses readable preview ink',()=>{const f=fixture();input(f.input('选择自定义纸张颜色'),'#101010');assert.equal(f.button('自定义纸色').getAttribute('aria-pressed'),'true');assert.equal(f.preview.style.values['--ts-paper-preview-ink'],'#f4f0e6');input(f.input('选择自定义纸张颜色'),'#ffffff');assert.equal(f.preview.style.values['--ts-paper-preview-ink'],'#403b32');f.button('应用').click();assert.equal(f.saves[0].paperPreset,'custom');assert.equal(f.saves[0].paperColor,'#ffffff');});
test('repeated clicks and shortcuts cannot duplicate a pending save or change its captured draft',async()=>{const f=fixture();f.button('纯白纸').click();f.button('应用').click();f.button('应用').click();key(f);f.button('牛皮纸').click();input(f.input('纸张纹理强度'),'100');assert.equal(f.saves.length,1);assert.equal(f.saves[0].paperPreset,'white');assert.equal(f.saves[0].paperTexture,55);assert.equal(f.button('牛皮纸').disabled,true);f.pending[0].resolve();await tick();assert.equal(f.modal.closeCount,1);});
test('a stale latent custom pigment rejects before writing and reload adopts current settings',()=>{const f=fixture({paperPreset:'cream',paperColor:'#aaaaaa'});f.button('纯白纸').click();f.setCurrent({paperColor:'#bbbbbb',paperTexture:20});f.button('应用').click();assert.equal(f.saves.length,0);assert.match(f.status.textContent,/其他窗口改变/);assert.equal(f.button('应用').disabled,true);assert.equal(f.button('载入当前设置').hidden,false);f.button('载入当前设置').click();assert.equal(f.input('自定义纸色十六进制代码').value,'#bbbbbb');assert.equal(f.input('纸张纹理强度').value,'20');assert.equal(f.button('载入当前设置').hidden,true);f.button('应用').click();assert.deepEqual(f.saves[0],f.current);});
test('save rejection retains draft and allows an explicit retry without closing',async()=>{const f=fixture();f.button('再生纸').click();f.button('应用').click();f.pending[0].reject(Error('磁盘暂时不可写'));await tick();assert.match(f.status.textContent,/保存失败.*磁盘暂时不可写.*可以重试/);assert.equal(f.modal.closeCount,0);assert.equal(f.button('应用').disabled,false);f.button('应用').click();assert.equal(f.saves.length,2);assert.equal(f.saves[1].paperPreset,'recycled');f.pending[1].resolve();await tick();assert.equal(f.modal.closeCount,1);});
test('closing while a save is pending prevents DOM revival and reports failed background saves once',async()=>{for(const failure of [false,true]){const f=fixture(),status=f.status,startNotices=notices.length;f.button('应用').click();f.modal.close();const writes=status.writes;if(failure)f.pending[0].reject(Error('写入失败'));else f.pending[0].resolve();await tick();assert.equal(f.root.children.length,0);assert.equal(status.writes,writes);assert.equal(f.modal.closeCount,1);assert.equal(notices.length-startNotices,failure?1:0);}});
test('reopening the same modal starts a fresh dialog that an earlier pending save cannot close',async()=>{const f=fixture();f.button('纯白纸').click();f.button('应用').click();f.modal.close();f.modal.open();assert.equal(f.root.querySelectorAll('.ts-paper-settings-body').length,1);assert.equal(f.button('米黄纸').getAttribute('aria-pressed'),'true');f.pending[0].resolve();await tick();assert.equal(f.modal.closeCount,1);assert.ok(f.root.children.length>0);assert.equal(f.button('应用').disabled,false);});
test('Ctrl or Cmd Enter applies while IME input and alternate modifiers remain untouched',()=>{for(const overrides of [{},{ctrlKey:false,metaKey:true}]){const f=fixture();assert.equal(key(f,overrides).prevented,true);assert.equal(f.saves.length,1);}for(const overrides of [{isComposing:true},{keyCode:229},{altKey:true},{shiftKey:true},{ctrlKey:false}]){const f=fixture();assert.equal(key(f,overrides).prevented,false);assert.equal(f.saves.length,0);}});
test('failed initial preference reads disable editing and offer reload without uninitialized draft crashes',()=>{const f=fixture({},true);assert.equal(f.button('应用').disabled,true);assert.equal(f.button('纯白纸').disabled,true);assert.equal(f.input('纸张纹理强度').disabled,true);assert.equal(f.button('载入当前设置').hidden,false);assert.match(f.status.textContent,/暂时无法读取/);f.readError(false);f.button('载入当前设置').click();assert.equal(f.button('应用').disabled,false);assert.equal(f.button('纯白纸').disabled,false);assert.equal(f.button('载入当前设置').hidden,true);f.button('应用').click();assert.equal(f.saves.length,1);});
test('detached controls and keyboard handlers cannot save after close',()=>{const f=fixture(),apply=f.button('应用'),swatch=f.button('纯白纸'),color=f.input('选择自定义纸张颜色'),status=f.status;f.modal.close();const writes=status.writes;apply.click();swatch.click();input(color,'#000000');key(f);assert.equal(f.saves.length,0);assert.equal(f.root.children.length,0);assert.equal(status.writes,writes);assert.equal(f.root.onkeydown,null);});
