import test from 'node:test';
import assert from 'node:assert/strict';
import {paperPresets,defaultPaperPreferences,cleanPaperPreferences,paperBaseColor,paperAppearanceStamp} from '../src/paper-appearance';
import {defaultAppearance} from '../src/workspace';
import {cleanPluginSettings} from '../src/plugin-settings';

test('missing and malformed paper settings preserve the cream paper default',()=>{for(const value of [undefined,null,false,42,'white',[],{}, {paperPreset:'unknown',paperColor:'red',paperTexture:NaN}])assert.deepEqual(cleanPaperPreferences(value),{paperPreset:'cream',paperColor:'#f3e9d4',paperTexture:55});assert.equal(defaultAppearance.paperPreset,'cream');assert.equal(defaultAppearance.paperColor,'#f3e9d4');assert.equal(defaultAppearance.paperTexture,55);});
test('common paper types resolve to shared names and exact base colors',()=>{assert.deepEqual(Object.keys(paperPresets),['cream','white','ivory','kraft','recycled','custom']);for(const [preset,paper]of Object.entries(paperPresets)){assert.match(paper.name,/[\u4e00-\u9fff]/);assert.match(paper.color,/^#[0-9a-f]{6}$/);const prefs=cleanPaperPreferences({paperPreset:preset,paperColor:'#102030',paperTexture:25});assert.equal(paperBaseColor(prefs),preset==='custom'?'#102030':paper.color);}assert.equal(paperPresets.white.color,'#ffffff');});
test('custom colors accept only six-digit hex and canonicalize letter case',()=>{assert.equal(cleanPaperPreferences({paperPreset:'custom',paperColor:'#A0B1C2'}).paperColor,'#a0b1c2');for(const paperColor of ['#fff','#11223344','white','rgb(0,0,0)','var(--secret)','url(https://example.com/a.png)','#123456; background:red',' #123456','#12345g',null,{},13]){const prefs=cleanPaperPreferences({paperPreset:'custom',paperColor});assert.equal(prefs.paperColor,'#f3e9d4');assert.equal(paperBaseColor(prefs),'#f3e9d4');}});
test('texture keeps zero, clamps finite values, preserves decimals and rejects coercion',()=>{for(const [paperTexture,expected]of [[0,0],[-10,0],[100,100],[500,100],[27.5,27.5],[NaN,55],[Infinity,55],[-Infinity,55],['0',55],[null,55],[false,55],[{},55]] as const)assert.equal(cleanPaperPreferences({paperTexture}).paperTexture,expected);});
test('prototype keys and object coercion cannot select presets or generate CSS',()=>{for(const paperPreset of ['__proto__','constructor','toString',{toString:()=>{throw Error('must not coerce');}}])assert.equal(cleanPaperPreferences({paperPreset}).paperPreset,'cream');const color={toString:()=>{throw Error('must not coerce');}};assert.equal(cleanPaperPreferences({paperColor:color}).paperColor,'#f3e9d4');});
test('cleaned paper settings contain only their own fields and never alias inputs or defaults',()=>{const raw={paperPreset:'custom',paperColor:'#ABCDEF',paperTexture:0,canvasBackground:'grid',secret:'no'},before=JSON.stringify(raw),first=cleanPaperPreferences(raw),second=cleanPaperPreferences(raw);assert.deepEqual(Object.keys(first).sort(),['paperColor','paperPreset','paperTexture']);first.paperColor='#000000';first.paperTexture=100;assert.equal(JSON.stringify(raw),before);assert.equal(second.paperColor,'#abcdef');assert.equal(second.paperTexture,0);assert.deepEqual(defaultPaperPreferences,{paperPreset:'cream',paperColor:'#f3e9d4',paperTexture:55});});
test('appearance stamps cover every persisted paper choice including a dormant custom color',()=>{const base=cleanPaperPreferences({paperPreset:'cream',paperTexture:0});assert.notEqual(paperAppearanceStamp(base),paperAppearanceStamp({...base,paperColor:'#000000'}));assert.equal(paperBaseColor(base),paperBaseColor({...base,paperColor:'#000000'}));assert.notEqual(paperAppearanceStamp(base),paperAppearanceStamp({...base,paperPreset:'white'}));assert.notEqual(paperAppearanceStamp(base),paperAppearanceStamp({...base,paperTexture:1}));const custom={...base,paperPreset:'custom' as const,paperColor:'#010203'};assert.notEqual(paperAppearanceStamp(custom),paperAppearanceStamp({...custom,paperColor:'#040506'}));assert.equal(paperAppearanceStamp({...custom,paperColor:'#AABBCC'}),paperAppearanceStamp({...custom,paperColor:'#aabbcc'}));});
test('plugin settings preserve validated paper choices without changing existing appearance or input settings',()=>{const raw={paperPreset:'custom',paperColor:'#BADCFE',paperTexture:0,canvasBackground:'grid',surfaceStyle:'soft',accent:'blue',readingSize:20,zoomSpeed:1.5,showMinimap:false},settings=cleanPluginSettings(raw);assert.equal(settings.paperPreset,'custom');assert.equal(settings.paperColor,'#badcfe');assert.equal(settings.paperTexture,0);assert.equal(settings.canvasBackground,'grid');assert.equal(settings.surfaceStyle,'soft');assert.equal(settings.accent,'blue');assert.equal(settings.readingSize,20);assert.equal(settings.zoomSpeed,1.5);assert.equal(settings.showMinimap,false);assert.deepEqual(cleanPaperPreferences(cleanPluginSettings(JSON.parse(JSON.stringify(settings)))),cleanPaperPreferences(settings));});
test('paper settings survive switching backgrounds and selecting presets without discarding the remembered custom pigment',()=>{const settings=cleanPluginSettings({canvasBackground:'paper',paperPreset:'white',paperColor:'#456789',paperTexture:80});const switched=cleanPluginSettings({...settings,canvasBackground:'dots'});assert.equal(switched.paperColor,'#456789');assert.equal(switched.paperTexture,80);assert.equal(paperBaseColor(switched),'#ffffff');const custom=cleanPluginSettings({...switched,paperPreset:'custom',canvasBackground:'paper'});assert.equal(paperBaseColor(custom),'#456789');});
