import test from 'node:test';
import assert from 'node:assert/strict';
import {paragraphOrigin,paragraphLink,paragraphRange,paragraphPresentation,locateParagraph,sameParagraph,validParagraphOrigin} from '../src/paragraph-card';
import {writingReferenceRanges} from '../src/writing-reference';
import {emptyBoard,parseBoard,History,type Card} from '../src/model';
import {createBoardReferenceRenamer} from '../src/board-reference-rename';
const raw='# 标题\n\n**段落** 与 [[资料/其他 笔记]]。\n\n重复段落。\n\n重复段落。\n';
const range={label:'选区',from:raw.indexOf('**'),to:raw.indexOf('\n\n重复')};
const origin=()=>paragraphOrigin('资料/中文 来源.md',raw,range,'snapshot');
const headings=(text:string)=>({headings:[...text.matchAll(/^# (.+)$/gm)].map(m=>({heading:m[1],level:1,position:{start:{offset:m.index},end:{offset:m.index+m[0].length}}}))});
test('snapshot retains exact Markdown and offsets without generating source anchors',()=>{const o=origin();assert.equal(o.quote,raw.slice(range.from,range.to));assert.equal(o.subpath,undefined);assert.equal(o.path,'资料/中文 来源.md');assert.equal(locateParagraph(o,raw,null).from,range.from);});
test('unchanged document disambiguates identical paragraphs using verified offsets',()=>{const from=raw.lastIndexOf('重复段落。'),o=paragraphOrigin('a.md',raw,{label:'second',from,to:from+5},'snapshot');assert.equal(locateParagraph(o,raw,null).from,from);assert.equal(locateParagraph(o,'new\n'+raw,null).from,undefined);});
test('after insertion only a unique exact quotation may relocate',()=>{const next='新增开头\n'+raw,result=locateParagraph(origin(),next,null);assert.equal(result.from,next.indexOf('**'));assert.match(result.status,/重新定位/);});
test('changed quoted content is uncertain and never falls back to obsolete offsets',()=>{const result=locateParagraph(origin(),raw.replace('段落','改写'),null);assert.equal(result.from,undefined);assert.match(result.status,/无法确认/);});
test('overlapping duplicate quotes also remain uncertain after source change',()=>{const o=paragraphOrigin('a.md','aaa',{label:'a',from:0,to:2},'snapshot');assert.equal(locateParagraph(o,'aaaa',null).from,undefined);});
test('dynamic reference is available only for a verified unique heading',()=>{const cache=headings(raw),r=writingReferenceRanges(raw,cache).find(r=>r.subpath)!;const o=paragraphOrigin('a.md',raw,r,'embed');assert.match(locateParagraph(o,raw.replace('段落','新文'),cache).status,/动态引用/);assert.throws(()=>paragraphOrigin('a.md',raw,range,'embed'),/已有且唯一/);});
test('duplicated or removed heading makes dynamic location uncertain',()=>{const r=writingReferenceRanges(raw,headings(raw)).find(r=>r.subpath)!;const o=paragraphOrigin('a.md',raw,r,'embed'),duplicated=raw+'\n# 标题\nmore';assert.equal(locateParagraph(o,duplicated,headings(duplicated)).from,undefined);const changed=raw.replace('# 标题','# 更名');assert.equal(locateParagraph(o,changed,headings(changed)).from,undefined);});
test('existing block anchor may follow edited source content',()=>{const before='Existing block ^stable',after='Edited block ^stable',cache=(s:string)=>({blocks:{stable:{id:'stable',position:{start:{offset:0},end:{offset:s.length}}}}});const r=writingReferenceRanges(before,cache(before)).find(r=>r.subpath)!;const o=paragraphOrigin('a.md',before,r,'embed');assert.deepEqual(locateParagraph(o,after,cache(after)),{from:0,to:after.length,status:'已核验现有标题或块 · 动态引用'});});
test('cursor paragraph and exact anchored selection reuse existing ranges',()=>{const ranges=writingReferenceRanges(raw,headings(raw));assert.equal(paragraphRange(raw,range.from+2,range.from+2,ranges).from,range.from);assert.equal(paragraphRange(raw,0,raw.length,ranges).subpath,'#标题');assert.equal(paragraphRange(raw,range.from+1,range.to,ranges).subpath,undefined);});
test('empty invalid and oversized selections are rejected',()=>{for(const r of [{from:0,to:0},{from:-1,to:2},{from:1,to:raw.length+1}])assert.throws(()=>paragraphOrigin('a.md',raw,{label:'x',...r},'snapshot'));assert.throws(()=>paragraphOrigin('a.md','x'.repeat(100001),{label:'big',from:0,to:100001},'snapshot'));});
test('origin parser rejects corrupt bounds, modes and unsafe source paths',()=>{for(const patch of [{path:'../a.md'},{path:'/a.md'},{path:'javascript:a.md'},{path:'a\nb.md'},{from:-1},{to:1000000},{quote:''},{hash:'x'},{mode:'auto'},{mode:'embed',subpath:undefined}])assert.equal(validParagraphOrigin({...origin(),...patch}),false);});
test('same source selection deduplicates while different ranges and semantics remain distinct',()=>{const o=origin();assert.equal(sameParagraph({...o},o),true);for(const patch of [{from:o.from+1},{quote:o.quote+'x'},{hash:'0'.repeat(64)},{path:'else.md'}])assert.equal(sameParagraph({...o,...patch},o),false);});
test('history and persistence preserve quote provenance and fold state',()=>{const b=emptyBoard(),h=new History(),node:Card={id:'quote',kind:'text',text:'**body**',paragraphQuote:origin(),x:20,y:30,width:320,height:72,expandedHeight:160,color:'sand',collapsed:true};h.push(b);b.version=3;b.nodes.push(node);const restored=parseBoard(JSON.stringify(b));assert.deepEqual(restored.nodes[0],node);const undo=h.undo(b)!;assert.equal(undo.nodes.length,0);assert.deepEqual(h.redo(undo)!.nodes[0],node);});
test('source rename migrates rendered links and provenance but preserves original quote',()=>{const o=origin(),b=emptyBoard();b.nodes.push({id:'q',kind:'text',text:'![[资料/中文 来源.md#标题]]\n\n`[[资料/中文 来源.md]]`',paragraphQuote:o,x:0,y:0,width:320,height:160,color:'sand'});const moved=createBoardReferenceRenamer(o.path,'新目录/新 来源.md',['新目录/新 来源.md'])(b,'B.thoughtspace')!;assert.equal(moved.nodes[0].paragraphQuote?.path,'新目录/新 来源.md');const movedOrigin=moved.nodes[0].paragraphQuote;assert.ok(movedOrigin?.mode==='snapshot');assert.equal(movedOrigin.quote,o.quote);assert.match(moved.nodes[0].text!,/!\[\[新目录\/新 来源.md#标题\]\]/);assert.match(moved.nodes[0].text!,/`\[\[资料\/中文 来源.md\]\]`/);assert.equal(b.nodes[0].paragraphQuote?.path,o.path);});

test('unfinished Markdown fence cannot hide paragraph provenance',()=>{const body='```js\nconst value=1;',p=paragraphPresentation(body+'\n\n> 来源：[[a]] · 第 1–2 行 · 静态摘录',origin(),'[[a]]');assert.equal(p.body,body);assert.equal(p.sources[0].link,'[[a]]');});
test('editing away the generated citation retains import provenance without altering body',()=>{const body='My independent edited card';const p=paragraphPresentation(body,origin(),'[[original]]');assert.equal(p.body,body);assert.match(p.sources[0].location,/回源时核验/);});
test('native dynamic metadata contains no copy of source content',()=>{const r=writingReferenceRanges(raw,headings(raw)).find(r=>r.subpath)!;assert.deepEqual(paragraphOrigin('a.md',raw,r,'embed'),{path:'a.md',subpath:'#标题',mode:'embed'});});

test('cursor inside a heading uses its existing native anchor',()=>{const ranges=writingReferenceRanges(raw,headings(raw));assert.equal(paragraphRange(raw,3,3,ranges).subpath,'#标题');});

test('native references retain full source paths across same-name files',()=>{assert.equal(paragraphLink('资料/中文 来源 (一).md','#^stable'), '[[资料/中文 来源 (一).md#^stable]]');assert.equal(paragraphLink('其他/中文 来源 (一).md','#Heading','别名'),'[[其他/中文 来源 (一).md#Heading|别名]]');});
test('literal hash in a filename uses encoded native Markdown destination',()=>{assert.equal(paragraphLink('资料/a#b.md','#标题'),'[a#b.md](<%E8%B5%84%E6%96%99/a%23b.md#%E6%A0%87%E9%A2%98>)');});
