import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{transformSync}from'esbuild';
const source=readFileSync('src/main.ts','utf8'),start=source.indexOf('  private dragDocuments='),end=source.indexOf('  private videoBridge?',start),moreStart=source.indexOf('  clearMaterialDrag(){');
const methods=source.slice(start,end)+source.slice(moreStart).split('\n').slice(0,2).join('\n');
function setup(){
 const callbacks:(()=>void)[]=[],pending:Promise<unknown>[]=[],received:unknown[]=[],errors:string[]=[];let token=0;
 class BoardView{session={blocked:false};closed=false;acceptsMaterialTarget(){return true}clearMaterialLanding(){}materialDropPoint(x:number,y:number){return{x,y}}}
 const Plugin=new Function('BoardView','VIEW','MATERIAL_DRAG','uid','act','Notice',transformSync('class Plugin{'+methods+'}\nreturn Plugin',{loader:'ts'}).code)(BoardView,'board','fragment',()=>String(++token),(fn:()=>unknown)=>{pending.push(Promise.resolve(fn()))},class{constructor(e:unknown){errors.push(String(e))}});
 const doc=Object.assign(new EventTarget(),{defaultView:new EventTarget(),elementFromPoint:()=>({}),getSelection:()=>({isCollapsed:false,rangeCount:1,getRangeAt:()=>({getClientRects:()=>[{left:0,right:100,top:0,bottom:100}]})})});
 const board=new BoardView(),plugin=new Plugin();plugin.app={workspace:{getLeavesOfType:()=>[{view:board}]}};plugin.register=(fn:()=>void)=>callbacks.push(fn);plugin.registerDomEvent=(target:EventTarget,type:string,fn:EventListener,options:any)=>{target.addEventListener(type,fn,options);callbacks.push(()=>target.removeEventListener(type,fn,options))};plugin.nativeSelection=()=>({text:'PDF source',pdf:true,run:async(...args:unknown[])=>{received.push(args)}});plugin.installNativeSelectionDrag(doc);
 const event=(type:string,properties:Record<string,unknown>={})=>{const e=new Event(type,{cancelable:true});Object.assign(e,{button:0,pointerId:1,clientX:20,clientY:20,detail:1,...properties});doc.dispatchEvent(e);return e};
 const transfer=(text='PDF source')=>{const data=new Map([['text/plain',text]]);return{getData:(k:string)=>data.get(k)||'',setData:(k:string,v:string)=>data.set(k,v),effectAllowed:''}};
 return{plugin,board,doc,event,transfer,received,errors,settle:()=>Promise.all(pending),close:()=>{for(const fn of callbacks.reverse())fn()}};
}
test('PDF native drag retains its source token through the browser pointercancel; drop is single-use',async()=>{const h=setup();try{const dt=h.transfer();h.event('dragstart',{dataTransfer:dt});h.event('pointercancel');assert.ok(h.plugin.materialDrag);await h.plugin.receiveMaterial({dataTransfer:dt},h.board,{x:200,y:300});await h.plugin.receiveMaterial({dataTransfer:dt},h.board,{x:200,y:300});assert.equal(h.received.length,1)}finally{h.close()}});
test('Escape and dragend still cancel native PDF drags',async()=>{for(const type of ['keydown','dragend']){const h=setup();try{const dt=h.transfer();h.event('dragstart',{dataTransfer:dt});h.event(type,{key:'Escape'});await h.plugin.receiveMaterial({dataTransfer:dt},h.board,{x:200,y:300});assert.equal(h.received.length,0)}finally{h.close()}}});
test('pointercancel cancels a direct PDF drag',async()=>{const h=setup();try{h.event('pointerdown');h.event('pointercancel');h.event('pointerup',{clientX:250});await h.settle();assert.equal(h.received.length,0)}finally{h.close()}});
test('an unrelated pointer cancellation must not discard the PDF drag',async()=>{const h=setup();try{h.event('pointerdown');h.event('pointercancel',{pointerId:2});h.event('pointerup',{clientX:250});await h.settle();assert.equal(h.received.length,1)}finally{h.close()}});
test('double-click selection must not drag a stale previous PDF selection',async()=>{const h=setup();try{h.event('pointerdown',{detail:2});h.event('pointerup',{clientX:250});await h.settle();assert.equal(h.received.length,0)}finally{h.close()}});
test('PDF native drag tolerates selection boundary whitespace but rejects different content',async()=>{for(const[text,count]of [['  PDF source\n',1],['different source',0]]as const){const h=setup();try{const dt=h.transfer(text);h.event('dragstart',{dataTransfer:dt});await h.plugin.receiveMaterial({dataTransfer:dt},h.board,{x:200,y:300});assert.equal(h.received.length,count)}finally{h.close()}}});

test('pointercancel in another window cannot discard the active PDF pointer drag',async()=>{const h=setup();try{const other=Object.assign(new EventTarget(),{defaultView:new EventTarget()});h.plugin.installNativeSelectionDrag(other);h.event('pointerdown');other.dispatchEvent(new Event('pointercancel'));h.event('pointerup',{clientX:250});await h.settle();assert.equal(h.received.length,1)}finally{h.close()}});
