import test from 'node:test';import assert from 'node:assert/strict';
import {pdfCard,pdfDropReference,pdfPage,pdfSubpath,renderPdfThumbnail} from '../src/pdf-card';
import {parseBoard,canvasExport,emptyBoard,clone} from '../src/model';
const board=()=>({...emptyBoard(),version:3 as const,nodes:[pdfCard('pdf','资料/测试.PDF',400,200)]});
test('PDF cards round-trip with geometry, connections and independent page state',()=>{const b=board();b.nodes[0].pdfPage=2;b.nodes.push({...clone(b.nodes[0]),id:'second',pdfPage:5});b.edges.push({id:'edge',from:'pdf',to:'second',label:'参考'});assert.deepEqual(parseBoard(JSON.stringify(b)),b);assert.equal(b.nodes[0].kind,'pdf');assert.equal(b.nodes[0].autoFit,undefined)});
test('PDF cards export to Canvas with the original file and page subpath',()=>{const b=board();b.nodes[0].pdfPage=4;const n=canvasExport(b).nodes[0];assert.equal(n.type,'file');assert.ok('file' in n);assert.equal(n.file,'资料/测试.PDF');assert.ok('subpath' in n);assert.equal(n.subpath,'#page=4')});
test('invalid PDF pages and paths cannot be persisted',()=>{for(const value of [0,-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>pdfPage(value));for(const path of ['/a.pdf','../a.pdf','a/../b.pdf','a.md'])assert.throws(()=>pdfCard('a',path,0,0));for(const value of [0,-1,1.5]){const b=board();b.nodes[0].pdfPage=value;assert.throws(()=>parseBoard(JSON.stringify(b)))}const b=board();b.nodes[0].file='a.md';assert.throws(()=>parseBoard(JSON.stringify(b)))});
test('PDF page metadata is rejected on Markdown cards',()=>{const b=board();b.nodes[0]={...b.nodes[0],kind:'card',file:'note.md',pdfPage:3};assert.throws(()=>parseBoard(JSON.stringify(b)))});
test('native PDF drops preserve page locators without consuming ordinary prose',()=>{assert.deepEqual(pdfDropReference('![[资料/a.pdf#page=3|证据]]'),{path:'资料/a.pdf',page:3});assert.deepEqual(pdfDropReference('a.PDF'),{path:'a.PDF',page:1});for(const text of ['https://example.com/a.pdf','普通文字','[[a.md]]','[[a.pdf#page=0]]','a.pdf\nb.pdf'])assert.equal(pdfDropReference(text),undefined);assert.equal(pdfSubpath(12),'#page=12')});
function fixture(options:{load?:()=>Promise<any>;render?:()=>Promise<void>;failRead?:boolean;size?:{width:number;height:number}}={}){
 let dispose=()=>{},destroyed=0,cancelled=0,appended=0,connected=true;const canvas={width:0,height:0,setAttribute(){},getContext(){return {}},remove(){}};
 const page={getViewport:({scale}:any)=>({width:(options.size?.width??600)*scale,height:(options.size?.height??800)*scale}),render:()=>({promise:options.render?.()??Promise.resolve(),cancel(){cancelled++}})};
 const task={promise:options.failRead?Promise.reject(Error('PDF 损坏')):Promise.resolve({numPages:3,getPage:async()=>page}),destroy:async()=>{destroyed++}};
 const host={ownerDocument:{createElement:()=>canvas},replaceChildren(){appended++}} as unknown as HTMLElement;
 return{run:(page=1)=>renderPdfThumbnail({host,src:'app://test.pdf',page,load:options.load??(async()=>({getDocument:()=>task})),register:fn=>dispose=fn,alive:()=>connected}),dispose:()=>{connected=false;dispose()},stats:()=>({destroyed,cancelled,appended,width:canvas.width,height:canvas.height})};
}
test('successful PDF thumbnails release the document and bound canvas memory',async()=>{const f=fixture({size:{width:4000,height:12000}});assert.deepEqual(await f.run(),{page:1,total:3});assert.deepEqual(f.stats(),{destroyed:1,cancelled:0,appended:1,width:300,height:900});f.dispose();assert.equal(f.stats().destroyed,1);assert.equal(f.stats().width,0)});
test('invalid/outdated pages fail clearly and release PDF resources',async()=>{const f=fixture();await assert.rejects(f.run(4),/共 3 页/);assert.equal(f.stats().destroyed,1);assert.equal(f.stats().appended,0)});
test('failed PDF reads release the loading task',async()=>{const f=fixture({failRead:true});await assert.rejects(f.run(),/损坏/);assert.equal(f.stats().destroyed,1)});
test('unmount during rendering cancels and prevents a late canvas append',async()=>{let done!:()=>void;const wait=new Promise<void>(resolve=>done=resolve),f=fixture({render:()=>wait});const pending=f.run();await new Promise(resolve=>setImmediate(resolve));f.dispose();done();assert.equal(await pending,undefined);assert.equal(f.stats().appended,0);assert.equal(f.stats().destroyed,1);assert.equal(f.stats().cancelled,1)});
test('invalid PDF page dimensions do not allocate an unbounded canvas',async()=>{const f=fixture({size:{width:Infinity,height:1}});await assert.rejects(f.run(),/尺寸/);assert.equal(f.stats().destroyed,1);assert.equal(f.stats().width,0)});
