import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';
const source=readFileSync('src/reading-desk-view.ts','utf8'),start=source.indexOf(' private async renderPage('),end=source.indexOf('\n private step(',start);
class TFile{path='note.md';stat={size:20,mtime:1};}
class Element{dataset:Record<string,string>={};style={};disabled=false;scrollTop=180;emptyCalls=0;empty(){this.emptyCalls++;this.scrollTop=0}createDiv(){return new Element()}createEl(){return new Element()}createSpan(){return new Element()}setAttribute(){}setText(){}querySelectorAll(){return []}addEventListener(){}}
function fixture(){let reads=0,renders=0,controls=0;const file=new TFile(),node:any={id:'a',kind:'card',file:'note.md'},view:any={alive:true,generation:0,pageKey:'',page:new Element(),headings:[],app:{vault:{getAbstractFileByPath:()=>file,cachedRead:async()=>{reads++;return '# Content'}}},host:{board:()=>({nodes:[node]})},button:()=>new Element(),items:()=>[node],renderCompanion(){},syncPageControls(){controls++}};
 const View=new Function('Component','TFile','readingTitle','reviewLabels','MarkdownRenderer','remoteImageUrl',transformSync('class View{'+source.slice(start,end)+'};return View',{loader:'ts'}).code)(class{load(){}unload(){}},TFile,(n:any)=>n.title||n.file,{later:'待读',reading:'在读',done:'已读'},{render:async()=>{renders++}},()=>undefined);
 view.renderPage=View.prototype.renderPage;return{view,file,node,counts:()=>({reads,renders,controls})};
}
test('filtering the same article retains its scroll and avoids rereading or rerendering Markdown',async()=>{const f=fixture();await f.view.renderPage(f.node);f.view.page.scrollTop=480;for(let i=0;i<25;i++)await f.view.renderPage(f.node);assert.equal(f.counts().reads,1);assert.equal(f.counts().renders,1);assert.equal(f.view.page.scrollTop,480);});
test('review and lock changes update controls while preserving the article',async()=>{const f=fixture();await f.view.renderPage(f.node);f.node.review='done';f.node.locked=true;await f.view.renderPage(f.node);assert.equal(f.counts().reads,1);assert(f.counts().controls>0);});
test('modified files and explicit refresh invalidate the active article',async()=>{const f=fixture();await f.view.renderPage(f.node);f.file.stat.mtime++;await f.view.renderPage(f.node);await f.view.renderPage(f.node,true);assert.equal(f.counts().reads,3);});
test('a failed read can be retried without changing the selected article',async()=>{const f=fixture();f.view.app.vault.cachedRead=async()=>{throw Error('disk')};await f.view.renderPage(f.node);let calls=0;f.view.app.vault.cachedRead=async()=>{calls++;return 'recovered'};await f.view.renderPage(f.node);assert.equal(calls,1);assert.equal(f.counts().renders,1);});
test('concurrent rendering requests for the same article share the pending read',async()=>{const f=fixture();let resolve!:(s:string)=>void,reads=0;f.view.app.vault.cachedRead=()=>{reads++;return new Promise<string>(r=>resolve=r)};const first=f.view.renderPage(f.node),second=f.view.renderPage(f.node);resolve('ready');await second;if(reads===1)await first;assert.equal(reads,1);});
