import {test} from 'node:test';import assert from 'node:assert/strict';import {Board,Card,emptyBoard,parseBoard} from '../src/model';import {readingItems,markReading,readingProgress,readingDigest} from '../src/reading-desk';
const n=(id:string,y=0):Card=>({id,kind:'text',text:id,x:0,y,width:200,height:100,color:'sand'});const board=():Board=>({...emptyBoard(),version:3,nodes:[n('Alpha',20),{...n('Beta'),review:'done'},{...n('Lock'),locked:true},{...n('Group'),kind:'section',title:'Group'}]});const options={query:'',status:'all',sort:'board',onlySelected:false} as const;
test('reading queue omits groups and defaults unset state to later',()=>{assert.equal(readingItems(board(),new Set(),options).length,3);assert.equal(readingItems(board(),new Set(),{...options,status:'later'}).length,2);});
test('reading scope intersects selection, query and review state',()=>{assert.deepEqual(readingItems(board(),new Set(['Alpha','Beta']),{...options,onlySelected:true,query:'ＡＬＰＨＡ',status:'later'}).map(n=>n.id),['Alpha']);});
test('reading ordering supports spatial and alphabetical without mutating board',()=>{const b=board();assert.equal(readingItems(b,new Set(),options)[0].id,'Beta');assert.equal(readingItems(b,new Set(),{...options,sort:'title'})[0].id,'Alpha');assert.equal(b.nodes[0].id,'Alpha');});
test('mark read changes layout metadata only and preserves locked objects',()=>{const b=board();markReading(b,new Set(b.nodes.map(n=>n.id)),'reading');assert.equal(b.nodes[0].review,'reading');assert.equal(b.nodes[0].text,'Alpha');assert.equal(b.nodes[2].review,undefined);assert.equal(b.nodes[3].review,undefined);});
test('mark later removes optional review property',()=>{const b=board();markReading(b,new Set(['Beta']),'later');assert.equal('review' in b.nodes[1],false);});
test('progress reports actual count with zero-safe denominator',()=>{assert.deepEqual(readingProgress([]),{total:0,done:0,reading:0,percent:0});assert.equal(readingProgress(readingItems(board(),new Set(),options)).percent,33);});
test('digest groups statuses and outputs file references without copying source text',()=>{const b=board();b.nodes[1]={...b.nodes[1],kind:'card',file:'Notes/来源.md'};const text=readingDigest(readingItems(b,new Set(),options),'我的\n白板');assert.ok(text.includes('# 我的 白板 · 阅读回顾'));assert.ok(text.includes('## 已读\n\n- [[Notes/来源.md]]'));});
test('review status persists and invalid values or group review are rejected',()=>{const b=board();assert.equal(parseBoard(JSON.stringify(b)).nodes[1].review,'done');b.nodes[0].review='invalid' as any;assert.throws(()=>parseBoard(JSON.stringify(b)));delete b.nodes[0].review;b.nodes[3].review='done';assert.throws(()=>parseBoard(JSON.stringify(b)));});

import {connectedReadingIds,readingRelations,readingWindow} from '../src/reading-desk';
test('connection filter ignores dangling links and non-readable containers',()=>{const b=board();b.edges=[{id:'a',from:'Alpha',to:'Beta',label:'evidence'},{id:'b',from:'Lock',to:'Group',label:''},{id:'c',from:'Lock',to:'missing',label:''}];assert.deepEqual([...connectedReadingIds(b)],['Alpha','Beta']);assert.deepEqual(readingItems(b,new Set(),{...options,connection:'isolated'}).map(n=>n.id),['Lock']);});
test('kind filter intersects links, status and selected scope',()=>{const b=board();b.nodes[1]={...b.nodes[1],kind:'card',file:'Notes/Beta.md'};b.edges=[{id:'a',from:'Alpha',to:'Beta',label:''}];assert.deepEqual(readingItems(b,new Set(['Beta']),{...options,kind:'card',connection:'connected',status:'done',onlySelected:true}).map(n=>n.id),['Beta']);assert.equal(readingItems(b,new Set(),{...options,kind:'image'}).length,0);});
test('relations preserve edge labels and direction for parallel connections',()=>{const b=board();b.edges=[{id:'out',from:'Alpha',to:'Beta',label:'依据'},{id:'in',from:'Beta',to:'Alpha',label:'质疑'},{id:'both',from:'Alpha',to:'Lock',label:'对照',direction:'both'},{id:'none',from:'Lock',to:'Alpha',label:'',direction:'none'}];assert.deepEqual(readingRelations(b,'Alpha').map(r=>[r.edgeId,r.direction,r.label]),[['out','指向','依据'],['in','来自','质疑'],['both','双向','对照'],['none','关联','未命名连线']]);});
test('relations do not fabricate targets for dangling edges or groups',()=>{const b=board();b.edges=[{id:'a',from:'Alpha',to:'unknown',label:''},{id:'b',from:'Alpha',to:'Group',label:''}];assert.deepEqual(readingRelations(b,'Alpha'),[]);});
test('queue windows bound DOM rows and always contain the active item past 1000',()=>{const items=Array.from({length:1205},(_,i)=>n(String(i),i));const window=readingWindow(items,'1201');assert.equal(window.start,1200);assert.equal(window.end,1205);assert.ok(window.nodes.some(n=>n.id==='1201'));assert.equal(readingWindow(items,'999').nodes.length,100);assert.equal(items.length,1205);});
test('empty and filtered-away active queue windows are safe',()=>{assert.deepEqual(readingWindow([],'missing'),{start:0,end:0,nodes:[]});assert.equal(readingWindow([n('a')],'missing').start,0);});
test('batch review honors the filtered set and restores through real history',async()=>{const {History}=await import('../src/model');const b=board(),h=new History();h.push(b);const ids=new Set(readingItems(b,new Set(),{...options,status:'later'}).map(n=>n.id));markReading(b,ids,'done');assert.equal(b.nodes[0].review,'done');assert.equal(b.nodes[2].review,undefined);const restored=h.undo(b)!;assert.equal(restored.nodes[0].review,undefined);assert.equal(restored.nodes[1].review,'done');});
