import {test} from 'node:test';import assert from 'node:assert/strict';
import {markdownEdit,markdownActive} from '../src/markdown-edit';
import {appendJournalTask} from '../src/calendar-tools';
import {quadrantOverride,stripQuadrant} from '../src/task-quadrants';
import {journalTaskBlock,planTasks} from '../src/task-planner-model';
import {extractTasks} from '../src/model';
import {cleanDatabasePreferences,customMatches} from '../src/database-custom';
const edit=(s:string,c:any,a=0,b=s.length)=>markdownEdit(s,a,b,c).text;
test('B04 clear inner selection removes strong underscore wrappers',()=>assert.equal(edit('__word__','clear',2,6),'word'));
test('B05 clear inner padded code selection removes all delimiters and padding',()=>assert.equal(edit('`` `x` ``','clear',3,6),'`x`'));
test('B06 escaped bold opening is not consumed as formatting',()=>assert.equal(edit('\\**word**','bold',3,7),'\\****word****'));
test('B07 whitespace-only formatting does not duplicate selected whitespace',()=>assert.equal(edit('  ','bold'),'  **文字**'));
test('B08 underline toggling round trips literal angle brackets',()=>{const a=markdownEdit('<x>',0,3,'underline');assert.equal(edit(a.text,'underline',a.start,a.end),'<x>');});
test('B09 clear preserves literal HTML inside code',()=>assert.equal(edit('`<u>literal</u>`','clear'),'<u>literal</u>'));
test('B10 toggle list spanning a blank paragraph preserves blank lines',()=>assert.equal(edit('- a\n\n- b','bullet'),'a\n\nb'));
test('B11 ordered task conversion does not duplicate checkboxes',()=>assert.equal(edit('1. [x] done','task'),'1. done'));
test('B12 multi-paragraph bold yields valid independent emphasis',()=>{assert.equal(edit('a\n\nb','bold'),'**a**\n\n**b**');assert.equal(edit('**a**\n\n**b**','bold'),'a\n\nb');});
test('B13 active formatting recognises underscore emphasis',()=>{assert(markdownActive('__word__',2,6).has('bold'));assert(markdownActive('_word_',1,5).has('italic'));});
test('B14 diary insertion ignores Obsidian comments and targets live section',()=>{const s='%%\n## 今日任务\n- [ ]\n%%\n\n## 今日任务\n- [ ]\n';assert.equal(appendJournalTask(s,'live'),'%%\n## 今日任务\n- [ ]\n%%\n\n## 今日任务\n- [ ] live\n');});
test('B15 quadrant metadata inside an Obsidian comment is literal',()=>{const s='task %% <!-- thoughtspace:quadrant=q1 --> %%';assert.equal(quadrantOverride(s),undefined);assert.equal(stripQuadrant(s),s);});
test('B16 malformed saved field cannot crash settings load',()=>assert.deepEqual(cleanDatabasePreferences({fields:[{key:12,type:'text'}]}),{fields:[],views:[]}));
test('B17 invalid typed saved filter does not crash matching',()=>assert.equal(customMatches({score:2},[{key:'score',op:'gte',value:'abc'}],[{key:'score',type:'number'}]),false));
test('B18 task code example does not suppress live diary task block',()=>{const s='````md\n```thoughtspace-tasks\n2026-09-14\n```\n````\n';assert.notEqual(journalTaskBlock(s,'2026-09-14'),s);});
test('B19 invalid date suffix is not truncated to a valid task date',()=>assert.equal(planTasks('- [ ] work 📅 2026-09-141','a.md','日记')[0].due,undefined));
test('B20 quote markers inside fenced code do not reset its context',()=>assert.equal(extractTasks('```md\n> example\n- [ ] hidden\n```').length,0));
test('B21 over-indented fence cannot close a top-level fenced example',()=>assert.equal(extractTasks('```md\n    ```\n- [ ] hidden\n```').length,0));
