import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import {Board,History,clone,emptyBoard,uid} from '../src/model';
import {studioDraft} from '../src/board-studio';
import {ViewTrail} from '../src/board-experience';
import {addSavedView,renameSavedView,removeSavedView,reorderSavedView,savedViewOrderStamp,savedViewStamp,savedViewViewport,updateSavedView} from '../src/saved-views';
type Options={cls?:string;text?:string;attr?:Record<string,string>;type?:string;value?:string};
class Document {activeElement?:Element;}
class Element {
 children:Element[]=[];parent?:Element;classes=new Set<string>();attributes:Record<string,string>={};value='';disabled=false;tabIndex=-1;selects=0;writes=0;private text='';onclick?:()=>void;ondblclick?:()=>void;oninput?:()=>void;onkeydown?:(event:any)=>void;
 constructor(readonly tagName:string,readonly ownerDocument:Document,options:Options|string={}){const opts=typeof options==='string'?{cls:options}:options;this.text=opts.text||'';this.attributes={...opts.attr};this.value=opts.value||'';for(const cls of (opts.cls||'').split(/\s+/).filter(Boolean))this.classes.add(cls);}
 get textContent():string{return this.text+this.children.map(child=>child.textContent).join('');}set textContent(value:string){this.text=value;this.writes++;}
 createEl(tag:string,options:Options|string={}){this.writes++;const child=new Element(tag.toUpperCase(),this.ownerDocument,options);child.parent=this;this.children.push(child);return child;}
 createDiv(options:Options|string={}){return this.createEl('div',options);}createSpan(options:Options|string={}){return this.createEl('span',options);}createSvg(tag:string,options:Options|string={}){return this.createEl(tag,options);}
 addClass(...names:string[]){for(const name of names)this.classes.add(name);}setAttribute(name:string,value:string){this.writes++;this.attributes[name]=value;}getAttribute(name:string){return this.attributes[name]??null;}
 setText(text:string){this.writes++;this.text=text;this.children=[];}empty(){this.writes++;for(const child of this.children)child.parent=undefined;this.children=[];this.text='';}focus(){this.ownerDocument.activeElement=this;}select(){this.selects++;}click(){if(!this.disabled)this.onclick?.();}
 matches(selector:string){if(selector.startsWith('.'))return this.classes.has(selector.slice(1));const attr=/^\[([^=]+)=([^\]]+)\]$/.exec(selector);return attr?this.getAttribute(attr[1])===attr[2]:this.tagName===selector.toUpperCase();}
 querySelectorAll(selector:string):Element[]{return this.children.flatMap(child=>[...(child.matches(selector)?[child]:[]),...child.querySelectorAll(selector)]);}querySelector(selector:string){return this.querySelectorAll(selector)[0];}
}
class Modal {readonly document=new Document();readonly modalEl=new Element('DIV',this.document);readonly titleEl=this.modalEl.createEl('h2');readonly contentEl=this.modalEl.createDiv();closeCount=0;constructor(readonly app:unknown){}close(){this.closeCount++;(this as unknown as {onClose:()=>void}).onClose();}}
const source=readFileSync('src/saved-views-view.ts','utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');
const SavedViewsModal=new Function('Modal','setIcon','themeSurface','clone','uid','addSavedView','renameSavedView','removeSavedView','reorderSavedView','savedViewOrderStamp','savedViewStamp','savedViewViewport','updateSavedView',transformSync(source+'\nreturn SavedViewsModal;',{loader:'ts'}).code)(Modal,()=>{},()=>{},clone,uid,addSavedView,renameSavedView,removeSavedView,reorderSavedView,savedViewOrderStamp,savedViewStamp,savedViewViewport,updateSavedView);
function fixture(count=3){const board:Board={...emptyBoard(),version:3,nodes:[{id:'a',kind:'text',text:'不修改正文',x:0,y:0,width:120,height:80,color:'green'}]},owner={board},history=new History(),trail=new ViewTrail();for(let i=0;i<count;i++){board.viewport={x:i*100+20,y:i*50+30,zoom:1+i*.25};addSavedView(board,`v${i}`,['材料区','写作区','结论区'][i]||`区域 ${i}`);}board.viewport={x:900,y:800,zoom:.6};let active=true,commits=0,onCommit:(()=>void)|undefined;const restored:string[]=[];
 const ensure=()=>{if(!active)throw Error('白板已切换或暂停写入');return owner.board;},host={board:ensure,commit:(edit:(board:Board)=>void)=>{const current=ensure(),next=studioDraft(current,edit);if(next){history.push(current);owner.board=next;commits++;}onCommit?.();},restore:(id:string)=>{const current=ensure();trail.remember(current.viewport);current.viewport=savedViewViewport(current,id);restored.push(id);}};
 const modal=new SavedViewsModal({},host);modal.onOpen();const root=modal.contentEl as Element,list=root.querySelector('.ts-view-list')!,detail=root.querySelector('.ts-view-detail')!,feedback=root.querySelector('.ts-view-feedback')!,search=root.querySelector('input')!;
 return{modal,root,list,detail,feedback,search,history,trail,restored,host,get board(){return owner.board;},get commits(){return commits;},switchBoard:()=>{active=false;},setOnCommit:(fn:()=>void)=>{onCommit=fn;},replace:(next:Board)=>{owner.board=next;},button:(label:string)=>root.querySelectorAll('button').find(button=>button.getAttribute('aria-label')===label)!,rows:()=>list.querySelectorAll('[role=option]'),name:()=>detail.querySelector('input')!};
}
function key(el:Element,key:string,options:Record<string,unknown>={}){const event={key,target:el,isComposing:false,keyCode:0,altKey:false,ctrlKey:false,metaKey:false,shiftKey:false,prevented:false,stopped:false,preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;},...options};el.onkeydown?.(event);return event;}
test('opening and filtering only read the board and select matching details',()=>{const f=fixture(),before=JSON.stringify(f.board);assert.equal(f.rows().length,3);f.search.value='写作';f.search.oninput?.();assert.equal(f.rows().length,1);assert.equal(f.name().value,'写作区');f.search.value='无匹配';f.search.oninput?.();assert.equal(f.rows().length,0);assert.match(f.detail.textContent,/没有匹配/);assert.equal(JSON.stringify(f.board),before);assert.equal(f.commits,0);});
test('saving captures the live camera once, selects its editable name, and undoes atomically',()=>{const f=fixture(),before=JSON.stringify(f.board),camera={...f.board.viewport};f.button('保存当前视角').click();assert.equal(f.commits,1);assert.equal(f.board.savedViews!.length,4);assert.deepEqual(f.board.savedViews!.at(-1)!.viewport,camera);assert.equal(f.modal.document.activeElement,f.name());assert.equal(f.name().selects,1);assert.equal(JSON.stringify(f.history.undo(f.board)),before);});
test('rename, camera update, reorder and removal each create a single reversible board edit',()=>{for(const action of ['保存名称','用当前白板位置更新','下移视角','移除视角']){const f=fixture(),before=JSON.stringify(f.board),camera={...f.board.viewport},content=JSON.stringify(f.board.nodes);if(action==='保存名称')f.name().value='新的名称';f.button(action).click();assert.equal(f.commits,1,action);assert.deepEqual(f.board.viewport,camera);assert.equal(JSON.stringify(f.board.nodes),content);assert.equal(JSON.stringify(f.history.undo(f.board)),before);}});
test('single clicks preserve row identity so native double click can restore the reviewed view',()=>{const f=fixture(),rows=f.rows(),camera={...f.board.viewport};rows[1].click();assert.deepEqual(f.rows(),rows);assert.equal(rows[1].getAttribute('aria-selected'),'true');rows[1].click();rows[1].ondblclick?.();assert.deepEqual(f.restored,['v1']);assert.equal(f.modal.closeCount,1);assert.equal(f.commits,0);assert.deepEqual(f.trail.travel(f.board.viewport),camera);});
test('arrow and Home End navigation keep roving focus without rebuilding rows',()=>{const f=fixture(),rows=f.rows();rows[0].focus();key(f.list,'ArrowDown',{target:rows[0]});assert.deepEqual(f.rows(),rows);assert.equal(f.modal.document.activeElement,rows[1]);assert.equal(rows[1].tabIndex,0);assert.equal(rows[0].tabIndex,-1);key(f.list,'End',{target:rows[1]});assert.equal(f.modal.document.activeElement,rows[2]);key(f.list,'Home',{target:rows[2]});assert.equal(f.modal.document.activeElement,rows[0]);});
test('composition and modifier keys cannot navigate the list or rename a view',()=>{for(const modifiers of [{isComposing:true},{keyCode:229},{altKey:true},{metaKey:true},{ctrlKey:true},{shiftKey:true}]){const f=fixture(),rows=f.rows();assert.equal(key(f.list,'ArrowDown',{target:rows[0],...modifiers}).prevented,false);f.name().value='不能改';assert.equal(key(f.name(),'Enter',modifiers).prevented,false);assert.equal(f.commits,0);}const f=fixture();f.name().value='确认名称';assert.equal(key(f.name(),'Enter').prevented,true);assert.equal(f.board.savedViews![0].name,'确认名称');});
test('stale rename, update and delete previews reject before a history or content write',()=>{for(const action of ['保存名称','用当前白板位置更新','移除视角']){const f=fixture();renameSavedView(f.board,'v0','另一窗口');f.name().value='旧名称';const before=JSON.stringify(f.board);f.button(action).click();assert.equal(JSON.stringify(f.board),before);assert.equal(f.commits,0);assert.match(f.feedback.textContent,/已变化/);f.button('刷新视角').click();assert.equal(f.name().value,'另一窗口');assert.equal(f.feedback.textContent,'');}});
test('stale restore and deleted cameras never close the modal or change the live camera',()=>{for(const mutate of [(board:Board)=>updateSavedView(board,'v0',{x:9,y:8,zoom:1}),(board:Board)=>removeSavedView(board,'v0')]){const f=fixture(),camera={...f.board.viewport};mutate(f.board);f.button('定位到这里').click();assert.deepEqual(f.board.viewport,camera);assert.deepEqual(f.restored,[]);assert.equal(f.modal.closeCount,0);assert.match(f.feedback.textContent,/已变化|已移除/);}});
test('stale reorder cannot move against a different neighbor and refresh accepts the new order',()=>{const f=fixture();reorderSavedView(f.board,'v2',-1);const before=JSON.stringify(f.board);f.button('下移视角').click();assert.equal(JSON.stringify(f.board),before);assert.match(f.feedback.textContent,/顺序已变化/);f.button('刷新视角').click();f.button('下移视角').click();assert.deepEqual(f.board.savedViews!.map(view=>view.id),['v2','v0','v1']);});
test('owner guards reject save, edits and restore after a board switch',()=>{for(const action of ['保存当前视角','保存名称','用当前白板位置更新','下移视角','移除视角','定位到这里']){const f=fixture(),before=JSON.stringify(f.board);f.switchBoard();f.button(action).click();assert.equal(JSON.stringify(f.board),before);assert.equal(f.commits,0);assert.deepEqual(f.restored,[]);assert.match(f.feedback.textContent,/白板已切换/);assert.equal(f.modal.closeCount,0);}});
test('undo replaces the board snapshot; refresh reads the restored cameras without stale references',()=>{const f=fixture();f.name().value='新名称';f.button('保存名称').click();f.replace(f.history.undo(f.board)!);f.button('刷新视角').click();assert.equal(f.name().value,'材料区');f.button('定位到这里').click();assert.deepEqual(f.board.viewport,{x:20,y:30,zoom:1});});
test('detached handlers do not write or rebuild feedback after closing',()=>{const f=fixture(),save=f.button('保存当前视角'),rename=f.button('保存名称'),row=f.rows()[0],before=JSON.stringify(f.board);f.modal.close();const feedbackWrites=f.feedback.writes;save.click();rename.click();row.click();row.ondblclick?.();f.search.oninput?.();assert.equal(JSON.stringify(f.board),before);assert.equal(f.feedback.writes,feedbackWrites);assert.equal(f.root.children.length,0);assert.equal(f.commits,0);});
test('closing during a host commit never recreates dialog UI or writes detached feedback',()=>{for(const action of ['保存当前视角','保存名称','用当前白板位置更新','下移视角','移除视角']){const f=fixture();f.name().value='新名称';let writes=0;f.setOnCommit(()=>{f.modal.close();writes=f.feedback.writes;});f.button(action).click();assert.equal(f.root.children.length,0,action);assert.equal(f.feedback.writes,writes,action);assert.equal(f.modal.closeCount,1,action);}});
test('restore closes without a detached feedback update or duplicate navigation',()=>{const f=fixture(),restore=f.button('定位到这里'),writes=f.feedback.writes;restore.click();restore.click();assert.deepEqual(f.restored,['v0']);assert.equal(f.feedback.writes,writes);assert.equal(f.modal.closeCount,1);});
test('preview names use unique SVG title references instead of native tooltip attributes',()=>{const first=fixture(),second=fixture(),ids:string[]=[];for(const f of [first,second]){const svg=f.detail.querySelector('svg')!,title=svg.querySelector('title')!;assert.equal(svg.getAttribute('aria-label'),null);assert.equal(svg.getAttribute('aria-labelledby'),title.getAttribute('id'));assert.match(title.textContent,/材料区的白板位置示意/);ids.push(title.getAttribute('id')!);}assert.equal(new Set(ids).size,2);});
