import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';import {selectionFormatKey} from '../src/selection-format';import {emptyBoard,Card} from '../src/model';
const card:Card={id:'c',kind:'card',file:'n.md',x:0,y:0,width:300,height:200,color:'sand'};
test('unchanged toolbar controls survive 200 pan frames; styles and owner invalidate them',()=>{assert.match(execFileSync(process.execPath,['qa/toolbar-stability-09411.cjs'],{encoding:'utf8'}),/PASS unchanged controls retained/);});
test('format key ignores geometry and content but includes appearance, identity and locks',()=>{const b=emptyBoard();b.nodes=[card];const ids=new Set(['c']),key=selectionFormatKey(b,ids,undefined);for(const patch of [{x:100},{width:600},{text:'changed'},{title:'new alias'}])assert.equal(selectionFormatKey({...b,nodes:[{...card,...patch}]},ids,undefined),key);for(const patch of [{locked:true},{file:'other.md'},{color:'blue' as const},{fontSize:17},{customBorder:true},{transparent:true},{textAlign:'right' as const}])assert.notEqual(selectionFormatKey({...b,nodes:[{...card,...patch}]},ids,undefined),key);assert.notEqual(selectionFormatKey(b,ids,undefined,true),key);assert.notEqual(selectionFormatKey(b,new Set(),undefined),key);});
test('font size dropdown matches rendered defaults and preserves nonpreset sizes',()=>{const line=readFileSync('src/main.ts','utf8').split('\n').find(l=>l.includes("select('字号'"))!;for(const [node,want]of [[card,'14'],[{...card,kind:'text'},'16'],[{...card,fontSize:17},'17']] as const){let actual='',options:Record<string,string>={};new Function('select','texts','patchText',transformSync(line,{loader:'ts'}).code)((_l:unknown,o:Record<string,string>,values:string[])=>{actual=values[0];options=o},[node],()=>{});assert.equal(actual,want);assert.ok(options[want]);}});

test('active Markdown toolbar survives refreshes and is replaced for a new editor',()=>{assert.match(execFileSync(process.execPath,['qa/toolbar-stability-09412.cjs'],{encoding:'utf8'}),/PASS active editor toolbar reused/);});
test('unselected boards and absent edge selection do not scan unrelated nodes or edges',()=>{
 const b=emptyBoard();let reads=0;Object.defineProperty(b,'nodes',{get(){reads++;return []}});Object.defineProperty(b,'edges',{get(){reads++;return []}});
 assert.equal(selectionFormatKey(b,new Set(),undefined),'[false,"nodes",[]]');assert.equal(reads,0);
});
