import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';
const source=readFileSync('src/main.ts','utf8'),start=source.indexOf('  async session(file:'),end=source.indexOf('\n  async readBoard(',start);
class Session{listeners=new Set();flush=async()=>{};constructor(_host:unknown,public file:unknown,public raw:string){}}
const Host=new Function('Session',transformSync('class Host{'+source.slice(start,end)+'};return Host',{loader:'ts'}).code)(Session);
function fixture(){const host=new Host();let reads=0;host.sessions=new Map();host.app={vault:{read:async()=>{reads++;return 'board'}}};return{host,file:{path:'board.thoughtspace'},reads:()=>reads};}
test('releasing a retired session does not evict the newer live session for the same file',async()=>{const f=fixture(),old=await f.host.session(f.file);await f.host.release(old);const current=await f.host.session(f.file);current.listeners.add(()=>{});await f.host.release(old);assert.equal(await f.host.session(f.file),current);assert.equal(f.reads(),2);});
test('an older delayed release cannot evict a replacement session',async()=>{const f=fixture(),old=await f.host.session(f.file);let resolve!:()=>void;old.flush=()=>new Promise<void>(r=>resolve=r);const first=f.host.release(old);old.flush=async()=>{};await f.host.release(old);const current=await f.host.session(f.file);resolve();await first;assert.equal(await f.host.session(f.file),current);});
test('a listener attached while flushing preserves the shared session',async()=>{const f=fixture(),s=await f.host.session(f.file);s.flush=async()=>{s.listeners.add(()=>{})};await f.host.release(s);assert.equal(await f.host.session(f.file),s);});
test('unused sessions are evicted and failed reads remain retryable',async()=>{const f=fixture(),s=await f.host.session(f.file);await f.host.release(s);assert.equal(f.host.sessions.size,0);f.host.app.vault.read=async()=>{throw Error('read')};await assert.rejects(f.host.session(f.file),/read/);assert.equal(f.host.sessions.size,0);f.host.app.vault.read=async()=> 'retry';assert.equal((await f.host.session(f.file)).raw,'retry');});
test('an older rejected read cannot remove a newer cache entry',async()=>{const f=fixture();let reject!:(e:Error)=>void;f.host.app.vault.read=()=>new Promise<string>((_,r)=>reject=r);const old=f.host.session(f.file),replacement=Promise.resolve(new Session({},f.file,'new'));f.host.sessions.set(f.file,replacement);reject(Error('old read'));await assert.rejects(old,/old read/);assert.equal(f.host.sessions.get(f.file),replacement);});
