import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';import * as model from '../src/model';import * as mindmap from '../src/mindmap';
const source=readFileSync('src/main.ts','utf8'),start=source.indexOf('class Session {'),end=source.indexOf('\nexport default class ThoughtSpace',start),deps={...model,...mindmap,Notice:class{},EXT:'thoughtspace',report:()=>{}};
const Session=new Function(...Object.keys(deps),transformSync(source.slice(start,end)+';return Session',{loader:'ts'}).code)(...Object.values(deps));
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(process?:(fn:(s:string)=>string)=>Promise<void>,readExternal?:()=>Promise<string>){let disk=JSON.stringify(model.emptyBoard(),null,2);const plugin={app:{vault:{process:async(_:unknown,fn:(s:string)=>string)=>process?process(fn):void(disk=fn(disk)),read:readExternal||(async()=>disk)}},createUnique:async()=>({path:'恢复草稿.thoughtspace'})};const s=new Session(plugin,{path:'board.thoughtspace',basename:'board'},disk);return{s,read:()=>disk};}
test('saving acknowledges status without re-invalidating shared board content',async()=>{const {s}=fixture(),events:string[]=[];s.listeners.add((kind:string)=>events.push(kind||'board'));s.change((b:model.Board)=>b.viewport.x=400);await s.flush();assert.equal(events.filter(e=>e==='board').length,1);assert(events.includes('status'));assert.equal(s.status,'已保存');});
test('saving a viewport does not invalidate linked material and sidebar content',async()=>{const {s}=fixture(),events:string[]=[];s.listeners.add((kind:string)=>events.push(kind||'board'));s.board.viewport.x=500;s.persist();await s.flush();assert(!events.includes('board'));assert(events.includes('status'));});
test('failed disk writes still invalidate read-only state and retain recovery behavior',async()=>{const {s}=fixture(async()=>{throw Error('外部冲突')}),events:string[]=[];s.listeners.add((kind:string)=>events.push(kind||'board'));s.change((b:model.Board)=>b.viewport.x=400);await s.flush();assert(s.blocked);assert.match(s.status,/恢复草稿/);assert.equal(events.at(-1),'board');});
test('flush waits for a write queued while a previous write is in flight',async()=>{const releases:(()=>void)[]=[];const {s}=fixture(async()=>new Promise<void>(resolve=>releases.push(resolve)));s.board.viewport.x=100;s.persist();await tick();let finished=false;const flushing=s.flush().then(()=>{finished=true});s.board.viewport.x=200;s.persist();releases[0]();await tick();const prematurelyFinished=finished;assert.equal(releases.length,2);releases[1]();await flushing;assert.equal(prematurelyFinished,false);assert.equal(s.status,'已保存');});
test('save acknowledgement stays pending while a newer write is queued',async()=>{const releases:(()=>void)[]=[];const {s}=fixture(async()=>new Promise<void>(resolve=>releases.push(resolve))),states:string[]=[];s.listeners.add(()=>states.push(s.status));s.board.viewport.x=100;s.persist();await tick();s.board.viewport.x=200;s.persist();releases[0]();await tick();const falselySaved=states.includes('已保存');releases[1]();await s.flush();assert.equal(falselySaved,false);assert.equal(s.status,'已保存');});
test('one failing view listener does not block saving or other linked views',async()=>{const {s}=fixture();let other=0;s.listeners.add(()=>{throw Error('broken panel')});s.listeners.add(()=>other++);s.change((b:model.Board)=>b.viewport.x=250);await s.flush();assert(other>0);assert.equal(s.status,'已保存');assert.equal(s.blocked,false);});
test('persist after a save conflict keeps the error state instead of showing saving again',async()=>{const {s}=fixture(async()=>{throw Error('外部冲突')});s.change((b:model.Board)=>b.viewport.x=300);await s.flush();const status=s.status;s.persist();await s.flush();assert.equal(s.status,status);assert(s.blocked);});
test('an external read started before a local edit cannot overwrite the newer saved board',async()=>{let resolve!:(s:string)=>void;const pending=new Promise<string>(r=>resolve=r),{s,read}=fixture(undefined,()=>pending),external=s.externalUpdate();await tick();s.change((b:model.Board)=>b.viewport.x=900);await s.flush();const latest=read();resolve(JSON.stringify({...model.emptyBoard(),viewport:{x:100,y:10,zoom:1}}));await external;assert.equal(s.board.viewport.x,900);assert.equal(s.baseline,latest);assert.equal(s.blocked,false);});
test('an outdated invalid external read does not block a successfully saved local edit',async()=>{let resolve!:(s:string)=>void;const pending=new Promise<string>(r=>resolve=r),{s}=fixture(undefined,()=>pending),external=s.externalUpdate();await tick();s.change((b:model.Board)=>b.viewport.x=800);await s.flush();resolve('partial JSON from an older read');await external;assert.equal(s.board.viewport.x,800);assert.equal(s.blocked,false);assert.equal(s.status,'已保存');});
test('out-of-order external reads keep the most recently applied board',async()=>{const resolves:((s:string)=>void)[]=[],{s}=fixture(undefined,()=>new Promise(r=>resolves.push(r))),first=s.externalUpdate();await tick();const second=s.externalUpdate();await tick();resolves[1](JSON.stringify({...model.emptyBoard(),viewport:{x:700,y:10,zoom:1}}));await second;resolves[0](JSON.stringify({...model.emptyBoard(),viewport:{x:100,y:10,zoom:1}}));await first;assert.equal(s.board.viewport.x,700);});
test('a newer external request is not discarded when the older read finishes first',async()=>{const resolves:((s:string)=>void)[]=[],{s}=fixture(undefined,()=>new Promise(r=>resolves.push(r))),first=s.externalUpdate();await tick();const second=s.externalUpdate();await tick();resolves[0](JSON.stringify({...model.emptyBoard(),viewport:{x:100,y:10,zoom:1}}));await first;resolves[1](JSON.stringify({...model.emptyBoard(),viewport:{x:700,y:10,zoom:1}}));await second;assert.equal(s.board.viewport.x,700);});
test('invalid card measurement rolls back before persistence and undo history',async()=>{const{s,read}=fixture();s.change((b:model.Board)=>b.nodes.push({id:'note',kind:'card',file:'note.md',color:'sand',x:0,y:0,width:300,height:200}));await s.flush();const saved=read(),history=s.history.undoStack.length;assert.throws(()=>s.change((b:model.Board)=>b.nodes[0].height=NaN));await s.flush();assert.equal(read(),saved);assert.equal(s.board.nodes[0].height,200);assert.equal(s.history.undoStack.length,history);});
test('direct invalid viewport never serializes NaN to null on disk',async()=>{const{s,read}=fixture(),saved=read();s.board.viewport.zoom=NaN;s.persist();await s.flush();assert.equal(read(),saved);assert.equal(s.blocked,true);});
