import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';
class BoardView{file:any;fitCalls=0;fit(){this.fitCalls++}}
const source=readFileSync('src/main.ts','utf8');
function method(name:string,next:string,deps:Record<string,unknown>={}){const start=source.indexOf('  async '+name+'('),end=source.indexOf('\n  '+next,start);return new Function('BoardView','VIEW','WRITING','requestAnimationFrame',...Object.keys(deps),transformSync('class Host{'+source.slice(start,end)+'};return Host.prototype.'+name,{loader:'ts'}).code)(BoardView,'board','writing',(fn:()=>void)=>fn(),...Object.values(deps));}
// Import remains optional before introducing the in-flight coalescer so the old path can be reproduced.
import {SharedOpen} from '../src/view-opening';
function fixture(){const leaves:any[]=[],file={path:'a.thoughtspace'},owner={blocked:false,flush:async()=>{}},board={file,session:owner,prepareWriting:async()=>{},closed:false};let creates=0;
 const workspace={getLeavesOfType:(type:string)=>leaves.filter(l=>l.getViewState().type===type),getLeaf:()=>{creates++;let state:any={type:'empty',state:{}};const leaf:any={view:new BoardView(),getViewState:()=>state,loadIfDeferred:async()=>{},openFile:async(f:any)=>{await Promise.resolve();leaf.view.file=f;state={type:'board',state:{file:f.path}}},setViewState:async(s:any)=>{await Promise.resolve();state=s},};leaves.push(leaf);return leaf;},revealLeaf:async()=>{},setActiveLeaf:()=>{}};
 const host:any={app:{workspace},boardOpening:new SharedOpen(),writingOpening:new SharedOpen(),writingPreparation:new SharedOpen(),currentBoard:board};return{host,board,file,leaves,workspace,created:()=>creates};}
test('concurrent requests create one board tab and fit works on an already open board',async()=>{const {host,file,created,leaves}=fixture();host.openBoard=method('openBoard','openBoardOrganizer(',{SharedOpen});await Promise.all([host.openBoard(file),host.openBoard(file),host.openBoard(file)]);assert.equal(created(),1);await host.openBoard(file,true);assert.equal(leaves[0].view.fitCalls,1);});
test('reopening writing reuses the same page without resetting its state',async()=>{const {host,board,created}=fixture();host.openWriting=method('openWriting','async recordBoardVisit(',{SharedOpen});const first=await host.openWriting(board),state=first.getViewState();state.state.resourceMode='reference';const next=await host.openWriting(board);assert.equal(next,first);assert.equal(created(),1);assert.equal(next.getViewState().state.resourceMode,'reference');});
test('concurrent writing requests prepare and create only once',async()=>{const {host,board,created}=fixture();let prepares=0;board.prepareWriting=async()=>{prepares++;await Promise.resolve()};host.openWriting=method('openWriting','async recordBoardVisit(',{SharedOpen});const [a,b]=await Promise.all([host.openWriting(board),host.openWriting(board)]);assert.equal(a,b);assert.equal(prepares,1);assert.equal(created(),1);});
test('switching the source board while preparing writing does not open the wrong document',async()=>{const {host,board,created}=fixture();board.prepareWriting=async()=>{board.file={path:'b.thoughtspace'}};host.openWriting=method('openWriting','async recordBoardVisit(',{SharedOpen});await assert.rejects(host.openWriting(board),/切换/);assert.equal(created(),0);});
test('failed openings are released and a later request can retry',async()=>{const opens=new SharedOpen<string,string>();let attempts=0;const fail=()=>{attempts++;return Promise.reject(Error('open failed'))};await Promise.all([assert.rejects(opens.run('a',fail),/failed/),assert.rejects(opens.run('a',fail),/failed/)]);assert.equal(attempts,1);assert.equal(await opens.run('a',async()=>{attempts++;return 'ready'}),'ready');assert.equal(attempts,2);assert.equal(await opens.run('a',async()=> 'new page'),'new page');});
test('different targets may open independently',async()=>{const opens=new SharedOpen<string,string>();assert.deepEqual(await Promise.all([opens.run('a',async()=> 'A'),opens.run('b',async()=> 'B')]),['A','B']);});
test('saving conflicts stop writing handoff without creating a new page',async()=>{const {host,board,created}=fixture();board.session.flush=async()=>{board.session.blocked=true};host.openWriting=method('openWriting','async recordBoardVisit(',{SharedOpen});await assert.rejects(host.openWriting(board),/暂停/);assert.equal(created(),0);});
test('two views of one board each commit their own draft before sharing the writing page',async()=>{const {host,board,created}=fixture();let first=0,second=0;board.prepareWriting=async()=>{first++};const other={...board,prepareWriting:async()=>{second++}};host.openWriting=method('openWriting','async recordBoardVisit(',{SharedOpen});const [a,b]=await Promise.all([host.openWriting(board),host.openWriting(other)]);assert.equal(a,b);assert.equal(first,1);assert.equal(second,1);assert.equal(created(),1);});
