import{test}from'node:test';import assert from'node:assert/strict';import{emptyBoard,parseBoard,clone,Card}from'../src/model';import{relatedNodes,orderNodes,matchSize,snapSelection,boardOutline}from'../src/workspace-tools';import{moveSelection,alignSelection,foldCards}from'../src/board-tools';
const fixture=()=>({...emptyBoard(),version:3 as const,nodes:[{id:'a',kind:'card',file:'A.md',x:13,y:19,width:260,height:180,color:'green'},{id:'b',kind:'card',file:'B.md',x:300,y:30,width:300,height:270,color:'blue'},{id:'c',kind:'text',text:'正文',x:610,y:30,width:300,height:200,color:'sand'}] as Card[],edges:[{id:'ab',from:'a',to:'b',label:'依据'},{id:'bc',from:'b',to:'c',label:''}]});
test('Direct neighbors do not expand transitively',()=>{assert.deepEqual([...relatedNodes(fixture(),new Set(['a']))],['a','b']);});
test('Layer changes preserve nodes edges references and locked order',()=>{const b=fixture();orderNodes(b,new Set(['a']),true);assert.equal(b.nodes.at(-1)!.id,'a');orderNodes(b,new Set(['a']),false);assert.equal(b.nodes[0].id,'a');b.nodes[0].locked=true;orderNodes(b,new Set(['a']),true);assert.equal(b.nodes[0].id,'a');assert.equal(b.edges.length,2);});
test('Size matching handles partial axes and excludes locks',()=>{const b=fixture();matchSize(b,new Set(['a','b']),'width');assert.equal(b.nodes[1].width,260);assert.equal(b.nodes[1].height,270);b.nodes[1].locked=true;assert.throws(()=>matchSize(b,new Set(['a','b']),'both'));});
test('Manual size matching disables text height fitting only on resized targets',()=>{
 for(const axis of ['width','height','both'] as const){const b=fixture();b.nodes[0]={...b.nodes[0],kind:'text',text:'reference',textAutoHeight:true};b.nodes[2].textAutoHeight=true;const unchanged=clone(b.nodes[1]);matchSize(b,new Set(['a','c']),axis);assert.equal(b.nodes[2].textAutoHeight,false,axis);assert.equal(b.nodes[2].autoSize,false,axis);assert.equal(b.nodes[2].width,axis==='height'?300:260);assert.equal(b.nodes[2].height,axis==='width'?200:180);assert.equal(b.nodes[0].textAutoHeight,true);assert.deepEqual(b.nodes[1],unchanged);}
});
test('Grid snap preserves group offsets and locked nodes',()=>{const b=fixture();b.nodes[2].locked=true;const delta=b.nodes[1].x-b.nodes[0].x;snapSelection(b,new Set(['a','b','c']));assert.equal(b.nodes[0].x%24,0);assert.equal(b.nodes[1].x-b.nodes[0].x,delta);assert.equal(b.nodes[2].x,610);});
test('Locked card resists move alignment and folding',()=>{const b=fixture();b.nodes[0].locked=true;const a=clone(b.nodes[0]);moveSelection(b,new Set(['a']),20,20);foldCards(b,new Set(['a']),true);alignSelection(b,new Set(['a','b','c']),'left');assert.deepEqual(b.nodes[0],a);});
test('New optional state roundtrips without mutating old files',()=>{const b=fixture();b.spaceId='space-123';b.snapToGrid=true;b.savedViews=[{id:'v',name:'问题区域',viewport:{x:10,y:20,zoom:.5}}];Object.assign(b.nodes[0],{autoFit:true,locked:true,borderWidth:3,borderStyle:'dashed'});assert.deepEqual(parseBoard(JSON.stringify(b)),b);assert.equal(parseBoard(JSON.stringify(emptyBoard())).savedViews,undefined);});
test('Parser rejects malformed styles and saved viewport values',()=>{for(const invalid of [{borderWidth:90},{locked:'yes'},{borderStyle:'oops'},{autoFit:'true'}]){const b=fixture();Object.assign(b.nodes[0],invalid);assert.throws(()=>parseBoard(JSON.stringify(b)));}const b=fixture();b.savedViews=[{id:'v',name:'x',viewport:{x:0,y:0,zoom:0}}];assert.throws(()=>parseBoard(JSON.stringify(b)));});
test('Markdown outline includes references text and relationship descriptions',()=>{const text=boardOutline(fixture(),'问题与证据');assert(text.includes('[[A.md]]'));assert(text.includes('正文'));assert(text.includes('A.md → B.md：依据'));});
