import {writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
const node=(id,kind,extra={})=>({id,kind,x:0,y:0,width:300,height:240,color:'sand',...extra});
const brain=nodes=>({version:3,presentation:'brain',nodes,edges:[],viewport:{x:0,y:0,zoom:1},brain:{version:1,centerId:'0',expandedIds:[],pins:[],history:{entries:['0'],index:0}}});
function pdf(){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 420] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>','<< /Length 48 >>\nstream\nBT /F1 18 Tf 30 350 Td (Synthetic QA PDF) Tj ET\nendstream','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let text='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(text));text+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(text);text+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return text;}
export async function run({page,browser,out,vault,report,check,screenshot,open}){
 await writeFile(path.join(vault,'QA.pdf'),pdf());await writeFile(path.join(vault,'QA-two.pdf'),pdf());
 const noteText='# Research\n\nNative source text with a [link](https://example.org).\n\n- [ ] A native task\n\n## Details\n\nSource identity and anchors stay in place.\n';
 await page.evaluate(async text=>{await app.vault.create('Research.md',text);await app.vault.create('Different.md','# Different\n\nA custom outer alias stays visible.\n');},noteText);
 const noteHash=createHash('sha256').update(noteText).digest('hex');
 const ordinary={version:3,nodes:[node('note','card',{file:'Research.md',title:'Research',x:60,y:100,autoFit:false,cardStyle:'band'}),node('alias','card',{file:'Different.md',title:'Custom alias',x:450,y:100,autoFit:false,cardStyle:'band'}),node('pdf-one','pdf',{file:'QA.pdf',title:'QA PDF',x:60,y:440,height:330}),node('pdf-two','pdf',{file:'QA-two.pdf',title:'QA two PDF',x:450,y:440,height:330}),node('group','section',{title:'Reading materials',x:20,y:60,width:820,height:750,color:'blue'})],edges:[],viewport:{x:50,y:10,zoom:1}};
 await writeFile(path.join(vault,'Materials.thoughtspace'),JSON.stringify(ordinary));await writeFile(path.join(vault,'Other.thoughtspace'),JSON.stringify({...ordinary,nodes:[]}));await open('Materials.thoughtspace');await page.evaluate(()=>{qaView.session.board.viewport={x:50,y:10,zoom:1};qaView.renderBoard();app.workspace.setActiveLeaf(qaView.leaf,{focus:true});});
 const card=id=>page.locator(`.workspace-leaf.mod-active .ts-node[data-id="${id}"]`);
 await page.waitForFunction(()=>document.querySelector('.workspace-leaf.mod-active .ts-card-preview h1')?.textContent==='Research');
 check('title compression is opt in',await card('note').evaluate(e=>e.classList.contains('is-title-source-line')),false);
 // Use the actual native preference control, then close its isolated window.
 await page.evaluate(()=>{app.setting.open();app.setting.openTabById('thoughtspace');});
 await page.waitForTimeout(250);let settingsPage=page;for(const p of browser.contexts()[0].pages())if(await p.locator('.ts-settings-v2').count()){settingsPage=p;break;}await settingsPage.locator('.ts-settings-search input').fill('精简重复卡片标题');
 let preference=settingsPage.locator('.setting-item').filter({hasText:'精简重复卡片标题'}).locator('.checkbox-container');await preference.click();await page.waitForTimeout(160);
 await settingsPage.screenshot({path:path.join(out,'title-preference.png')});report.screenshots.push('title-preference.png');await settingsPage.keyboard.press('Escape');await page.evaluate(()=>app.setting.close());await page.bringToFront();await page.evaluate(()=>require('@electron/remote').getCurrentWindow().focus());
 await page.waitForFunction(()=>document.querySelector('.workspace-leaf.mod-active .ts-node[data-id="note"]')?.classList.contains('is-title-source-line'));
 const titleState=await card('note').evaluate(e=>({h1:e.querySelector('h1')?.textContent,headerHeight:e.querySelector('.ts-node-header').getBoundingClientRect().height,sourcePrefix:getComputedStyle(e.querySelector('.ts-card-note-title'),'::before').content,sourceReachable:!!e.querySelector('[data-card-quick-action="open"]')||!!e.querySelector('.ts-card-actions button'),nativeHeadingId:e.querySelector('h1')?.getAttribute('data-heading')}));
 report.titleState=titleState;check('duplicate title becomes a compact source line',titleState.sourcePrefix.includes('来源')&&titleState.headerHeight>0&&titleState.headerHeight<34);check('native H1 remains Research',titleState.h1,'Research');check('custom alias stays full',await card('alias').evaluate(e=>e.classList.contains('is-title-source-line')),false);await screenshot('title-source-line-light.png');
 const outer=card('note').locator('.ts-card-note-title');await outer.dblclick({position:{x:18,y:8}});await page.getByRole('textbox',{name:'编辑卡片标题'}).fill('Cancelled alias');await page.keyboard.press('Escape');check('title keyboard cancellation retains the matching title',await outer.textContent(),'Research');
 await page.waitForTimeout(150);await outer.dblclick({position:{x:18,y:8}});await page.getByRole('textbox',{name:'编辑卡片标题'}).fill('New alias');await page.keyboard.press('Enter');await page.waitForTimeout(130);check('different saved alias restores full title',await card('note').evaluate(e=>e.classList.contains('is-title-source-line')),false);
 await page.locator('.workspace-leaf.mod-active .ts-stage').focus();await page.keyboard.press('Meta+z');await page.waitForTimeout(120);check('title undo restores source line',await card('note').evaluate(e=>e.classList.contains('is-title-source-line')));await page.keyboard.press('Meta+Shift+z');await page.waitForTimeout(120);check('title redo preserves alias',await card('note').locator('.ts-card-note-title').textContent(),'New alias');await page.keyboard.press('Meta+z');
 await page.evaluate(()=>{qaView.session.change(b=>{b.nodes.find(n=>n.id==='note').collapsed=true;});});await page.waitForTimeout(100);check('folded card keeps an explicit title',await card('note').evaluate(e=>!e.classList.contains('is-title-source-line')));await page.evaluate(()=>{qaView.session.undo();qaView.session.board.viewport.zoom=.25;qaView.renderBoard();});await page.waitForTimeout(100);check('low zoom summary keeps explicit title',await card('note').evaluate(e=>!e.classList.contains('is-title-source-line')));await screenshot('title-low-zoom.png');await page.evaluate(()=>{qaView.session.board.viewport.zoom=1;qaView.renderBoard();});
 await page.evaluate(()=>{app.setting.open();app.setting.openTabById('thoughtspace');});await page.waitForTimeout(250);for(const p of browser.contexts()[0].pages())if(await p.locator('.ts-settings-v2').count()){settingsPage=p;break;}await settingsPage.locator('.ts-settings-search input').fill('精简重复卡片标题');preference=settingsPage.locator('.setting-item').filter({hasText:'精简重复卡片标题'}).locator('.checkbox-container');await preference.click();await settingsPage.keyboard.press('Escape');await page.evaluate(()=>app.setting.close());await page.bringToFront();await page.evaluate(()=>require('@electron/remote').getCurrentWindow().focus());await page.waitForTimeout(120);check('turning preference off restores original shell',await card('note').evaluate(e=>!e.classList.contains('is-title-source-line')));
 check('title operations preserve source bytes',createHash('sha256').update(await readFile(path.join(vault,'Research.md'))).digest('hex'),noteHash);
 // A real third-party stylesheet is confined to this test document.
 const minimal=await readFile(path.resolve('../qa/fixtures/minimal-theme.css'),'utf8');report.theme={name:'Minimal',source:'https://github.com/kepano/obsidian-minimal',commit:'93321bdc23fc879966e1e3aa0cfeda77012f540f',sha256:createHash('sha256').update(minimal).digest('hex')};
 for(const thirdParty of [false,true])for(const theme of ['light','dark']){
  await page.evaluate(({theme,thirdParty,css})=>{document.querySelector('[data-qa-third-party]')?.remove();if(thirdParty){const style=document.createElement('style');style.dataset.qaThirdParty='true';style.textContent=css;document.head.append(style);}document.body.classList.toggle('theme-dark',theme==='dark');document.body.classList.toggle('theme-light',theme==='light');document.body.style.setProperty('--interactive-accent','#8d43c2');document.body.style.setProperty('--color-accent','#8d43c2');qaView.plugin.settings.accent='forest';qaView.applyPreferences();qaView.selected=new Set(['note']);qaView.updateSelection();qaView.renderSelectionTools();},{theme,thirdParty,css:minimal});
  const mode=page.locator('.workspace-leaf.mod-active .ts-format-mode-button[data-mode="fill"]');if(await mode.getAttribute('aria-pressed')!=='true')await mode.click();await mode.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');
  await page.waitForTimeout(240);const colors=await mode.evaluate(e=>{const s=getComputedStyle(e),root=getComputedStyle(e.closest('.ts-root'));const preview=document.querySelector('.workspace-leaf.mod-active .ts-card-preview');return{control:s.color,outline:s.outlineColor,outlineStyle:s.outlineStyle,accent:root.getPropertyValue('--ts-accent').trim(),host:getComputedStyle(document.body).getPropertyValue('--interactive-accent').trim(),link:getComputedStyle(preview.querySelector('a')).color,focus:e.matches(':focus-visible'),selected:e.getAttribute('aria-pressed')};});report.accent??=[];report.accent.push({theme,thirdParty,...colors});
  const accentRGB=await page.evaluate(color=>{const p=document.createElement('span');p.style.color=color;document.body.append(p);const value=getComputedStyle(p).color;p.remove();return value;},colors.accent);check(`${thirdParty?'Minimal':'default'} ${theme}: selected control uses plugin accent`,colors.control,accentRGB);check(`${thirdParty?'Minimal':'default'} ${theme}: keyboard focus is visible`,colors.focus&&colors.outlineStyle!=='none');await screenshot(`accent-${thirdParty?'minimal':'default'}-${theme}.png`);
 }
 await page.evaluate(()=>{document.querySelector('[data-qa-third-party]')?.remove();document.body.classList.remove('theme-dark');document.body.classList.add('theme-light');document.body.style.removeProperty('--interactive-accent');document.body.style.removeProperty('--color-accent');});
 // Board-owned dynamic search conditions; all changes are native UI intents.
 await page.locator('.workspace-leaf.mod-active').getByRole('button',{name:'搜索白板',exact:true}).click();const modal=page.locator('.ts-board-search');const closeSearch=async()=>{await page.keyboard.press('Escape');await modal.waitFor({state:'hidden'});await page.waitForTimeout(160);};await modal.waitFor();await modal.getByRole('combobox',{name:'对象类型',exact:true}).selectOption('pdf');await modal.getByRole('combobox',{name:'阅读状态',exact:true}).selectOption('later');await modal.locator('.ts-board-search-saved summary').click();await modal.getByRole('textbox',{name:'材料清单名称'}).fill('Pending PDFs');
 check('pending PDF query starts with two current materials',await modal.locator('.ts-board-search-row').count(),2);await modal.getByRole('button',{name:'保存当前查询为材料清单'}).click();await page.waitForFunction(()=>qaView.session.board.savedSearches?.length===1);await page.evaluate(()=>qaView.session.flush());
 const saved=JSON.parse(await readFile(path.join(vault,'Materials.thoughtspace'))).savedSearches;check('saved list contains only six conditions',Object.keys(saved[0].query).sort(),['color','full','group','kind','query','review']);check('saved criteria retain pending PDF state',saved[0].query.kind==='pdf'&&saved[0].query.review==='later');
 await modal.locator('[data-search-node="pdf-one"] select').selectOption('reading');await page.waitForTimeout(180);check('state update dynamically removes PDF from pending results',await modal.locator('.ts-board-search-row').count(),1);await screenshot('saved-pending-pdfs.png');
 await modal.getByRole('textbox',{name:'材料清单名称'}).fill('Reading queue');await modal.getByRole('button',{name:'重命名材料清单'}).click();await page.waitForTimeout(100);check('rename preserves query',await page.evaluate(()=>qaView.session.board.savedSearches[0].name),'Reading queue');
 await closeSearch();await page.locator('.workspace-leaf.mod-active .ts-stage').focus();await page.keyboard.press('Meta+z');await page.waitForTimeout(100);check('native undo restores saved name',await page.evaluate(()=>qaView.session.board.savedSearches[0].name),'Pending PDFs');await page.keyboard.press('Meta+Shift+z');await page.waitForTimeout(100);
 await page.evaluate(async()=>{await qaView.session.flush();await qaView.leaf.detach();});await open('Materials.thoughtspace');await page.locator('.workspace-leaf.mod-active').getByRole('button',{name:'搜索白板',exact:true}).click();await modal.waitFor();await modal.locator('.ts-board-search-saved summary').click();await modal.getByRole('combobox',{name:'已保存材料清单'}).selectOption(saved[0].id);await page.waitForTimeout(120);check('reopened saved query recalculates current results',await modal.locator('.ts-board-search-row').count(),1);check('PDF status persisted across reopen',await page.evaluate(()=>qaView.session.board.nodes.find(n=>n.id==='pdf-one').review),'reading');
 await closeSearch();await page.evaluate(()=>qaView.session.change(b=>b.nodes.push({id:'pdf-three',kind:'pdf',file:'QA-two.pdf',title:'New pending PDF',x:850,y:440,width:300,height:330,color:'sand',review:'later'})));await page.locator('.workspace-leaf.mod-active').getByRole('button',{name:'搜索白板',exact:true}).click();await modal.waitFor();await modal.locator('.ts-board-search-saved summary').click();await modal.getByRole('combobox',{name:'已保存材料清单'}).selectOption(saved[0].id);await page.waitForTimeout(150);check('saved query dynamically includes newly added matching material',await modal.locator('.ts-board-search-row').count(),2);await closeSearch();
 await page.locator('.workspace-leaf.mod-active').getByRole('button',{name:'工作区',exact:true}).click();await page.locator('.menu-item').filter({hasText:'打开阅读桌'}).click();const reading=page.locator('.ts-reading-desk');await reading.waitFor();await reading.locator('.ts-reading-filter-panel summary').click();await reading.getByRole('combobox',{name:'阅读内容类型',exact:true}).selectOption('pdf');await reading.locator('[data-node="pdf-one"]').click();await reading.locator('.pdf-embed').waitFor();await reading.locator('.pdf-embed .page').first().waitFor({timeout:12000});await page.waitForFunction(()=>document.querySelector('.ts-reading-desk .pdf-embed .textLayer')?.textContent.includes('Synthetic QA PDF'),{},{timeout:12000});check('native PDF page content loads',await reading.locator('.pdf-embed .textLayer').textContent().then(t=>t.includes('Synthetic QA PDF')));check('reading desk renders native PDF embed',await reading.locator('.pdf-embed').count(),1);await reading.getByRole('combobox',{name:'当前阅读状态',exact:true}).selectOption('done');await page.waitForTimeout(120);check('reading desk shares the PDF review state',await page.evaluate(()=>qaView.session.board.nodes.find(n=>n.id==='pdf-one').review),'done');await screenshot('reading-desk-native-pdf.png');await closeSearch();await page.locator('.workspace-leaf.mod-active').getByRole('button',{name:'搜索白板',exact:true}).click();await modal.waitFor();await modal.locator('.ts-board-search-saved summary').click();await modal.getByRole('combobox',{name:'已保存材料清单'}).selectOption(saved[0].id);await page.waitForTimeout(120);check('pending saved query recalculates after reading desk status change',await modal.locator('.ts-board-search-row').count(),2);
 await modal.getByRole('button',{name:'删除材料清单'}).click();await page.waitForTimeout(100);check('native delete removes saved conditions',await page.evaluate(()=>qaView.session.board.savedSearches.length),0);await closeSearch();await page.locator('.workspace-leaf.mod-active .ts-stage').focus();await page.keyboard.press('Meta+z');await page.waitForTimeout(100);check('native undo restores deleted list',await page.evaluate(()=>qaView.session.board.savedSearches.length),1);
 await open('Other.thoughtspace');await page.waitForTimeout(200);await page.locator('.workspace-leaf.mod-active').getByRole('button',{name:'搜索白板',exact:true}).click();await modal.waitFor();await modal.locator('.ts-board-search-saved summary').click();await modal.getByRole('combobox',{name:'已保存材料清单'}).locator('option').first().waitFor({state:'attached'});check('lists remain isolated to their own board',await modal.getByRole('combobox',{name:'已保存材料清单'}).locator('option[value]:not([value=""])').count(),0);await closeSearch();
 await page.evaluate(async()=>{await qaView.leaf.detach();});await open('Materials.thoughtspace');await page.locator('.workspace-leaf.mod-active').getByRole('button',{name:'搜索白板',exact:true}).click();await modal.waitFor();await modal.getByRole('button',{name:'清除关键词与筛选',exact:true}).click();await modal.getByRole('combobox',{name:'所属分组'}).selectOption('group');await modal.locator('.ts-board-search-saved summary').click();await modal.getByRole('textbox',{name:'材料清单名称'}).fill('Grouped materials');await modal.getByRole('button',{name:'保存当前查询为材料清单'}).click();await page.waitForTimeout(120);const grouped=await page.evaluate(()=>qaView.session.board.savedSearches.at(-1).id);await closeSearch();await page.evaluate(()=>qaView.session.change(b=>{b.nodes=b.nodes.filter(n=>n.id!=='group');}));await page.locator('.workspace-leaf.mod-active').getByRole('button',{name:'搜索白板',exact:true}).click();await modal.waitFor();await modal.locator('.ts-board-search-saved summary').click();await modal.getByRole('combobox',{name:'已保存材料清单'}).selectOption(grouped);await page.waitForTimeout(100);check('deleted group produces explicit empty dynamic results',await modal.locator('.ts-board-search-row').count(),0);await screenshot('saved-deleted-group-empty.png');
 await modal.getByRole('textbox',{name:'材料清单名称'}).fill('');await modal.getByRole('button',{name:'重命名材料清单'}).click();await page.waitForTimeout(100);check('invalid rename preserves input and shows recoverable inline error',await modal.locator('.ts-board-search-saved-status').textContent().then(t=>t.includes('失败')));await modal.getByRole('textbox',{name:'材料清单名称'}).fill('Recovered group');await modal.getByRole('button',{name:'重命名材料清单'}).click();await page.waitForTimeout(100);check('corrected rename succeeds after error',await page.evaluate(()=>qaView.session.board.savedSearches.at(-1).name),'Recovered group');
 await page.evaluate(()=>{window.qaOriginalFlush=qaView.session.flush;qaView.session.flush=async()=>{throw Error('Synthetic QA write rejection');};});await modal.getByRole('textbox',{name:'材料清单名称'}).fill('Retained draft');await modal.getByRole('button',{name:'重命名材料清单'}).click();await page.waitForTimeout(120);check('native write failure retains recoverable input and draft',(await modal.locator('.ts-board-search-saved-status').textContent()).includes('Synthetic QA write rejection')&&await modal.getByRole('textbox',{name:'材料清单名称'}).inputValue()==='Retained draft'&&await page.evaluate(()=>qaView.session.board.savedSearches.at(-1).name)==='Retained draft');await screenshot('saved-write-failure-recovery.png');await page.evaluate(()=>{qaView.session.flush=qaOriginalFlush;delete window.qaOriginalFlush;});await modal.getByRole('textbox',{name:'材料清单名称'}).fill('Restored after write');await modal.getByRole('button',{name:'重命名材料清单'}).click();await page.waitForTimeout(120);check('corrected write persists after recovery',JSON.parse(await readFile(path.join(vault,'Materials.thoughtspace'))).savedSearches.at(-1).name,'Restored after write');await closeSearch();
 // Parallel semantic identities and deeper paths, sampled from actual native SVG.
 const semantic=brain(['0','1','2'].map(id=>node(id,'card',{file:'Research.md',title:`Node ${id}`})));semantic.edges=[{id:'parent-child',from:'0',to:'1',kind:'branch',label:'hierarchy'},{id:'association',from:'0',to:'1',direction:'both',label:'reference'},{id:'grandchild',from:'1',to:'2',kind:'branch',label:''}];semantic.brain.descendantDepth=3;await writeFile(path.join(vault,'Semantic.thoughtspace'),JSON.stringify(semantic));await open('Semantic.thoughtspace');await page.waitForTimeout(120);
 const links=await page.locator('.workspace-leaf.mod-active [data-brain-from="0"][data-brain-to="1"]').evaluateAll(paths=>paths.map(p=>({ids:JSON.parse(p.dataset.brainEdgeIds),role:p.dataset.brainRole,direction:p.dataset.brainDirection,dashed:p.classList.contains('is-associated'),d:p.getAttribute('d')})));check('native SVG preserves both relationship identities',links.flatMap(l=>l.ids).sort(),['association','parent-child']);check('semantic paths are independently visible',links.length===2&&links[0].d!==links[1].d);await page.waitForTimeout(3500);await screenshot('brain-parallel-relationships.png');
 await page.evaluate(()=>qaView.session.change(b=>b.edges.reverse()));const reversed=await page.locator('.workspace-leaf.mod-active [data-brain-from="0"][data-brain-to="1"]').evaluateAll(paths=>paths.flatMap(p=>JSON.parse(p.dataset.brainEdgeIds)).sort());check('edge input order cannot drop native relationships',reversed,['association','parent-child']);
 const deep=brain(Array.from({length:100},(_,i)=>node(String(i),'card',{file:'Research.md',title:`Node ${i}`})));deep.edges=Array.from({length:99},(_,i)=>({id:`e${i+1}`,from:String(Math.floor(i/4)),to:String(i+1),kind:'branch',label:''}));deep.brain.descendantDepth=3;await writeFile(path.join(vault,'Deep.thoughtspace'),JSON.stringify(deep));await open('Deep.thoughtspace');await page.waitForTimeout(150);const expandCenter=async()=>{await page.locator('.workspace-leaf.mod-active [data-brain-node-id="0"] .ts-brain-node-title').hover();await page.locator('.workspace-leaf.mod-active [data-brain-node-id="0"] [data-brain-action="expand"]').click();};
 const crossing=()=>page.evaluate(()=>{const brain=qaView.brainBoardView,layout=brain.layout,rects=layout.nodes.flatMap(n=>[{id:n.id,left:n.x,right:n.x+n.width,top:n.y,bottom:n.y+n.height},...(n.previewWidth?[{id:n.id,left:n.x+n.width/2-n.previewWidth/2,right:n.x+n.width/2+n.previewWidth/2,top:n.y+n.height+12,bottom:n.y+n.height+212}]:[])]),collisions=[];for(const p of document.querySelectorAll('.workspace-leaf.mod-active .ts-brain-links path[data-brain-from]')){const length=p.getTotalLength();for(let d=0;d<=length;d+=4){const q=p.getPointAtLength(d);const hit=rects.find(r=>r.id!==p.dataset.brainFrom&&r.id!==p.dataset.brainTo&&q.x>r.left+1&&q.x<r.right-1&&q.y>r.top+1&&q.y<r.bottom-1);if(hit){collisions.push({from:p.dataset.brainFrom,to:p.dataset.brainTo,node:hit.id});break;}}}return{nodes:layout.nodes.length,paths:layout.links.length,collisions};});
 for(const depth of [3,4,5]){if(depth!==3){await page.locator('.workspace-leaf.mod-active [data-brain-action="depth"]').click();await page.locator('.menu-item').filter({hasText:`显示 ${depth} 层`}).click();}const result=await crossing();report.routing??=[];report.routing.push({depth,...result});check(`native depth ${depth}: paths avoid unrelated pills`,result.collisions,[]);check(`native depth ${depth}: bounded projection`,result.nodes<=48);await screenshot(`brain-depth-${depth}.png`);}
 await page.locator('.workspace-leaf.mod-active [data-brain-action="next-branches"]').click();const next=await crossing();check('native next relationship page remains obstacle free',next.collisions,[]);await page.locator('.workspace-leaf.mod-active [data-brain-action="previous-branches"]').click();
 await expandCenter();await page.waitForFunction(()=>!!document.querySelector('.workspace-leaf.mod-active [data-brain-node-id="0"] .ts-brain-preview h1'));const expanded=await crossing();check('native expanded reading frame also remains obstacle free',expanded.collisions,[]);await screenshot('brain-depth-expanded.png');
 const preview=await page.locator('.workspace-leaf.mod-active [data-brain-node-id="0"] .ts-brain-preview').evaluate(e=>{window.qaPreview=e;return e.textContent;});await page.evaluate(()=>qaView.brainBoardView.refresh());check('unchanged refresh retains native reading DOM',await page.locator('.workspace-leaf.mod-active [data-brain-node-id="0"] .ts-brain-preview').evaluate(e=>e===qaPreview));
 // Mutating a native reference produces a new semantic projection and body.
 await page.evaluate(async()=>{await app.vault.create('Native-second.md','# Second\n\nTarget');qaView.session.change(b=>b.nodes.push({id:'native-new',kind:'card',file:'Native-second.md',title:'Second',x:0,y:0,width:300,height:200,color:'sand'}));await app.vault.modify(app.vault.getAbstractFileByPath('Research.md'),'# Research\n\n[[Native-second]]\n\nChanged native source');});await page.waitForTimeout(600);
 check('native source edit invalidates rendered reading body',await page.locator('.workspace-leaf.mod-active [data-brain-node-id="0"] .ts-brain-preview').textContent().then(t=>t.includes('Changed native source')));
 await page.locator('.workspace-leaf.mod-active [data-brain-node-id="1"] .ts-brain-node-title').click();const moving=await page.evaluate(()=>qaView.brainBoardView.motion.active);check('center switch retains the motion lifecycle',moving);await page.waitForTimeout(350);await page.locator('.workspace-leaf.mod-active [data-brain-action="back"]').click();await page.waitForTimeout(350);check('native history returns to original center',await page.evaluate(()=>qaView.session.board.brain.centerId),'0');
 await expandCenter();for(let i=0;i<6;i++)await expandCenter();check('rapid fold/unfold retains latest input',await page.evaluate(()=>!qaView.session.board.brain.expandedIds.includes('0')));await page.locator('.workspace-leaf.mod-active .ts-brain-shell').focus();await page.keyboard.press('Meta+z');await page.waitForTimeout(120);check('native undo restores expanded reading body',await page.evaluate(()=>qaView.session.board.brain.expandedIds.includes('0')));await page.keyboard.press('Meta+Shift+z');await page.waitForTimeout(120);check('native redo restores folded body',await page.evaluate(()=>!qaView.session.board.brain.expandedIds.includes('0')));
 check('projection and search do not delete original semantic graph',await page.evaluate(()=>{const view=app.workspace.getLeavesOfType('thoughtspace-board').find(l=>l.view.file?.path==='Semantic.thoughtspace')?.view;return view?.session.board.edges.map(e=>e.id).sort();}),['association','grandchild','parent-child']);
}
