import {boardExtras} from './extras.mjs';
import {writeFile,readFile,copyFile} from 'node:fs/promises';
import path from 'node:path';
const card=(id,kind,extra={})=>({id,kind,x:0,y:0,width:300,height:220,color:'sand',...extra});
export async function run({page,browser,out,vault,report,check,screenshot,open}){
 const fixtureDir=path.resolve('../qa/fixtures');for(const ext of ['png','mp4','wav'])await copyFile(path.join(fixtureDir,`fixture.${ext}`),path.join(vault,`fixture.${ext}`));
 await page.evaluate(async()=>{await app.vault.create('阅读材料.md','# 阅读材料\n\n这是一段合成的研究资料，用于查看中文正文、[原生链接](https://example.org)与任务框。\n\n- [ ] 保留正文主题与来源\n\n## 第二节\n\n'+('可读的材料内容与清晰的操作层次。\n\n').repeat(12));await app.vault.create('长标题.md','# 长标题材料\n\n另一份合成材料。\n');});
 // A simple valid empty-page PDF; feature-stage QA already checks actual text-layer PDF loading.
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 320 180] /Resources << >> /Contents 4 0 R >>','<< /Length 0 >>\nstream\n\nendstream'];let pdf='%PDF-1.4\n',offsets=[];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const x=pdf.length;pdf+='xref\n0 5\n0000000000 65535 f \n'+offsets.map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF\n`;await writeFile(path.join(vault,'fixture.pdf'),pdf);
 const board={version:3,nodes:[card('note','card',{file:'阅读材料.md',title:'阅读材料',x:80,y:90,autoFit:false,cardStyle:'index'}),card('long','card',{file:'长标题.md',title:'中文长标题：追踪阅读、材料来源与下一步验证的完整问题',x:480,y:90,autoFit:false,cardStyle:'band',fillColor:'#c6a363',locked:true}),card('text','text',{text:'## 一份合成的工作清单\n\n- [ ] 核对材料\n- [x] 保留来源\n\n清楚的状态，比额外装饰更有用。',x:80,y:390,autoSize:false,textAutoHeight:false}),card('pdf','pdf',{file:'fixture.pdf',title:'待读 PDF 材料',x:480,y:390}),card('group','section',{title:'研究材料 · 很长的中文分组名称用于观察窄窗边界',x:40,y:40,width:820,height:630,color:'blue'}),card('video','video',{file:'fixture.mp4',title:'合成视频',x:940,y:90}),card('audio','audio',{file:'fixture.wav',title:'合成音频',x:940,y:390}),card('image','image',{file:'fixture.png',title:'合成图片',x:940,y:700})],edges:[{id:'e',from:'note',to:'text',label:'下一步'}],viewport:{x:20,y:20,zoom:1},savedViews:[{id:'wide',name:'阅读材料总览 · 保留来源与中文长名称的完整可达性',viewport:{x:20,y:20,zoom:1}}],savedSearches:[{id:'pending',name:'待读PDF：下一次重开继续动态材料清单',query:{query:'',kind:'pdf',group:'',color:'',review:'later',full:false}}]};
 await writeFile(path.join(vault,'UI.thoughtspace'),JSON.stringify(board));await writeFile(path.join(vault,'Empty.thoughtspace'),JSON.stringify({...board,nodes:[],edges:[],savedViews:[],savedSearches:[]}));await open('UI.thoughtspace');await page.evaluate(()=>{window.qaBoard=qaView;window.qaFixtureGeometry=qaView.session.board.nodes.map(n=>[n.id,n.x,n.y,n.width,n.height,n.fillColor]);});
 await page.waitForFunction(()=>['pdf','image'].every(id=>qaBoard.session.board.nodes.find(n=>n.id===id).height===168.75)&&qaBoard.pendingFits.size===0&&qaBoard.contentEl.querySelector('.ts-pdf-preview[aria-busy=true]')===null);
 await page.evaluate(async()=>{await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));window.qaInitialGeometry=qaBoard.session.board.nodes.map(n=>[n.id,n.x,n.y,n.width,n.height,n.fillColor]);});
 report.geometry={fixture:await page.evaluate(()=>qaFixtureGeometry),settled:await page.evaluate(()=>qaInitialGeometry)};
 const active=()=>page.locator('.workspace-leaf.mod-active');
 const setTheme=async(theme)=>{await page.evaluate(theme=>{document.body.classList.toggle('theme-dark',theme==='dark');document.body.classList.toggle('theme-light',theme==='light');document.body.style.setProperty('--interactive-accent','#8d43c2');qaBoard.plugin.settings.accent='forest';qaBoard.applyPreferences();},theme);await page.waitForTimeout(240);};
 const front=async()=>{await page.bringToFront();await page.evaluate(()=>{require('@electron/remote').getCurrentWindow().focus();app.workspace.setActiveLeaf(qaBoard.leaf,{focus:true});window.qaView=qaBoard;});};
 const size=async(width=1440,height=1040)=>{await page.evaluate(({width,height})=>require('@electron/remote').getCurrentWindow().setBounds({x:40,y:40,width,height}),{width,height});await page.waitForTimeout(220);};
 const close=async(selector)=>{await page.keyboard.press('Escape');await page.locator(selector).waitFor({state:'hidden',timeout:6000});await page.waitForTimeout(140);};
 const select=async ids=>{await front();await page.evaluate(ids=>{qaBoard.selected=new Set(ids);qaBoard.updateSelection();qaBoard.renderSelectionTools();},ids);await page.waitForTimeout(150);};
 const workspace=async(label,selector)=>{await front();await active().getByRole('button',{name:'工作区',exact:true}).click();await page.locator('.menu-item').filter({hasText:new RegExp('^'+label+'$')}).click();await page.locator(selector).waitFor();await page.waitForTimeout(200);};
 const record=async(name,selector)=>{await screenshot(name);report.surfaces??=[];report.surfaces.push({name,selector,theme:await page.evaluate(()=>document.body.classList.contains('theme-dark')?'dark':'light'),viewport:await page.evaluate(()=>({width:innerWidth,height:innerHeight})),bounds:await page.locator(selector).first().evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth};})});};
 if(process.env.QA_SURFACE_PART!=='media')for(const theme of ['light','dark']){
  await size();await front();await setTheme(theme);await select(['note']);await active().locator('.ts-format-mode-button[data-mode="card"]').click();await page.waitForTimeout(240);
  const style=active().locator('.ts-card-style-option[aria-pressed="true"]');report.picker??=[];report.picker.push({theme,...await style.evaluate(e=>{const s=getComputedStyle(e);return{color:s.color,border:s.borderColor,background:s.backgroundColor,accent:getComputedStyle(e.closest('.ts-root')).getPropertyValue('--ts-accent').trim(),text:e.textContent};})});await record(`board-${theme}-picker.png`,'.ts-floating-formatbar');
  await active().locator('.ts-format-mode-button[data-mode="card"]').click();await select([]);await record(`board-${theme}-overview.png`,'.ts-stage');
  for(const [label,selector,name]of [['整理白板','.ts-layout-planner','layout'],['移入已有分组','.ts-group-organizer','group'],['分组预览','.ts-section-catalog','catalog'],['打开阅读桌','.ts-reading-desk','reading'],['打开知识空间','.ts-space-hub','space']]){
   await select(label==='移入已有分组'?['note']:[]);await workspace(label,selector);await record(`${name}-${theme}-wide.png`,selector);
   if(['layout','reading','space'].includes(name)){await size(640,760);await record(`${name}-${theme}-narrow.png`,selector);await size();}
   await close(selector);
  }
  await front();await active().getByRole('button',{name:'常用视角',exact:true}).click();await page.locator('.ts-saved-views').waitFor();await record(`views-${theme}-wide.png`,'.ts-saved-views');await size(640,760);await record(`views-${theme}-narrow.png`,'.ts-saved-views');await close('.ts-saved-views');await size();
  await active().getByRole('button',{name:/白板背景：/}).click();await page.locator('.menu-item').filter({hasText:'自定义纸张…'}).click();await page.locator('.ts-paper-settings').waitFor();await record(`paper-${theme}-wide.png`,'.ts-paper-settings');await size(640,760);await record(`paper-${theme}-narrow.png`,'.ts-paper-settings');await close('.ts-paper-settings');await size();
  await active().getByRole('button',{name:/白板背景：/}).click();await page.locator('.menu-item').filter({hasText:'设置背景图片…'}).click();await page.locator('.ts-background-settings').waitFor();await record(`background-${theme}-empty.png`,'.ts-background-settings');await close('.ts-background-settings');
  await active().getByRole('button',{name:'搜索白板',exact:true}).click();const search=page.locator('.ts-board-search');await search.waitFor();await search.locator('.ts-board-search-saved summary').click();await search.getByRole('combobox',{name:'已保存材料清单'}).selectOption('pending');await page.waitForTimeout(180);await record(`search-${theme}-wide.png`,'.ts-board-search');await size(640,760);await record(`search-${theme}-narrow.png`,'.ts-board-search');await search.getByRole('searchbox',{name:'搜索白板内容'}).fill('无匹配的合成关键词');await page.waitForTimeout(180);await record(`search-${theme}-empty.png`,'.ts-board-search');await close('.ts-board-search');await size();
  await boardExtras({page,theme,active,front,size,select,workspace,close,record,report,check});
  // Eight preference pages in their actual native settings window.
  await page.evaluate(()=>{app.setting.open();app.setting.openTabById('thoughtspace');});await page.waitForTimeout(250);let settings;for(const p of browser.contexts()[0].pages())if(await p.locator('.ts-settings-v2').count())settings=p;if(!settings)throw Error('Native settings window missing');
  await settings.evaluate(theme=>{document.body.classList.toggle('theme-dark',theme==='dark');document.body.classList.toggle('theme-light',theme==='light');},theme);
  for(const id of ['general','cards','board','input','reading','filing','images','profiles']){await settings.locator(`[data-settings-page="${id}"]`).click();await settings.waitForTimeout(100);const name=`settings-${theme}-${id}.png`;await settings.screenshot({path:path.join(out,name)});report.screenshots.push(name);}
  await settings.getByRole('searchbox',{name:'搜索全部设置'}).fill('找不到任何设置的合成词');await settings.keyboard.press('Tab');await settings.keyboard.press('Shift+Tab');await settings.waitForTimeout(200);const name=`settings-${theme}-empty-focus.png`;await settings.screenshot({path:path.join(out,name)});report.screenshots.push(name);report.settingsFocus??=[];report.settingsFocus.push({theme,...await settings.locator('.ts-settings-search input').evaluate(e=>({inputOutline:getComputedStyle(e).outlineStyle,wrapperBorder:getComputedStyle(e.parentElement).borderColor,focused:e===document.activeElement}))});await settings.keyboard.press('Escape');await settings.locator('[data-settings-page=cards]').click();await settings.evaluate(()=>require('@electron/remote').getCurrentWindow().setBounds({width:420,height:520}));await settings.waitForTimeout(180);const toggles=settings.locator('.ts-settings-panel:not([hidden]) .checkbox-container');await toggles.last().focus();await settings.keyboard.press('Tab');const short=`settings-${theme}-short-focus.png`;await settings.screenshot({path:path.join(out,short)});report.screenshots.push(short);report.settingsShort??=[];report.settingsShort.push(await settings.evaluate(()=>({width:innerWidth,height:innerHeight,focused:document.activeElement?.getAttribute('aria-label'),rootWidth:document.querySelector('.ts-settings-v2')?.clientWidth})));await settings.locator('.ts-settings-panel:not([hidden])').getByRole('button',{name:'恢复本分类默认值',exact:true}).click();await settings.getByRole('button',{name:'取消',exact:true}).click();await page.evaluate(()=>app.setting.close());await front();
 }
 // Writing workbench and native CodeMirror. Fixture state is initialized through the registered view API.
 if(process.env.QA_SURFACE_PART!=='media'){await size();await setTheme('light');await select([]);await workspace('白板写作模式','.ts-writing');await page.waitForTimeout(300);await record('writing-light-editor.png','.ts-writing');await page.locator('.ts-writing [data-article-mode="outline"]').click();await record('writing-light-outline.png','.ts-writing');await page.locator('.ts-writing [data-article-mode="preview"]').click();await record('writing-light-preview.png','.ts-writing');await size(640,760);await record('writing-light-narrow.png','.ts-writing');await size();await page.evaluate(()=>{document.body.classList.remove('theme-light');document.body.classList.add('theme-dark');});await page.waitForTimeout(240);await record('writing-dark-preview.png','.ts-writing');await page.locator('.ts-writing [data-article-mode="write"]').click();await record('writing-dark-editor.png','.ts-writing');await page.locator('.ts-writing-material[data-writing-node=note] .ts-writing-name').click();await page.waitForTimeout(240);await record('writing-dark-reference.png','.ts-writing');await page.getByRole('button',{name:'返回白板',exact:true}).click();await front();}
 // Local and online workspaces use fresh registered leaves, confined to synthetic files.
 for(const kind of ['empty','video','audio']){
  await page.evaluate(async kind=>{const leaf=app.workspace.getLeaf('tab');await leaf.setViewState({type:'thoughtspace-media-player',active:true,state:{...(kind==='empty'?{}:{file:kind==='video'?'fixture.mp4':'fixture.wav'}),placement:'tab'}});await leaf.loadIfDeferred();window.qaMedia=leaf.view;},kind);await page.locator('.workspace-leaf.mod-active .ts-media-workspace').waitFor();await page.waitForTimeout(400);
  for(const theme of ['light','dark']){await size();await page.evaluate(theme=>{document.body.classList.toggle('theme-dark',theme==='dark');document.body.classList.toggle('theme-light',theme==='light');},theme);await page.waitForTimeout(240);await record(`media-${kind}-${theme}-wide.png`,'.workspace-leaf.mod-active .ts-media-workspace');if(kind!=='empty'){await size(640,760);await record(`media-${kind}-${theme}-narrow.png`,'.workspace-leaf.mod-active .ts-media-workspace');await size();}}
  if(kind==='video'){await page.locator('.ts-media-workspace__layout-options > summary').click();await record('media-video-layout-controls.png','.ts-media-workspace__layout-options');await page.keyboard.press('Escape');await page.getByRole('button',{name:'更多媒体操作',exact:true}).click();await page.waitForTimeout(200);report.mediaMenu=await page.evaluate(()=>({status:qaMedia.status?.textContent,menu:document.querySelector('.menu')?.textContent,ownMenu:Object.keys(qaMedia.contextMenu||{}),parentAPI:typeof qaMedia.contextMenu?.setParentElement}));await record('media-more-menu.png','.ts-media-workspace');if(report.mediaMenu.menu){await page.locator('.menu-item-title').filter({hasText:/^收起画面$/}).click();await record('media-video-compact.png','.ts-media-workspace');await page.getByRole('button',{name:'更多媒体操作',exact:true}).click();await page.locator('.menu-item-title').filter({hasText:/^展开画面$/}).click();}else{report.boundaries??=[];report.boundaries.push('Frozen baseline uses macOS native media menu; page capture cannot inspect system-menu items. Compact state is verified only after the menu is unified.');await page.evaluate(()=>qaMedia.contextMenu?.hide());}}
  if(kind==='video'){await active().locator('.ts-media-card__play').click();await page.waitForFunction(()=>document.querySelector('.workspace-leaf.mod-active video')?.readyState>=2);await active().getByRole('textbox',{name:'摘录 Markdown 正文'}).fill('合成媒体摘录：保留时间点、正文与可达操作。');await active().getByRole('button',{name:'保存摘录',exact:true}).click();await active().locator('.ts-media-workspace__moment').first().waitFor();await record('media-video-saved-timeline.png','.ts-media-workspace');await check('media native save renders a timeline entry',await active().locator('.ts-media-workspace__moment').count(),1);}
  await page.evaluate(async()=>qaMedia.leaf.detach());
 }
 await page.evaluate(async()=>{const leaf=app.workspace.getLeaf('tab');await leaf.setViewState({type:'thoughtspace-online-player',active:true,state:{placement:'tab'}});await leaf.loadIfDeferred();window.qaOnline=leaf.view;});await page.waitForTimeout(300);await record('online-empty-dark.png','.workspace-leaf.mod-active .ts-online-workspace');await size(640,760);await record('online-empty-narrow.png','.workspace-leaf.mod-active .ts-online-workspace');await page.evaluate(async()=>qaOnline.leaf.detach());
 await size();await front();await check('UI audit preserves source Markdown',await page.evaluate(async()=>await app.vault.read(app.vault.getAbstractFileByPath('长标题.md'))),'# 长标题材料\n\n另一份合成材料。\n');report.geometry.final=await page.evaluate(()=>qaBoard.session.board.nodes.map(n=>[n.id,n.x,n.y,n.width,n.height,n.fillColor]));await check('UI audit preserves node geometry',await page.evaluate(()=>JSON.stringify(qaBoard.session.board.nodes.map(n=>[n.id,n.x,n.y,n.width,n.height,n.fillColor]))===JSON.stringify(qaInitialGeometry)));await check('UI audit preserves locked custom card color',await page.evaluate(()=>qaBoard.session.board.nodes.find(n=>n.id==='long').fillColor),'#c6a363');await check('UI audit preserves source graph edge',await page.evaluate(()=>qaBoard.session.board.edges[0].id),'e');
}
