import {readFile,writeFile,mkdir,copyFile,mkdtemp,readdir,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';

const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const builtRoot=path.resolve(process.env.QA_PLUGIN_ROOT||root);
const out=path.resolve(process.env.QA_OUTPUT||path.join(root,'dist/card-editor-polish'));
const temporary=await mkdtemp(path.join(tmpdir(),'thoughtspace-card-editor-'));
const profile=path.join(temporary,'profile'),vault=path.join(temporary,'vault'),plugin=path.join(vault,'.obsidian/plugins/thoughtspace');
await mkdir(plugin,{recursive:true});await mkdir(profile);await mkdir(out,{recursive:true});
const profileSource=path.join(process.env.HOME,'Library/Application Support/obsidian');
const packages=(await readdir(profileSource)).filter(file=>/^obsidian-\d+\.\d+\.\d+\.asar$/.test(file)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
assert.ok(packages.length,'An installed Obsidian runtime is required');
await copyFile(path.join(profileSource,packages.at(-1)),path.join(profile,packages.at(-1)));
await writeFile(path.join(profile,'obsidian.json'),JSON.stringify({vaults:{ca4ded1700000001:{path:vault,ts:Date.now(),open:true}}}));
await writeFile(path.join(vault,'.obsidian/community-plugins.json'),'["thoughtspace"]');
await writeFile(path.join(vault,'.obsidian/app.json'),JSON.stringify({alwaysUpdateLinks:true,showUnsupportedFiles:true}));
for(const file of ['main.js','styles.css','manifest.json'])await copyFile(path.join(builtRoot,file),path.join(plugin,file));
await writeFile(path.join(plugin,'data.json'),JSON.stringify({onboardingVersion:99}));
const original='First sentence';
await writeFile(path.join(vault,'note.md'),original);
await writeFile(path.join(vault,'second.md'),'Second note');
await writeFile(path.join(vault,'Editor.thoughtspace'),JSON.stringify({version:3,nodes:[{id:'note',kind:'card',file:'note.md',x:100,y:150,width:380,height:300,color:'blue',autoFit:false,cardStyle:'index'},{id:'second',kind:'card',file:'second.md',x:600,y:150,width:380,height:300,color:'rose',autoFit:false,cardStyle:'sticky'}],edges:[],viewport:{x:0,y:0,zoom:1}}));
const report={scope:'Isolated native Obsidian; real keyboard/mouse input and production formatting/undo/save handlers. IME composition events and storage failure are synthetic boundary probes, not physical IME validation.',temporary,runtime:packages.at(-1),checks:[],errors:[]};
report.build=Object.fromEntries(await Promise.all(['main.js','styles.css','manifest.json'].map(async file=>[file,createHash('sha256').update(await readFile(path.join(plugin,file))).digest('hex')])));
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const check=(name,actual,expected)=>{report.checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});assert.deepEqual(actual,expected,name);console.log(`PASS ${name}`);};
let application,browser,page;
try{
 application=spawn('/Applications/Obsidian.app/Contents/MacOS/Obsidian',[`--user-data-dir=${profile}`,'--remote-debugging-port=0'],{stdio:'ignore'});
 let port;for(let i=0;i<100&&!port;i++){try{port=(await readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];}catch{await sleep(200);}}
 assert.ok(port,'Isolated CDP endpoint failed to start');
 browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`);page=browser.contexts()[0].pages()[0];
 check('isolated profile',await realpath(await page.evaluate(()=>require('@electron/remote').app.getPath('userData'))),await realpath(profile));
 page.on('pageerror',error=>report.errors.push(error.message));
 await page.waitForFunction(()=>window.app?.workspace?.layoutReady,{},{timeout:40000});
 const trust=page.getByRole('button',{name:/信任仓库作者并启用插件|Trust author and enable plugins/});if(await trust.count())await trust.click();
 await page.waitForFunction(()=>!!app.plugins.plugins.thoughtspace,{},{timeout:20000});
 await page.waitForTimeout(1000);
 await page.evaluate(()=>app.setting.close());await page.bringToFront();
 for(const other of browser.contexts()[0].pages())if(other!==page)await other.close();
 await page.evaluate(()=>{const remote=require('@electron/remote');remote.app.focus({steal:true});remote.getCurrentWindow().focus();});await page.waitForTimeout(100);
 await page.evaluate(async()=>{const leaf=app.workspace.getLeaf(false);await leaf.setViewState({type:'thoughtspace-board',state:{file:'Editor.thoughtspace'},active:true});window.qaView=leaf.view;app.workspace.leftSplit.collapse();app.workspace.rightSplit.collapse();require('@electron/remote').getCurrentWindow().setBounds({x:40,y:40,width:1200,height:900});});
 await page.waitForFunction(()=>window.qaView?.session?.board?.nodes?.length===2);
 await page.locator('.ts-node[data-id="note"] .ts-node-header').click();
 await page.waitForFunction(()=>activeWindow===window,{},{timeout:5000});
 check('native active window owns the board',await page.evaluate(()=>activeWindow===window),true);
 await page.evaluate(()=>qaView.startInlineEdit('note'));
 await page.locator('.ts-inline-native .cm-content').focus();
 await page.keyboard.insertText(' first keyboard save');await page.keyboard.press('Meta+Enter');
 await page.waitForFunction(()=>!qaView.inline,{},{timeout:3000});
 check('first keyboard save persists draft',await readFile(path.join(vault,'note.md'),'utf8'),original+' first keyboard save');
 await page.evaluate(async value=>{await app.vault.modify(app.vault.getAbstractFileByPath('note.md'),value);await qaView.startInlineEdit('note');},original);
 await page.locator('.ts-inline-native .cm-content').focus();
 await page.keyboard.type(' [[sec');await page.locator('.suggestion-container:visible').waitFor();
 await page.screenshot({path:path.join(out,'native-wikilink-suggestion.png')});
 check('native Wiki suggestion opens',await page.locator('.suggestion-container:visible').count()>0,true);
 const draft=await page.evaluate(()=>qaView.inline.value);await page.keyboard.press('Escape');
 check('suggestion Escape keeps draft active',await page.evaluate(()=>!!qaView.inline),true);
 check('suggestion Escape preserves draft text',await page.evaluate(()=>qaView.inline.value),draft);
 check('suggestion Escape closes suggestion',await page.locator('.suggestion-container:visible').count(),0);
 await page.keyboard.press('Escape');check('second Escape cancels draft',await page.evaluate(()=>!!qaView.inline),false);
 check('suggestion cancellation preserves original note',await readFile(path.join(vault,'note.md'),'utf8'),original);
 await page.evaluate(()=>qaView.startInlineEdit('note'));await page.locator('.ts-inline-native .cm-content').focus();
 await page.keyboard.insertText(' plus new words');
 const typed=original+' plus new words';
 check('real keyboard input reaches draft',await page.evaluate(()=>qaView.inline.value),typed);
 await page.evaluate(()=>{const e=qaView.inline;e.input.setSelectionRange(e.value.length-5,e.value.length);});await page.keyboard.press('Meta+b');
 check('format affects selected words',await page.evaluate(()=>qaView.inline.value),original+' plus new **words**');
 await page.keyboard.press('Meta+z');
 check('undo formatting preserves preceding typing',await page.evaluate(()=>qaView.inline.value),typed);
 await page.keyboard.press('Meta+Shift+z');
 check('redo formatting restores only formatting',await page.evaluate(()=>qaView.inline.value),original+' plus new **words**');
 await page.evaluate(()=>{const e=qaView.inline,start=e.value.indexOf('words');e.input.setSelectionRange(start,start+5);});await page.keyboard.press('Meta+i');
 check('native italic shortcut remains available',await page.evaluate(()=>qaView.inline.value),original+' plus new ***words***');
 await page.keyboard.press('Meta+z');check('native undo reverts only italic formatting',await page.evaluate(()=>qaView.inline.value),original+' plus new **words**');
 await page.evaluate(()=>qaView.inline.findText());
 let dialogPage;
 for(let i=0;i<50&&!dialogPage;i++){for(const candidate of browser.contexts()[0].pages())if(await candidate.locator('.ts-editor-search').isVisible()){dialogPage=candidate;break;}if(!dialogPage)await sleep(100);}
 assert.ok(dialogPage,'Native search dialog should be visible in its owning window');
 await dialogPage.screenshot({path:path.join(out,'native-search-modal.png')});
 await dialogPage.keyboard.press('Escape');await page.waitForFunction(()=>!qaView.inline?.searchDialog?.modalEl.isConnected);
 check('search modal Escape preserves the underlying draft',await page.evaluate(()=>qaView.inline.value),original+' plus new **words**');
 check('search modal returns focus to native draft',await page.evaluate(()=>!!document.activeElement?.closest('.ts-inline-native')),true);
 await page.evaluate(()=>qaView.inline.cancel());
 check('cancel preserves original note',await readFile(path.join(vault,'note.md'),'utf8'),original);
 check('cancel removes inline editor',await page.locator('.ts-inline-native').count(),0);
 await page.evaluate(()=>qaView.startInlineEdit('note'));
 await page.locator('.ts-inline-native .cm-content').focus();await page.keyboard.insertText(' saved change');
 check('save shortcut window owns the board',await page.evaluate(()=>activeWindow===window),true);
 check('save shortcut focus remains inside the draft',await page.evaluate(()=>!!document.activeElement?.closest('.ts-inline-native')),true);
 await page.keyboard.press('Control+Enter');await page.waitForFunction(()=>!qaView.inline);
 check('keyboard save writes exact content',await readFile(path.join(vault,'note.md'),'utf8'),original+' saved change');
 await page.evaluate(()=>qaView.startInlineEdit('note'));await page.locator('.ts-inline-native .cm-content').focus();await page.keyboard.insertText(' cancelled');
 await page.keyboard.press('Escape');
 check('Escape closes the active native draft',await page.evaluate(()=>!!qaView.inline),false);
 check('Escape discards only new draft',await readFile(path.join(vault,'note.md'),'utf8'),original+' saved change');

 await page.evaluate(()=>qaView.startInlineEdit('note'));await page.locator('.ts-inline-native .cm-content').focus();await page.keyboard.insertText(' retry draft');
 await page.evaluate(()=>{window.qaProcess=app.vault.process;app.vault.process=async()=>{throw Error('QA_DISK_WRITE_FAILURE');};});
 await page.keyboard.press('Meta+Enter');await page.waitForFunction(()=>qaView.inline&&!qaView.inline.saving&&qaView.inline.el.classList.contains('has-error'));
 check('failed save keeps exact draft',await page.evaluate(()=>qaView.inline.value),original+' saved change retry draft');
 check('failed save unlocks editing',await page.evaluate(()=>qaView.inline.input.readOnly),false);
 check('failed save does not alter disk',await readFile(path.join(vault,'note.md'),'utf8'),original+' saved change');
 check('failed save exposes retry caption',await page.locator('.ts-inline-save-caption').textContent(),'重试');
 await page.locator('.ts-inline-native .cm-content').focus();await page.keyboard.insertText(' continued');
 check('failed draft remains editable',await page.evaluate(()=>qaView.inline.value),original+' saved change retry draft continued');
 await page.evaluate(()=>{app.vault.process=window.qaProcess;delete window.qaProcess;});
 await page.keyboard.press('Meta+Enter');await page.waitForFunction(()=>!qaView.inline);
 let current=original+' saved change retry draft continued';
 check('retry saves latest draft without duplicate content',await readFile(path.join(vault,'note.md'),'utf8'),current);

 await page.evaluate(()=>qaView.startInlineEdit('note'));await page.locator('.ts-inline-native .cm-content').focus();await page.keyboard.insertText(' blur saved');
 const blank=await page.evaluate(()=>{const r=qaView.stage.getBoundingClientRect();return{x:r.left+20,y:r.bottom-30};});
 await page.mouse.click(blank.x,blank.y);await page.waitForFunction(()=>!qaView.inline);
 current+=' blur saved';check('blank canvas click saves current draft',await readFile(path.join(vault,'note.md'),'utf8'),current);

 await page.evaluate(()=>qaView.startInlineEdit('note'));await page.locator('.ts-inline-native .cm-content').focus();await page.keyboard.insertText(' switched');
 await page.evaluate(async()=>{await Promise.all([qaView.startInlineEdit('second'),qaView.startInlineEdit('note'),qaView.startInlineEdit('second')]);});
 check('rapid switching selects last requested card',await page.evaluate(()=>qaView.inlineId),'second');
 check('rapid switching leaves one native draft',await page.locator('.ts-inline-native').count(),1);
 check('rapid switching preserves source note content',await readFile(path.join(vault,'note.md'),'utf8'),current+' switched');
 current+=' switched';check('target draft uses target note',await page.evaluate(()=>qaView.inline.value),'Second note');
 await page.evaluate(()=>qaView.inline.cancel());

 await page.evaluate(()=>qaView.startInlineEdit('note'));await page.locator('.ts-inline-native .cm-content').focus();
 await page.evaluate(()=>qaView.inline.input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''})));
 await page.keyboard.insertText(' 中文输入');await page.keyboard.press('Meta+Enter');await page.keyboard.press('Escape');
 check('composition blocks premature save and cancel',await page.evaluate(()=>!!qaView.inline&&qaView.inline.snapshot().busy),true);
 check('composition does not write draft early',await readFile(path.join(vault,'note.md'),'utf8'),current);
 check('composition disables save button',await page.locator('.ts-inline-save').isDisabled(),true);
 await page.mouse.click(blank.x,blank.y);await page.waitForTimeout(50);
 check('composition blur keeps draft active',await page.evaluate(()=>!!qaView.inline),true);
 await page.evaluate(()=>qaView.inline.input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'中文输入'})));
 await page.waitForFunction(()=>!qaView.inline);current+=' 中文输入';
 check('composition completion after blur saves exact text',await readFile(path.join(vault,'note.md'),'utf8'),current);

 await page.evaluate(()=>qaView.startInlineEdit('note'));await page.locator('.ts-inline-native .cm-content').focus();await page.keyboard.insertText(' recoverable draft');
 await page.evaluate(()=>{window.qaProcess=app.vault.process;app.vault.process=async()=>{throw Error('QA_NAVIGATION_WRITE_FAILURE');};});
 await page.evaluate(()=>qaView.finishInlineForNavigation());
 await page.evaluate(()=>{app.vault.process=window.qaProcess;delete window.qaProcess;});
 check('navigation recovery preserves original note',await readFile(path.join(vault,'note.md'),'utf8'),current);
 const recoveries=await page.evaluate(async()=>{const files=app.vault.getMarkdownFiles().filter(f=>f.path.includes('恢复草稿'));return await Promise.all(files.map(async f=>({path:f.path,text:await app.vault.read(f)})));});
 check('navigation writes one recovery file',recoveries.length,1);
 check('recovery file contains complete draft',recoveries[0].text,current+' recoverable draft');
 check('navigation clears active draft after recovery',await page.evaluate(()=>!!qaView.inline),false);
 check('closed drafts leave no chrome',await page.locator('.ts-inline-chrome').count(),0);
 check('closed drafts leave no measurement surfaces',await page.locator('.ts-inline-measure').count(),0);
 check('source and target notes remain distinct',await readFile(path.join(vault,'second.md'),'utf8'),'Second note');
 check('no native page errors',report.errors,[]);
 await page.screenshot({path:path.join(out,'native-editor.png')});
}catch(error){report.failure={message:error.message,stack:error.stack};if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});throw error;}
finally{
 await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));
 if(application&&application.exitCode===null){const closed=new Promise(resolve=>application.once('exit',resolve));application.kill('SIGTERM');await Promise.race([closed,sleep(2000)]);if(application.exitCode===null)application.kill('SIGKILL');await Promise.race([closed,sleep(1000)]);}
 if(browser)await Promise.race([browser.close(),sleep(1000)]);
 console.log(JSON.stringify(report,null,2));
}
