import {LayoutRefreshQueue} from './layout-refresh-queue';
import {App,Modal,Notice,setIcon} from 'obsidian';
import {Board} from './model';
import {readingTitle} from './reading-desk';
import {LayoutOptions,LayoutPlan,layoutModes,layoutBounds,planLayout,planSectionLayout,applyLayout,resolveLayoutScope,LayoutScope,LayoutViewport,layoutChanges,layoutHasChanges} from './layout-planner';
import {PreviewCamera,zoomPreviewAt,previewConnection,focusPreviewRect} from './layout-preview-geometry';
import {PreviewEntry,indexPreview,searchPreview} from './layout-preview-search';
import {themeSurface} from './ui-tokens';
interface LayoutHost{board:()=>Board;ids:Set<string>;viewport?:()=>LayoutViewport;commit:(edit:(b:Board)=>void)=>void;focus?:(ids:Set<string>)=>void;}
const ns='http://www.w3.org/2000/svg';let layoutPreviewScene=0;
const modeIcons:Record<LayoutOptions['mode'],string>={grid:'layout-grid',masonry:'panels-top-left',row:'columns-3',column:'rows-3',kind:'shapes',color:'palette',review:'book-open-check',connections:'network',distributeX:'align-horizontal-space-around',distributeY:'align-vertical-space-around',alignLeft:'align-start-vertical',alignCenter:'align-center-vertical',alignRight:'align-end-vertical',alignTop:'align-start-horizontal',alignMiddle:'align-center-horizontal',alignBottom:'align-end-horizontal'};
const shortModes:Record<LayoutOptions['mode'],string>={grid:'网格',row:'横向',column:'纵向',masonry:'瀑布流',kind:'类型',color:'颜色',review:'阅读状态',connections:'连线聚类',distributeX:'横向等距',distributeY:'纵向等距',alignLeft:'左对齐',alignCenter:'水平居中',alignRight:'右对齐',alignTop:'顶端对齐',alignMiddle:'垂直居中',alignBottom:'底端对齐'};
const modeHints:Record<LayoutOptions['mode'],string>={grid:'规整对齐，适合浏览与比较',row:'沿水平方向展开内容',column:'按纵向顺序梳理思路',masonry:'利用高低差，减少版面空隙',kind:'分开整理笔记、文本和图片',color:'让同色内容自然聚在一起',review:'按阅读进度梳理材料',connections:'按所选内容之间的连线归类；未连接内容单列，不创建分组框',distributeX:'按当前横向顺序均匀留白，保持纵向位置',distributeY:'按当前纵向顺序均匀留白，保持横向位置',alignLeft:'对齐左边缘，保持纵向位置；可能产生重叠',alignCenter:'对齐水平中心，保持纵向位置；可能产生重叠',alignRight:'对齐右边缘，保持纵向位置；可能产生重叠',alignTop:'对齐上边缘，保持横向位置；可能产生重叠',alignMiddle:'对齐垂直中心，保持横向位置；可能产生重叠',alignBottom:'对齐下边缘，保持横向位置；可能产生重叠'};
const preferences=new WeakMap<App,{options:LayoutOptions;focus:boolean;edges:boolean}>();
export class LayoutPlannerModal extends Modal{
 private layoutScope:LayoutScope='selection';private initialSelection=new Set<string>();private scopeSelect!:HTMLSelectElement;private scopeCount!:HTMLElement;private scopeNote!:HTMLElement;
 private options:LayoutOptions={mode:'grid',columns:3,gap:40,sort:'position',anchor:'center'};
 private plan?:LayoutPlan;private canvas!:HTMLElement;private summary!:HTMLElement;private apply!:HTMLButtonElement;private columns!:HTMLInputElement;private gap!:HTMLInputElement;
 private before=false;private compare!:HTMLButtonElement;private afterCompare!:HTMLButtonElement;private modes!:HTMLElement;private refreshQueue=new LayoutRefreshQueue(()=>this.refresh(),{frame:run=>this.contentEl.win.requestAnimationFrame(run),cancelFrame:id=>this.contentEl.win.cancelAnimationFrame(id),later:(run,ms)=>this.contentEl.win.setTimeout(run,ms),cancelLater:id=>this.contentEl.win.clearTimeout(id)});private closed=false;private showEdges=true;private sectionId?:string;private scopeEl!:HTMLElement;
 private searchBar!:HTMLElement;private searchInput!:HTMLInputElement;private searchStatus!:HTMLElement;private searchToggle!:HTMLButtonElement;private searchPrev!:HTMLButtonElement;private searchNext!:HTMLButtonElement;private searchIndex:PreviewEntry[]=[];private matches:PreviewEntry[]=[];private matchIndex=0;
 private cameras=new Map<boolean,PreviewCamera>();private focused=false;private hint!:HTMLElement;private previewTitle!:HTMLElement;private presets!:HTMLElement;private previews=new Map<boolean,{svg:SVGSVGElement;bounds:{x:number;y:number;width:number;height:number}}>();private focusAfter=true;private svg?:SVGSVGElement;private zoom=1;private pan={x:0,y:0};private base={x:0,y:0,width:1,height:1};private zoomLabel!:HTMLButtonElement;private drag?:{id:number;x:number;y:number};
 constructor(app:App,private host:LayoutHost){super(app);const saved=preferences.get(app);if(saved){this.options={...saved.options};this.focusAfter=saved.focus;this.showEdges=saved.edges;}}
 private run(fn:()=>void){try{fn();}catch(e){new Notice(String(e));}}
 private button(el:HTMLElement,label:string,icon:string,fn:()=>void){const b=el.createEl('button',{attr:{'aria-label':label,title:label}});if(icon)setIcon(b.createSpan(),icon);b.createSpan({text:label});b.onclick=()=>this.run(fn);return b;}
 private select<K extends 'sort'|'anchor'>(el:HTMLElement,key:K,label:string,values:Record<string,string>){const l=el.createEl('label');l.createSpan({text:label});const s=l.createEl('select',{attr:{'aria-label':label}});for(const[value,text]of Object.entries(values))s.createEl('option',{value,text});s.value=this.options[key];s.onchange=()=>{this.options[key]=s.value as LayoutOptions[K];this.schedule();};}
 onOpen(){themeSurface(this.modalEl);this.modalEl.addClass('ts-layout-planner');this.titleEl.empty();const heading=this.titleEl.createDiv('ts-layout-heading');setIcon(heading.createSpan('ts-layout-heading-icon'),'layout-grid');heading.createSpan({text:'整理白板'});this.titleEl.createDiv({cls:'ts-layout-subtitle',text:'选择排列方式，预览后应用'});
  const b=this.host.board();this.initialSelection=new Set(this.host.ids);this.layoutScope=this.initialSelection.size?'selection':'loose';
  this.scopeEl=this.contentEl.createDiv({cls:'ts-layout-scope'});setIcon(this.scopeEl.createSpan(),'scan');
  this.scopeSelect=this.scopeEl.createEl('select',{attr:{'aria-label':'整理范围'}});
  const scopes:[LayoutScope,string][]=[['selection','当前选择'],['loose','白板全部散卡'],...(this.host.viewport?[['visible','当前视野散卡'] as [LayoutScope,string]]:[]),...b.nodes.filter(n=>n.kind==='section').map(n=>[`section:${n.id}` as LayoutScope,'分组 · '+(n.title||'未命名分组')] as [LayoutScope,string])];
  for(const [value,text]of scopes){const option=this.scopeSelect.createEl('option',{value,text});if(value==='selection'&&!this.initialSelection.size)option.disabled=true;}
  this.scopeSelect.value=this.layoutScope;this.scopeSelect.onchange=()=>{this.layoutScope=this.scopeSelect.value as LayoutScope;this.searchInput.value='';this.svg=undefined;this.canvas.empty();this.schedule();};this.scopeCount=this.scopeEl.createSpan('ts-layout-scope-count');
  const body=this.contentEl.createDiv('ts-layout-body'),controls=body.createDiv('ts-layout-controls');
  controls.createDiv({cls:'ts-layout-label',text:'整理范围'});controls.appendChild(this.scopeEl);
  this.modes=controls.createDiv({cls:'ts-layout-modes',attr:{role:'group','aria-label':'排列方式'}});
  for(const [mode,label]of Object.entries(layoutModes).filter(([mode])=>!mode.startsWith('align'))){const key=mode as LayoutOptions['mode'];const category=({grid:'基础排列',kind:'内容归类',distributeX:'均匀分布'} as Partial<Record<LayoutOptions['mode'],string>>)[key];if(category)this.modes.createSpan({cls:'ts-layout-mode-divider',text:category});const btn=this.button(this.modes,label,modeIcons[key],()=>{if(this.options.mode===key)return;this.options.mode=key;this.schedule();});btn.lastElementChild!.textContent=shortModes[key];btn.title=shortModes[key]+' · '+modeHints[key];btn.dataset.mode=key;const sample=btn.firstElementChild as HTMLElement;sample.empty();sample.addClass('ts-layout-miniature');sample.setAttribute('aria-hidden','true');for(let i=0;i<4;i++)sample.createSpan();btn.setAttribute('aria-pressed',String(key===this.options.mode));}
  this.modes.onkeydown=e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.isComposing||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;const buttons=Array.from(this.modes.querySelectorAll<HTMLButtonElement>('button')),at=buttons.indexOf(e.target as HTMLButtonElement);if(at<0)return;e.preventDefault();e.stopPropagation();const columns=Math.max(1,getComputedStyle(this.modes).gridTemplateColumns.split(' ').length),delta=e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:e.key==='ArrowUp'?-columns:columns,index=e.key==='Home'?0:e.key==='End'?buttons.length-1:(at+delta+buttons.length)%buttons.length;buttons[index].focus();buttons[index].click();};
  controls.createDiv({cls:'ts-layout-label',text:'边缘对齐'});const align=controls.createDiv({cls:'ts-layout-alignments',attr:{role:'group','aria-label':'对齐位置'}});
  for(const [mode,label]of Object.entries(layoutModes).filter(([mode])=>mode.startsWith('align'))){const key=mode as LayoutOptions['mode'];const btn=this.button(align,label,modeIcons[key],()=>{this.options.mode=key;this.schedule();});btn.dataset.mode=key;btn.addClass('ts-layout-icon');}
  const fields=controls.createDiv('ts-layout-fields');
  for(const [key,label]of [['columns','列数'],['gap','对象间距']] as const){const l=fields.createEl('label');l.createSpan({text:label});const input=l.createEl('input',{type:'number',value:String(this.options[key]),attr:{'aria-label':label,min:key==='columns'?'1':'8',max:key==='columns'?'12':'240',step:'1'}});if(key==='columns')this.columns=input;else this.gap=input;input.oninput=()=>{this.options[key]=Number(input.value);this.schedule();};}
  const presets=this.presets=controls.createDiv({cls:'ts-layout-presets',attr:{role:'group','aria-label':'间距预设'}});
  for(const [label,gap]of [['紧凑',24],['标准',40],['宽松',72]] as const){const btn=this.button(presets,label,'',()=>{if(this.options.gap===gap)return;this.options.gap=gap;this.gap.value=String(gap);this.schedule();});btn.dataset.gap=String(gap);}
  const advanced=controls.createEl('details',{cls:'ts-layout-advanced'});advanced.createEl('summary',{text:'更多选项'});const advancedBody=advanced.createDiv('ts-layout-advanced-body');
  this.select(advancedBody,'sort','内容顺序',{position:'当前空间顺序',title:'按标题排序'});
  this.select(advancedBody,'anchor','布局位置',{center:'保留选区中心',corner:'保留左上角'});
  this.scopeNote=advancedBody.createDiv({cls:'ts-layout-note'});
  this.button(advancedBody,'重置排列参数','rotate-ccw',()=>{this.options={mode:'grid',columns:3,gap:40,sort:'position',anchor:'center'};this.columns.value='3';this.gap.value='40';(this.modalEl.querySelector('[aria-label="内容顺序"]') as HTMLSelectElement).value='position';(this.modalEl.querySelector('[aria-label="布局位置"]') as HTMLSelectElement).value='center';this.schedule();}).addClass('ts-layout-reset');
  const preview=body.createDiv('ts-layout-preview'),previewHeader=preview.createDiv('ts-layout-preview-tools'),copy=previewHeader.createDiv('ts-layout-preview-copy');this.previewTitle=copy.createSpan({cls:'ts-layout-preview-title',text:'布局预览'});this.hint=copy.createDiv({cls:'ts-layout-mode-hint'});const tools=previewHeader.createDiv('ts-layout-preview-actions');
  const viewbar=preview.createDiv('ts-layout-viewbar'),comparison=viewbar.createDiv({cls:'ts-layout-comparison',attr:{role:'group','aria-label':'比较布局'}});
  this.compare=this.button(comparison,'查看原布局','split-square-horizontal',()=>{this.flush();this.before=true;this.compare.setAttribute('aria-pressed',String(this.before));this.draw();});this.compare.setAttribute('aria-pressed','false');this.compare.lastElementChild!.textContent='原布局';
  this.afterCompare=this.button(comparison,'查看整理后布局','',()=>{this.flush();this.before=false;this.draw();});this.afterCompare.lastElementChild!.textContent='整理后';this.afterCompare.setAttribute('aria-pressed','true');
  const edges=this.button(tools,'显示连线','git-pull-request',()=>{this.showEdges=!this.showEdges;edges.setAttribute('aria-pressed',String(this.showEdges));this.updateEdges();});edges.setAttribute('aria-pressed',String(this.showEdges));
  edges.addClass('ts-layout-icon');this.button(tools,'重新预览','refresh-cw',()=>{this.refreshQueue.cancel();this.refresh();}).addClass('ts-layout-icon');
  const focus=this.button(tools,'专注预览','expand',()=>{this.focused=!this.focused;this.modalEl.toggleClass('is-preview-focused',this.focused);focus.setAttribute('aria-pressed',String(this.focused));});focus.addClass('ts-layout-icon');focus.setAttribute('aria-pressed','false');
  this.searchToggle=this.button(tools,'查找预览内容','search',()=>this.toggleSearch());this.searchToggle.addClass('ts-layout-icon');this.searchToggle.setAttribute('aria-expanded','false');
  this.searchBar=preview.createDiv('ts-layout-search');this.searchBar.hidden=true;const searchRow=this.searchBar.createDiv('ts-layout-search-row');setIcon(searchRow.createSpan(),'search');this.searchInput=searchRow.createEl('input',{type:'search',attr:{placeholder:'查找标题或路径…','aria-label':'查找预览内容的标题或路径'}});this.searchInput.oninput=()=>this.findPreview();this.searchInput.onkeydown=e=>{if(e.isComposing||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Enter'){e.preventDefault();e.stopPropagation();this.stepMatch(e.shiftKey?-1:1);}};this.searchPrev=this.button(searchRow,'上一个匹配','chevron-up',()=>this.stepMatch(-1));this.searchNext=this.button(searchRow,'下一个匹配','chevron-down',()=>this.stepMatch(1));this.button(searchRow,'关闭查找','x',()=>this.toggleSearch(false)).addClass('ts-layout-icon');this.searchPrev.addClass('ts-layout-icon');this.searchNext.addClass('ts-layout-icon');this.searchStatus=this.searchBar.createDiv({cls:'ts-layout-search-status',attr:{role:'status','aria-live':'polite'}});this.searchStatus.setText('仅定位预览，不改变整理范围');this.searchPrev.disabled=this.searchNext.disabled=true;
  viewbar.createSpan({cls:'ts-layout-preview-status',text:'实时预览'});
  const surface=preview.createDiv('ts-layout-surface');this.canvas=surface.createDiv({cls:'ts-layout-canvas',attr:{'aria-label':'所选对象布局示意'}});
  this.canvas.tabIndex=0;this.canvas.setAttribute('aria-description','拖动平移；Ctrl 或 Command 加滚轮围绕鼠标缩放；加减键缩放，数字 0 适应全部，方向键平移');
  this.canvas.addEventListener('wheel',e=>{if(!(e.ctrlKey||e.metaKey)||!this.svg||!this.plan)return;const matrix=this.svg.getScreenCTM();if(!matrix)return;e.preventDefault();e.stopPropagation();const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?this.canvas.clientHeight:1);this.changeZoom(Math.exp(-Math.max(-120,Math.min(120,delta))*.006),point);},{passive:false});
  this.canvas.ondblclick=e=>{e.preventDefault();this.resetCamera();};
  this.canvas.onpointerdown=e=>{if(e.button!==0||(e.target as Element).closest('button')||!this.svg)return;this.canvas.focus();this.drag={id:e.pointerId,x:e.clientX,y:e.clientY};this.canvas.setPointerCapture(e.pointerId);this.canvas.addClass('is-panning');};
  this.canvas.onpointermove=e=>{if(!this.drag||e.pointerId!==this.drag.id||!this.svg)return;const scale=this.svg.getScreenCTM()?.a;if(!scale)return;this.pan.x-=(e.clientX-this.drag.x)/scale;this.pan.y-=(e.clientY-this.drag.y)/scale;this.drag.x=e.clientX;this.drag.y=e.clientY;this.camera();};
  const end=()=>{this.drag=undefined;this.canvas.removeClass('is-panning');};this.canvas.onpointerup=end;this.canvas.onpointercancel=end;this.canvas.onlostpointercapture=end;
  this.canvas.onkeydown=e=>{if(e.target!==this.canvas||e.metaKey||e.ctrlKey||e.altKey)return;if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();e.stopPropagation();if(e.key==='0')this.resetCamera();else if(['+','=','-'].includes(e.key))this.changeZoom(e.key==='-'?1/1.3:1.3);else{const step=50/this.zoom;this.pan.x+=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0;this.pan.y+=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;this.camera();}}};
  const nav=surface.createDiv('ts-layout-navigation');nav.createSpan({text:'拖动查看细节',cls:'ts-layout-navigation-hint'});
  const icon=(label:string,name:string,fn:()=>void)=>{const b=this.button(nav,label,name,fn);b.addClass('ts-layout-icon');return b;};
  icon('缩小预览','minus',()=>this.changeZoom(1/1.3));this.zoomLabel=this.button(nav,'适应预览','',()=>this.resetCamera());icon('放大预览','plus',()=>this.changeZoom(1.3));icon('重置预览视角','scan',()=>this.resetCamera());
  this.summary=preview.createDiv({cls:'ts-layout-summary',attr:{role:'status','aria-live':'polite'}});
  const footer=this.contentEl.createDiv('ts-layout-footer');const follow=footer.createEl('label',{cls:'ts-layout-follow'}),check=follow.createEl('input',{type:'checkbox'});check.checked=this.focusAfter;check.onchange=()=>{this.focusAfter=check.checked;};follow.createSpan({text:'应用后定位到结果'});
  this.button(footer,'取消','',()=>this.close());this.apply=this.button(footer,'应用布局','check',()=>{this.flush();if(!this.plan||!layoutHasChanges(this.plan))return;const plan=this.plan;try{this.host.commit(board=>applyLayout(board,plan));}catch(e){this.apply.disabled=true;this.summary.setText(`${String(e).replace(/^Error: /,'')}。点击右上角刷新后再应用。`);return;}preferences.set(this.app,{options:{...this.options},focus:this.focusAfter,edges:this.showEdges});this.close();if(this.focusAfter)this.host.focus?.(new Set(this.sectionId?[this.sectionId]:plan.ids));});this.apply.addClass('mod-cta');this.apply.title='应用布局 · Ctrl / ⌘ + Enter';this.contentEl.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)&&!e.isComposing){e.preventDefault();e.stopPropagation();this.flush();if(!this.apply.disabled)this.apply.click();}});this.refresh();
 }
 /** Coalesce input events, keep controls/focus intact, and never commit a stale pending preview. */
 private schedule(){if(this.closed)return;this.apply.disabled=true;this.canvas.setAttribute('aria-busy','true');this.refreshQueue.schedule();}
 private flush(){this.refreshQueue.flush();}
 private refresh(){if(this.closed)return;this.apply.lastElementChild!.textContent='应用布局';this.compare.disabled=this.afterCompare.disabled=true;this.columns.disabled=!['grid','masonry','connections'].includes(this.options.mode);this.columns.setAttribute('aria-invalid',String(!this.columns.disabled&&(!Number.isInteger(this.options.columns)||this.options.columns<1||this.options.columns>12)));this.gap.disabled=this.options.mode.startsWith('align');this.gap.setAttribute('aria-invalid',String(!this.gap.disabled&&(!Number.isFinite(this.options.gap)||this.options.gap<8||this.options.gap>240)));(this.modalEl.querySelector('[aria-label="内容顺序"]') as HTMLSelectElement).disabled=this.options.mode.startsWith('align')||this.options.mode.startsWith('distribute');this.plan=undefined;this.previews.clear();this.cameras.clear();this.canvas.setAttribute('aria-busy','false');this.canvas.removeClass('has-layout-error');this.hint.setText(modeHints[this.options.mode]);this.previewTitle.setText(layoutModes[this.options.mode]);this.presets.querySelectorAll<HTMLButtonElement>('button').forEach(b=>{b.disabled=this.gap.disabled;b.setAttribute('aria-pressed',String(!b.disabled&&Number(b.dataset.gap)===this.options.gap));});
  this.modalEl.querySelectorAll<HTMLButtonElement>('button[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===this.options.mode)));
  try{const scope=resolveLayoutScope(this.host.board(),this.layoutScope,this.initialSelection,this.host.viewport?.());this.host.ids=scope.ids;this.sectionId=scope.sectionId;this.scopeCount.setText(this.sectionId?'分组内整理':`${scope.ids.size} 项`);this.scopeNote.setText(this.sectionId?'只整理框内对象，分组框自动贴合；锁定对象或嵌套分组须先处理。':'散卡范围保留分组内内容。只移动未锁定对象，保留尺寸、笔记和连线。');(this.modalEl.querySelector('[aria-label="布局位置"]') as HTMLSelectElement).disabled=!!this.sectionId||this.options.mode.startsWith('align');
   this.plan=this.sectionId?planSectionLayout(this.host.board(),this.sectionId,this.options):planLayout(this.host.board(),this.host.ids,this.options);this.before=false;this.compare.disabled=this.afterCompare.disabled=false;this.showSummary(this.plan);this.apply.disabled=!layoutHasChanges(this.plan);this.apply.lastElementChild!.textContent=this.apply.disabled?'无需移动':'应用布局';this.searchIndex=indexPreview(this.plan.items);this.matches=searchPreview(this.searchIndex,this.searchInput.value);this.matchIndex=0;this.draw();this.updateSearchStatus();}
  catch(e){this.apply.disabled=true;this.searchIndex=[];this.matches=[];this.updateSearchStatus();this.canvas.querySelector('.ts-layout-empty')?.remove();this.svg?.querySelector('.ts-layout-match')?.remove();this.canvas.addClass('has-layout-error');this.canvas.querySelector('.ts-layout-preview-label')?.remove();this.canvas.createDiv({cls:'ts-layout-empty',text:String(e).replace(/^Error: /,'')});this.summary.setText(this.svg?'当前条件不可应用 · 保留上一次预览':'调整选区或参数后重新预览。');}
 }
 private showSummary(plan:LayoutPlan){
  this.summary.empty();const stat=(value:string,label:string)=>{const item=this.summary.createSpan('ts-layout-stat');item.createEl('strong',{text:value});item.createSpan({text:label});};
  stat(String(plan.items.length),' 项参与整理');stat(String(layoutChanges(plan)),' 项位置改变');if(plan.skipped)stat(String(plan.skipped),' 项保持原位');
  const dimensions=this.summary.createSpan({cls:'ts-layout-dimensions',text:`${Math.round(plan.bounds.width)} × ${Math.round(plan.bounds.height)}`});dimensions.title='整理后内容范围';
  if(plan.section)this.summary.createSpan({cls:'ts-layout-summary-note',text:'分组框自动贴合'});if(!layoutHasChanges(plan))this.summary.createSpan({cls:'ts-layout-summary-note',text:'当前布局已符合条件'});
 }
 private toggleSearch(open=this.searchBar.hidden){this.searchBar.hidden=!open;this.searchToggle.setAttribute('aria-expanded',String(open));if(open)this.searchInput.focus();else{this.searchInput.value='';this.findPreview(false);this.searchToggle.focus();}}
 private updateSearchStatus(){const q=this.searchInput.value.trim(),hit=this.matches[this.matchIndex];this.searchStatus.setText(q?(hit?`${this.matchIndex+1} / ${this.matches.length} · ${hit.title}`:'没有匹配的标题或路径'):'仅定位预览，不改变整理范围');this.searchStatus.title=hit?.title||'';this.searchPrev.disabled=this.searchNext.disabled=!this.matches.length;}
 private findPreview(focus=true){this.matches=searchPreview(this.searchIndex,this.searchInput.value);this.matchIndex=0;this.updateSearchStatus();this.markMatch(focus);}
 private stepMatch(step:number){if(!this.matches.length)return;this.matchIndex=(this.matchIndex+step+this.matches.length)%this.matches.length;this.updateSearchStatus();this.markMatch(true);}
 private markMatch(focus=false){for(const {svg}of this.previews.values())svg.querySelector('.ts-layout-match')?.remove();const hit=this.matches[this.matchIndex],n=(this.before?this.plan?.originals:this.plan?.items)?.find(n=>n.id===hit?.id);if(!this.svg||!n)return;const ring=document.createElementNS(ns,'rect');for(const[k,v]of Object.entries({x:n.x-5,y:n.y-5,width:n.width+10,height:n.height+10,rx:15}))ring.setAttribute(k,String(v));ring.setAttribute('class','ts-layout-match');ring.setAttribute('data-node-id',n.id);this.svg.appendChild(ring);if(focus){const next=focusPreviewRect(this.base,n,this.canvas.clientWidth/this.canvas.clientHeight);this.zoom=next.zoom;this.pan=next.pan;this.camera();}}
 private changeZoom(factor:number,point?:{x:number;y:number}){if(!this.plan)return;const next=zoomPreviewAt(this.base,{zoom:this.zoom,pan:this.pan},factor,point);this.zoom=next.zoom;this.pan=next.pan;this.camera();}
 private resetCamera(){this.zoom=1;this.pan={x:0,y:0};this.camera();}
 private camera(){if(!this.svg)return;const b=this.base,w=b.width/this.zoom,h=b.height/this.zoom;this.pan.x=Math.max(-b.width,Math.min(b.width,this.pan.x));this.pan.y=Math.max(-b.height,Math.min(b.height,this.pan.y));this.svg.setAttribute('viewBox',`${b.x+(b.width-w)/2+this.pan.x} ${b.y+(b.height-h)/2+this.pan.y} ${w} ${h}`);this.cameras.set(this.before,{zoom:this.zoom,pan:{...this.pan}});this.zoomLabel.setText(this.zoom===1?'适应':`${Math.round(this.zoom*100)}%`);}
 private updateEdges(){for(const {svg}of this.previews.values())svg.querySelector('.ts-layout-connections')?.classList.toggle('is-hidden',!this.showEdges);}
 private mountPreview(){this.compare.setAttribute('aria-pressed',String(this.before));this.afterCompare.setAttribute('aria-pressed',String(!this.before));this.canvas.replaceChildren(this.svg!);this.updateEdges();this.canvas.createDiv({cls:'ts-layout-preview-label',text:this.before?'原布局':`待应用${this.plan!.items.length>160?' · 简化预览':''}`});const saved=this.cameras.get(this.before);if(saved){this.zoom=saved.zoom;this.pan={...saved.pan};this.camera();}else this.resetCamera();this.markMatch();}
 private draw(){if(!this.plan)return;const cached=this.previews.get(this.before);if(cached){this.svg=cached.svg;this.base=cached.bounds;this.mountPreview();return;}const nodes=this.before?this.plan.originals:this.plan.items,frame=this.plan.section&&(this.before?this.plan.section.original:this.plan.section.next),bounds=layoutBounds(frame?[...nodes,frame]:nodes);const svg=document.createElementNS(ns,'svg');this.base={x:bounds.x-30,y:bounds.y-75,width:bounds.width+60,height:bounds.height+110};this.svg=svg;svg.setAttribute('role','img');
  // Native aria-label tooltips assume HTMLElement; SVG names use linked titles.
  const title=document.createElementNS(ns,'title'),titleId=`ts-layout-preview-title-${++layoutPreviewScene}`;title.setAttribute('id',titleId);svg.setAttribute('aria-labelledby',titleId);title.textContent=`${this.before?'原布局':layoutModes[this.options.mode]} · ${nodes.length} 项内容`;svg.appendChild(title);
  const palette:Record<string,string>={sand:'#cfb963',green:'#71b69d',blue:'#7aaacc',rose:'#cd8da0',purple:'#ac91c9',orange:'#dba271',red:'#d17d7a',teal:'#7db7ac',cyan:'#85bbc9',lime:'#abc178',slate:'#9da9b9',brown:'#b59883'};
  const path=(d:string,cls:string,color?:string)=>{const p=document.createElementNS(ns,'path');p.setAttribute('d',d);p.setAttribute('class',cls);if(color){p.setAttribute('fill',color);p.setAttribute('stroke',color);}svg.appendChild(p);};
  if(frame){const r=document.createElementNS(ns,'rect');for(const[k,v]of Object.entries({x:frame.x,y:frame.y,width:frame.width,height:frame.height,rx:14}))r.setAttribute(k,String(v));r.setAttribute('class','ts-layout-frame');svg.appendChild(r);}
  {const positions=new Map(nodes.map(n=>[n.id,n]));let d='',count=0;for(const e of this.host.board().edges){const a=positions.get(e.from),b=positions.get(e.to);if(!a||!b)continue;if(count++>=1000)break;d+=previewConnection(a,b);}if(d)path(d,'ts-layout-connections');}
  if(!this.before)for(const lane of this.plan.lanes){const text=document.createElementNS(ns,'text');text.setAttribute('x',String(lane.x));text.setAttribute('y',String((lane.y??this.plan.bounds.y)-26));text.setAttribute('font-size','18');text.setAttribute('fill','currentColor');text.textContent=lane.label;svg.appendChild(text);}
  // At large sizes, one path per color replaces thousands of individual DOM nodes.
  if(nodes.length>160){const paths=new Map<string,string>();for(const n of nodes){const color=palette[n.color]||palette.slate;paths.set(color,(paths.get(color)||'')+`M${n.x},${n.y}h${n.width}v${n.height}h${-n.width}Z`);}for(const[color,d]of paths)path(d,'ts-layout-object',color);}
  else for(const n of nodes){const group=document.createElementNS(ns,'g'),rect=document.createElementNS(ns,'rect');for(const [key,value]of Object.entries({x:n.x,y:n.y,width:n.width,height:n.height,rx:12,fill:palette[n.color]||palette.slate,stroke:palette[n.color]||palette.slate}))rect.setAttribute(key,String(value));rect.setAttribute('class','ts-layout-object');group.appendChild(rect);const title=document.createElementNS(ns,'title');title.textContent=readingTitle(n);group.appendChild(title);
   const text=document.createElementNS(ns,'text');text.setAttribute('x',String(n.x+12));text.setAttribute('y',String(n.y+Math.min(29,n.height-8)));text.setAttribute('font-size','16');text.setAttribute('fill','currentColor');text.textContent=readingTitle(n).slice(0,Math.max(2,Math.floor((n.width-24)/16)));group.appendChild(text);if(n.kind==='text'&&n.height>=68){const line=(n.text||'').split('\n').filter(l=>l.trim()).slice(1).find(l=>l.trim());if(line){const sub=document.createElementNS(ns,'text');sub.setAttribute('x',String(n.x+12));sub.setAttribute('y',String(n.y+51));sub.setAttribute('font-size','12');sub.setAttribute('class','ts-layout-caption');sub.textContent=line.replace(/^[#>*\s-]+/,'').slice(0,Math.max(2,Math.floor((n.width-24)/12)));group.appendChild(sub);}}svg.appendChild(group);
  }
  this.previews.set(this.before,{svg,bounds:this.base});this.mountPreview();
 }
 onClose(){this.closed=true;this.refreshQueue.cancel();this.plan=undefined;this.svg=undefined;this.drag=undefined;this.previews.clear();this.cameras.clear();this.searchIndex=[];this.matches=[];this.contentEl.empty();}
}
