import {ItemView,View,Scope,setIcon,type WorkspaceLeaf,type ViewStateResult} from 'obsidian';
import {clone,type Board,type Edge} from './model';
import {captureLocalRelationEdit,type LocalRelationMutation,type LocalRelationValue,type LocalRelationEditResult} from './local-relations-edit';
import {localNeighborhood,localRelationMatches,localRelationNode,supportsLocalRelations,searchLocalCenters,localRelationKinds,LocalRelationHistory,LocalRelationPins,type LocalRelationKind} from './local-relations';

import {cleanLocalRelationsState,cleanLocalRelationsWorkspaceState,rememberLocalRelation,displayLocalRelationRecent,type LocalRelationsSavedState,type LocalRelationsWorkspaceState,type LocalRelationsFollow,type LocalRelationsFilter} from './local-relations-state';
import type {NativeLocalEvidence,NativeLocalRelation} from './local-relations-native';

import {localHeadingPage,type LocalHeadingTree,type LocalHeadingTarget} from './local-relations-headings';
import {localRelationDepth,type LocalDepthItem} from './local-relations-depth';
import {LocalRelationMotion,type LocalRelationMotionSnapshot} from './local-relations-motion';

export const LOCAL_RELATIONS_VIEW='thoughtspace-local-relations';
export interface LocalRelationsSnapshot {board:Board;path:string;name:string;selectedId?:string;key?:object;originLeafId?:string;}
export interface LocalRelationsSource {label:string;path?:string;available:boolean;reason?:string;canExplain?:boolean;canEdit?:boolean;editReason?:string;}
export interface LocalRelationsHost {
 snapshot:()=>LocalRelationsSnapshot|undefined;
 subscribe:(notify:()=>void)=>()=>void;
 locate:(id:string,current:(allowHidden?:boolean)=>boolean)=>unknown;
 openSource?:(id:string,current:(allowHidden?:boolean)=>boolean)=>unknown;
 explain?:(id:string,current:(allowHidden?:boolean)=>boolean)=>unknown;
 source?:(id:string)=>LocalRelationsSource;
 returnToBoard?:(current:(allowHidden?:boolean)=>boolean)=>unknown;
 loadState?:(path:string)=>LocalRelationsSavedState|undefined;
 saveState?:(path:string,state:LocalRelationsSavedState)=>void;
 restoreContext?:(path:string,originLeafId:string|undefined,current:()=>boolean)=>Promise<boolean>;
 activeSource?:()=>{id?:string;ids?:string[];ambiguous?:boolean};
 setCompanion?:(enabled:boolean)=>void;
 companion?:()=>{enabled:boolean;available:boolean};
 editSource?:(id:string,current:(allowHidden?:boolean)=>boolean)=>unknown;
 editCenter?:(id:string,current:(allowHidden?:boolean)=>boolean)=>unknown;
 syncSource?:(id:string,current:(allowHidden?:boolean)=>boolean)=>unknown;
 native?:(id:string)=>{relations:readonly NativeLocalRelation[];tagsByNode:ReadonlyMap<string,readonly string[]>;pendingPaths?:readonly string[]};
 openEvidence?:(evidence:NativeLocalEvidence,current:(allowHidden?:boolean)=>boolean)=>unknown;
 relationEditing?:()=>{available:boolean;reason?:string;canUndo?:boolean;canRedo?:boolean};
 historyRelation?:(redo:boolean,current:()=>boolean)=>Promise<LocalRelationEditResult>;
 editRelation?:(command:LocalRelationMutation,current:()=>boolean)=>Promise<LocalRelationEditResult>;
 headings?:(id:string)=>LocalHeadingTree;
 openHeading?:(id:string,heading:LocalHeadingTarget,current:(allowHidden?:boolean)=>boolean)=>unknown;
}
const labels={parents:'父节点',children:'子节点',siblings:'同级节点',incoming:'指向这里',outgoing:'从这里指向',associated:'双向 / 无向'};
/** Navigation never changes board data; explicit relation edits use the host transaction. */
export class LocalRelationsView extends ItemView {
 private alive=false;private frame=0;private frameWindow?:Window;private generation=0;private linkFrame=0;private linkWindow?:Window;private unsubscribe?:()=>void;
 private motion=new LocalRelationMotion();private motionSnapshot?:LocalRelationMotionSnapshot;private motionActive=false;private motionWindow?:Window;private motionEpoch=0;
 private paintedCenter?:string;private history=new LocalRelationHistory();private pins=new LocalRelationPins();private context?:object|string;private selected?:string;private follow:LocalRelationsFollow='board';private query='';private pending?:{id:string;token:symbol;allowHidden:boolean;action?:string;inspector?:boolean};
 private lastSaved='';private saved=cleanLocalRelationsState(undefined);private recent:string[]=[];private boardPath?:string;private originLeafId?:string;private restoreEpoch=0;private pendingWorkspace?:LocalRelationsWorkspaceState;private restoreFlight?:Promise<void>;private closed=false;private sourceSelected?:string;private syncedCenter?:string;
 private pages:Partial<Record<LocalRelationKind,number>>={};private proofPages=new Map<string,number>();private proofEpochs=new Map<string,number>();private nativeData?:{relations:readonly NativeLocalRelation[];tagsByNode:ReadonlyMap<string,readonly string[]>;pendingPaths?:readonly string[]};
 private optionsHost?:HTMLElement;private recentHost?:HTMLElement;private recentPaintedCenter?:string;private recentContext?:object|string;private pickerHost?:HTMLElement;private pickerSearch?:HTMLInputElement;private pickerResults?:HTMLElement;private pickerOpen=false;private pickerQuery='';private pickerPage=0;
 private relationEditorDetails?:HTMLDetailsElement;private relationEditorStatus?:HTMLElement;private relationEditorCenter?:HTMLElement;private relationEdgeList?:HTMLElement;private relationForm?:HTMLElement;private relationTargetLabel?:HTMLElement;private relationTargetSearch?:HTMLInputElement;private relationTargetResults?:HTMLElement;private relationKind?:HTMLSelectElement;private relationOrientation?:HTMLSelectElement;private relationDirection?:HTMLSelectElement;private relationLabel?:HTMLInputElement;private relationKindHint?:HTMLElement;private relationConfirmation?:HTMLElement;
 private relationDraft?:{baseline:Board;edgeId?:string;targetId:string;orientation:'outgoing'|'incoming';kind:LocalRelationValue['kind'];direction:LocalRelationValue['direction'];label:string};private relationEditEpoch=0;private relationEditPending?:symbol;private relationPendingLabel='正在提交本板关系…';private relationMessage='';private relationRemoveConfirm=false;private relationEdgePage=0;private relationTargetPage=0;private relationTargetQuery='';private relationTargetOpen=false;private relationGraphScroll=0;
 private inspectorEpoch=0;private inspectorsHost?:HTMLElement;private headingStatus?:HTMLElement;private headingDetails?:HTMLDetailsElement;private headingSummary?:HTMLElement;private headingSearch?:HTMLInputElement;private headingRows?:HTMLElement;private headingTree?:LocalHeadingTree;private headingQuery='';private headingCollapsed=new Set<string>();private headingPage=0;
 private depthDetails?:HTMLDetailsElement;private depthSummary?:HTMLElement;private depthBody?:HTMLElement;private depthExpanded:string[]=[];private depthPages:Record<string,number>={};private depthProofPages=new Map<string,number>();private inspectorCenter?:string;private inspectorContext?:object|string;private lastNeighborhood?:ReturnType<typeof localNeighborhood>;
 private toolbar?:HTMLElement;private toolbarNavigation?:HTMLElement;private toolbarTools?:HTMLElement;private centerHost?:HTMLElement;private pinHost?:HTMLElement;private groupsHost?:HTMLElement;private search?:HTMLInputElement;private counts?:HTMLElement;private feedback?:HTMLElement;private footer?:HTMLElement;
 private filterPanel?:HTMLElement;private filterOpen=false;private morePanel?:HTMLElement;private secondaryToolbar?:HTMLElement;private moreOpen=false;private recentOpen=true;private visibleRoles=new Map<string,LocalRelationKind[]>();
 constructor(leaf:WorkspaceLeaf,private host:LocalRelationsHost){
  super(leaf);
  // Native find can consume Mod-F before DOM keydown reaches this view.
  // View.scope is activated by Obsidian with view focus; no global scope push.
  this.scope=new Scope(this.app.scope);this.scope.register(['Mod'],'f',event=>{
   const doc=this.contentEl.ownerDocument,active=doc.activeElement,ownsFocus=this.contentEl.contains(active)||((!active||active===doc.body)&&this.app.workspace.getActiveViewOfType(LocalRelationsView)===this);
   if(!this.alive||!this.visible()||event.defaultPrevented||!ownsFocus||(event.target&&event.target!==doc.body&&!this.contentEl.contains(event.target as Node)))return;
   this.keydown(event);if(event.defaultPrevented)return false;
  });
  // Native Escape can switch leaves before the view's DOM listener runs.
  this.scope.register([],'Escape',event=>{
   const doc=this.contentEl.ownerDocument,active=doc.activeElement,ownsFocus=this.contentEl.contains(active)||!active||active===doc.body;
   if(!this.alive||!this.visible()||event.defaultPrevented||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||!ownsFocus||this.app.workspace.getActiveViewOfType(View)!==this||(event.target&&event.target!==doc.body&&!this.contentEl.contains(event.target as Node)))return;
   this.keydown(event);if(event.defaultPrevented)return false;
  });
 }
 getViewType(){return LOCAL_RELATIONS_VIEW;}getDisplayText(){return '独立关系浏览';}getIcon(){return 'network';}
 async onOpen(){
  this.alive=true;this.closed=false;this.contentEl.empty();this.contentEl.addClass('ts-local-relations');
  this.toolbar=this.contentEl.createDiv({cls:'ts-local-relations-toolbar',attr:{'aria-label':'关系浏览'}});
  this.toolbarNavigation=this.toolbar.createDiv('ts-local-relations-navigation');
  this.search=this.toolbar.createEl('input',{cls:'ts-local-relations-search',type:'search',attr:{'aria-label':'筛选当前一跳邻居','data-relation-focus':'relation-search',placeholder:'筛选当前关系…'}});this.search.value=this.query;
  this.search.oninput=()=>{this.query=this.search?.value||'';this.filterChanged();};this.toolbarTools=this.toolbar.createDiv('ts-local-relations-toolbar-tools');
  this.pickerHost=this.contentEl.createDiv('ts-local-relations-picker');this.morePanel=this.contentEl.createDiv({cls:'ts-local-relations-more-panel',attr:{'aria-label':'更多关系工具'}});this.morePanel.hidden=true;this.secondaryToolbar=this.morePanel.createDiv('ts-local-relations-secondary-toolbar');
  this.filterPanel=this.contentEl.createDiv({cls:'ts-local-relations-filter-panel',attr:{'aria-label':'高级关系筛选'}});this.filterPanel.hidden=true;this.optionsHost=this.filterPanel.createEl('details',{cls:'ts-local-relations-options'});(this.optionsHost as HTMLDetailsElement).open=true;this.buildOptions();
  this.centerHost=this.contentEl.createDiv('ts-local-relations-center');this.pinHost=this.contentEl.createDiv('ts-local-relations-pins');
  this.counts=this.filterPanel.createDiv({cls:'ts-local-relations-counts',attr:{role:'status','aria-live':'polite'}});
  this.groupsHost=this.contentEl.createDiv('ts-local-relations-groups');this.groupsHost.onscroll=()=>this.queueLinks();this.buildInspectors();this.feedback=this.contentEl.createDiv({cls:'ts-local-relations-feedback',attr:{role:'status','aria-live':'polite'}});this.footer=this.contentEl.createDiv('ts-local-relations-actions');this.recentHost=this.contentEl.createDiv('ts-local-relations-recent');
  this.registerDomEvent(this.contentEl,'keydown',this.keydown);
  this.unsubscribe=this.host.subscribe(()=>this.refresh());this.registerEvent(this.app.workspace.on('layout-change',()=>this.refresh()));this.registerEvent(this.app.workspace.on('active-leaf-change',()=>this.refresh()));this.refresh();
 }
 private keydown=(event:KeyboardEvent)=>{
  // Some Electron IME integrations expose only the legacy composition key code.
  if(event.defaultPrevented||event.isComposing||Reflect.get(event,'keyCode')===229)return;
  const search=!event.shiftKey&&((event.key==='F4'&&!event.altKey&&!event.ctrlKey&&!event.metaKey)||((event.ctrlKey||event.metaKey)&&!event.altKey&&event.key.toLowerCase()==='f'));
  if(search&&this.relationEditorDetails?.open){const target=this.relationTargetSearch;if(!this.relationDraft||!target||target.disabled)return;event.preventDefault();event.stopPropagation();this.relationTargetOpen=true;this.paintRelationTargets();target.focus();return;}
  if(search){if(!this.search||this.search.disabled)return;event.preventDefault();event.stopPropagation();if(this.pickerOpen){this.pickerOpen=false;this.paintPicker();}this.search.focus();return;}
  if(this.navigateResults(event))return;
  if(event.key==='Escape'&&this.pickerOpen){event.preventDefault();event.stopPropagation();this.pickerOpen=false;this.paintPicker();this.toolbar?.querySelector<HTMLElement>('[data-relation-focus="center-picker-toggle"]')?.focus();return;}
  if(event.key==='Escape'&&this.inspectorsHost&&!this.inspectorsHost.hidden&&this.inspectorsHost.contains(this.contentEl.ownerDocument.activeElement)){event.preventDefault();event.stopPropagation();this.closeInspectors();return;}
  if(event.key==='Escape'){const info=this.centerHost?.querySelector<HTMLDetailsElement>('.ts-local-center-info');if(info?.open&&info.contains(this.contentEl.ownerDocument.activeElement)){event.preventDefault();event.stopPropagation();info.open=false;info.querySelector<HTMLElement>('summary')?.focus({preventScroll:true});this.queueLinks();return;}}
  if(event.key==='Escape'&&this.moreOpen&&(!this.filterOpen||this.morePanel?.contains(this.contentEl.ownerDocument.activeElement))){event.preventDefault();event.stopPropagation();this.showMore(false);this.toolbar?.querySelector<HTMLElement>('[data-relation-focus="more-toggle"]')?.focus();return;}
  if(event.key==='Escape'&&this.filterOpen&&this.filterPanel?.contains(this.contentEl.ownerDocument.activeElement)){event.preventDefault();event.stopPropagation();this.showFilter(false);return;}
  if(event.key==='Escape'&&this.query&&this.search&&!this.search.hidden){event.preventDefault();event.stopPropagation();this.generation++;this.query='';this.search.value='';this.search.focus();this.filterChanged();return;}
  if(event.key==='Escape'&&this.filterOpen){event.preventDefault();event.stopPropagation();this.showFilter(false);this.toolbar?.querySelector<HTMLElement>('[data-relation-focus="filter-toggle"]')?.focus();return;}
  if(event.key==='Escape'&&this.moreOpen){event.preventDefault();event.stopPropagation();this.showMore(false);this.toolbar?.querySelector<HTMLElement>('[data-relation-focus="more-toggle"]')?.focus();return;}
  if(event.altKey&&!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&(event.key==='ArrowLeft'||event.key==='ArrowRight')){const active=this.contentEl.ownerDocument.activeElement as HTMLElement|null;if(this.relationEditorDetails?.open&&active&&this.relationEditorDetails.contains(active)&&(['INPUT','TEXTAREA','SELECT'].includes(active.tagName)||active.isContentEditable||active.closest('[contenteditable="true"]')))return;event.preventDefault();event.stopPropagation();this.travel(event.key==='ArrowRight');}
 };
 onResize(){this.refresh();}
 /** Explicit opening or neighbor browsing changes only the panel center. */
 setContext(id?:string){this.pendingWorkspace=undefined;this.restoreEpoch++;this.generation++;const snapshot=this.host.snapshot();this.syncContext(snapshot);if(id&&snapshot?.board.nodes.some(n=>n.id===id&&supportsLocalRelations(n)))this.visit(id);else if(!id&&!this.history.current){const fallback=snapshot?.board.nodes.find(n=>n.id===snapshot.selectedId&&supportsLocalRelations(n))||snapshot?.board.nodes.find(supportsLocalRelations);if(fallback)this.visit(fallback.id);}this.selected=snapshot?.selectedId;this.refresh();}
 setFollowSelection(follow:boolean){this.setFollow(follow?'board':'locked');}
 refresh(){if(!this.alive)return;const win=this.contentEl.ownerDocument.defaultView;if(this.motionWindow&&this.motionWindow!==win){this.motion.cancel();this.motionActive=false;this.motionWindow=undefined;this.motionEpoch++;}if(this.frame&&this.frameWindow!==win){this.frameWindow?.cancelAnimationFrame(this.frame);this.frame=0;this.frameWindow=undefined;}if(this.linkFrame&&this.linkWindow!==win){this.linkWindow?.cancelAnimationFrame(this.linkFrame);this.linkFrame=0;this.linkWindow=undefined;}if(!this.visible()){this.motion.cancel();this.motionActive=false;this.motionEpoch++;if(this.relationEditPending)this.invalidateRelationRequest();if(this.pending&&!this.pending.allowHidden){this.generation++;this.pending=undefined;}return;}if(this.pendingWorkspace)void this.tryRestore();if(this.frame||!win||win.closed)return;this.frameWindow=win;const frame=win.requestAnimationFrame(()=>{if(this.frameWindow!==win||this.frame!==frame)return;this.frame=0;this.frameWindow=undefined;if(this.alive&&this.visible()&&this.contentEl.ownerDocument.defaultView===win)this.render();});this.frame=frame;}
 private visible(){return this.contentEl.isConnected&&this.contentEl.getClientRects().length>0;}
 private syncContext(snapshot:LocalRelationsSnapshot|undefined){
  if(!snapshot)return;const key=snapshot.key||snapshot.path;if(this.context!==key){this.persist();this.generation++;this.pending=undefined;this.context=key;this.boardPath=snapshot.path;this.originLeafId=snapshot.originLeafId;this.paintedCenter=undefined;this.selected=undefined;this.sourceSelected=undefined;this.syncedCenter=undefined;this.pages={};this.proofPages.clear();this.nativeData=undefined;this.applySaved(this.host.loadState?.(snapshot.path));}
  this.boardPath=snapshot.path;this.originLeafId=snapshot.originLeafId;const ids=snapshot.board.nodes.filter(supportsLocalRelations).map(n=>n.id);this.history.reconcile(ids);this.pins.reconcile(ids);const valid=new Set(ids);this.recent=this.recent.filter(id=>valid.has(id));
 }
 private render(){if(this.pendingWorkspace){this.resetInspectors();if(this.inspectorsHost)this.inspectorsHost.hidden=true;this.paint(undefined,undefined);this.centerHost?.createEl('p',{text:'等待原白板加载：'+this.pendingWorkspace.boardPath+'。打开原白板后将自动恢复脑图。'});return;}const focusKey=this.captureFocusKey(),snapshot=this.host.snapshot();this.syncContext(snapshot);
  if(snapshot&&this.follow==='board'&&snapshot.selectedId!==this.selected){this.generation++;if(snapshot.selectedId&&snapshot.board.nodes.some(n=>n.id===snapshot.selectedId&&supportsLocalRelations(n)))this.visit(snapshot.selectedId);this.selected=snapshot.selectedId;}
  if(snapshot&&this.follow==='note'){const source=this.host.activeSource?.();if(source?.id&&source.id!==this.sourceSelected&&snapshot.board.nodes.some(n=>n.id===source.id&&supportsLocalRelations(n))){this.generation++;this.visit(source.id);}this.sourceSelected=source?.id;if(source?.ambiguous&&!source.ids?.includes(this.history.current||''))this.report('同一来源对应多个卡片，请选择中心对象。');}
  this.nativeData=snapshot&&this.history.current?this.host.native?.(this.history.current):undefined;
  const raw=snapshot&&this.history.current?localNeighborhood(snapshot.board,this.history.current,{...this.filters(),pageSize:10,pageByKind:this.pages,nativeRelations:this.nativeData?.relations,tagsByNode:this.nativeData?.tagsByNode}):undefined,neighborhood=raw&&snapshot?this.uniqueNeighborhood(snapshot.board,raw):undefined;
  this.paint(snapshot,neighborhood);this.updateOptions();this.paintPicker();this.paintRecent(snapshot);this.renderInspectors(snapshot,neighborhood);
  this.restoreFocus(focusKey);
  // Complete the new layout and its connectors in the same frame. Scroll-only
  // redraws still use queueLinks and never rebuild the neighborhood.
  if(this.linkFrame)this.linkWindow?.cancelAnimationFrame(this.linkFrame);this.linkFrame=0;this.linkWindow=undefined;this.drawLinks();this.playMotion();
  if(neighborhood?.center&&this.host.companion?.().enabled&&this.syncedCenter!==neighborhood.center.id){this.syncedCenter=neighborhood.center.id;this.invoke('syncSource');}
 }
 private captureSaved():LocalRelationsSavedState{return cleanLocalRelationsState({...this.saved,...this.filters(),version:1,center:this.history.current,history:this.history.snapshot(),pins:this.pins.ids,recent:this.recent,follow:this.follow});}
 getState(){if(this.pendingWorkspace)return{...this.pendingWorkspace};const state:LocalRelationsWorkspaceState={version:1,boardPath:this.boardPath,originLeafId:this.originLeafId,state:this.captureSaved()};return{...state};}
 async setState(raw:unknown,_result?:ViewStateResult){const next=cleanLocalRelationsWorkspaceState(raw);this.restoreEpoch++;if(!next.boardPath)return;this.pendingWorkspace=next;await this.tryRestore();this.refresh();}
 private async tryRestore(){if(this.restoreFlight)return this.restoreFlight;const next=this.pendingWorkspace;if(!next?.boardPath||this.closed)return;const epoch=this.restoreEpoch,doc=this.contentEl.ownerDocument,win=doc.defaultView,current=()=>!this.closed&&epoch===this.restoreEpoch&&this.pendingWorkspace===next&&this.contentEl.ownerDocument===doc&&doc.defaultView===win&&!win?.closed;
  const flight=(async()=>{try{if(this.host.restoreContext&&!await this.host.restoreContext(next.boardPath!,next.originLeafId,current))return;if(!current())return;const snapshot=this.host.snapshot();if(!snapshot||snapshot.path!==next.boardPath)return;this.pendingWorkspace=undefined;this.context=snapshot.key||snapshot.path;this.boardPath=snapshot.path;this.originLeafId=snapshot.originLeafId;this.applySaved(next.state);this.syncContext(snapshot);this.selected=snapshot.selectedId;this.refresh();}catch(error){if(current())this.report(error);}})();this.restoreFlight=flight;try{await flight;}finally{if(this.restoreFlight===flight)this.restoreFlight=undefined;}
 }
 private applySaved(raw:unknown){this.saved=cleanLocalRelationsState(raw);this.history.restore(this.saved.history);if(this.saved.center&&this.history.current!==this.saved.center)this.history.visit(this.saved.center);this.pins.restore(this.saved.pins);this.recent=[...this.saved.recent];this.recentOpen=true;this.follow=this.saved.follow;this.query=this.saved.query;this.filterOpen=false;this.pages={};this.proofPages.clear();if(this.search)this.search.value=this.query;this.lastSaved=JSON.stringify(this.captureSaved());}
 private persist(){if(!this.boardPath||this.pendingWorkspace)return;const state=this.captureSaved(),encoded=JSON.stringify(state);if(encoded===this.lastSaved)return;this.host.saveState?.(this.boardPath,state);this.lastSaved=encoded;this.app.workspace.requestSaveLayout();}
 private filters():LocalRelationsFilter{return{query:this.query,queryField:this.saved.queryField,kindFilter:this.saved.kindFilter,tag:this.saved.tag,kindFilters:[...this.saved.kindFilters]};}
 private visit(id:string){if(id!==this.history.current){this.pages={};this.proofPages.clear();}this.history.visit(id);this.recent=rememberLocalRelation(this.recent,id);this.persist();}
 private setFollow(mode:LocalRelationsFollow){this.generation++;this.follow=mode;this.selected=undefined;this.sourceSelected=undefined;this.persist();this.refresh();}
 private filterChanged(){this.generation++;this.pages={};this.proofPages.clear();this.persist();this.refresh();}
 private showFilter(open:boolean){if(open){this.showMore(false);if(this.pickerOpen){this.pickerOpen=false;this.paintPicker();}}this.filterOpen=open;this.returnDisclosureFocus(this.filterPanel,open,'filter-toggle');if(this.filterPanel)this.filterPanel.hidden=!open;this.toolbar?.querySelector('[data-relation-focus="filter-toggle"]')?.setAttribute('aria-expanded',String(open));this.queueLinks();}
 private showMore(open:boolean){if(open){this.showFilter(false);if(this.pickerOpen){this.pickerOpen=false;this.paintPicker();}}this.moreOpen=open;this.returnDisclosureFocus(this.morePanel,open,'more-toggle');if(this.morePanel)this.morePanel.hidden=!open;this.toolbar?.querySelector('[data-relation-focus="more-toggle"]')?.setAttribute('aria-expanded',String(open));this.queueLinks();}
 private returnDisclosureFocus(panel:HTMLElement|undefined,open:boolean,key:string){if(!open&&panel?.contains(this.contentEl.ownerDocument.activeElement)&&this.alive&&this.visible()&&this.app.workspace.getActiveViewOfType(View)===this)this.toolbar?.querySelector<HTMLElement>(`[data-relation-focus="${key}"]`)?.focus({preventScroll:true});}
 private updateInspectorVisibility(){const heading=!!this.headingDetails?.open&&this.headingTree?.status!=='unsupported',depth=!!this.depthDetails?.open,editing=!!this.relationEditorDetails?.open;if(this.inspectorsHost)this.inspectorsHost.hidden=!heading&&!depth&&!editing;if(this.headingDetails)this.headingDetails.hidden=!heading;if(this.depthDetails)this.depthDetails.hidden=!depth;if(this.relationEditorDetails)this.relationEditorDetails.hidden=!editing;if(this.headingStatus)this.headingStatus.hidden=!heading;}
 private closeInspectors(){this.returnDisclosureFocus(this.inspectorsHost,false,'more-toggle');if(this.relationEditorDetails?.open)this.closeRelationEditor();this.editInspectors(()=>{if(this.headingDetails)this.headingDetails.open=false;if(this.depthDetails)this.depthDetails.open=false;this.paintHeadings();this.paintDepth();this.updateInspectorVisibility();});this.queueLinks();}
 private uniqueNeighborhood(board:Board,value:ReturnType<typeof localNeighborhood>):ReturnType<typeof localNeighborhood>{
  this.visibleRoles.clear();if(!value.center)return value;
  const priority:LocalRelationKind[]=['parents','children','associated','siblings','incoming','outgoing'],placed=new Map<string,LocalRelationKind>();
  for(const kind of priority)for(const item of value.groups.find(group=>group.kind===kind)?.items||[])if(!placed.has(item.id))placed.set(item.id,kind);
  const all=localRelationMatches(board,value.center.id,{nativeRelations:this.nativeData?.relations}),rows=new Map<string,typeof value.groups[number]['items']>();
  for(const group of all.groups)for(const item of group.items)if(placed.has(item.id)){const existing=rows.get(item.id)||[];existing.push(item);rows.set(item.id,existing);const roles=this.visibleRoles.get(item.id)||[];roles.push(group.kind);this.visibleRoles.set(item.id,roles);}
  const groups=value.groups.map(group=>{const items=group.items.filter(item=>placed.get(item.id)===group.kind).map(item=>{const related=rows.get(item.id)||[item],nativeEvidence=[...new Map(related.flatMap(row=>row.nativeEvidence).map(proof=>[proof.id,proof])).values()];return{...item,edgeIds:[...new Set(related.flatMap(row=>row.edgeIds))],labels:[...new Set(related.flatMap(row=>row.labels))],viaParentIds:[...new Set(related.flatMap(row=>row.viaParentIds))],nativeEvidence,nativeEvidenceTotal:nativeEvidence.length};});return{...group,items,shown:items.length};});
  return{...value,groups,shown:groups.reduce((sum,group)=>sum+group.shown,0)};
 }
 private buildInspectors(){
  const host=this.inspectorsHost=this.contentEl.createDiv({cls:'ts-local-relations-inspectors',attr:{'aria-label':'标题与关系工具'}});host.hidden=true;this.button(host,'关闭工具','x','inspectors-close',()=>this.closeInspectors());this.headingStatus=host.createDiv({cls:'ts-local-heading-status',attr:{role:'status','aria-live':'polite'}});
  const headings=this.headingDetails=host.createEl('details',{cls:'ts-local-heading-section'});this.headingSummary=headings.createEl('summary',{text:'笔记标题',attr:{'data-relation-focus':'heading-section'}});const body=headings.createDiv('ts-local-heading-body');this.headingSearch=body.createEl('input',{type:'search',attr:{'aria-label':'筛选原生笔记标题',placeholder:'筛选笔记标题…','data-relation-focus':'heading-search'}});this.headingSearch.oninput=()=>{this.editInspectors(()=>{this.headingQuery=this.headingSearch?.value||'';this.headingPage=0;this.paintHeadings();});};this.headingRows=body.createDiv({cls:'ts-local-heading-rows',attr:{role:'list'}});headings.ontoggle=()=>{if(!this.alive||!this.visible())return;if(!headings.open||!this.headingRows?.childElementCount)this.editInspectors(()=>this.paintHeadings());this.queueLinks();};
  const depth=this.depthDetails=host.createEl('details',{cls:'ts-local-depth-section'});this.depthSummary=depth.createEl('summary',{text:'第二层 · 按邻居展开',attr:{'data-relation-focus':'depth-section'}});this.depthBody=depth.createDiv('ts-local-depth-body');depth.ontoggle=()=>{if(!this.alive||!this.visible())return;if(!depth.open||!this.depthBody?.childElementCount)this.editInspectors(()=>this.paintDepth());this.queueLinks();};this.buildRelationEditor(host);
 }
 /** DOM focus may remain on an old button after Obsidian activates another leaf. */
 private captureFocusKey(){const active=this.contentEl.ownerDocument.activeElement;return this.app.workspace.getActiveViewOfType(View)===this&&active&&this.contentEl.contains(active)?active.getAttribute('data-relation-focus'):null;}
 private focusVisible(element:HTMLElement){for(let parent:HTMLElement|null=element;parent&&parent!==this.contentEl;parent=parent.parentElement){if(parent.hidden)return false;if(parent.tagName==='DETAILS'&&!(parent as HTMLDetailsElement).open&&!Array.from(parent.children).find(child=>child.tagName==='SUMMARY')?.contains(element))return false;}return element.isConnected;}
 private restoreFocus(key:string|null|undefined,fallback?:HTMLElement){if(!key||!this.alive||!this.visible()||this.app.workspace.getActiveViewOfType(View)!==this)return;const doc=this.contentEl.ownerDocument,active=doc.activeElement;if(active&&active!==doc.body&&!this.contentEl.contains(active))return;const next=Array.from(this.contentEl.querySelectorAll<HTMLElement>('[data-relation-focus]')).find(el=>el.dataset.relationFocus===key&&!('disabled'in el&&el.disabled)&&this.focusVisible(el));(next||(fallback&&this.focusVisible(fallback)?fallback:undefined))?.focus({preventScroll:true});}
 private editInspectors(change:()=>void){this.inspectorEpoch++;if(this.pending?.inspector&&!this.pending.allowHidden){this.pending=undefined;if(this.feedback?.textContent==='正在打开…')this.feedback.empty();this.refresh();}const key=this.captureFocusKey();change();this.restoreFocus(key);}
 private inspectorGuard(key:string){const epoch=this.inspectorEpoch;return()=>epoch===this.inspectorEpoch&&Array.from(this.inspectorsHost?.querySelectorAll<HTMLElement>('[data-relation-focus]')||[]).some(el=>{if(el.dataset.relationFocus!==key)return false;for(let parent=el.parentElement;parent&&parent!==this.inspectorsHost;parent=parent.parentElement)if(parent.tagName==='DETAILS'&&!(parent as HTMLDetailsElement).open)return false;return true;});}
 private resetInspectors(){this.inspectorEpoch++;this.resetRelationEditor();this.headingTree=undefined;this.headingQuery='';this.headingPage=0;this.headingCollapsed.clear();if(this.headingSearch)this.headingSearch.value='';if(this.headingDetails)this.headingDetails.open=false;this.headingRows?.empty();this.depthExpanded=[];this.depthPages={};this.depthProofPages.clear();if(this.depthDetails)this.depthDetails.open=false;this.depthBody?.empty();this.inspectorCenter=undefined;this.inspectorContext=undefined;}
 private renderInspectors(snapshot:LocalRelationsSnapshot|undefined,neighborhood:ReturnType<typeof localNeighborhood>|undefined){
  if(!this.inspectorsHost)return;this.inspectorsHost.hidden=!snapshot||!neighborhood?.center;if(!snapshot||!neighborhood?.center){this.resetInspectors();this.lastNeighborhood=undefined;return;}
  if(this.inspectorCenter!==neighborhood.center.id||this.inspectorContext!==this.context){this.resetInspectors();this.inspectorCenter=neighborhood.center.id;this.inspectorContext=this.context;}
  this.lastNeighborhood=neighborhood;this.headingTree=this.host.headings?.(neighborhood.center.id);this.paintHeadings();this.paintDepth();this.paintRelationEditor();this.updateInspectorVisibility();
 }
 private paintHeadings(){
  if(!this.alive||!this.visible())return;const tree=this.headingTree,rows=this.headingRows,details=this.headingDetails,status=this.headingStatus;if(!rows||!details||!status||!this.headingSummary)return;
  const jump=this.secondaryToolbar?.querySelector<HTMLButtonElement>('[data-relation-focus="heading-jump"]');if(jump){jump.disabled=!tree||tree.status==='unsupported';jump.title=tree?.status==='missing'?'笔记标题 · 来源笔记不可用':tree?.status==='pending'?'笔记标题 · 索引尚未就绪':tree?.status==='unsupported'?'标题树仅用于 Markdown 笔记':'笔记标题 · '+(tree?.total||0)+' 项';jump.setAttribute('aria-label',jump.title);}if(!tree){status.hidden=true;details.hidden=true;rows.empty();return;}status.hidden=false;status.setAttribute('data-heading-state',tree.status);details.hidden=tree.status==='unsupported';status.setText((tree.status==='unsupported'?'标题树仅用于 Markdown 笔记':tree.status==='missing'?'来源笔记不可用':tree.status==='pending'?'标题索引尚未就绪':'原生笔记标题')+(tree.sourcePath?' · '+tree.sourcePath:''));status.title=tree.sourcePath||'';this.headingSummary.setText(`笔记标题 · ${tree.total}`);this.headingSummary.setAttribute('aria-label',`原生笔记标题，共 ${tree.total} 项`);
  const ids=new Set(tree.items.map(item=>item.id));this.headingCollapsed=new Set([...this.headingCollapsed].filter(id=>ids.has(id)));if(this.headingSearch)this.headingSearch.disabled=tree.status!=='ready';if(!details.open){rows.empty();return;}rows.empty();
  if(tree.status!=='ready'){rows.createEl('p',{text:tree.status==='missing'?'恢复来源笔记后可继续浏览标题。':'等待 Obsidian 原生标题索引。'});return;}
  const page=localHeadingPage(tree,{query:this.headingQuery,collapsed:this.headingCollapsed,page:this.headingPage,pageSize:30});this.headingPage=page.page;rows.createEl('small',{cls:'ts-local-heading-counts',text:`本页 ${page.shown} · 匹配 ${page.matched} / 共 ${page.total} · 折叠隐藏 ${page.hiddenByCollapse}`});if(!page.shown)rows.createEl('p',{text:tree.total?'没有匹配的标题。':'这篇笔记还没有标题。'});
  for(const item of page.items){const row=rows.createDiv({cls:'ts-local-heading-row',attr:{role:'listitem','data-heading-id':item.id,'data-heading-depth':String(item.depth)}});row.style.paddingInlineStart=`${Math.min(item.depth,5)*12}px`;if(item.childIds.length){const toggle=this.button(row,(this.headingCollapsed.has(item.id)?'展开':'折叠')+'标题 '+item.heading,this.headingCollapsed.has(item.id)?'chevron-right':'chevron-down','heading-toggle:'+item.id,()=>this.editInspectors(()=>{if(this.headingCollapsed.has(item.id))this.headingCollapsed.delete(item.id);else this.headingCollapsed.add(item.id);this.headingPage=0;this.paintHeadings();}));toggle.setAttribute('aria-expanded',String(!this.headingCollapsed.has(item.id)));toggle.disabled=!!this.headingQuery;toggle.title=this.headingQuery?'筛选会显示所有匹配标题；清空筛选后可折叠':'仅折叠此视图中的下级标题';}else row.createSpan({cls:'ts-local-heading-spacer',attr:{'aria-hidden':'true'}});row.createEl('small',{text:'H'+item.level,attr:{'aria-hidden':'true'}});const open=this.button(row,item.heading,'','heading-open:'+item.id,()=>{const current=this.inspectorGuard('heading-open:'+item.id);this.invoke('openHeading',undefined,item.target,()=>this.headingDetails?.open===true&&this.headingTree?.mtime===item.target.mtime&&this.headingTree?.sourcePath===item.target.sourcePath&&current());});open.disabled=!this.host.openHeading;open.setAttribute('aria-label',`打开标题 ${item.heading}，第 ${item.line+1} 行`);open.title=`${tree.sourcePath} · 第 ${item.line+1} 行`;}
  this.pager(rows,'heading-page',page.page,page.pageCount,next=>this.editInspectors(()=>{this.headingPage=next;this.paintHeadings();}),'原生笔记标题');
 }
 private firstPageIds(){const open=new Set(Array.from(this.groupsHost?.querySelectorAll<HTMLDetailsElement>('.ts-local-relations-group')||[]).filter(group=>group.open).map(group=>group.dataset.kind));return[...new Set(this.lastNeighborhood?.groups.filter(group=>open.has(group.kind)).flatMap(group=>group.items.map(item=>item.id))||[])];}
 private toggleDepth(id:string){if(!this.alive||!this.visible()||!this.firstPageIds().includes(id))return;this.editInspectors(()=>{const at=this.depthExpanded.indexOf(id);if(at>=0){this.depthExpanded.splice(at,1);delete this.depthPages[id];}else{if(this.depthExpanded.length>=3){this.report('最多展开 3 个当前已列出的一级邻居，请先收回一个。');return;}this.depthExpanded.push(id);}if(this.depthDetails)this.depthDetails.open=true;this.paintDepth();this.updateInspectorVisibility();this.queueLinks();});}
 private updateDepthButtons(){for(const button of Array.from(this.groupsHost?.querySelectorAll<HTMLButtonElement>('[data-depth-source]')||[])){const expanded=this.depthExpanded.includes(button.dataset.depthSource||'');button.setAttribute('aria-pressed',String(expanded));button.setAttribute('aria-label',expanded?'收回下一层':'展开下一层');button.title=expanded?'收回此邻居的第二层':'只读查看此邻居的下一层关系，最多展开 3 个';const label=Array.from(button.querySelectorAll('span')).at(-1);label?.setText(expanded?'收回下一层':'展开下一层');}}
 private paintDepth(){
  if(!this.alive||!this.visible())return;const body=this.depthBody,details=this.depthDetails,snapshot=this.host.snapshot(),center=this.history.current;if(!body||!details||!this.depthSummary)return;const visible=new Set(this.firstPageIds());const retained=this.depthExpanded.filter(id=>visible.has(id));if(retained.length!==this.depthExpanded.length)this.inspectorEpoch++;this.depthExpanded=retained;this.depthSummary.setText(`第二层 · 已展开 ${this.depthExpanded.length} / 3`);this.updateDepthButtons();if(!details.open){body.empty();return;}if(!snapshot||!center){body.empty();return;}
  const expandedProofs=new Set(Array.from(body.querySelectorAll<HTMLDetailsElement>('[data-depth-proof]')).filter(el=>el.open).map(el=>el.dataset.depthProof));const previousScroll=body.scrollTop;body.empty();if(!this.depthExpanded.length){body.createEl('p',{text:'在当前一级邻居旁点击“展开下一层”。只读展开不会改变中心、历史或原白板。'});return;}
  let indexPending=false;const result=localRelationDepth(snapshot.board,center,this.depthExpanded,{...this.filters(),visibleFirstLayerIds:[...visible],centerNativeRelations:this.nativeData?.relations,tagsByNode:this.nativeData?.tagsByNode,pageBySource:this.depthPages,nativeFor:id=>{const native=this.host.native?.(id);indexPending||=!!native?.pendingPaths?.length;return native?.relations||[];}});this.depthExpanded=result.expandedIds;this.updateDepthButtons();body.createEl('small',{cls:'ts-local-depth-counts',text:`第二层 · ${result.nodes.length} 个新增对象 / 上限 24 · 每个一级邻居每页 8 项；返回已显示对象不重复建节点。`});
  if(indexPending)body.createEl('p',{text:'部分第二层来源索引尚未就绪，原生关系可能暂不完整。'});if(result.invalidBranches)body.createEl('p',{text:'父子结构存在冲突，第二层仍只显示有效普通关系。'});
  const names=new Map(snapshot.board.nodes.map(node=>[node.id,localRelationNode(node).title]));for(const branch of result.branches){const group=body.createDiv({cls:'ts-local-depth-branch',attr:{'data-depth-source-group':branch.source.id}}),header=group.createDiv('ts-local-depth-branch-header');header.createEl('strong',{text:branch.source.title,attr:{title:branch.source.detail}});this.button(header,'收回 '+branch.source.title,'x','depth-remove:'+branch.source.id,()=>this.toggleDepth(branch.source.id));group.createEl('small',{text:`本页 ${branch.shown} · 匹配 ${branch.matched} / 共 ${branch.total}`});if(!branch.matched)group.createEl('small',{text:'没有符合当前筛选的第二层关系。'});for(const item of branch.items.filter(item=>item.placement!=='new')){const b=this.button(group,(item.placement==='center'?'返回中心':'已在第一层')+' · '+item.title,'corner-up-left','depth-return:'+JSON.stringify([branch.source.id,item.id]),()=>this.browse(item.id));b.title=item.detail;}this.pager(group,'depth-page:'+branch.source.id,branch.page,branch.pages,page=>this.editInspectors(()=>{this.depthPages[branch.source.id]=page;this.paintDepth();}),branch.source.title+' 的第二层');}
  const targets=body.createDiv('ts-local-depth-targets');for(const item of result.nodes){const row=targets.createDiv({cls:'ts-local-depth-target',attr:{'data-depth-target':item.id}}),button=this.button(row,item.title,'','depth-target:'+item.id,()=>this.browse(item.id));button.title=item.detail;button.setAttribute('aria-label',item.title+' · '+item.detail);const vias=[...new Set(item.via.map(via=>via.sourceId))];row.createEl('small',{text:(item.shared?'共享对象 · ':'经由 ')+vias.map(id=>names.get(id)||id).join('、')});this.depthProof(row,item,expandedProofs.has(item.id),snapshot);}
  body.scrollTop=previousScroll;
 }
 private depthProof(row:HTMLElement,item:LocalDepthItem,open:boolean,snapshot:LocalRelationsSnapshot){
  const details=row.createEl('details',{cls:'ts-local-depth-proof',attr:{'data-depth-proof':item.id}}),proofs=item.via.flatMap(via=>[...via.edgeIds.map(id=>({sourceId:via.sourceId,kind:via.kind,edgeId:id,native:undefined as NativeLocalEvidence|undefined})),...via.nativeEvidence.map(native=>({sourceId:via.sourceId,kind:via.kind,edgeId:undefined as string|undefined,native}))]);details.open=open;details.createEl('summary',{text:`第二层关系依据 · ${proofs.length} 条`,attr:{'data-relation-focus':'depth-proof:'+item.id}});
  const populate=()=>{if(!details.open||details.dataset.loaded)return;details.dataset.loaded='true';const pages=Math.max(1,Math.ceil(proofs.length/20)),page=Math.min(this.depthProofPages.get(item.id)||0,pages-1);for(const proof of proofs.slice(page*20,(page+1)*20)){const source=snapshot.board.nodes.find(node=>node.id===proof.sourceId),prefix=(source?localRelationNode(source).title:proof.sourceId)+' · '+labels[proof.kind]+'：';if(proof.native){const evidence=proof.native,key='depth-native-evidence:'+JSON.stringify([item.id,proof.sourceId,proof.kind,evidence.id]),button=this.button(details,prefix+(evidence.kind==='property'?'属性 '+(evidence.property||''):evidence.kind==='embed'?'嵌入':evidence.kind==='indexed'?`原生索引链接 · ${evidence.count||1} 次（位置未就绪）`:'原生链接')+' · '+evidence.sourcePath+' → '+evidence.targetPath+(evidence.subpath||''),'file-text',key,()=>{const current=this.inspectorGuard(key);this.invoke('openSource',evidence,undefined,()=>this.depthDetails?.open===true&&current());});button.setAttribute('data-evidence-row','native');button.disabled=!this.host.openEvidence;}else{const edge=snapshot.board.edges.find(edge=>edge.id===proof.edgeId);if(edge)details.createDiv({text:prefix+(edge.kind==='branch'?'本板父子连线':'本板连线')+' · '+edge.from+(edge.direction==='both'?' ↔ ':edge.direction==='none'?' — ':' → ')+edge.to+(edge.label?' · '+edge.label.slice(0,240):''),attr:{'data-evidence-row':'board',title:'连线 '+edge.id}});}}this.pager(details,'depth-proof-page:'+item.id,page,pages,next=>this.editInspectors(()=>{this.depthProofPages.set(item.id,next);this.paintDepth();}),item.title+' 的第二层依据');};details.ontoggle=()=>{if(this.alive&&this.visible()&&details.isConnected){if(!details.open)this.editInspectors(()=>{});populate();}};populate();
 }
 private buildRelationEditor(host:HTMLElement){
  const details=this.relationEditorDetails=host.createEl('details',{cls:'ts-local-relation-editor'});
  details.createEl('summary',{text:'编辑本板关系',attr:{'data-relation-focus':'relation-editor'}});
  const body=details.createDiv('ts-local-relation-editor-body');this.relationEditorCenter=body.createDiv('ts-local-relation-editor-center');body.createEl('small',{text:'只编辑本板连线；原生链接、嵌入与属性引用保持只读。撤销／重做使用白板完整历史，也包括白板上的其他操作。'});
  this.relationEditorStatus=body.createDiv({cls:'ts-local-relation-editor-status',attr:{role:'status','aria-live':'polite'}});
  const tools=body.createDiv('ts-local-relation-editor-actions');this.button(tools,'撤销白板上一步','undo-2','relation-undo',()=>this.applyRelationHistory(false));this.button(tools,'重做白板上一步','redo-2','relation-redo',()=>this.applyRelationHistory(true));this.button(tools,'新建连线','plus','relation-new',()=>this.startRelationDraft());this.button(tools,'关闭编辑面板','x','relation-editor-close',()=>this.closeRelationEditor());
  this.relationEdgeList=body.createDiv('ts-local-relation-edge-list');
  const form=this.relationForm=body.createDiv({cls:'ts-local-relation-form',attr:{'aria-label':'本板连线表单'}});form.hidden=true;
  this.relationTargetLabel=form.createDiv('ts-local-relation-target-label');this.button(form,'更换目标','search','relation-target-change',()=>{this.relationTargetOpen=true;this.paintRelationTargets();this.relationTargetSearch?.focus({preventScroll:true});});
  const target=form.createEl('label',{text:'查找本板目标'});this.relationTargetSearch=target.createEl('input',{type:'search',attr:{'aria-label':'查找本板目标','data-relation-focus':'relation-target-search',placeholder:'名称、路径或对象 ID…'}});this.relationTargetSearch.oninput=()=>{this.relationTargetQuery=this.relationTargetSearch?.value||'';this.relationTargetPage=0;this.paintRelationTargets();};
  this.relationTargetResults=form.createDiv('ts-local-relation-target-results');
  const fields=form.createDiv('ts-local-relation-fields');
  const select=(label:string,key:string,items:readonly(readonly[string,string])[],change:(value:string)=>void)=>{const row=fields.createEl('label',{text:label}),input=row.createEl('select',{attr:{'aria-label':label,'data-relation-focus':key}});for(const[value,text]of items)input.createEl('option',{value,text});input.onchange=()=>{if(!this.relationDraft)return;this.invalidateRelationRequest();change(input.value);this.relationRemoveConfirm=false;this.relationMessage='';this.paintRelationEditor();};return input;};
  this.relationKind=select('关系语义','relation-kind',[['ordinary','普通关联'],['branch','父子关系']],value=>{this.relationDraft!.kind=value==='branch'?'branch':'ordinary';if(value==='branch')this.relationDraft!.direction='forward';});
  this.relationOrientation=select('起点与终点','relation-orientation',[['outgoing','中心 → 目标'],['incoming','目标 → 中心']],value=>this.relationDraft!.orientation=value==='incoming'?'incoming':'outgoing');
  this.relationDirection=select('箭头方向','relation-direction',[['forward','单向 →'],['both','双向 ↔'],['none','无向 —']],value=>this.relationDraft!.direction=value as LocalRelationValue['direction']);
  const label=fields.createEl('label',{text:'连线标签'});this.relationLabel=label.createEl('input',{type:'text',attr:{'aria-label':'连线标签','data-relation-focus':'relation-label',maxlength:'200'}});this.relationLabel.oninput=()=>{if(!this.relationDraft)return;this.invalidateRelationRequest();this.relationDraft.label=this.relationLabel?.value||'';this.relationRemoveConfirm=false;this.relationMessage='';this.paintRelationConfirmation();this.updateRelationEditorState();};
  this.relationKindHint=form.createEl('small');const actions=form.createDiv('ts-local-relation-editor-actions');this.button(actions,'保存连线','check','relation-save',()=>this.submitRelation(false));this.button(actions,'移除这条连线','trash-2','relation-remove',()=>{this.relationRemoveConfirm=true;this.paintRelationConfirmation();});this.button(actions,'取消表单','x','relation-cancel',()=>{this.invalidateRelationRequest();this.relationDraft=undefined;this.relationRemoveConfirm=false;this.relationMessage='';this.paintRelationEditor();});
  this.relationConfirmation=form.createDiv({cls:'ts-local-relation-remove-confirm',attr:{role:'group','aria-label':'确认移除选定本板连线'}});this.relationConfirmation.hidden=true;
  details.ontoggle=()=>{if(!this.alive||!this.visible())return;if(!details.open){if(this.groupsHost?.dataset.relationEditing==='true')this.closeRelationEditor();}else{if(this.groupsHost?.dataset.relationEditing!=='true')this.relationGraphScroll=this.groupsHost?.scrollTop||0;this.paintRelationEditor();}this.queueLinks();};
 }
 private invalidateRelationRequest(){this.relationEditEpoch++;this.relationEditPending=undefined;}
 private resetRelationEditor(){this.invalidateRelationRequest();this.relationDraft=undefined;this.relationMessage='';this.relationRemoveConfirm=false;this.relationEdgePage=0;this.relationTargetPage=0;this.relationTargetQuery='';this.relationTargetOpen=false;this.relationGraphScroll=0;this.groupsHost?.setAttribute('data-relation-editing','false');if(this.relationEditorDetails)this.relationEditorDetails.open=false;}
 private closeRelationEditor(){const scroll=this.relationGraphScroll;this.resetRelationEditor();this.paintRelationEditor();this.updateInspectorVisibility();if(this.groupsHost)this.groupsHost.scrollTop=scroll;this.queueLinks();}
 private openRelationEditor(){if(!this.host.editRelation||!this.relationEditorDetails)return;this.showMore(false);this.relationGraphScroll=this.groupsHost?.scrollTop||0;this.relationEditorDetails.open=true;this.paintRelationEditor();this.updateInspectorVisibility();if(this.groupsHost)this.groupsHost.scrollTop=0;this.relationEditorDetails.scrollIntoView({block:'nearest',inline:'nearest'});this.relationEditorDetails.querySelector<HTMLElement>('summary')?.focus({preventScroll:true});}
 private relationEdgeDescription(edge:Edge,board:Board){const title=(id:string)=>{const node=board.nodes.find(item=>item.id===id);return node?localRelationNode(node).title:'已删除对象';};const arrow=edge.kind==='branch'||!edge.direction||edge.direction==='forward'?' → ':edge.direction==='both'?' ↔ ':' — ';return`${edge.kind==='branch'?'父子关系':'普通关联'} · ${title(edge.from)}${arrow}${title(edge.to)}${edge.label?' · '+edge.label:''}`;}
 private startRelationDraft(edgeId?:string){
  const snapshot=this.host.snapshot(),centerId=this.history.current;if(!snapshot||!centerId||!this.host.editRelation||this.relationEditPending)return;
  if(this.pending?.action==='editCenter'){this.generation++;this.pending=undefined;this.refresh();}
  const edge=edgeId?snapshot.board.edges.find(item=>item.id===edgeId):undefined;if(edgeId&&!edge){this.relationMessage='该连线已被移除，请重新选择。';this.paintRelationEditor();return;}
  this.invalidateRelationRequest();this.relationDraft={baseline:clone(snapshot.board),edgeId,targetId:edge?(edge.from===centerId?edge.to:edge.from):'',orientation:edge?.to===centerId?'incoming':'outgoing',kind:edge?.kind==='branch'?'branch':'ordinary',direction:edge?.direction||'forward',label:edge?.label||''};this.relationRemoveConfirm=false;this.relationMessage='';this.relationTargetQuery='';this.relationTargetPage=0;this.relationTargetOpen=!edge;if(this.relationTargetSearch)this.relationTargetSearch.value='';
  if(this.relationLabel)this.relationLabel.value=this.relationDraft.label;this.paintRelationEditor();(edge?this.relationLabel:this.relationTargetSearch)?.focus({preventScroll:true});
 }
 private relationValue():LocalRelationValue|undefined{const draft=this.relationDraft,center=this.history.current;if(!draft||!center||!draft.targetId)return;return{from:draft.orientation==='outgoing'?center:draft.targetId,to:draft.orientation==='outgoing'?draft.targetId:center,kind:draft.kind,direction:draft.kind==='branch'?'forward':draft.direction,label:draft.label};}
 private relationEndpoints(remove=false){const draft=this.relationDraft,edge=draft?.edgeId?draft.baseline.edges.find(item=>item.id===draft.edgeId):undefined,value=this.relationValue();return[...new Set([...(edge?[edge.from,edge.to]:[]),...(!remove&&value?[value.from,value.to]:[])])];}
 private relationStale(remove=false){const snapshot=this.host.snapshot(),draft=this.relationDraft,ids=this.relationEndpoints(remove);if(!snapshot||!draft||!ids.length)return false;try{const expected=captureLocalRelationEdit(draft.baseline,ids,draft.edgeId),latest=captureLocalRelationEdit(snapshot.board,ids,draft.edgeId);return expected.edge!==latest.edge||Object.keys(expected.nodes).some(id=>expected.nodes[id]!==latest.nodes[id]);}catch{return true;}}
 private relationLocked(remove=false){const ids=new Set(this.relationEndpoints(remove));return!!this.host.snapshot()?.board.nodes.some(node=>ids.has(node.id)&&node.locked);}
 private paintRelationEditor(){
  const details=this.relationEditorDetails,list=this.relationEdgeList,snapshot=this.host.snapshot(),center=this.history.current;if(!details||!list)return;this.updateCenterEditButton();details.hidden=!this.host.editRelation;this.groupsHost?.setAttribute('data-relation-editing',String(!details.hidden&&details.open));if(details.hidden||!details.open){list.empty();if(this.relationForm)this.relationForm.hidden=true;return;}if(!snapshot||!center)return;const centerNode=snapshot.board.nodes.find(node=>node.id===center);if(this.relationEditorCenter){this.relationEditorCenter.empty();if(centerNode){const item=localRelationNode(centerNode);this.relationEditorCenter.createEl('strong',{text:'中心：'+item.title});this.relationEditorCenter.createEl('small',{text:(item.kind==='section'?'分组':item.kind==='board'?'子白板':'笔记卡片')+' · '+item.detail,attr:{title:item.detail}});}}
  const focus=this.captureFocusKey(),eligible=new Set(snapshot.board.nodes.filter(supportsLocalRelations).map(node=>node.id)),edges=snapshot.board.edges.filter(edge=>(edge.from===center||edge.to===center)&&eligible.has(edge.from)&&eligible.has(edge.to));list.hidden=!!this.relationDraft;list.empty();const pages=Math.max(1,Math.ceil(edges.length/8));this.relationEdgePage=Math.min(this.relationEdgePage,pages-1);list.createEl('small',{text:`本板具体连线 ${edges.length} 条 · 每页 8 条；平行连线按 ID 分别编辑。`});
  for(const edge of edges.slice(this.relationEdgePage*8,(this.relationEdgePage+1)*8)){const row=list.createDiv({attr:{'data-edit-edge':edge.id}}),button=this.button(row,this.relationEdgeDescription(edge,snapshot.board),'','relation-edge:'+JSON.stringify(edge.id),()=>this.startRelationDraft(edge.id));button.disabled=!!this.relationEditPending;button.title='连线 '+edge.id+' · '+edge.from+' → '+edge.to;button.setAttribute('aria-label',this.relationEdgeDescription(edge,snapshot.board)+' · 连线 ID '+edge.id);row.createEl('small',{text:'连线 · '+edge.id,attr:{title:edge.id}});}
  if(!edges.length)list.createEl('p',{text:'当前中心没有可编辑的本板连线。原生引用可在关系依据中查看。'});this.pager(list,'relation-edge-page',this.relationEdgePage,pages,page=>{this.relationEdgePage=page;this.paintRelationEditor();},'本板具体连线');
  if(this.relationForm)this.relationForm.hidden=!this.relationDraft;if(this.relationDraft){if(this.relationKind)this.relationKind.value=this.relationDraft.kind;if(this.relationOrientation)this.relationOrientation.value=this.relationDraft.orientation;if(this.relationDirection)this.relationDirection.value=this.relationDraft.kind==='branch'?'forward':this.relationDraft.direction;this.paintRelationTargets();this.paintRelationConfirmation();}this.updateRelationEditorState();this.restoreFocus(focus);
 }
 private paintRelationTargets(){
  const host=this.relationTargetResults,snapshot=this.host.snapshot(),draft=this.relationDraft,center=this.history.current;if(!host||!snapshot||!draft||!center)return;host.empty();const selected=snapshot.board.nodes.find(node=>node.id===draft.targetId);this.relationTargetLabel?.setText(selected?'目标：'+localRelationNode(selected).title+' · '+localRelationNode(selected).detail:draft.targetId?'目标已被移除，请重新选择。':'请选择本板目标对象。');
  const choosing=!draft.targetId||this.relationTargetOpen;if(this.relationTargetSearch?.parentElement)this.relationTargetSearch.parentElement.hidden=!choosing;host.hidden=!choosing;const change=this.relationForm?.querySelector<HTMLButtonElement>('[data-relation-focus="relation-target-change"]');if(change){change.hidden=choosing;change.disabled=!!this.relationEditPending;}
  const result=searchLocalCenters({...snapshot.board,nodes:snapshot.board.nodes.filter(node=>node.id!==center&&supportsLocalRelations(node))},this.relationTargetQuery,{page:this.relationTargetPage,pageSize:8});this.relationTargetPage=result.page;
  for(const item of result.items){const button=this.button(host,item.title,'','relation-target:'+JSON.stringify(item.id),()=>{if(!this.relationDraft)return;this.invalidateRelationRequest();this.relationDraft.targetId=item.id;this.relationTargetOpen=false;this.relationMessage='';this.relationRemoveConfirm=false;this.paintRelationEditor();});button.title=item.detail;button.setAttribute('aria-label',item.title+' · '+item.detail);button.setAttribute('aria-pressed',String(item.id===draft.targetId));button.disabled=!!this.relationEditPending;}
  if(!result.matched)host.createEl('small',{text:'没有匹配的笔记卡片、子白板或分组。'});this.pager(host,'relation-target-page',result.page,result.pages,page=>{this.relationTargetPage=page;this.paintRelationTargets();},'本板连线目标');
 }
 private paintRelationConfirmation(){const host=this.relationConfirmation,draft=this.relationDraft;if(!host)return;host.empty();host.hidden=!this.relationRemoveConfirm||!draft?.edgeId;if(host.hidden||!draft?.edgeId)return;const edge=draft.baseline.edges.find(item=>item.id===draft.edgeId);if(!edge)return;host.createEl('p',{text:'确认仅移除这一条本板连线？未保存的表单修改不会提交；笔记、卡片和原生引用不会删除。'});host.createEl('p',{text:this.relationEdgeDescription(edge,draft.baseline)});host.createEl('small',{text:'连线 ID：'+edge.id});this.button(host,'确认移除这条连线','trash-2','relation-remove-confirm',()=>this.submitRelation(true));this.button(host,'保留连线','x','relation-remove-cancel',()=>{this.relationRemoveConfirm=false;this.paintRelationConfirmation();});this.updateRelationEditorState();}
 private updateRelationEditorState(){
  const details=this.relationEditorDetails,draft=this.relationDraft;if(!details)return;const availability=this.host.relationEditing?.()||{available:!!this.host.editRelation},pending=!!this.relationEditPending,stale=this.relationStale(),value=this.relationValue(),locked=this.relationLocked(),blocked=!availability.available||pending||stale||locked,removeBlocked=!availability.available||pending||this.relationStale(true)||this.relationLocked(true);
  const message=pending?this.relationPendingLabel:[this.relationMessage,!availability.available?availability.reason||'当前白板暂时不能编辑关系。':!this.relationMessage?(locked?'关系端点已锁定，请先在白板解锁。':stale?'连线或端点已变化，请取消表单后重新编辑。':''):''].filter(Boolean).join(' · ');this.relationEditorStatus?.setText(message);this.relationKindHint?.setText(draft?.kind==='branch'?'父子关系使用单向箭头：起点为父节点，终点为子节点；不允许循环或多个父节点。':'普通关联不会改变父子层级。');
  for(const input of [this.relationTargetSearch,this.relationKind,this.relationOrientation,this.relationDirection,this.relationLabel])if(input)input.disabled=pending||!availability.available;if(this.relationDirection&&draft?.kind==='branch')this.relationDirection.disabled=true;
  const control=(key:string)=>Array.from(details.querySelectorAll<HTMLButtonElement>('[data-relation-focus]')).find(button=>button.dataset.relationFocus===key);
  for(const [key,enabled]of [['relation-undo',availability.canUndo],['relation-redo',availability.canRedo]] as const){const button=control(key);if(button){button.hidden=!this.host.historyRelation;button.disabled=!enabled||!!draft||pending||!availability.available;}}
  const save=control('relation-save');if(save)save.disabled=blocked||!value;const remove=control('relation-remove');if(remove){remove.hidden=!draft?.edgeId;remove.disabled=removeBlocked||!draft?.edgeId;}const confirm=control('relation-remove-confirm');if(confirm)confirm.disabled=removeBlocked||!draft?.edgeId;const create=control('relation-new');if(create)create.disabled=pending||!availability.available;const close=control('relation-editor-close');if(close)close.title=pending?'关闭不取消已提交更改，可在白板撤销；撤销使用全板历史。':'关闭编辑面板，不提交表单。';
 }
 private async applyRelationHistory(redo:boolean){
  const snapshot=this.host.snapshot(),doc=this.contentEl.ownerDocument,win=doc.defaultView;if(!snapshot||!win||win.closed||!this.host.historyRelation||this.relationDraft||this.relationEditPending)return;const availability=this.host.relationEditing?.();if(availability?.available===false||!(redo?availability?.canRedo:availability?.canUndo))return;
  const epoch=++this.relationEditEpoch,generation=this.generation,key=snapshot.key||snapshot.path,token=Symbol('relation-history');this.relationEditPending=token;this.relationPendingLabel=redo?'正在重做白板上一步…':'正在撤销白板上一步…';this.relationMessage='';this.paintRelationEditor();
  const current=()=>this.alive&&this.visible()&&this.relationEditorDetails?.open===true&&!this.relationDraft&&this.relationEditPending===token&&this.relationEditEpoch===epoch&&this.generation===generation&&this.contentEl.ownerDocument===doc&&doc.defaultView===win&&!win.closed&&this.app.workspace.getActiveViewOfType(View)===this&&(this.host.snapshot()?.key||this.host.snapshot()?.path)===key;
  try{const result=await this.host.historyRelation(redo,current);if(current())this.relationMessage=result.changed?(redo?'已重做白板上一步。':'已撤销白板上一步。'):'白板历史没有变化。';}catch(error){if(current()){const committed=typeof error==='object'&&error!==null&&'committed'in error&&error.committed===true;this.relationMessage=(error instanceof Error?error.message:String(error))+(committed?'；操作已应用到白板内存，保存尚未完成。':'');}}finally{if(this.relationEditPending===token){this.relationEditPending=undefined;this.paintRelationEditor();this.refresh();}}
 }
 private async submitRelation(remove:boolean){
  const snapshot=this.host.snapshot(),draft=this.relationDraft,center=this.history.current,value=this.relationValue(),doc=this.contentEl.ownerDocument,win=doc.defaultView;if(!snapshot||!draft||!center||!remove&&!value||!win||win.closed||!this.host.editRelation||this.relationEditPending||remove&&(!draft.edgeId||!this.relationRemoveConfirm))return;
  let command:LocalRelationMutation;try{const expected=captureLocalRelationEdit(draft.baseline,this.relationEndpoints(remove),draft.edgeId);command=remove?{action:'remove',centerId:center,edgeId:draft.edgeId!,expected}:draft.edgeId?{action:'update',centerId:center,edgeId:draft.edgeId,value:value!,expected}:{action:'create',centerId:center,value:value!,expected};}catch(error){this.relationMessage=error instanceof Error?error.message:String(error);this.updateRelationEditorState();return;}
  const epoch=++this.relationEditEpoch,generation=this.generation,key=snapshot.key||snapshot.path,token=Symbol('relation-edit');this.relationEditPending=token;this.relationPendingLabel='正在提交本板关系…';this.relationMessage='';this.paintRelationEditor();
  const current=()=>this.alive&&this.visible()&&this.relationEditorDetails?.open===true&&this.relationDraft===draft&&this.relationEditPending===token&&this.relationEditEpoch===epoch&&this.generation===generation&&this.history.current===center&&this.contentEl.ownerDocument===doc&&doc.defaultView===win&&!win.closed&&this.app.workspace.getActiveViewOfType(View)===this&&(this.host.snapshot()?.key||this.host.snapshot()?.path)===key;
  try{const result=await this.host.editRelation(command,current);if(!current())return;this.relationDraft=undefined;this.relationRemoveConfirm=false;this.relationMessage=result.changed?'本板关系已更新，可在白板撤销。':'连线没有变化。';}catch(error){if(!current())return;const committed=typeof error==='object'&&error!==null&&'committed'in error&&error.committed===true;this.relationMessage=(error instanceof Error?error.message:String(error))+(committed?'；操作已应用到白板内存，保存尚未完成。':'');if(committed){this.relationDraft=undefined;this.relationRemoveConfirm=false;}}finally{if(this.relationEditPending===token){this.relationEditPending=undefined;this.paintRelationEditor();this.refresh();}}
 }
 private buildOptions(){
  const host=this.optionsHost;if(!host)return;host.createEl('summary',{text:'筛选与显示'});const body=host.createDiv({cls:'ts-local-relations-options-body',attr:{role:'group','aria-label':'筛选与显示选项',tabindex:'0'}}),controls=body.createDiv('ts-local-relations-controls');
  const select=(name:string,key:string,values:readonly (readonly [string,string])[],change:(value:string)=>void)=>{const label=controls.createEl('label',{text:name}),el=label.createEl('select',{attr:{'aria-label':name,'data-relation-focus':key}});for(const [value,text]of values)el.createEl('option',{value,text});el.onchange=()=>change(el.value);return el;};
  select('搜索范围','query-field',[['all','全部字段'],['name','名称'],['tag','标签'],['type','对象类型']],value=>{this.saved.queryField=value as LocalRelationsSavedState['queryField'];this.filterChanged();});
  select('对象类型','node-kind',[['all','全部对象'],['card','笔记卡片'],['board','子白板'],['section','分组']],value=>{this.saved.kindFilter=value as LocalRelationsSavedState['kindFilter'];this.filterChanged();});
  select('密度','density',[['compact','紧凑'],['comfortable','舒适']],value=>{this.saved.settings.density=value==='comfortable'?'comfortable':'compact';this.persist();this.refresh();});
  const paths=controls.createEl('label',{text:'显示来源路径'}),pathCheck=paths.createEl('input',{type:'checkbox',attr:{'data-relation-focus':'show-paths'}});pathCheck.onchange=()=>{this.saved.settings.showPaths=pathCheck.checked;this.persist();this.refresh();};
  const kinds=body.createDiv({cls:'ts-local-relations-kind-filters',attr:{'aria-label':'显示的关系类别'}});for(const kind of localRelationKinds){const label=kinds.createEl('label',{text:labels[kind]}),box=label.createEl('input',{type:'checkbox',attr:{'data-relation-focus':'kind:'+kind}});box.onchange=()=>{this.saved.kindFilters=box.checked?[...new Set([...this.saved.kindFilters,kind])]:this.saved.kindFilters.filter(value=>value!==kind);this.filterChanged();};}
  const lenses=body.createDiv('ts-local-relations-lenses'),choose=lenses.createEl('select',{attr:{'aria-label':'已保存筛选','data-relation-focus':'lens-select'}});choose.onchange=()=>{const lens=this.saved.lenses.find(item=>item.name===choose.value);if(!lens)return;Object.assign(this.saved,{queryField:lens.queryField,kindFilter:lens.kindFilter,tag:lens.tag,kindFilters:[...lens.kindFilters]});this.query=lens.query;if(this.search)this.search.value=this.query;this.filterChanged();};
  const name=lenses.createEl('input',{type:'text',attr:{placeholder:'筛选名称（最多 8 个）','aria-label':'筛选名称','data-relation-focus':'lens-name',maxlength:'80'}});
  this.button(lenses,'保存筛选','bookmark-plus','lens-save',()=>{const title=name.value.trim().slice(0,80);if(!title){this.report('请填写筛选名称。');name.focus();return;}const at=this.saved.lenses.findIndex(lens=>lens.name===title);if(at<0&&this.saved.lenses.length>=8){this.report('最多保存 8 个筛选，请先删除一个。');return;}const lens={name:title,...this.filters()};if(at<0)this.saved.lenses.push(lens);else this.saved.lenses[at]=lens;this.persist();this.updateOptions();choose.value=title;this.report('筛选已保存。');});
  this.button(lenses,'删除筛选','trash-2','lens-delete',()=>{if(!choose.value)return;this.saved.lenses=this.saved.lenses.filter(lens=>lens.name!==choose.value);this.persist();this.updateOptions();});
 }
 private updateOptions(){const host=this.optionsHost;if(!host)return;const field=<T extends HTMLElement>(key:string)=>host.querySelector<T>(`[data-relation-focus="${key}"]`);const query=field<HTMLSelectElement>('query-field');if(query)query.value=this.saved.queryField;const kind=field<HTMLSelectElement>('node-kind');if(kind)kind.value=this.saved.kindFilter;const density=field<HTMLSelectElement>('density');if(density)density.value=this.saved.settings.density;const paths=field<HTMLInputElement>('show-paths');if(paths)paths.checked=this.saved.settings.showPaths;for(const kind of localRelationKinds){const box=field<HTMLInputElement>('kind:'+kind);if(box)box.checked=this.saved.kindFilters.includes(kind);}const lenses=field<HTMLSelectElement>('lens-select');if(lenses){const value=lenses.value;lenses.empty();lenses.createEl('option',{value:'',text:'已保存筛选'});for(const lens of this.saved.lenses)lenses.createEl('option',{value:lens.name,text:lens.name});lenses.value=this.saved.lenses.some(lens=>lens.name===value)?value:'';}this.contentEl.setAttribute('data-density',this.saved.settings.density);this.contentEl.setAttribute('data-show-paths',String(this.saved.settings.showPaths));}
 private togglePicker(){this.pickerOpen=!this.pickerOpen;if(this.pickerOpen){this.showFilter(false);this.showMore(false);}this.paintPicker();if(this.pickerOpen)this.pickerSearch?.focus();}
 private paintPicker(){const host=this.pickerHost;if(!host)return;host.hidden=!this.pickerOpen;if(this.search)this.search.hidden=this.pickerOpen;this.toolbar?.querySelector('[data-relation-focus="center-picker-toggle"]')?.setAttribute('aria-expanded',String(this.pickerOpen));if(!this.pickerOpen)return;if(!this.pickerSearch){host.createEl('small',{text:'选择本板中心 · 包括没有连线的笔记卡片、子白板和分组'});this.pickerSearch=host.createEl('input',{type:'search',attr:{'aria-label':'查找本板中心','data-relation-focus':'center-picker-search',placeholder:'搜索本板对象名称、路径…'}});this.pickerSearch.oninput=()=>{this.pickerQuery=this.pickerSearch?.value||'';this.pickerPage=0;this.paintPicker();};this.pickerResults=host.createDiv('ts-local-relations-center-results');}const results=this.pickerResults,snapshot=this.host.snapshot();if(!results)return;results.empty();if(!snapshot){results.createEl('small',{text:'原白板尚未打开。'});return;}const found=searchLocalCenters(snapshot.board,this.pickerQuery,{page:this.pickerPage,pageSize:12,tagsByNode:this.nativeData?.tagsByNode});this.pickerPage=found.page;results.createEl('small',{text:`本板对象 ${found.matched} / ${found.total} · 第 ${found.page+1} / ${found.pages} 页`});for(const item of found.items){const b=this.button(results,item.title,'','center-result:'+item.id,()=>{this.pickerOpen=false;this.browse(item.id);this.paintPicker();});b.title=item.detail;b.createEl('small',{text:item.path||(item.kind==='section'?'分组':item.kind==='board'?'子白板':'笔记卡片')});}if(!found.matched)results.createEl('p',{text:'没有匹配的本板对象。'});this.pager(results,'center-page',found.page,found.pages,page=>{this.pickerPage=page;this.paintPicker();},'本板中心搜索');}
 private navigateResults(event:KeyboardEvent){if(event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||!['ArrowDown','ArrowUp','Enter'].includes(event.key))return false;const doc=this.contentEl.ownerDocument,active=doc.activeElement,picker=this.pickerOpen&&(active===this.pickerSearch||!!(active&&this.pickerResults?.contains(active))),input=picker?this.pickerSearch:this.search,container=picker?this.pickerResults:this.groupsHost;if(!container)return false;const results=Array.from(container.querySelectorAll<HTMLButtonElement>('button')).filter(button=>!button.disabled&&(picker?button.dataset.relationFocus?.startsWith('center-result:'):!!button.dataset.relationKind)&&button.closest<HTMLDetailsElement>('details')?.open!==false&&button.getClientRects().length>0);if(!picker)results.sort((a,b)=>localRelationKinds.indexOf(a.dataset.relationKind as LocalRelationKind)-localRelationKinds.indexOf(b.dataset.relationKind as LocalRelationKind));if(active!==input&&!results.includes(active as HTMLButtonElement))return false;if(event.key==='Enter'){if(active!==input||!results.length)return false;event.preventDefault();event.stopPropagation();results[0].click();return true;}if(!results.length)return false;event.preventDefault();event.stopPropagation();const at=results.indexOf(active as HTMLButtonElement),next=at<0?(event.key==='ArrowDown'?0:results.length-1):Math.max(0,Math.min(results.length-1,at+(event.key==='ArrowDown'?1:-1)));results[next].focus({preventScroll:true});results[next].scrollIntoView({block:'nearest',inline:'nearest'});return true;}
 private pager(host:HTMLElement,key:string,page:number,pages:number,change:(page:number)=>void,context='关系结果'){if(pages<=1)return;const row=host.createEl('nav',{cls:'ts-local-relations-pager',attr:{'aria-label':context+'分页'}}),previous=this.button(row,context+'：上一页','chevron-left',key+':previous',()=>change(page-1));previous.disabled=page===0;row.createSpan({text:`${page+1} / ${pages}`});const next=this.button(row,context+'：下一页','chevron-right',key+':next',()=>change(page+1));next.disabled=page+1>=pages;}
 private paintRecent(snapshot:LocalRelationsSnapshot|undefined){if(!this.recentHost)return;const nodes=displayLocalRelationRecent(this.recent).flatMap(id=>{const node=snapshot?.board.nodes.find(node=>node.id===id&&supportsLocalRelations(node));return node?[node]:[];}),open=this.recentOpen&&nodes.length>0;this.returnDisclosureFocus(this.recentHost,open,'more-toggle');this.recentHost.hidden=!open;this.recentHost.setAttribute('aria-label','最近浏览，与前进后退历史独立');const context=snapshot?.key||snapshot?.path,same=this.recentPaintedCenter===this.history.current&&this.recentContext===context,scroll=same?this.recentHost.querySelector<HTMLElement>('.ts-local-relations-recent-list')?.scrollLeft||0:0;this.recentPaintedCenter=this.history.current;this.recentContext=context;this.recentHost.empty();if(!snapshot||!nodes.length)return;const list=this.recentHost.createDiv('ts-local-relations-recent-list');for(const node of nodes){const item=localRelationNode(node),button=this.button(list,item.title,'','recent:'+node.id,()=>this.browse(node.id));button.title=item.detail;button.setAttribute('aria-label',item.title+' · '+item.detail);button.setAttribute('aria-current',String(node.id===this.history.current));}list.scrollLeft=scroll;this.button(this.recentHost,'收起最近浏览','x','recent-close',()=>{this.recentOpen=false;this.paintRecent(this.host.snapshot());});}
 private evidenceGuard(key:string,nativeKey:string,kind:LocalRelationKind){const epoch=this.proofEpochs.get(key)||0,groupPage=this.pages[kind]||0,proofPage=this.proofPages.get(key)||0;return()=>{if((this.proofEpochs.get(key)||0)!==epoch||(this.pages[kind]||0)!==groupPage||(this.proofPages.get(key)||0)!==proofPage)return false;const proof=Array.from(this.groupsHost?.querySelectorAll<HTMLDetailsElement>('[data-relation-evidence]')||[]).find(el=>el.dataset.relationEvidence===key),group=proof?.closest<HTMLDetailsElement>('.ts-local-relations-group');return !!(proof?.isConnected&&proof.open&&group?.open&&group.dataset.kind===kind&&Array.from(proof.querySelectorAll<HTMLElement>('[data-relation-focus]')).some(el=>el.dataset.relationFocus===nativeKey));};}
 private closeEvidence(key:string){this.proofEpochs.set(key,(this.proofEpochs.get(key)||0)+1);}
 private button(parent:HTMLElement,label:string,icon:string,key:string,run:()=>unknown){const b=parent.createEl('button',{attr:{'aria-label':label,title:label,'data-relation-focus':key}});if(icon)setIcon(b.createSpan(),icon);b.createSpan({text:label});b.onclick=()=>{if(!this.alive||!b.isConnected||b.disabled)return;try{void Promise.resolve(run()).catch(error=>this.report(error));}catch(error){this.report(error);}};return b;}
 private report(error:unknown){if(this.alive&&this.feedback)this.feedback.setText(error instanceof Error?error.message:String(error));}
 private browse(id:string){this.setContext(id);}
 private travel(forward:boolean){this.generation++;if(forward)this.history.forward();else this.history.back();this.pages={};this.proofPages.clear();if(this.history.current)this.recent=rememberLocalRelation(this.recent,this.history.current);this.selected=this.host.snapshot()?.selectedId;this.persist();this.refresh();}
 private togglePin(id:string){if(!this.host.snapshot()?.board.nodes.some(node=>node.id===id&&supportsLocalRelations(node)))return;const outcome=this.pins.toggle(id);if(outcome==='full')this.report('最多固定 6 个对象，请先取消一个固定。');else if(this.feedback)this.feedback.empty();this.persist();this.refresh();}
 private updateCenterEditButton(source?:LocalRelationsSource){
  if(!this.host.editCenter)return;const button=this.footer?.querySelector<HTMLButtonElement>('[data-relation-focus="edit-source"]');if(!button)return;const id=this.history.current,node=this.host.snapshot()?.board.nodes.find(node=>node.id===id);source??=id?this.host.source?.(id):undefined;const hasDraft=!!this.relationDraft||!!this.relationEditPending,available=node?.kind==='card'&&!!source?.available&&source.canEdit!==false;button.disabled=!available||hasDraft||this.pending?.id===id;button.title=hasDraft?'请先保存或取消本板关系表单，再进入编辑模式。':source?.editReason||(!available?'此对象不支持原生笔记编辑。':'原生笔记自动保存；返回脑图不会撤销笔记修改。');
 }
 private invoke(action:'locate'|'openSource'|'explain'|'returnToBoard'|'editSource'|'editCenter'|'syncSource'|'openHeading',evidence?:NativeLocalEvidence,heading?:LocalHeadingTarget,available?:()=>boolean){
  if(action==='editCenter'&&(this.relationDraft||this.relationEditPending)){this.report('请先保存或取消本板关系表单，再进入编辑模式。');return;}
  const id=this.history.current,snapshot=this.host.snapshot(),doc=this.contentEl.ownerDocument,win=doc.defaultView,generation=this.generation;
  if((!id&&action!=='returnToBoard')||!snapshot||!win||win.closed||(action!=='returnToBoard'&&this.pending?.id===id))return;
  const navigation=action==='locate'||action==='returnToBoard',key=snapshot.key||snapshot.path,token=Symbol('relation-action');let committed=navigation;
  const current=(allowHidden=false)=>{const latest=this.host.snapshot();if((action==='editCenter'&&(this.relationDraft||this.relationEditPending))||(available&&!available())||!this.alive||generation!==this.generation||this.history.current!==id||this.contentEl.ownerDocument!==doc||doc.defaultView!==win||win.closed||!latest||(latest.key||latest.path)!==key||(id&&!latest.board.nodes.some(n=>n.id===id&&supportsLocalRelations(n))))return false;
   if(allowHidden&&!committed){if(!this.visible())return false;committed=true;if(this.pending?.token===token)this.pending.allowHidden=true;}return committed||this.visible();};
  if(!current())return;if(id&&action!=='returnToBoard'){this.pending={id,token,allowHidden:navigation,action,inspector:!!available};this.feedback?.setText(action==='syncSource'?'正在同步伙伴页…':'正在打开…');this.footer?.querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.disabled=true);const sourceButton=this.centerHost?.querySelector<HTMLButtonElement>('[data-relation-focus="source"]');if(sourceButton)sourceButton.disabled=true;}
  const done=()=>{if(this.pending?.token===token){this.pending=undefined;if(this.feedback?.textContent==='正在打开…'||this.feedback?.textContent==='正在同步伙伴页…')this.feedback.empty();this.refresh();}};
  try{const result=heading&&id?this.host.openHeading?.(id,heading,current):evidence?this.host.openEvidence?.(evidence,current):action==='returnToBoard'?this.host.returnToBoard?.(current):id&&action!=='openHeading'?this.host[action]?.(id,current):undefined;void Promise.resolve(result).catch(error=>{if(current())this.report(error);}).finally(done);}catch(error){if(current())this.report(error);done();}
 }
 private queueLinks(){const win=this.contentEl.ownerDocument.defaultView;if(this.linkFrame&&this.linkWindow!==win){this.linkWindow?.cancelAnimationFrame(this.linkFrame);this.linkFrame=0;this.linkWindow=undefined;}if(!this.alive||!this.visible()||this.linkFrame||!win||win.closed)return;this.linkWindow=win;const frame=win.requestAnimationFrame(()=>{if(this.linkWindow!==win||this.linkFrame!==frame)return;this.linkFrame=0;this.linkWindow=undefined;if(this.contentEl.ownerDocument.defaultView===win)this.drawLinks();});this.linkFrame=frame;}
 private playMotion(){const root=this.groupsHost,snapshot=this.motionSnapshot;this.motionSnapshot=undefined;if(!root||!snapshot)return;const epoch=this.motionEpoch,doc=this.contentEl.ownerDocument,win=doc.defaultView,id=this.history.current,generation=this.generation;this.motionActive=true;this.motionWindow=win||undefined;root.setAttribute('data-relation-transitioning','true');this.motion.play(root,snapshot,()=>{if(epoch!==this.motionEpoch||!this.alive||!this.visible()||this.contentEl.ownerDocument!==doc||doc.defaultView!==win||win?.closed||generation!==this.generation||id!==this.history.current)return;this.motionActive=false;this.motionWindow=undefined;root.setAttribute('data-relation-transitioning','false');this.drawLinks();});}
 private drawLinks(){
  if(this.motionActive)return;
  const host=this.groupsHost,center=this.centerHost?.querySelector<HTMLElement>('h3')||this.centerHost;if(!this.alive||!this.visible()||!host||!center||!center.isConnected)return;
  host.querySelector('.ts-local-relations-lines')?.remove();
  const svg=host.createSvg('svg',{cls:'ts-local-relations-lines',attr:{'aria-hidden':'true'}}),box=host.getBoundingClientRect(),origin=center.getBoundingClientRect(),width=Math.max(host.scrollWidth,host.clientWidth),height=Math.max(host.scrollHeight,host.clientHeight);
  svg.setAttribute('width',String(width));svg.setAttribute('height',String(height));svg.setAttribute('viewBox',`0 0 ${width} ${height}`);
  const narrow=host.ownerDocument.defaultView?.getComputedStyle(host).getPropertyValue('--ts-relations-wide')!=='1',cx=origin.left-box.left+host.scrollLeft+origin.width/2,cy=origin.top-box.top+host.scrollTop+origin.height/2;
  for(const button of Array.from(host.querySelectorAll<HTMLElement>('[data-relation-kind]'))){
   if(button.closest<HTMLDetailsElement>('.ts-local-relations-group')?.open===false||!button.getClientRects().length)continue;const rect=button.getBoundingClientRect(),list=button.closest<HTMLElement>('.ts-local-relations-neighbors')?.getBoundingClientRect(),section=button.closest<HTMLElement>('.ts-local-relations-group')?.getBoundingClientRect();
   // Nested group scrolling must not draw a fan toward rows outside the viewport.
   const left=Math.max(rect.left,list?.left??box.left,section?.left??box.left,box.left),right=Math.min(rect.right,list?.right??box.right,section?.right??box.right,box.right),top=Math.max(rect.top,list?.top??box.top,section?.top??box.top,box.top),bottom=Math.min(rect.bottom,list?.bottom??box.bottom,section?.bottom??box.bottom,box.bottom);
   if(right<=left||bottom<=top)continue;const visibleWidth=right-left,visibleHeight=bottom-top,x=left-box.left+host.scrollLeft+visibleWidth/2,y=top-box.top+host.scrollTop+visibleHeight/2,kind=button.dataset.relationKind,vertical=!narrow&&(kind==='parents'||kind==='children'),side=narrow||kind==='incoming'||kind==='associated'?-1:1,sx=vertical?cx:cx+side*origin.width/2,sy=vertical?cy+(kind==='parents'?-1:1)*origin.height/2:cy,tx=narrow?x-visibleWidth/2:vertical?x:x-side*visibleWidth/2,ty=vertical?y+(kind==='parents'?1:-1)*visibleHeight/2:y;
   const path=svg.createSvg('path',{attr:{d:vertical?`M ${sx} ${sy} C ${sx} ${(sy+ty)/2}, ${tx} ${(sy+ty)/2}, ${tx} ${ty}`:narrow?`M ${sx} ${sy} H ${side<0?3:width-3} V ${ty} H ${tx}`:`M ${sx} ${sy} C ${(sx+tx)/2} ${sy}, ${(sx+tx)/2} ${ty}, ${tx} ${ty}`,'data-kind':kind||''}});
   if(kind==='siblings')path.setAttribute('stroke-dasharray','3 4');for(const [x,y]of [[sx,sy],[tx,ty]])svg.createSvg('circle',{cls:'ts-local-relations-port-dot',attr:{cx:String(x),cy:String(y),r:'2.5','data-relation-dot':kind||''}});
   if(kind!=='associated'&&kind!=='siblings'){const reverse=kind==='parents'||kind==='incoming',ax=reverse?sx:tx,ay=reverse?sy:ty,sign=reverse?-1:1,ux=narrow?1:vertical?0:side*sign,uy=vertical?(kind==='parents'?-1:1)*sign:0;svg.createSvg('path',{cls:'ts-local-relations-arrow',attr:{d:`M ${ax-ux*7-uy*4} ${ay-uy*7+ux*4} L ${ax} ${ay} L ${ax-ux*7+uy*4} ${ay-uy*7-ux*4}`}});}
  }
 }
 private paint(snapshot:LocalRelationsSnapshot|undefined,neighborhood:ReturnType<typeof localNeighborhood>|undefined){
  if(!this.toolbar||!this.toolbarNavigation||!this.toolbarTools||!this.secondaryToolbar||!this.centerHost||!this.pinHost||!this.groupsHost||!this.counts||!this.footer)return;
  const sameCenter=this.paintedCenter===neighborhood?.center?.id,key=this.captureFocusKey(),scroll=sameCenter?this.groupsHost.scrollTop:0;this.motionEpoch++;this.motionSnapshot=this.paintedCenter&&neighborhood?.center&&!sameCenter?this.motion.capture(this.groupsHost):undefined;if(!this.motionSnapshot)this.motion.cancel();this.motionActive=false;this.motionWindow=undefined;this.groupsHost.setAttribute('data-relation-transitioning','false');this.paintedCenter=neighborhood?.center?.id;
  const sectionScroll=new Map(sameCenter?Array.from(this.groupsHost.querySelectorAll<HTMLElement>('.ts-local-relations-group')).map(el=>[el.dataset.kind,el.scrollTop] as const):[]);
  const groupScroll=new Map(sameCenter?Array.from(this.groupsHost.querySelectorAll<HTMLElement>('.ts-local-relations-neighbors')).map(el=>[el.parentElement?.dataset.kind,el.scrollTop] as const):[]);
  if(!sameCenter){this.feedback?.empty();this.proofEpochs.clear();}
  const expanded=new Map(sameCenter?Array.from(this.groupsHost.querySelectorAll<HTMLDetailsElement>('details')).map(el=>[el.dataset.kind||el.dataset.relationEvidence||el.dataset.relationCenterInfo,el.open] as const):[]);
  this.toolbarNavigation.empty();this.toolbarTools.empty();if(this.host.returnToBoard)this.button(this.toolbarNavigation,'返回白板','panels-top-left','return',()=>this.invoke('returnToBoard'));const back=this.button(this.toolbarNavigation,'后退','arrow-left','back',()=>this.travel(false));back.disabled=!this.history.canBack;const forward=this.button(this.toolbarNavigation,'前进','arrow-right','forward',()=>this.travel(true));forward.disabled=!this.history.canForward;
  this.button(this.toolbarTools,'选择中心','search','center-picker-toggle',()=>this.togglePicker());const filter=this.button(this.toolbarTools,'高级筛选','list-filter','filter-toggle',()=>this.showFilter(!this.filterOpen));filter.setAttribute('aria-expanded',String(this.filterOpen));filter.setAttribute('aria-pressed',String(!!this.query||!!this.saved.tag||this.saved.kindFilter!=='all'||this.saved.kindFilters.length!==localRelationKinds.length));this.button(this.toolbarTools,'更多工具','ellipsis','more-toggle',()=>this.showMore(!this.moreOpen)).setAttribute('aria-expanded',String(this.moreOpen));this.showFilter(this.filterOpen);this.showMore(this.moreOpen);
  this.secondaryToolbar.empty();this.button(this.secondaryToolbar,'回到中心','focus','return-center',()=>{this.showMore(false);if(this.relationEditorDetails?.open)this.closeRelationEditor();this.centerHost?.scrollIntoView({block:'nearest',inline:'nearest'});});if(this.host.headings)this.button(this.secondaryToolbar,'笔记标题','list-tree','heading-jump',()=>{if(!this.headingDetails||this.headingTree?.status==='unsupported')return;this.showMore(false);this.headingDetails.open=true;this.paintHeadings();this.updateInspectorVisibility();this.headingSummary?.scrollIntoView({block:'start',inline:'nearest'});this.headingSummary?.focus({preventScroll:true});});
  this.button(this.secondaryToolbar,'第二层关系','git-fork','depth-jump',()=>{this.showMore(false);if(this.depthDetails)this.depthDetails.open=true;this.paintDepth();this.updateInspectorVisibility();this.depthSummary?.scrollIntoView({block:'nearest'});this.depthSummary?.focus({preventScroll:true});});
  if(this.host.editRelation)this.button(this.secondaryToolbar,'编辑本板关系','network','relation-edit-open',()=>this.openRelationEditor());
  const follow=this.secondaryToolbar.createEl('select',{attr:{'aria-label':'中心跟随方式','data-relation-focus':'follow'}});for(const [value,text]of [['board','跟随白板'],['note','跟随笔记'],['locked','锁定中心']])follow.createEl('option',{value,text});follow.value=this.follow;follow.onchange=()=>this.setFollow(follow.value as LocalRelationsFollow);follow.title='固定入口与跟随方式互相独立';
  if(this.host.setCompanion){const state=this.host.companion?.(),partner=this.button(this.secondaryToolbar,'伙伴页','panel-right','companion',()=>{this.host.setCompanion?.(!this.host.companion?.().enabled);this.syncedCenter=undefined;this.refresh();});partner.setAttribute('aria-pressed',String(!!state?.enabled));partner.title='开启后跟随中心显示原生笔记；关闭不会关闭笔记页';}this.button(this.secondaryToolbar,'最近浏览','history','recent-toggle',()=>{this.recentOpen=!this.recentOpen;this.paintRecent(this.host.snapshot());this.showMore(false);if(this.recentOpen)this.recentHost?.scrollIntoView({block:'nearest'});}).setAttribute('aria-expanded',String(this.recentOpen));
  this.centerHost.empty();this.pinHost.empty();this.groupsHost.empty();this.groupsHost.appendChild(this.centerHost);if(this.inspectorsHost)this.groupsHost.appendChild(this.inspectorsHost);this.footer.empty();if(this.search)this.search.disabled=!neighborhood?.center;
  if(!snapshot){this.centerHost.createEl('strong',{text:'白板尚未打开'});this.centerHost.createEl('p',{text:'打开白板并选择一个对象，查看它的局部关系。'});this.counts.setText('默认浏览不修改白板；编辑本板关系需显式进入。');return;}
  this.groupsHost.setAttribute('data-has-relations',String(!!neighborhood?.matched));
  const center=neighborhood?.center;if(!center){this.centerHost.createEl('strong',{text:'选择一个中心对象'});this.centerHost.createEl('p',{text:'在白板选择笔记卡片、子白板或分组；文本不参与脑图。'});this.counts.setText('0 个关系项');return;}
  this.centerHost.createEl('h3',{text:center.title,attr:{title:center.detail,'data-relation-motion-id':center.id,'data-relation-motion-center':'true'}});const source=this.host.source?.(center.id)||{label:'来源',path:center.path,available:!!center.path,canExplain:/\.md(?:#|$)/i.test(center.path)};
  const centerInfo=this.centerHost.createEl('details',{cls:'ts-local-center-info',attr:{'data-relation-center-info':'center-info'}});centerInfo.open=expanded.get('center-info')??false;const infoSummary=centerInfo.createEl('summary',{attr:{'data-relation-focus':'center-info','aria-label':center.title+'：中心与来源信息',title:'中心与来源信息'}});setIcon(infoSummary.createSpan(),'info');infoSummary.createSpan({text:'中心信息'});centerInfo.createEl('small',{cls:'ts-local-relations-board',text:snapshot.name,attr:{title:snapshot.path}});centerInfo.createEl('small',{cls:'ts-local-relations-path',text:source.path||'白板内对象 · 无来源笔记',attr:{title:source.path||''}});centerInfo.ontoggle=()=>this.queueLinks();if(source.reason)this.centerHost.createEl('p',{cls:'ts-local-relations-source-state',text:source.reason});
  if(this.nativeData?.pendingPaths?.length)this.centerHost.createEl('p',{cls:'ts-local-relations-source-state',text:'部分来源索引尚未就绪，原生关系可能暂不完整。'});
  if(!neighborhood.total&&!this.nativeData?.pendingPaths?.length)this.centerHost.createEl('p',{cls:'ts-local-relations-empty-state',text:'此对象暂无本板连线。'+(center.kind==='section'?'分组成员不会自动成为父子节点。':center.kind==='board'?'子白板内容不会在此递归展开，可打开来源查看。':'')});
  const partner=this.secondaryToolbar.querySelector<HTMLButtonElement>('[data-relation-focus="companion"]');if(partner)partner.disabled=!this.host.companion?.().enabled&&(!source.available||source.canExplain===false);
  const pin=this.button(this.centerHost,this.pins.ids.includes(center.id)?'取消固定':'固定中心','pin','pin-center',()=>this.togglePin(center.id));pin.setAttribute('aria-pressed',String(this.pins.ids.includes(center.id)));pin.title=(this.pins.ids.includes(center.id)?'取消固定 ':'固定中心 ')+center.title;
  const ports=centerInfo.createDiv({cls:'ts-local-relations-ports',attr:{'aria-label':'关系入口'}});for(const group of neighborhood.groups){const port=this.button(ports,`${labels[group.kind]} ${group.matched}`,'','goto:'+group.kind,()=>{const target=Array.from(this.groupsHost!.querySelectorAll<HTMLDetailsElement>('.ts-local-relations-group')).find(el=>el.dataset.kind===group.kind);if(target){target.open=true;target.scrollIntoView({block:'nearest',inline:'nearest'});}});port.disabled=!this.saved.kindFilters.includes(group.kind)||!group.items.length&&group.pages<=1;}
  this.pinHost.hidden=!this.pins.ids.length;this.pinHost.createEl('small',{text:`固定 ${this.pins.ids.length} / 6`,attr:{title:'按白板保存'}});const pinList=this.pinHost.createDiv('ts-local-relations-pin-list');for(const id of this.pins.ids){const node=snapshot.board.nodes.find(n=>n.id===id);if(!node||!supportsLocalRelations(node))continue;const item=localRelationNode(node),chip=pinList.createDiv('ts-local-relations-pin');const fixed=this.button(chip,item.title,'','pin:'+id,()=>this.browse(id));fixed.title=item.detail;fixed.setAttribute('aria-label',item.title+' · '+item.detail);const remove=this.button(chip,'取消固定 '+item.title,'x','unpin:'+id,()=>this.togglePin(id));remove.setAttribute('aria-label','取消固定 '+item.title+' · '+item.detail);remove.title='取消固定 '+item.detail;}
  this.counts.setText(`对象：列出 ${neighborhood.shown} · 关系匹配 ${neighborhood.matched} / 共 ${neighborhood.total}`);this.counts.title='每组每页 10 项，总计最多 60。同一对象只显示一次；完整关系类型和依据可在其详情查看。';
  if(neighborhood.invalidBranches)this.groupsHost.createEl('p',{cls:'ts-local-relations-empty',text:'父子结构存在冲突，暂不展示亲属关系。普通关联仍可查看。'});
  if(this.query&&!neighborhood.matched)this.groupsHost.createEl('p',{cls:'ts-local-relations-empty',text:'没有匹配的邻居；清空筛选或启用关系类别后再查看。'});
  const leftSide=this.groupsHost.createDiv('ts-local-relations-side ts-local-relations-side-left'),rightSide=this.groupsHost.createDiv('ts-local-relations-side ts-local-relations-side-right');
  const byId=new Map(snapshot.board.nodes.map(node=>[node.id,node])),edges=new Map(snapshot.board.edges.map(edge=>[edge.id,edge]));
  for(const group of neighborhood.groups){if(!this.saved.kindFilters.includes(group.kind)||!group.items.length&&group.pages<=1)continue;const parent=group.kind==='incoming'||group.kind==='associated'?leftSide:group.kind==='outgoing'||group.kind==='siblings'?rightSide:this.groupsHost;const section=parent.createEl('details',{cls:'ts-local-relations-group',attr:{'data-kind':group.kind,'data-empty':String(!group.items.length)}});section.open=expanded.get(group.kind)??true;section.onscroll=()=>this.queueLinks();section.ontoggle=()=>{if(!this.alive||!this.visible()||!section.isConnected)return;if(!section.open)for(const proof of Array.from(section.querySelectorAll<HTMLElement>('[data-relation-evidence]')))this.closeEvidence(proof.dataset.relationEvidence!);const valid=new Set(this.firstPageIds());if(this.depthExpanded.some(id=>!valid.has(id)))this.editInspectors(()=>this.paintDepth());this.queueLinks();};section.createEl('summary',{text:labels[group.kind],attr:{title:`本页 ${group.shown} 个对象 · 匹配 ${group.matched} / 共 ${group.total} 条关系；其他角色可在对象详情查看`,'aria-label':`${labels[group.kind]} · ${group.matched} 条匹配，共 ${group.total} 条关系`,'data-relation-focus':'group:'+group.kind}});const list=section.createDiv('ts-local-relations-neighbors');list.scrollTop=groupScroll.get(group.kind)||0;list.onscroll=()=>this.queueLinks();for(const item of group.items){const row=list.createDiv('ts-local-relations-neighbor'),b=this.button(row,item.title,'','neighbor:'+group.kind+':'+item.id,()=>this.browse(item.id)),roles=this.visibleRoles.get(item.id)||[group.kind];b.title=item.detail+(roles.length>1?'\n关系：'+roles.map(kind=>labels[kind]).join('、'):'');b.setAttribute('data-relation-kind',group.kind);b.setAttribute('data-relation-motion-id',item.id);b.querySelector('span')?.addClass('ts-local-relations-neighbor-title');const evidence=[...(roles.length>1?['关系：'+roles.map(kind=>labels[kind]).join('、')]:[]),...item.labels.slice(0,3).map(label=>label.slice(0,120)),...(item.labels.length>3?[`另 ${item.labels.length-3} 个标签`]:[]),...(item.viaParentIds.length?[`共同父节点 ${item.viaParentIds.length}`]:[])];
    const evidenceKey='evidence:'+group.kind+':'+item.id,proof=row.createEl('details',{cls:'ts-local-relations-proof',attr:{'data-relation-evidence':evidenceKey}}),totalProof=item.edgeIds.length+item.nativeEvidence.length;proof.open=expanded.get(evidenceKey)??false;const summary=proof.createEl('summary',{attr:{'data-relation-focus':evidenceKey,'aria-label':item.title+'：来源与关系依据，'+totalProof+' 条',title:'来源与关系依据 · '+totalProof+' 条'}});setIcon(summary.createSpan(),'ellipsis');summary.createSpan({text:`关系依据 · ${totalProof} 条`});proof.createEl('small',{cls:'ts-local-relations-neighbor-path',text:item.path||(item.kind==='section'?'分组':item.kind==='board'?'子白板':'笔记卡片'),attr:{title:item.detail}});if(evidence.length)proof.createEl('small',{cls:'ts-local-relations-evidence',text:evidence.join(' · ')});
    const expand=this.button(proof,'展开下一层','plus','depth-expand:'+group.kind+':'+item.id,()=>this.toggleDepth(item.id));expand.addClass('ts-local-depth-expand');expand.setAttribute('data-depth-source',item.id);expand.setAttribute('aria-pressed',String(this.depthExpanded.includes(item.id)));
    const populateProof=()=>{if(!proof.open||proof.dataset.loaded)return;proof.dataset.loaded='true';const title=(id:string)=>{const node=byId.get(id);return node?localRelationNode(node).title:'已删除对象';};for(const parent of item.viaParentIds.slice(0,1))proof.createEl('small',{text:'共同父节点：'+title(parent),attr:{title:parent}});
     const pages=Math.max(1,Math.ceil(totalProof/20)),page=Math.min(this.proofPages.get(evidenceKey)||0,pages-1);this.proofPages.set(evidenceKey,page);
     for(let at=page*20;at<Math.min(totalProof,(page+1)*20);at++){if(at<item.edgeIds.length){const id=item.edgeIds[at],edge=edges.get(id);if(!edge)continue;const arrow=edge.direction==='both'?' ↔ ':edge.direction==='none'?' — ':' → ';proof.createDiv({text:`${edge.kind==='branch'?'本板父子连线':'本板连线'}：${title(edge.from)}${arrow}${title(edge.to)}${edge.label?' · '+edge.label.slice(0,240):''}`,attr:{title:`连线 ${id} · ${edge.from} → ${edge.to}`,'data-evidence-row':'board'}});}else{const evidence=item.nativeEvidence[at-item.edgeIds.length],label=`${evidence.kind==='property'?'属性 '+(evidence.property||''):evidence.kind==='embed'?'嵌入':evidence.kind==='indexed'?`原生索引链接 · ${evidence.count||1} 次（位置未就绪）`:'原生链接'}：${evidence.sourcePath} → ${evidence.targetPath}${evidence.subpath||''}`,b=this.button(proof,label,'file-text','native-evidence:'+evidence.id,()=>this.invoke('openSource',evidence,undefined,this.evidenceGuard(evidenceKey,'native-evidence:'+evidence.id,group.kind)));b.setAttribute('data-evidence-row','native');b.disabled=!this.host.openEvidence;b.title=evidence.original||label;}}
     if(totalProof>20)proof.createEl('small',{text:`本页 ${page*20+1}–${Math.min(totalProof,(page+1)*20)} / ${totalProof} 条；其余 ${Math.max(0,totalProof-20)} 条未列出，可翻页查看。`});
     this.pager(proof,'proof-page:'+group.kind+':'+item.id,page,pages,next=>{this.proofPages.set(evidenceKey,next);this.refresh();},labels[group.kind]+' · '+item.title+' · '+item.detail+' 的关系依据');
    };proof.ontoggle=()=>{if(!this.alive||!this.visible()||!proof.isConnected)return;if(!proof.open)this.closeEvidence(evidenceKey);populateProof();this.queueLinks();};populateProof();
}this.pager(section,'page:'+group.kind,group.page,group.pages,page=>{this.editInspectors(()=>{});this.pages[group.kind]=page;list.scrollTop=0;section.scrollTop=0;this.refresh();},labels[group.kind]+'关系');list.scrollTop=groupScroll.get(group.kind)||0;section.scrollTop=sectionScroll.get(group.kind)||0;if(!group.total)section.createEl('small',{cls:'ts-local-relations-empty',text:'暂无'});}
  centerInfo.appendChild(this.footer);this.button(this.footer,'在白板定位','locate-fixed','locate',()=>this.invoke('locate'));const actions=this.centerHost.createDiv('ts-local-relations-center-actions'),open=this.button(actions,'打开来源','file-text','source',()=>this.invoke('openSource'));open.disabled=!source.available||!this.host.openSource;open.title=source.reason||source.path||'此对象没有可打开的来源';if(this.host.editCenter||this.host.editSource){const edit=this.button(this.footer,this.host.editCenter?'编辑模式':'编辑来源','pencil','edit-source',()=>this.invoke(this.host.editCenter?'editCenter':'editSource'));edit.disabled=!source.available||source.canExplain===false;if(this.host.editCenter){this.updateCenterEditButton(source);if(center.kind==='card'&&source.available&&source.canEdit!==false)this.footer.createEl('small',{cls:'ts-local-relations-edit-note',text:'原生编辑自动保存',attr:{title:'返回脑图不会撤销笔记修改。'}});}}const explain=this.button(this.footer,'来源与引用','network','explain',()=>this.invoke('explain'));explain.disabled=!source.available||source.canExplain===false||!this.host.explain;explain.title=source.canExplain===false?'仅 Markdown 来源支持来源与引用':source.reason||'查看原生来源与引用';
  if(this.pending?.id===center.id){open.disabled=true;this.footer.querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.disabled=true);}this.groupsHost.scrollTop=scroll;this.queueLinks();this.restoreFocus(key,this.search);
 }
 async onClose(){this.motion.cancel();this.motionEpoch++;this.motionActive=false;this.motionSnapshot=undefined;this.closed=true;this.restoreEpoch++;this.alive=false;this.pending=undefined;this.generation++;if(this.frame)this.frameWindow?.cancelAnimationFrame(this.frame);if(this.linkFrame)this.linkWindow?.cancelAnimationFrame(this.linkFrame);this.linkFrame=0;this.linkWindow=undefined;this.frame=0;this.frameWindow=undefined;this.unsubscribe?.();this.unsubscribe=undefined;this.resetInspectors();this.lastNeighborhood=undefined;this.history.clear();this.pins.clear();this.paintedCenter=undefined;this.context=undefined;this.contentEl.empty();}
}
