import {App,Component,MarkdownRenderer,Modal,Notice,TFile,setIcon} from 'obsidian';
import {Fragment,FragmentKind,OutlineTopic,extractFragments,fragmentLabels,parseOutline,MaterialImportOptions,MaterialImportResult,MaterialProgress} from './materials';
import {themeSurface} from './ui-tokens';
export type MaterialImporter=(file:TFile,raw:string,fragments:Fragment[],group:boolean,link:boolean,options?:MaterialImportOptions)=>Promise<MaterialImportResult>;
export interface MaterialAdapter {
 docked?:boolean;
 target?:()=>{name:string;path:string}|undefined;
 pickTarget?:()=>unknown;
 locate?:(result:MaterialImportResult)=>unknown;
 placed?:(result:MaterialImportResult)=>boolean;
 watch?:(notify:()=>void)=>(()=>void);
 drag?:(event:DragEvent,accept:(importer:MaterialImporter,point:{x:number;y:number})=>Promise<void>)=>void;
 endDrag?:()=>void;
 initial?:TFile;
 pick:(done:(file:TFile)=>void)=>void;
 open:(file:TFile,line?:number)=>unknown;
 excerpts:MaterialImporter;
 outline:(topics:OutlineTopic[],title:string,direction:'right'|'down'|'up')=>void;
}
/** Workbench owns previews; the adapter owns all file/board mutations. */
export class MaterialsWorkbench {
 private mode:'excerpts'|'outline'='excerpts';private file?:TFile;private raw='';private sourceRaw='';private outlineDraft='';private fragments:Fragment[]=[];private topics:OutlineTopic[]=[];
 private selected=new Set<string>();private active?:string;private query='';private kind:FragmentKind|'all'='all';private direction:'right'|'down'|'up'='right';private grouped=true;private linked=true;
 private progress=new MaterialProgress();private sourceDrafts=new Map<TFile,{raw:string;selected:Set<string>;active?:string;outline:string;title:string;insight:string;scroll:number;limit:number}>();private recent:TFile[]=[];private lastResult?:MaterialImportResult;private lastSource?:TFile;private merge=false;private customTitle='';private repeat=false;private hideDone=false;private stale=false;private targetEl?:HTMLElement;private lifetime=new Component();private previousOutline='';private reading=true;private readerLimit=24;private readerScroll=0;private insight='';private unwatch?:()=>void;
 private busy=false;private alive=false;private revision=0;private previewScope?:Component;private renderRevision=0;private truncated=false;private error='';
 private body!:HTMLElement;private footer!:HTMLElement;private source!:HTMLElement;private tabs!:HTMLElement;
 constructor(private app:App,private adapter:MaterialAdapter,public modalEl:HTMLElement,public contentEl:HTMLElement,public titleEl:HTMLElement,private dismiss:()=>void){}
 onOpen(){this.alive=true;this.lifetime.load();themeSurface(this.modalEl);this.modalEl.addClass(this.adapter.docked?'ts-materials-panel':'ts-materials-modal');this.titleEl.setText('材料工作台');
  const hero=this.contentEl.createDiv('ts-materials-intro');hero.createDiv({cls:'ts-materials-eyebrow',text:'READ · EXTRACT · CONNECT'});hero.createEl('p',{text:'让阅读留下线索，让材料生长为结构。'});
  if(this.adapter.docked){this.targetEl=this.contentEl.createDiv('ts-materials-target');this.refreshTarget();this.lifetime.registerEvent(this.app.vault.on('modify',file=>{if(file===this.file){this.stale=true;this.renderFooter();}}));this.lifetime.registerEvent(this.app.vault.on('rename',()=>{this.renderSource();this.refreshTarget();}));this.lifetime.registerDomEvent(this.contentEl,'keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();e.stopPropagation();void this.apply();}});}
  this.tabs=this.contentEl.createDiv({cls:'ts-materials-tabs',attr:{role:'tablist','aria-label':'材料工作流'}});this.source=this.contentEl.createDiv('ts-materials-source');this.body=this.contentEl.createDiv('ts-materials-body');this.footer=this.contentEl.createDiv('ts-materials-footer');this.renderTabs();this.renderSource();this.render();
  if(this.adapter.initial)void this.load(this.adapter.initial);
 }
 get sourceFile(){return this.file;}
 refreshTarget(){this.unwatch?.();this.unwatch=this.adapter.watch?.(()=>{if(!this.alive||this.busy)return;const list=this.body?.querySelector<HTMLElement>('.ts-materials-list');if(list)this.renderFragmentList(list);if(this.body?.querySelector('.ts-materials-reader'))this.refreshReaderState();if(this.footer)this.renderFooter();});if(this.targetEl){this.targetEl.empty();const target=this.adapter.target?.();this.targetEl.createSpan({text:'目标白板'});this.action(this.targetEl,target?.name||'选择白板','panels-top-left',()=>this.adapter.pickTarget?.());}if(this.footer)this.renderFooter();if(this.body&&this.adapter.docked&&this.mode==='excerpts')this.render();}
 private action(parent:HTMLElement,label:string,icon:string,run:()=>unknown,cls=''){const b=parent.createEl('button',{cls,attr:{'aria-label':label,title:label}});if(icon)setIcon(b.createSpan(),icon);b.createSpan({text:label});b.onclick=()=>{try{Promise.resolve(run()).catch(e=>this.fail(e));}catch(e){this.fail(e);}};return b;}
 private fail(e:unknown){this.error=e instanceof Error?e.message:String(e);if(this.alive)this.renderFooter();else new Notice(this.error,10000);}
 private renderTabs(){this.tabs.empty();for(const [mode,label,icon] of [['excerpts','摘录成笔记','notebook-pen'],['outline','大纲转导图','git-fork']] as const){const b=this.action(this.tabs,label,icon,()=>{if(this.busy)return;if(this.mode==='outline')this.outlineDraft=this.raw;this.mode=mode;this.raw=mode==='excerpts'?this.sourceRaw:this.outlineDraft;this.error='';this.parse();this.renderTabs();this.renderSource();this.render();});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(this.mode===mode));b.disabled=this.busy;}}
 private renderSource(){this.source.empty();const identity=this.source.createDiv('ts-materials-source-name');setIcon(identity.createSpan(),this.file?'file-text':'book-open');const text=identity.createDiv();text.createEl('strong',{text:this.file?.basename||'选择一篇材料'});text.createEl('small',{text:this.file?.path||'支持仓库中的 Markdown 笔记，也可在大纲模式粘贴内容'});
  const actions=this.source.createDiv('ts-materials-source-actions');this.action(actions,this.file?'更换材料':'选择笔记','folder-search',()=>this.adapter.pick(f=>{if(this.alive&&!this.busy)void this.load(f);})).disabled=this.busy;
  if(this.recent.length>1){const recent=actions.createEl('select',{attr:{'aria-label':'最近材料'}});recent.createEl('option',{value:'',text:'最近材料'});for(const [i,f]of this.recent.entries())if(f!==this.file&&this.app.vault.getAbstractFileByPath(f.path)===f)recent.createEl('option',{value:String(i),text:f.basename});recent.disabled=this.busy;recent.onchange=()=>{if(recent.value)void this.load(this.recent[Number(recent.value)]);};}
  if(this.file){this.action(actions,'刷新','refresh-cw',()=>this.load(this.file!)).disabled=this.busy;this.action(actions,'打开原文','panel-right',()=>this.adapter.open(this.file!));}
 }
 async load(file:TFile){if(this.busy)return;if(this.file){this.sourceDrafts.delete(this.file);this.sourceDrafts.set(this.file,{raw:this.sourceRaw,selected:new Set(this.selected),active:this.active,outline:this.mode==='outline'?this.raw:this.outlineDraft,title:this.customTitle,insight:this.insight,scroll:this.body.querySelector('.ts-materials-reader')?.scrollTop||this.readerScroll,limit:this.readerLimit});while(this.sourceDrafts.size>6)this.sourceDrafts.delete(this.sourceDrafts.keys().next().value!);}const revision=++this.revision;this.busy=true;this.error='';this.renderTabs();this.renderSource();this.renderFooter();try{if(file.stat.size>2000000)throw Error('材料超过 2 MB，请分章节读取');const raw=await this.app.vault.read(file);if(!this.alive||revision!==this.revision)return;const saved=this.sourceDrafts.get(file);this.file=file;this.sourceRaw=raw;this.outlineDraft=saved?.outline||raw;this.raw=this.mode==='outline'?this.outlineDraft:raw;this.selected=saved?.raw===raw?new Set(saved.selected):new Set();this.active=saved?.raw===raw?saved.active:undefined;this.query='';this.kind='all';this.stale=false;this.customTitle=saved?.title||'';this.insight=saved?.insight||'';this.readerLimit=saved?.limit||24;this.readerScroll=saved?.scroll||0;this.recent=[file,...this.recent.filter(f=>f!==file)].slice(0,6);this.parse();}catch(e){this.fail(e);}finally{if(this.alive&&revision===this.revision){this.busy=false;this.renderTabs();this.renderSource();this.render();}}}
 private parse(){this.fragments=[];this.topics=[];this.truncated=false;try{if(this.mode==='excerpts'){const result=extractFragments(this.raw);this.fragments=result.fragments;this.truncated=result.truncated;if(!this.fragments.some(f=>f.id===this.active))this.active=this.fragments[0]?.id;}else this.topics=parseOutline(this.raw);}catch(e){this.error=e instanceof Error?e.message:String(e);}}
 private imported(f:Fragment){const target=this.adapter.target?.();if(!this.file||!target)return;const result=this.progress.get(this.file,f,target.path);return result&&(!this.adapter.placed||this.adapter.placed(result))?result:undefined;}
 private matches(){const q=this.query.trim().toLocaleLowerCase();return this.fragments.filter(f=>(!this.hideDone||!this.imported(f))&&(this.kind==='all'||f.kind===this.kind)&&(!q||`${f.title} ${f.heading} ${f.body}`.toLocaleLowerCase().includes(q)));}
 private render(){if(!this.alive)return;const reader=this.body.querySelector<HTMLElement>('.ts-materials-reader');if(reader?.dataset.source===this.file?.path)this.readerScroll=reader?.scrollTop||0;this.previewScope?.unload();this.previewScope=undefined;this.renderRevision++;this.body.empty();if(this.mode==='outline')this.renderOutline();else this.renderExcerpts();this.renderFooter();const next=this.body.querySelector('.ts-materials-reader');if(next)next.scrollTop=this.readerScroll;}
 private renderExcerpts(){
  this.body.classList.toggle('is-reading',this.adapter.docked===true&&this.reading);if(this.adapter.docked){const switcher=this.body.createDiv('ts-materials-reading-switch');for(const[reading,label,icon]of [[true,'连续阅读','book-open'],[false,'片段列表','list-filter']] as const){const b=this.action(switcher,label,icon,()=>{this.reading=reading;this.render();});b.setAttribute('aria-pressed',String(this.reading===reading));}if(this.reading){this.renderContinuous();return;}}
  const left=this.body.createDiv('ts-materials-library'),tools=left.createDiv('ts-materials-filters');const search=tools.createEl('input',{type:'search',placeholder:'搜索片段、章节…',value:this.query,attr:{'aria-label':'搜索材料片段'}});search.oninput=()=>{this.query=search.value;this.renderFragmentList(list);this.renderFooter();};
  const select=tools.createEl('select',{attr:{'aria-label':'片段类型'}});select.createEl('option',{value:'all',text:'全部类型'});for(const[k,v]of Object.entries(fragmentLabels))select.createEl('option',{value:k,text:v});select.value=this.kind;select.onchange=()=>{this.kind=select.value as typeof this.kind;this.renderFragmentList(list);this.renderFooter();};
  if(this.adapter.docked)this.checkbox(tools,'仅看未摘录',this.hideDone,v=>{this.hideDone=v;this.render();});
  const batch=left.createDiv('ts-materials-batch');this.action(batch,'选择筛选结果','check-check',()=>{for(const f of this.matches())if(this.repeat||!this.imported(f))this.selected.add(f.id);this.renderFragmentList(list);this.renderFooter();});this.action(batch,'清空选择','x',()=>{this.selected.clear();this.renderFragmentList(list);this.renderFooter();});
  const list=left.createDiv({cls:'ts-materials-list',attr:{'aria-label':'材料片段'}});this.renderFragmentList(list);
  const preview=this.body.createDiv('ts-materials-detail');this.renderPreview(preview);
 }
 private refreshReaderState(){for(const row of Array.from(this.body.querySelectorAll<HTMLElement>('.ts-materials-reading-block'))){const f=this.fragments.find(f=>f.id===row.dataset.fragment);if(!f)continue;const done=this.imported(f),input=row.querySelector<HTMLInputElement>('input[type=checkbox]');row.classList.toggle('is-imported',!!done);row.classList.toggle('is-selected',this.selected.has(f.id));if(input){input.checked=this.selected.has(f.id);input.disabled=this.busy||(!this.repeat&&!!done);}const handle=row.querySelector<HTMLElement>('.ts-materials-drag-handle');if(handle)handle.draggable=!this.busy&&!this.stale&&(!done||this.repeat);}}
 private renderContinuous(){
  const reader=this.body.createDiv({cls:'ts-materials-reader',attr:{'aria-label':'连续阅读正文','data-source':this.file?.path||'',tabindex:'0'}});if(!this.file){reader.createDiv({cls:'ts-materials-empty',text:'选择一篇材料，沿着章节阅读，再把相关段落放入白板。'});return;}
  const scope=new Component();scope.load();this.previewScope=scope;reader.createEl('h2',{text:this.file.basename});let heading='';
  const append=()=>{const visible=this.fragments.slice(reader.querySelectorAll('.ts-materials-reading-block').length,this.readerLimit);for(const f of visible){if(f.heading&&f.heading!==heading){reader.createEl('h3',{text:f.heading});heading=f.heading;}const row=reader.createEl('article',{cls:'ts-materials-reading-block',attr:{'data-fragment':f.id}}),tools=row.createDiv('ts-materials-reading-block-tools'),check=tools.createEl('input',{type:'checkbox',attr:{'aria-label':`选择：${f.title}`}});check.checked=this.selected.has(f.id);check.onchange=()=>{if(check.checked)this.selected.add(f.id);else this.selected.delete(f.id);this.active=f.id;this.refreshReaderState();this.renderFooter();};const handle=this.action(tools,'拖到白板','grip-vertical',()=>{check.click();},'ts-materials-drag-handle');handle.tabIndex=-1;this.action(tools,'定位原文','file-search',()=>this.adapter.open(this.file!,f.start-1));const md=row.createDiv('ts-materials-markdown markdown-rendered');void MarkdownRenderer.render(this.app,f.body.slice(0,30000),md,this.file!.path,scope).then(()=>{md.querySelectorAll<HTMLInputElement>('input[type=checkbox]').forEach(input=>input.disabled=true);}).catch(e=>this.fail(e));if(f.body.length>30000)row.createEl('small',{text:'此段仅预览前 30,000 字符；摘录保留完整内容。'});row.ondragstart=e=>this.startDrag(e,f);row.ondragend=()=>this.adapter.endDrag?.();}
   this.refreshReaderState();if(this.readerLimit<this.fragments.length){const more=this.action(reader,'继续阅读','chevrons-down',()=>{more.remove();this.readerLimit+=24;append();},'ts-materials-reader-more');}};append();
 }
 private renderFragmentList(list:HTMLElement){list.empty();const matches=this.matches();if(!matches.length)list.createDiv({cls:'ts-materials-empty',text:this.file?'没有匹配的片段，试试其他关键词或类型。':'先选择一篇笔记，在这里挑选值得保留的片段。'});
  for(const f of matches){const row=list.createDiv({cls:'ts-materials-fragment'});row.classList.toggle('is-active',f.id===this.active);const input=row.createEl('input',{type:'checkbox',attr:{'aria-label':`选择：${f.title}`}});input.checked=this.selected.has(f.id);input.disabled=this.busy||(!this.repeat&&!!this.imported(f));input.onchange=()=>{if(input.checked)this.selected.add(f.id);else this.selected.delete(f.id);this.customTitle='';this.renderFooter();};
   const b=this.action(row,f.title,'',()=>{this.active=f.id;list.querySelectorAll('.ts-materials-fragment').forEach(el=>el.classList.remove('is-active'));row.classList.add('is-active');this.customTitle='';const detail=this.body.querySelector<HTMLElement>('.ts-materials-detail');if(detail)this.renderPreview(detail);},'ts-materials-fragment-title');b.createEl('small',{text:`${fragmentLabels[f.kind]} · ${f.heading||'正文'} · ${f.start}–${f.end} 行`});if(this.adapter.docked){const done=this.imported(f);row.classList.toggle('is-imported',!!done);const quick=this.action(row,done?'定位摘录':'摘录此段',done?'check':'plus',()=>done?this.adapter.locate?.(done):this.perform([f]),'ts-materials-quick');quick.disabled=this.busy||this.stale;row.draggable=!this.busy&&!this.stale&&(!done||this.repeat);row.ondragstart=e=>this.startDrag(e,f);row.ondragend=()=>this.adapter.endDrag?.();}
  }
 }
 private renderPreview(host:HTMLElement){this.previewScope?.unload();host.empty();const revision=++this.renderRevision,f=this.fragments.find(f=>f.id===this.active);if(!f){host.createDiv({cls:'ts-materials-empty',text:'从左侧选择片段，在这里预览完整内容。'});return;}
  if(this.adapter.docked){const nav=host.createDiv('ts-materials-preview-nav');this.action(nav,'上一段','chevron-left',()=>this.step(-1));this.action(nav,'定位原文','file-search',()=>this.file&&this.adapter.open(this.file,f.start-1));this.action(nav,'下一段','chevron-right',()=>this.step(1));}
  const cap=host.createDiv('ts-materials-preview-cap');cap.createSpan({text:fragmentLabels[f.kind]});cap.createSpan({text:`原文 ${f.start}–${f.end} 行`});host.createEl('h3',{text:f.heading||'材料预览'});
  const content=host.createDiv('ts-materials-markdown markdown-rendered'),scope=new Component();scope.load();this.previewScope=scope;
  void MarkdownRenderer.render(this.app,f.body.slice(0,30000),content,this.file?.path||'',scope).then(()=>{if(this.alive&&revision===this.renderRevision)content.querySelectorAll<HTMLInputElement>('input[type=checkbox]').forEach(input=>input.disabled=true);}).catch(e=>{if(this.alive&&revision===this.renderRevision)this.fail(e);});if(f.body.length>30000)host.createEl('small',{text:'预览显示前 30,000 字符，导入保留完整片段。'});
 }
 private renderOutline(){
  this.body.removeClass('is-reading');
  const editor=this.body.createDiv('ts-materials-library ts-materials-outline-editor');editor.createEl('label',{text:'Markdown 大纲',attr:{for:'ts-materials-outline'}});const input=editor.createEl('textarea',{value:this.raw,placeholder:'# 研究问题\n## 证据\n- 关键发现\n  - 支持材料\n## 下一步',attr:{id:'ts-materials-outline','aria-label':'Markdown 大纲'}});input.value=this.raw;input.disabled=this.busy;
  editor.createEl('small',{text:'标题与缩进列表生成层级；普通正文与代码块不会生成主题。'});
  const preview=this.body.createDiv('ts-materials-detail');input.oninput=()=>{this.raw=input.value;this.error='';this.parse();this.renderTree(preview);this.renderFooter();};this.renderTree(preview);
 }
 private renderTree(host:HTMLElement){host.empty();const cap=host.createDiv('ts-materials-preview-cap');cap.createSpan({text:'结构预览'});cap.createSpan({text:`${this.topics.length} 个主题`});
  if(!this.topics.length){host.createDiv({cls:'ts-materials-empty',text:'输入标题或列表，实时查看导图层级。'});return;}
  const tree=host.createDiv({cls:'ts-materials-tree',attr:{role:'list','aria-label':'导图结构预览'}});for(const t of this.topics){const row=tree.createDiv({cls:'ts-materials-topic',attr:{role:'listitem'}});row.style.paddingLeft=`${Math.min(t.depth,12)*18+12}px`;setIcon(row.createSpan(),t.parent===null?'circle-dot':'corner-down-right');row.createSpan({text:t.title});}
 }
 private checkbox(host:HTMLElement,label:string,checked:boolean,change:(v:boolean)=>void){const wrap=host.createEl('label'),input=wrap.createEl('input',{type:'checkbox'});input.checked=checked;input.disabled=this.busy;input.onchange=()=>change(input.checked);wrap.createSpan({text:label});}
 private renderFooter(){if(!this.alive)return;this.footer.empty();if(this.stale)this.footer.createDiv({cls:'ts-materials-warning',text:'原文已更新，刷新材料后继续。当前选择与草稿仍保留。'});if(this.error)this.footer.createDiv({cls:'ts-materials-error',text:this.error,attr:{role:'alert'}});if(this.truncated)this.footer.createDiv({cls:'ts-materials-warning',text:'仅显示前 200 个片段；其余内容请分章节导入。'});
  if(this.lastResult&&this.adapter.docked&&this.lastResult.boardPath===this.adapter.target?.()?.path){const receipt=this.footer.createDiv('ts-materials-receipt');receipt.createSpan({text:`已放入 ${this.lastResult.files.length} 篇笔记`});this.action(receipt,'在白板定位','locate-fixed',()=>this.adapter.locate?.(this.lastResult!));}
  if(this.mode==='excerpts'&&this.adapter.docked){const compose=this.footer.createDiv('ts-materials-compose');this.checkbox(compose,'合并为概念笔记',this.merge,v=>{this.merge=v;this.renderFooter();});const title=compose.createEl('input',{type:'text',value:this.customTitle,placeholder:this.merge?'概念标题（必填）':'单篇摘录标题（可选）',attr:{'aria-label':'摘录笔记标题',maxlength:'100'}});title.disabled=this.busy;title.oninput=()=>{this.customTitle=title.value;const save=this.footer.querySelector<HTMLButtonElement>('.ts-materials-commit .mod-cta');if(save)save.disabled=!this.canApply();};}
  if(this.mode==='excerpts'&&this.adapter.docked){const reflection=this.footer.createEl('details',{cls:'ts-materials-reflection'});reflection.createEl('summary',{text:this.insight.trim()?'我的理解 · 已填写':'写下我的理解（可选）'});const input=reflection.createEl('textarea',{value:this.insight,placeholder:'这个概念说明了什么？它和已有知识有什么关系？',attr:{'aria-label':'我的理解',maxlength:'10000'}});input.value=this.insight;input.disabled=this.busy;input.oninput=()=>this.insight=input.value;}
  const options=this.footer.createDiv('ts-materials-options');if(this.mode==='excerpts'){this.checkbox(options,'汇入命名分组',this.grouped,v=>this.grouped=v);this.checkbox(options,'连接原文卡片',this.linked,v=>this.linked=v);if(this.adapter.docked)this.checkbox(options,'允许重复摘录',this.repeat,v=>{this.repeat=v;this.render();});}else{options.createSpan({text:'生长方向'});for(const [d,label,icon]of [['right','向右','arrow-right'],['down','向下','arrow-down'],['up','向上','arrow-up']] as const){const b=this.action(options,label,icon,()=>{this.direction=d;this.renderFooter();});b.setAttribute('aria-pressed',String(this.direction===d));b.disabled=this.busy;}if(this.adapter.docked)this.checkbox(options,'允许重复生成',this.repeat,v=>{this.repeat=v;this.renderFooter();});}
  const bottom=this.footer.createDiv('ts-materials-commit'),info=bottom.createDiv();info.createEl('strong',{text:this.busy?'正在处理材料…':this.mode==='excerpts'?`已选 ${this.selected.size} / ${this.fragments.length} 个片段`:`将生成 ${this.topics.length+(this.topics.filter(t=>t.parent===null).length>1?1:0)} 个主题`});info.createEl('small',{text:this.mode==='excerpts'?'创建独立 Markdown 笔记并保留来源链接；原文不变。':'先预览，再生成。新导图放在现有内容旁边。'});
  const save=this.action(bottom,this.mode==='excerpts'?'创建摘录笔记':'生成思维导图',this.mode==='excerpts'?'plus':'git-fork',()=>this.apply(),'mod-cta');save.disabled=!this.canApply();
 }
 private canApply(){return !this.busy&&!this.stale&&(!this.adapter.docked||!!this.adapter.target?.())&&(this.mode==='excerpts'?!!this.file&&this.fragments.some(f=>this.selected.has(f.id)&&(this.repeat||!this.imported(f)))&&(!this.merge||!!this.customTitle.trim()):this.topics.length>0&&(this.repeat||(this.adapter.target?.()?.path||'')+'\n'+this.raw!==this.previousOutline));}
 private step(direction:number){const list=this.matches();if(!list.length)return;const index=list.findIndex(f=>f.id===this.active);this.active=list[Math.max(0,Math.min(list.length-1,index+direction))].id;this.customTitle='';this.render();this.body.querySelector('.is-active')?.scrollIntoView({block:'nearest'});}
 private startDrag(event:DragEvent,fragment:Fragment){if(this.busy||this.stale||(!this.repeat&&this.imported(fragment))||!this.adapter.drag){event.preventDefault();return;}const file=this.file,raw=this.sourceRaw,fragments=this.selected.has(fragment.id)?this.fragments.filter(f=>this.selected.has(f.id)&&(this.repeat||!this.imported(f))):[fragment];this.adapter.drag(event,async(importer,position)=>{if(!this.alive||file!==this.file||raw!==this.sourceRaw)throw Error('材料已切换，请重新拖动');await this.perform(fragments,{position},importer);});}
 async perform(fragments:Fragment[],options:MaterialImportOptions={},importer:MaterialImporter=this.adapter.excerpts){
  if(this.busy||this.stale)return;const source=this.file,raw=this.sourceRaw;if(!source||!fragments.length)return;const keepFocus=this.contentEl.contains(document.activeElement),target=this.adapter.target?.();
  this.busy=true;this.error='';this.renderTabs();this.renderSource();this.renderFooter();
  try{const same=this.lastSource===source&&this.lastResult?.boardPath===target?.path;const result=await importer(source,raw,fragments,this.grouped,this.linked,{focus:!this.adapter.docked,insight:this.insight,...(same&&this.grouped&&!options.position?{groupId:this.lastResult?.groupId}:{}),...(this.merge?{mergeTitle:this.customTitle}:fragments.length===1&&this.customTitle?{title:this.customTitle}:{}),...options});
   this.progress.record(source,fragments,result);this.lastSource=source;this.lastResult=result;for(const f of fragments)this.selected.delete(f.id);this.customTitle='';this.insight='';if(!this.adapter.docked)this.close();
  }catch(e){this.fail(e);}finally{this.busy=false;if(this.alive){this.renderTabs();this.renderSource();this.render();if(keepFocus&&document.activeElement===document.body)this.body.querySelector<HTMLElement>('.is-active button,.ts-materials-fragment button,.ts-materials-reader')?.focus({preventScroll:true});}}
 }
 private async apply(){if(!this.canApply())return;if(this.mode==='excerpts')return this.perform(this.fragments.filter(f=>this.selected.has(f.id)&&(this.repeat||!this.imported(f))));
  this.busy=true;this.error='';this.renderFooter();try{this.adapter.outline(this.topics,this.file?.basename||'材料大纲',this.direction);this.previousOutline=(this.adapter.target?.()?.path||'')+'\n'+this.raw;if(!this.adapter.docked)this.close();}catch(e){this.fail(e);}finally{this.busy=false;if(this.alive)this.renderFooter();}
 }
 close(){this.onClose();this.dismiss();}
 onClose(){this.alive=false;this.revision++;this.renderRevision++;this.previewScope?.unload();this.unwatch?.();this.unwatch=undefined;this.lifetime.unload();this.sourceDrafts.clear();this.recent=[];this.progress.clear();this.contentEl.empty();}
}
export class MaterialsModal extends Modal {
 workbench!:MaterialsWorkbench;
 constructor(app:App,private adapter:MaterialAdapter){super(app);}
 onOpen(){this.workbench=new MaterialsWorkbench(this.app,this.adapter,this.modalEl,this.contentEl,this.titleEl,()=>this.close());this.workbench.onOpen();}
 onClose(){this.workbench?.onClose();}
}
