import {createTopicPreviewLabel,updateTopicPreviewLabel} from './mindmap-preview-label';
import {configureAutomaticTree} from './mindmap-auto';
import {arrangeBranchDepth} from './mindmap-branches';
import {renderTopicRelations} from './mindmap-relations-view';
import {renderPresetGallery} from './mindmap-presets-view';
import {insertPreset} from './mindmap-presets';
import {parseTopicOutline,appendTopicOutline,topicReplacementPlan,applyTopicReplacements,topicThemes,themeTopicTree,topicSvg} from './mindmap-content';
import {markdownEdit} from './markdown-edit';
import {fitTextNode} from './text-tools';
import {connectionPath} from './connections';
import {TopicDraft,TopicAction,editTopic,topicRows,topicLabel} from './mindmap-editor';
import {branchMarkdown} from './mindmap-flow';
import {App,Modal,Notice,setIcon} from 'obsidian';
import {Board,cardFillHex,clone} from './model';
import {branchState,MindmapLayout,mindmapRoot} from './mindmap';
import {MindmapOptions,mindmapLayouts,mindmapPlan,mindmapSignature} from './mindmap-studio';
import {themeSurface} from './ui-tokens';
interface Host {board():Board;selected?:string;apply(board:Board,signature:string,ids:Set<string>):void;outline(id:string):void;}
const ns='http://www.w3.org/2000/svg';let relationScene=0;
export class MindmapStudioModal extends Modal {
 private exportSelected=false;private toolPanel?:HTMLElement;private presenting=false;private beforePresentation?:string;private presentationBar?:HTMLElement;private draggedId?:string;private draft:TopicDraft;private list!:HTMLElement;private editor!:HTMLElement;private rows:ReturnType<typeof topicRows>=[];private query='';private page=0;private searchTimer?:number;private undoButton!:HTMLButtonElement;private redoButton!:HTMLButtonElement;private focused=false;private baseline:Board;private signature:string;private options:MindmapOptions;private rootId:string;private preview!:HTMLElement;private status!:HTMLElement;private applyButton!:HTMLButtonElement;private plan?:ReturnType<typeof mindmapPlan>;private before=false;
 constructor(app:App,private host:Host){super(app);this.baseline=clone(host.board());this.signature=mindmapSignature(this.baseline);const parents=branchState(this.baseline).parents;this.rootId=host.selected||this.baseline.nodes.find(n=>n.topic&&!parents.has(n.id))?.id||this.baseline.nodes.find(n=>n.kind!=='section')?.id||'';if(this.rootId)this.rootId=mindmapRoot(this.baseline,this.rootId);this.draft=new TopicDraft(this.baseline,host.selected||this.rootId);this.options={layout:this.baseline.nodes.find(n=>n.id===this.rootId)?.mindmapRules?.layout||this.baseline.mindmapLayout||this.baseline.mindmapDirection||'bilateral',density:this.baseline.nodes.find(n=>n.id===this.rootId)?.mindmapRules?.density||this.baseline.mindmapDensity||'standard',depth:'keep',rainbow:false};}
 onOpen(){themeSurface(this.modalEl);this.modalEl.addClass('ts-mindmap-studio');this.titleEl.setText('思维导图工作台');this.contentEl.createEl('p',{cls:'ts-mm-intro',text:'组织思路 · 调整结构 · 在白板中继续创作'});
  const actions=this.contentEl.createDiv('ts-mm-workflow-bar');for(const [label,icon,run]of [['预设模板','layout-template',()=>this.openPresets()],['导入大纲','list-tree',()=>this.openTool('import')],['查找替换','replace',()=>this.openTool('replace')],['分支演示','presentation',()=>this.togglePresentation()],['导出 Markdown','file-down',()=>this.download('markdown')],['导出 SVG','image-down',()=>this.download('svg')]] as const){const b=actions.createEl('button',{text:label});const i=b.createSpan();b.prepend(i);setIcon(i,icon);b.onclick=run;}
  const scope=actions.createEl('select',{attr:{'aria-label':'导出范围'}});scope.createEl('option',{value:'tree',text:'导出整棵树'});scope.createEl('option',{value:'branch',text:'导出所选分支'});scope.onchange=()=>this.exportSelected=scope.value==='branch';
  this.modalEl.addEventListener('keydown',e=>{if(!this.presenting)return;if(['ArrowRight','ArrowDown','PageDown','ArrowLeft','ArrowUp','PageUp','Escape'].includes(e.key)){e.preventDefault();e.stopPropagation();if(e.key==='Escape')this.togglePresentation();else this.presentationStep(['ArrowRight','ArrowDown','PageDown'].includes(e.key)?1:-1);}},true);
  const body=this.contentEl.createDiv('ts-mm-body'),controls=body.createDiv('ts-mm-controls');
  const parents=branchState(this.baseline).parents,roots=this.baseline.nodes.filter(n=>n.kind!=='section'&&!parents.has(n.id));
  this.select(controls,'主题树',Object.fromEntries(roots.map(n=>[n.id,(n.text||n.title||n.file||'未命名主题').split('\n')[0].slice(0,50)])),roots.some(n=>n.id===this.rootId)?this.rootId:roots.find(n=>this.treeContains(n.id,this.rootId))?.id||'',value=>{if(this.plan)this.draft.board=this.plan.board;this.rootId=value;this.draft.root=value;this.draft.selected=value;this.page=0;this.focused=false;this.syncRootRules();this.refresh();});
  controls.createEl('h3',{text:'结构'});const layouts=controls.createDiv('ts-mm-layouts');
  for(const [key,label]of Object.entries(mindmapLayouts)){const b=layouts.createEl('button',{text:label,attr:{'data-layout':key,'aria-pressed':String(this.options.layout===key)}});const icon=b.createSpan();b.prepend(icon);setIcon(icon,key==='bilateral'?'git-fork':key==='down'?'network':key==='left'?'arrow-left':'arrow-right');b.onclick=()=>{this.options.layout=key as MindmapLayout;layouts.querySelectorAll('button').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));this.refresh();};}
  this.select(controls,'分支间距',{compact:'紧凑',standard:'标准',relaxed:'舒展'},this.options.density,v=>{this.options.density=v as MindmapOptions['density'];this.refresh();});
  this.select(controls,'展开层级',{keep:'保留当前',all:'全部展开','1':'显示一级','2':'显示二级','3':'显示三级'},'keep',v=>{this.options.depth=v as MindmapOptions['depth'];this.refresh();});
  const row=controls.createEl('label',{cls:'ts-mm-check'}),rainbow=row.createEl('input',{type:'checkbox'});row.createSpan({text:'按一级分支配色'});rainbow.onchange=()=>{this.options.rainbow=rainbow.checked;this.refresh();};
  let preset='classic',line:'curve'|'elbow'|'straight'='curve';const applyTheme=(kind:'palette'|'line')=>{try{if(!this.plan)return;this.draft.commit(themeTopicTree(this.plan.board,this.rootId,kind==='palette'?preset:undefined,kind==='line'?line:undefined));this.options.rainbow=false;rainbow.checked=false;this.afterCommand();}catch(e){this.status.setText(String(e));}};
  this.select(controls,'分支主题',Object.fromEntries(Object.entries(topicThemes).map(([id,t])=>[id,t.name])),preset,v=>{preset=v;applyTheme('palette');});this.select(controls,'连线路径',{curve:'柔和曲线',elbow:'圆角折线',straight:'简洁直线'},line,v=>{line=v as typeof line;applyTheme('line');});
  const automatic=controls.createEl('label',{cls:'ts-mm-check'}),autoInput=automatic.createEl('input',{type:'checkbox',attr:{'aria-label':'自动保持模板布局'}});automatic.createSpan({text:'自动保持模板布局'});autoInput.checked=!!this.draft.board.nodes.find(n=>n.id===this.rootId)?.mindmapRules?.automatic;autoInput.onchange=()=>{try{if(this.plan){this.draft.commit(configureAutomaticTree(this.plan.board,this.draft.selected,autoInput.checked,n=>fitTextNode(n,this.modalEl)));this.afterCommand();}}catch(e){autoInput.checked=!autoInput.checked;this.status.setText(String(e));}};
  const repair=controls.createEl('button',{text:'一键适配模板',cls:'ts-mm-auto-repair'});repair.onclick=()=>{try{if(this.plan){this.draft.commit(configureAutomaticTree(this.plan.board,this.draft.selected,true,n=>fitTextNode(n,this.modalEl)));this.afterCommand();}}catch(e){this.status.setText(String(e));}};
  const branch=controls.createDiv('ts-mm-branch-controls');branch.createEl('small',{text:'所选分支'});for(const [value,title]of [['focus','专注此分支'],['all','全部展开'],['1','展开一级'],['2','展开二级']] as const){const b=branch.createEl('button',{text:title});b.onclick=()=>{try{if(this.plan){this.draft.commit(arrangeBranchDepth(this.plan.board,this.draft.selected,value));this.afterCommand();}}catch(e){this.status.setText(String(e));}};}
  controls.createEl('p',{cls:'ts-mm-help',text:'Tab 子主题 · Enter 同级主题\nShift Enter 换行 · 新标题可直接输入'});
  this.buildOutline(body);
  const right=body.createDiv('ts-mm-scene'),bar=right.createDiv('ts-mm-preview-bar');bar.createSpan({text:'布局预览'});const compare=bar.createEl('button',{text:'查看原布局',attr:{'aria-pressed':'false'}});compare.onclick=()=>{this.before=!this.before;compare.setText(this.before?'返回新布局':'查看原布局');compare.setAttribute('aria-pressed',String(this.before));this.draw();};this.preview=right.createDiv('ts-mm-preview');this.editor=right.createDiv('ts-mm-editor');body.append(controls);
  const zoom=bar.createDiv('ts-mm-preview-actions');this.icon(zoom,'scan','显示整棵树',()=>{this.focused=false;this.draw();});this.icon(zoom,'focus','聚焦所选',()=>{this.focused=true;this.draw();});
  const footer=this.contentEl.createDiv('ts-mm-footer');this.status=footer.createSpan({attr:{role:'status'}});const cancel=footer.createEl('button',{text:'取消'});cancel.onclick=()=>this.close();const outline=footer.createEl('button',{text:'复制 Markdown 大纲'});outline.onclick=async()=>{try{if(this.plan)await navigator.clipboard.writeText(branchMarkdown(this.plan.board,this.rootId));this.status.setText('已复制当前草稿的大纲');}catch(e){new Notice(String(e));}};this.applyButton=footer.createEl('button',{text:'应用到白板',cls:'mod-cta'});this.applyButton.onclick=()=>{try{if(!this.plan)return;this.host.apply(this.plan.board,this.signature,this.plan.ids);this.close();}catch(e){this.status.setText(String(e));new Notice(String(e));}};
  this.refresh();
 }

 private icon(el:HTMLElement,icon:string,label:string,run:()=>void){const b=el.createEl('button',{attr:{'aria-label':label,title:label}});setIcon(b,icon);b.onclick=run;return b;}
 private buildOutline(body:HTMLElement){
  const pane=body.createDiv('ts-mm-outline');body.prepend(pane);const heading=pane.createDiv('ts-mm-outline-heading');heading.createEl('strong',{text:'主题大纲'});
  this.undoButton=this.icon(heading,'undo-2','撤销草稿操作',()=>{this.draft.undo();this.afterCommand();});this.redoButton=this.icon(heading,'redo-2','重做草稿操作',()=>{this.draft.redo();this.afterCommand();});
  const search=pane.createEl('input',{type:'search',attr:{placeholder:'搜索主题、笔记…','aria-label':'搜索导图主题'}});search.addEventListener('compositionstart',()=>{if(this.searchTimer)this.contentEl.win.clearTimeout(this.searchTimer);});search.oninput=e=>{if(this.searchTimer)this.contentEl.win.clearTimeout(this.searchTimer);if((e as InputEvent).isComposing)return;this.searchTimer=this.contentEl.win.setTimeout(()=>{this.query=search.value;this.page=0;this.renderList();},100);};
  this.list=pane.createDiv('ts-mm-topic-list');this.list.setAttribute('role','listbox');this.list.setAttribute('aria-label','主题列表');
  this.list.onkeydown=e=>{if(e.isComposing||!(e.target as Element).closest('.ts-mm-topic-row'))return;const matches=this.matches(),index=matches.findIndex(r=>r.node.id===this.draft.selected);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(e.altKey){this.command(e.key==='ArrowUp'?'up':'down');return;}const next=matches[Math.max(0,Math.min(matches.length-1,index+(e.key==='ArrowDown'?1:-1)))];if(next)this.choose(next.node.id);}
   else if(e.key==='Tab'){e.preventDefault();this.command(e.shiftKey?'outdent':'indent');}else if(e.key==='Enter'){e.preventDefault();this.command('sibling');}
  };
  pane.createDiv({cls:'ts-mm-outline-hint',text:'拖到主题上，移动为其子主题\n↑↓ 选择 · Alt ↑↓ 排序 · Tab 升降级'});
 }
 private matches(){const terms=this.query.normalize('NFKC').toLocaleLowerCase().trim().split(/\s+/);return this.rows.filter(r=>terms.every(w=>(topicLabel(r.node)+' '+(r.node.file||'')).normalize('NFKC').toLocaleLowerCase().includes(w)));}
 private renderList(){if(!this.list)return;this.list.empty();this.undoButton.disabled=!this.draft.canUndo;this.redoButton.disabled=!this.draft.canRedo;const matches=this.matches(),total=matches.length;this.page=Math.min(this.page,Math.max(0,Math.ceil(total/80)-1));
  const pageRows=matches.slice(this.page*80,this.page*80+80),focusId=pageRows.some(r=>r.node.id===this.draft.selected)?this.draft.selected:pageRows[0]?.node.id;
  for(const {node,depth}of pageRows){const row=this.list.createEl('button',{cls:'ts-mm-topic-row',attr:{role:'option','aria-selected':String(node.id===this.draft.selected),'data-topic':node.id,title:topicLabel(node)}});row.style.setProperty('--depth',String(Math.min(depth,6)));row.tabIndex=node.id===focusId?0:-1;const icon=row.createSpan();setIcon(icon,node.branchFolded?'chevron-right':node.kind==='card'?'file-text':'circle');row.createSpan({text:topicLabel(node).replace(/\s+/g,' ')});row.onclick=()=>this.choose(node.id);row.draggable=!node.locked;row.ondragstart=e=>{this.draggedId=node.id;e.dataTransfer?.setData('text/plain',topicLabel(node));};row.ondragend=()=>{this.draggedId=undefined;this.list.querySelectorAll('[data-drop]').forEach(el=>el.removeAttribute('data-drop'));};row.ondragover=e=>{if(this.draggedId&&this.draggedId!==node.id&&!node.locked){e.preventDefault();row.dataset.drop='true';}};row.ondragleave=()=>row.removeAttribute('data-drop');row.ondrop=e=>{e.preventDefault();row.removeAttribute('data-drop');if(this.draggedId){this.draft.selected=this.draggedId;this.draggedId=undefined;this.command('reparent',[node.id]);}};}
  if(!total)this.list.createDiv({cls:'ts-mm-empty',text:'没有匹配的主题'});
  const pager=this.list.createDiv('ts-mm-pager');const prev=this.icon(pager,'chevron-left','上一页主题',()=>{this.page--;this.renderList();});prev.disabled=this.page===0;pager.createSpan({text:`${total} 个主题 · ${this.page+1}/${Math.max(1,Math.ceil(total/80))}`});const next=this.icon(pager,'chevron-right','下一页主题',()=>{this.page++;this.renderList();});next.disabled=(this.page+1)*80>=total;
 }
 private choose(id:string){this.draft.selected=id;if(this.presenting){this.presentationStep(0);this.presentationBar?.querySelector<HTMLButtonElement>('button')?.focus();return;}const index=this.matches().findIndex(r=>r.node.id===id);if(index>=0)this.page=Math.floor(index/80);this.focused=true;this.renderList();this.renderEditor();this.draw();this.list.querySelectorAll<HTMLButtonElement>('[data-topic]').forEach(el=>{if(el.dataset.topic===id)el.focus({preventScroll:true});});}
 private command(action:TopicAction,values?:readonly string[]){try{if(!this.plan)return;if(action==='sibling'&&this.draft.selected===this.rootId)action='child';const labels=values?.length?values:action==='child'?['子主题']:action==='sibling'?['同级主题']:undefined;this.draft.commit(editTopic(this.plan.board,this.draft.selected,action,labels));this.afterCommand();if(['child','sibling','parent'].includes(action)){const input=this.editor.querySelector<HTMLTextAreaElement>('[aria-label="编辑主题文字"]');input?.focus({preventScroll:true});input?.setSelectionRange(0,input.value.length);}}catch(e){this.status.setText(String(e));}}
 private afterCommand(){this.rootId=this.draft.root;this.syncRootRules();this.options.depth='keep';const select=this.contentEl.querySelector<HTMLSelectElement>('[aria-label="展开层级"]');if(select)select.value='keep';this.before=false;const compare=this.contentEl.querySelector<HTMLButtonElement>('.ts-mm-preview-bar>button');if(compare){compare.setText('查看原布局');compare.setAttribute('aria-pressed','false');}this.refresh();const index=this.matches().findIndex(r=>r.node.id===this.draft.selected);if(index>=0){this.page=Math.floor(index/80);this.renderList();this.list.querySelectorAll<HTMLButtonElement>('[data-topic]').forEach(el=>{if(el.dataset.topic===this.draft.selected)el.focus({preventScroll:true});});}}
 private renderEditor(){if(!this.editor)return;this.editor.empty();const node=this.draft.board.nodes.find(n=>n.id===this.draft.selected);if(!node)return;
  const bar=this.editor.createDiv('ts-mm-commandbar');
  for(const [action,icon,label]of [['child','plus','添加子主题'],['sibling','corner-down-right','添加同级主题'],['parent','git-merge','插入父主题'],['up','arrow-up','向上排序'],['down','arrow-down','向下排序'],['indent','indent-increase','降低层级'],['outdent','indent-decrease','提升层级'],['duplicate','copy','复制整个分支'],['fold','fold-vertical','折叠或展开分支'],['promote','ungroup','移除主题并提升子主题']] as const){const b=this.icon(bar,icon,label,()=>this.command(action));b.disabled=!!node.locked;}
  this.icon(bar,'waypoints','管理主题关联',()=>this.openRelations());
  const label=this.editor.createEl('label',{cls:'ts-mm-edit-label',text:node.kind==='text'?'主题文字':'关联材料'});
  if(node.kind==='text'){const input=label.createEl('textarea',{attr:{'aria-label':'编辑主题文字',rows:'2'}});input.value=node.text||'';input.disabled=!!node.locked;input.onkeydown=e=>{if(e.isComposing||e.keyCode===229||e.shiftKey||e.altKey||e.ctrlKey||e.metaKey||!['Tab','Enter'].includes(e.key))return;e.preventDefault();e.stopPropagation();if(e.repeat)return;input.dispatchEvent(new Event('change'));if(this.draft.board.nodes.find(n=>n.id===node.id)?.text!==input.value)return;this.command(e.key==='Tab'?'child':'sibling');};const format=this.editor.createDiv('ts-mm-markdown-tools');for(const [label,icon,cmd]of [['粗体','bold','bold'],['斜体','italic','italic'],['行内代码','code','code'],['标题','heading-2','h2'],['任务','list-todo','task'],['链接','link','link']] as const){const b=this.icon(format,icon,label,()=>{input.dispatchEvent(new Event('change'));const edit=markdownEdit(input.value,input.selectionStart,input.selectionEnd,cmd);input.value=edit.text;input.setSelectionRange(edit.start,edit.end);input.focus();input.dispatchEvent(new Event('change'));});b.onmousedown=e=>e.preventDefault();b.disabled=!!node.locked;}input.onchange=()=>{try{if(input.value===this.draft.board.nodes.find(n=>n.id===node.id)?.text)return;if(this.plan)this.draft.board=this.plan.board;this.draft.rename(input.value,n=>fitTextNode(n,this.modalEl));this.rows=topicRows(this.draft.board,this.rootId);this.plan=mindmapPlan(this.draft.board,this.rootId,this.options);this.list.querySelectorAll<HTMLElement>('[data-topic]').forEach(el=>{if(el.dataset.topic===node.id){el.title=input.value;el.lastElementChild!.textContent=input.value.replace(/\s+/g,' ');}});if(!this.before)this.patchPreview();this.undoButton.disabled=!this.draft.canUndo;this.redoButton.disabled=!this.draft.canRedo;this.status.setText('文字已暂存，应用后写入白板');}catch(e){input.value=this.draft.board.nodes.find(n=>n.id===node.id)?.text||'';this.status.setText(String(e));}};}
  else {label.createSpan({text:node.file||topicLabel(node)});if(node.file){const open=this.editor.createEl('button',{text:'在 Obsidian 中打开原文'});open.onclick=()=>{void this.app.workspace.openLinkText(node.file!,'','split').catch(e=>new Notice(String(e)));};}}
  const details=this.editor.createEl('details',{cls:'ts-mm-batch'});details.createEl('summary',{text:'批量添加子主题'});const input=details.createEl('textarea',{attr:{'aria-label':'批量子主题',placeholder:'每行一个主题，最多 100 个',rows:'3'}});const add=details.createEl('button',{text:'添加到所选主题'});add.onclick=()=>this.command('child',input.value.split(/\r?\n/));
 }
 private openRelations(){if(!this.plan)return;this.closeTool();const body=this.contentEl.querySelector<HTMLElement>('.ts-mm-body')!;body.hidden=true;this.applyButton.disabled=true;const panel=this.contentEl.createDiv('ts-mm-tool-sheet');this.toolPanel=panel;body.before(panel);const head=panel.createDiv('ts-mm-tool-head');head.createEl('h3',{text:'连接相关的观点'});head.createEl('button',{text:'返回导图'}).onclick=()=>this.closeTool();renderTopicRelations(panel,this.plan.board,this.draft.selected,result=>{this.draft.commit(result);this.closeTool();this.afterCommand();});}
 private openPresets(){this.closeTool();const body=this.contentEl.querySelector<HTMLElement>('.ts-mm-body')!;body.hidden=true;this.applyButton.disabled=true;const panel=this.contentEl.createDiv('ts-mm-tool-sheet');this.toolPanel=panel;body.before(panel);const head=panel.createDiv('ts-mm-tool-head');head.createEl('h3',{text:'预设思维导图'});head.createEl('button',{text:'返回导图'}).onclick=()=>this.closeTool();renderPresetGallery(panel,'添加为独立主题树',board=>{this.draft.commit(insertPreset(this.plan?.board||this.draft.board,board));this.options.layout=board.mindmapLayout||'bilateral';this.options.density='standard';this.closeTool();this.afterCommand();this.contentEl.querySelectorAll<HTMLButtonElement>('.ts-mm-layouts button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===this.options.layout)));const density=this.contentEl.querySelector<HTMLSelectElement>('[aria-label="分支间距"]');if(density)density.value='standard';});}
 private openTool(mode:'import'|'replace'){
  this.closeTool();const body=this.contentEl.querySelector<HTMLElement>('.ts-mm-body')!;body.hidden=true;this.applyButton.disabled=true;
  const panel=this.contentEl.createDiv('ts-mm-tool-sheet');this.toolPanel=panel;body.before(panel);const head=panel.createDiv('ts-mm-tool-head');head.createEl('h3',{text:mode==='import'?'从大纲生长一棵树':'查找与替换主题'});const back=head.createEl('button',{text:'返回导图'});back.onclick=()=>this.closeTool();
  const columns=panel.createDiv('ts-mm-tool-columns'),fields=columns.createDiv('ts-mm-tool-fields'),preview=columns.createDiv('ts-mm-tool-preview');preview.setAttribute('aria-live','polite');
  const controls=panel.createDiv('ts-mm-tool-actions'),show=controls.createEl('button',{text:'预览变化'}),confirm=controls.createEl('button',{text:'加入草稿',cls:'mod-cta'});confirm.disabled=true;
  let commit:(()=>void|Promise<void>)|undefined;const invalid=()=>{confirm.disabled=true;commit=undefined;preview.empty();};
  const field=(label:string,placeholder='')=>{const row=fields.createEl('label',{cls:'ts-mm-field'});row.createSpan({text:label});const input=row.createEl('textarea',{attr:{'aria-label':label,placeholder,rows:mode==='import'?'12':'2'}});input.oninput=invalid;return input;};
  if(mode==='import'){
   fields.createEl('p',{text:'导入为当前所选主题的子分支。标题建立层级，正文与代码保留在主题中。',cls:'ts-mm-help'});
   const format=fields.createEl('select',{attr:{'aria-label':'大纲格式'}});format.createEl('option',{value:'markdown',text:'Markdown 标题与列表'});format.createEl('option',{value:'indent',text:'缩进文本'});format.onchange=invalid;
   const input=field('待导入的大纲','# 项目计划\n## 目标\n- 第一项\n- 第二项');
   show.onclick=()=>{try{const items=parseTopicOutline(input.value,format.value as 'markdown'|'indent'),signature=mindmapSignature(this.draft.board),parent=this.draft.selected;preview.empty();preview.createEl('strong',{text:`${items.length} 个主题 · 最深 ${Math.max(...items.map(i=>i.depth))+1} 层`});for(const item of items.slice(0,40)){const row=preview.createDiv({cls:'ts-mm-import-row',text:item.text.split('\n')[0]});row.style.paddingLeft=`${Math.min(8,item.depth)*14}px`;}if(items.length>40)preview.createEl('small',{text:'预览显示前 40 项，导入保留全部主题。'});
    commit=()=>{if(mindmapSignature(this.draft.board)!==signature)throw Error('草稿已变化，请重新预览');this.draft.commit(appendTopicOutline(this.plan?.board||this.draft.board,parent,items));};confirm.disabled=false;
   }catch(e){invalid();preview.setText(String(e));}};
  }else{
   fields.createEl('p',{text:'范围：白板文字主题。支持区分大小写和整词匹配。',cls:'ts-mm-help'});
   const scope=fields.createEl('select',{attr:{'aria-label':'替换范围'}});scope.createEl('option',{value:'tree',text:'当前主题树'});scope.createEl('option',{value:'branch',text:'所选分支'});scope.onchange=invalid;
   const query=field('查找文字'),replacement=field('替换为');const checks=fields.createDiv('ts-mm-replace-checks');
   const toggle=(name:string)=>{const row=checks.createEl('label');const input=row.createEl('input',{type:'checkbox',attr:{'aria-label':name}});row.createSpan({text:name});input.onchange=invalid;return input;};const caseSensitive=toggle('区分大小写'),wholeWord=toggle('整词匹配');
   show.onclick=()=>{try{const root=scope.value==='branch'?this.draft.selected:this.rootId,changes=topicReplacementPlan(this.draft.board,root,query.value,replacement.value,caseSensitive.checked,wholeWord.checked);preview.empty();preview.createEl('strong',{text:`${changes.length} 个主题 · ${changes.reduce((n,c)=>n+c.count,0)} 处匹配`});for(const change of changes.slice(0,25)){const row=preview.createDiv('ts-mm-replace-row');row.createEl('small',{text:'原文'});row.createEl('pre',{text:change.before.slice(0,400)});row.createEl('small',{text:'替换后'});row.createEl('pre',{text:change.after.slice(0,400)});}if(changes.length>25)preview.createEl('small',{text:'预览显示前 25 个主题，全部匹配将在确认后加入草稿。'});
    commit=async()=>{const source=this.plan?.board||this.draft.board,signature=mindmapSignature(this.draft.board),nodes=new Map(source.nodes.map(n=>[n.id,n])),sizes=new Map<string,{width:number;height:number}>();
     for(let i=0;i<changes.length;i++){if(this.toolPanel!==panel)return;const c=changes[i],original=nodes.get(c.id);if(!original)throw Error('主题已变化，请重新预览');const n={...original,text:c.after};fitTextNode(n,this.modalEl);sizes.set(c.id,{width:n.width,height:n.height});if(i%25===24)await new Promise<void>(resolve=>this.contentEl.win.requestAnimationFrame(()=>resolve()));}
     if(this.toolPanel!==panel)return;if(mindmapSignature(this.draft.board)!==signature)throw Error('草稿已变化，请重新预览');this.draft.commit(applyTopicReplacements(source,root,changes,n=>Object.assign(n,sizes.get(n.id))));};confirm.disabled=!changes.length;
   }catch(e){invalid();preview.setText(String(e));}};
  }
  confirm.onclick=async()=>{if(!commit)return;confirm.disabled=true;show.disabled=true;fields.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('input,select,textarea').forEach(el=>el.disabled=true);try{await commit();if(this.toolPanel!==panel)return;this.closeTool();this.afterCommand();}catch(e){if(this.toolPanel===panel){preview.setText(String(e));confirm.disabled=true;show.disabled=false;fields.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('input,select,textarea').forEach(el=>el.disabled=false);}}};
 }
 private closeTool(){this.toolPanel?.remove();this.toolPanel=undefined;const body=this.contentEl.querySelector<HTMLElement>('.ts-mm-body');if(body)body.hidden=false;if(this.applyButton)this.applyButton.disabled=!this.plan;}
 private download(kind:'markdown'|'svg'){
  try{if(!this.plan)return;const root=this.exportSelected?this.draft.selected:this.rootId,content=kind==='svg'?topicSvg(this.plan.board,root):branchMarkdown(this.plan.board,root),blob=new Blob([content],{type:kind==='svg'?'image/svg+xml;charset=utf-8':'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=this.contentEl.createEl('a');a.href=url;a.download='思维导图.'+(kind==='svg'?'svg':'md');a.click();a.remove();this.contentEl.win.setTimeout(()=>URL.revokeObjectURL(url),1000);this.status.setText('已导出当前草稿');}catch(e){this.status.setText(String(e));}
 }
 private togglePresentation(){
  if(this.presenting){this.presenting=false;this.modalEl.classList.remove('is-presenting');this.presentationBar?.remove();this.presentationBar=undefined;this.draft.selected=this.beforePresentation||this.rootId;this.focused=false;this.renderList();this.renderEditor();this.draw();return;}
  this.closeTool();this.presenting=true;this.beforePresentation=this.draft.selected;this.before=false;const compare=this.contentEl.querySelector<HTMLButtonElement>('.ts-mm-preview-bar>button');if(compare){compare.setText('查看原布局');compare.setAttribute('aria-pressed','false');}this.modalEl.classList.add('is-presenting');const bar=this.contentEl.createDiv('ts-mm-presentation-bar');this.presentationBar=bar;this.contentEl.querySelector('.ts-mm-body')!.before(bar);
  this.icon(bar,'chevron-left','上一主题',()=>this.presentationStep(-1));bar.createSpan({cls:'ts-mm-slide-title'});this.icon(bar,'chevron-right','下一主题',()=>this.presentationStep(1));const end=bar.createEl('button',{text:'结束演示'});end.onclick=()=>this.togglePresentation();this.presentationStep(0);bar.querySelector<HTMLButtonElement>('button')?.focus();
 }
 private presentationStep(delta:number){const rows=this.rows;if(!rows.length)return;const index=Math.max(0,Math.min(rows.length-1,rows.findIndex(r=>r.node.id===this.draft.selected)+delta)),n=rows[index].node;this.draft.selected=n.id;this.focused=true;this.presentationBar?.querySelector('.ts-mm-slide-title')?.setText(`${index+1} / ${rows.length} · ${topicLabel(n).split('\n')[0]}`);this.draw();}

 private treeContains(root:string,id:string){const {parents}=branchState(this.baseline);let current:string|undefined=id;while(current){if(current===root)return true;current=parents.get(current);}return false;}
 private select(el:HTMLElement,label:string,choices:Record<string,string>,value:string,change:(value:string)=>void){const row=el.createEl('label',{cls:'ts-mm-field'});row.createSpan({text:label});const s=row.createEl('select',{attr:{'aria-label':label}});for(const [key,text]of Object.entries(choices))s.createEl('option',{value:key,text});s.value=value;s.onchange=()=>change(s.value);}
 private syncRootRules(){const rules=this.draft.board.nodes.find(n=>n.id===this.rootId)?.mindmapRules;if(rules){this.options.layout=rules.layout;this.options.density=rules.density;}this.contentEl.querySelectorAll<HTMLButtonElement>('.ts-mm-layouts button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===this.options.layout)));const density=this.contentEl.querySelector<HTMLSelectElement>('[aria-label="分支间距"]');if(density)density.value=this.options.density;const automatic=this.contentEl.querySelector<HTMLInputElement>('[aria-label="自动保持模板布局"]');if(automatic)automatic.checked=!!rules?.automatic;}
 private refresh(){try{this.plan=mindmapPlan(this.draft.board,this.rootId,this.options);this.status.setText(`${this.plan.ids.size} 个主题 · 可撤销`);this.applyButton.disabled=false;this.rows=topicRows(this.draft.board,this.rootId);const select=this.contentEl.querySelector<HTMLSelectElement>('[aria-label="主题树"]');if(select){select.empty();const parents=branchState(this.draft.board).parents;for(const n of this.draft.board.nodes)if(n.kind!=='section'&&!parents.has(n.id))select.createEl('option',{value:n.id,text:topicLabel(n).slice(0,50)});select.value=this.rootId;}this.renderList();this.renderEditor();this.draw();}catch(e){this.plan=undefined;this.applyButton.disabled=true;this.preview.empty();this.editor?.empty();this.list?.empty();this.status.setText(String(e));}}
 /** Update geometry in place: a blur must not remove the node receiving the click. */
 private patchPreview(){if(!this.plan)return;const board=this.plan.board,nodes=new Map(board.nodes.map(n=>[n.id,n]));let x=Infinity,y=Infinity,right=-Infinity,bottom=-Infinity;
  this.preview.querySelectorAll<SVGRectElement>('rect[data-node-id]').forEach(el=>{const n=nodes.get(el.dataset.nodeId!);if(!n)return;for(const k of ['x','y','width','height'] as const)el.setAttribute(k,String(n[k]));x=Math.min(x,n.x);y=Math.min(y,n.y);right=Math.max(right,n.x+n.width);bottom=Math.max(bottom,n.y+n.height);});
  const edges=new Map(board.edges.map(e=>[e.id,e]));this.preview.querySelectorAll<SVGPathElement>('[data-edge-id]').forEach(el=>{const edge=edges.get(el.dataset.edgeId!),a=edge&&nodes.get(edge.from),b=edge&&nodes.get(edge.to);if(edge&&a&&b)el.setAttribute('d',connectionPath(a,b,edge).path);});
  this.preview.querySelectorAll<SVGTextElement>('[data-relation-label]').forEach(el=>{const e=edges.get(el.dataset.relationLabel!),a=e&&nodes.get(e.from),b=e&&nodes.get(e.to);if(e&&a&&b){const p=connectionPath(a,b,e).label;el.setAttribute('x',String(p.x));el.setAttribute('y',String(p.y-8));}});
  this.preview.querySelectorAll<SVGForeignObjectElement>('[data-topic-label]').forEach(el=>{const n=nodes.get(el.dataset.topicLabel!);if(n)updateTopicPreviewLabel(el,n);});
  if(Number.isFinite(x))this.preview.querySelector('svg')?.setAttribute('viewBox',`${x-30} ${y-30} ${right-x+60} ${bottom-y+60}`);
 }
 private previewGestures(svg:SVGSVGElement,initial:{x:number;y:number;width:number;height:number}){
  let box={...initial},drag:{x:number;y:number;box:typeof initial;id:number}|undefined;
  const sync=()=>{const v=svg.viewBox.baseVal;box={x:v.x,y:v.y,width:v.width,height:v.height};};
  const render=()=>svg.setAttribute('viewBox',`${box.x} ${box.y} ${box.width} ${box.height}`);
  svg.addEventListener('wheel',e=>{e.preventDefault();e.stopPropagation();sync();const r=svg.getBoundingClientRect(),scale=Math.max(box.width/r.width,box.height/r.height),px=box.x+box.width/2+(e.clientX-r.left-r.width/2)*scale,py=box.y+box.height/2+(e.clientY-r.top-r.height/2)*scale,factor=Math.exp(Math.max(-200,Math.min(200,e.deltaY))*.002),width=Math.min(initial.width*3,Math.max(initial.width/8,box.width*factor)),ratio=width/box.width;box={x:px+(box.x-px)*ratio,y:py+(box.y-py)*ratio,width,height:box.height*ratio};render();},{passive:false});
  svg.addEventListener('pointerdown',e=>{if(e.button!==0||(e.target as Element).tagName==='rect')return;sync();drag={x:e.clientX,y:e.clientY,box:{...box},id:e.pointerId};svg.setPointerCapture(e.pointerId);});
  svg.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const r=svg.getBoundingClientRect(),scale=Math.max(drag.box.width/r.width,drag.box.height/r.height);box={...drag.box,x:drag.box.x-(e.clientX-drag.x)*scale,y:drag.box.y-(e.clientY-drag.y)*scale};render();});
  const stop=()=>{drag=undefined;};svg.addEventListener('pointerup',stop);svg.addEventListener('pointercancel',stop);svg.addEventListener('lostpointercapture',stop);
 }
 private draw(){this.preview.empty();if(!this.plan)return;const board=this.before?this.baseline:this.plan.board,{hidden}=branchState(board);let ids=this.plan.ids;
  if(this.before){const origin=this.plan.board.nodes.find(n=>ids.has(n.id)&&this.baseline.nodes.some(old=>old.id===n.id));if(!origin)return;ids=new Set(topicRows(this.baseline,mindmapRoot(this.baseline,origin.id)).map(r=>r.node.id));}
  const all=board.nodes.filter(n=>ids.has(n.id)&&!hidden.has(n.id));if(!all.length)return;
  const selected=board.nodes.find(n=>n.id===this.draft.selected),nodes=this.focused&&selected?all.filter(n=>Math.abs(n.x-selected.x)<1500&&Math.abs(n.y-selected.y)<1100).slice(0,1200):all.slice(0,1200);if(this.presenting&&selected){const {children,parents}=branchState(board),ids=new Set([selected.id,...children.get(selected.id)||[],parents.get(selected.id)]);const subset=nodes.filter(n=>ids.has(n.id));nodes.splice(0,nodes.length,...subset);}
  if(this.focused&&selected&&!nodes.some(n=>n.id===selected.id)){nodes.unshift(selected);if(nodes.length>1200)nodes.pop();}
  const byId=new Map(nodes.map(n=>[n.id,n])),minX=Math.min(...nodes.map(n=>n.x))-30,minY=Math.min(...nodes.map(n=>n.y))-30,maxX=Math.max(...nodes.map(n=>n.x+n.width))+30,maxY=Math.max(...nodes.map(n=>n.y+n.height))+30;
  const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`${minX} ${minY} ${maxX-minX} ${maxY-minY}`);const markerId=`ts-mm-relation-${++relationScene}`,defs=document.createElementNS(ns,'defs'),marker=document.createElementNS(ns,'marker');for(const [k,v]of Object.entries({id:markerId,viewBox:'0 0 10 10',refX:'9',refY:'5',markerWidth:'5',markerHeight:'5',orient:'auto-start-reverse'}))marker.setAttribute(k,v);const arrow=document.createElementNS(ns,'path');arrow.setAttribute('d','M 0 0 L 10 5 L 0 10 z');arrow.setAttribute('fill','var(--text-muted)');marker.append(arrow);defs.append(marker);svg.append(defs);svg.setAttribute('role','img');
  // Native aria-label tooltips assume HTMLElement; SVG names use linked titles.
  const title=document.createElementNS(ns,'title'),titleId=`${markerId}-title`;title.setAttribute('id',titleId);title.textContent=this.before?'原思维导图布局':'新思维导图布局';svg.append(title);svg.setAttribute('aria-labelledby',titleId);this.preview.append(svg);this.previewGestures(svg,{x:minX,y:minY,width:maxX-minX,height:maxY-minY});
  // Preview is bounded; layout and application retain the complete tree.
  const visible=new Set(nodes.slice(0,1200).map(n=>n.id));for(const e of board.edges){const a=byId.get(e.from),b=byId.get(e.to);if(!a||!b||!visible.has(a.id)||!visible.has(b.id))continue;const path=document.createElementNS(ns,'path');path.dataset.edgeId=e.id;path.setAttribute('d',connectionPath(a,b,e).path);path.setAttribute('stroke',cardFillHex[e.color||b.color]);path.setAttribute('fill','none');path.setAttribute('stroke-width',e.kind==='branch'?'3':'2');if(e.kind!=='branch'){path.dataset.relationId=e.id;path.setAttribute('stroke',e.color?cardFillHex[e.color]:'var(--text-muted)');if(e.dashed)path.setAttribute('stroke-dasharray','7 5');if(e.direction!=='none')path.setAttribute('marker-end',`url(#${markerId})`);if(e.direction==='both')path.setAttribute('marker-start',`url(#${markerId})`);if(e.label&&nodes.length<150){const pos=connectionPath(a,b,e).label,text=document.createElementNS(ns,'text');text.dataset.relationLabel=e.id;text.setAttribute('x',String(pos.x));text.setAttribute('y',String(pos.y-8));text.setAttribute('text-anchor','middle');text.textContent=e.label.slice(0,80);svg.append(text);}}svg.append(path);}
  for(const n of nodes.slice(0,1200)){const rect=document.createElementNS(ns,'rect');for(const [key,value]of Object.entries({x:n.x,y:n.y,width:n.width,height:n.height,rx:12}))rect.setAttribute(key,String(value));rect.setAttribute('fill','var(--background-primary)');rect.setAttribute('stroke',n.id===this.draft.selected?'var(--interactive-accent)':cardFillHex[n.color]);rect.dataset.nodeId=n.id;rect.setAttribute('cursor','pointer');rect.addEventListener('click',()=>{if(this.draft.board.nodes.some(node=>node.id===n.id))this.choose(n.id);});rect.setAttribute('stroke-width','3');svg.append(rect);if(nodes.length<150)createTopicPreviewLabel(svg,n);}
  if(all.length>1200)this.preview.createEl('small',{text:'预览最多显示 1,200 个主题；在大纲搜索并聚焦，可查看任意主题。'});
 }
 onClose(){this.toolPanel=undefined;this.presentationBar=undefined;if(this.searchTimer)this.contentEl.win.clearTimeout(this.searchTimer);this.contentEl.empty();}
}
