import {App,Modal,Notice,setIcon} from 'obsidian';
import {PaperPreferences,cleanPaperPreferences,paperAppearanceStamp,paperBaseColor,paperPresets} from './paper-appearance';
import {themeSurface} from './ui-tokens';

export interface PaperSettingsHost {preferences:()=>PaperPreferences;save:(preferences:PaperPreferences)=>Promise<void>;}
const previewInk=(color:string)=>{const channels=[1,3,5].map(at=>parseInt(color.slice(at,at+2),16)/255).map(value=>value<=.04045?value/12.92:Math.pow((value+.055)/1.055,2.4));return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722>.179?'#403b32':'#f4f0e6';};
/** Changes stay in this dialog until Apply; native Modal selection state is untouched. */
export class PaperSettingsModal extends Modal {
 private paperDraft:PaperPreferences=cleanPaperPreferences(undefined);private paperBaseline='';private paperBusy=false;private paperClosed=false;private paperInvalidColor=false;private paperConflict=false;private paperLoadFailed=false;private paperRun=0;
 private paperSwatches=new Map<PaperPreferences['paperPreset'],HTMLButtonElement>();private paperCustom!:HTMLButtonElement;private paperPicker!:HTMLInputElement;private paperHex!:HTMLInputElement;private paperSlider!:HTMLInputElement;private paperStrength!:HTMLOutputElement;private paperPreview!:HTMLElement;private paperStatus!:HTMLElement;private paperApply!:HTMLButtonElement;private paperReload!:HTMLButtonElement;
 constructor(app:App,private paperHost:PaperSettingsHost){super(app);}
 private paperButton(parent:HTMLElement,label:string,run:()=>void,cls=''){const button=parent.createEl('button',{text:label,cls,attr:{'aria-label':label}});button.onclick=()=>{if(!this.paperClosed&&!this.paperBusy)run();};return button;}
 onOpen(){this.paperRun++;this.paperClosed=false;this.paperBusy=false;this.paperInvalidColor=false;this.paperConflict=false;this.paperLoadFailed=false;this.paperSwatches.clear();this.contentEl.empty();themeSurface(this.modalEl);this.modalEl.addClass('ts-paper-settings');this.titleEl.setText('纸张与纹理');
  this.contentEl.createEl('p',{cls:'ts-paper-intro',text:'选一张喜欢的纸，让想法自然落笔。'});
  const body=this.contentEl.createDiv('ts-paper-settings-body'),controls=body.createDiv('ts-paper-controls');controls.createEl('h3',{text:'纸张颜色'});
  const swatches=controls.createDiv({cls:'ts-paper-swatches',attr:{role:'group','aria-label':'纸张颜色预设'}});
  for(const preset of Object.keys(paperPresets) as PaperPreferences['paperPreset'][]){if(preset==='custom')continue;const item=paperPresets[preset],button=this.paperButton(swatches,item.name,()=>{this.paperDraft.paperPreset=preset;this.paperInvalidColor=false;this.paperHex.value=this.paperDraft.paperColor;this.paperStatus.setText('');this.paperSync();},'ts-paper-swatch');button.style.setProperty('--ts-paper-swatch-color',item.color);button.setAttribute('data-paper-preset',preset);const chip=button.createSpan('ts-paper-swatch-chip');button.prepend(chip);this.paperSwatches.set(preset,button);}
  const custom=controls.createDiv('ts-paper-custom-row');this.paperCustom=this.paperButton(custom,'自定义纸色',()=>{this.paperDraft.paperPreset='custom';this.paperSync();},'ts-paper-custom-label');this.paperPicker=custom.createEl('input',{type:'color',attr:{'aria-label':'选择自定义纸张颜色'}});this.paperHex=custom.createEl('input',{type:'text',attr:{'aria-label':'自定义纸色十六进制代码',placeholder:'#f3e9d4',maxlength:'7',spellcheck:'false'}});
  this.paperPicker.oninput=()=>{if(this.paperClosed||this.paperBusy)return;this.paperDraft.paperColor=this.paperPicker.value.toLowerCase();this.paperDraft.paperPreset='custom';this.paperHex.value=this.paperDraft.paperColor;this.paperInvalidColor=false;this.paperStatus.setText('');this.paperSync();};
  this.paperHex.oninput=()=>{if(this.paperClosed||this.paperBusy)return;const value=this.paperHex.value.trim().toLowerCase();this.paperInvalidColor=!/^#[0-9a-f]{6}$/.test(value);if(!this.paperInvalidColor){this.paperDraft.paperColor=value;this.paperDraft.paperPreset='custom';this.paperStatus.setText('');}else this.paperStatus.setText('请填写完整的颜色代码，例如 #f3e9d4。');this.paperSync();};
  const texture=controls.createDiv('ts-paper-texture-control'),label=texture.createEl('label');label.createSpan({text:'纹理强度'});this.paperStrength=label.createEl('output',{attr:{'aria-live':'polite'}});this.paperSlider=texture.createEl('input',{type:'range',attr:{min:'0',max:'100',step:'1','aria-label':'纸张纹理强度'}});this.paperSlider.oninput=()=>{if(this.paperClosed||this.paperBusy)return;this.paperDraft.paperTexture=cleanPaperPreferences({...this.paperDraft,paperTexture:Number(this.paperSlider.value)}).paperTexture;this.paperSync();};const limits=texture.createDiv('ts-paper-texture-limits');limits.createSpan({text:'平滑纯色'});limits.createSpan({text:'明显纸纹'});
  const scene=body.createDiv('ts-paper-preview-pane');scene.createDiv({cls:'ts-paper-preview-heading',text:'纸面预览'});this.paperPreview=scene.createDiv({cls:'ts-paper-preview',attr:{'aria-label':'纸色与纹理预览'}});const content=this.paperPreview.createDiv('ts-paper-preview-content');content.createSpan({cls:'ts-paper-preview-caption',text:'灵感手记'});content.createEl('h3',{text:'从一个想法开始'});content.createEl('p',{text:'记录眼前的线索，留一点空白给接下来的思考。'});const note=content.createDiv('ts-paper-preview-note');setIcon(note.createSpan(),'sprout');note.createSpan({text:'让思绪在纸上生长'});scene.createDiv({cls:'ts-paper-preview-hint',text:'拖动滑条，即时感受纸纹的变化。'});
  this.paperStatus=this.contentEl.createDiv({cls:'ts-paper-settings-status',attr:{role:'status','aria-live':'polite'}});
  const footer=this.contentEl.createDiv('ts-paper-settings-footer');this.paperReload=this.paperButton(footer,'载入当前设置',()=>this.paperLoad(),'ts-paper-reload');this.paperReload.hidden=true;const cancel=footer.createEl('button',{text:'取消'});cancel.onclick=()=>{if(!this.paperClosed)this.close();};this.paperApply=this.paperButton(footer,'应用',()=>{void this.paperSave();},'mod-cta');
  this.contentEl.onkeydown=event=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey)&&!event.altKey&&!event.shiftKey&&!event.isComposing&&event.keyCode!==229){event.preventDefault();if(!this.paperApply.disabled)void this.paperSave();}};
  this.paperLoad();
 }
 private paperLoad(){if(this.paperClosed||this.paperBusy)return;try{this.paperDraft=cleanPaperPreferences(this.paperHost.preferences());this.paperBaseline=paperAppearanceStamp(this.paperDraft);this.paperConflict=false;this.paperLoadFailed=false;this.paperInvalidColor=false;this.paperHex.value=this.paperDraft.paperColor;this.paperStatus.setText('');this.paperSync();}catch(error){this.paperLoadFailed=true;this.paperStatus.setText(String(error).replace(/^Error: /,''));this.paperSync();}}
 private paperSync(){if(this.paperClosed)return;for(const[preset,button]of this.paperSwatches){button.setAttribute('aria-pressed',String(this.paperDraft.paperPreset===preset));button.disabled=this.paperBusy||this.paperLoadFailed;}this.paperCustom.setAttribute('aria-pressed',String(this.paperDraft.paperPreset==='custom'));this.paperCustom.disabled=this.paperPicker.disabled=this.paperHex.disabled=this.paperSlider.disabled=this.paperBusy||this.paperLoadFailed;
  this.paperPicker.value=this.paperDraft.paperColor;this.paperHex.setAttribute('aria-invalid',String(this.paperInvalidColor));this.paperSlider.value=String(this.paperDraft.paperTexture);this.paperStrength.setText(`${this.paperDraft.paperTexture}%`);const color=paperBaseColor(this.paperDraft);this.paperPreview.style.setProperty('--ts-paper-color',color);this.paperPreview.style.setProperty('--ts-paper-texture',String(this.paperDraft.paperTexture/100));this.paperPreview.style.setProperty('--ts-paper-preview-ink',previewInk(color));
  this.paperApply.disabled=this.paperBusy||this.paperInvalidColor||this.paperConflict||this.paperLoadFailed;this.paperApply.setText(this.paperBusy?'正在应用…':'应用');this.paperReload.hidden=!this.paperConflict&&!this.paperLoadFailed;this.paperReload.disabled=this.paperBusy;
 }
 private async paperSave(){if(this.paperClosed||this.paperBusy||this.paperApply.disabled)return;
  try{const current=cleanPaperPreferences(this.paperHost.preferences());if(paperAppearanceStamp(current)!==this.paperBaseline){this.paperConflict=true;this.paperStatus.setText('纸张设置已在其他窗口改变。请载入当前设置后重新调整。');this.paperSync();return;}}
  catch(error){this.paperStatus.setText(String(error).replace(/^Error: /,''));return;}
  const next=cleanPaperPreferences(this.paperDraft),run=this.paperRun;this.paperBusy=true;this.paperStatus.setText('正在保存纸张设置…');this.paperSync();
  try{await this.paperHost.save(next);if(this.paperClosed||run!==this.paperRun)return;this.paperBusy=false;this.close();}
  catch(error){const message=`纸张设置保存失败：${String(error).replace(/^Error: /,'')}`;if(this.paperClosed||run!==this.paperRun){new Notice(message);return;}this.paperBusy=false;this.paperStatus.setText(`${message}。可以重试。`);this.paperSync();}
 }
 onClose(){this.paperRun++;this.paperClosed=true;this.paperSwatches.clear();this.contentEl.onkeydown=null;this.contentEl.empty();}
}
