import {App,Modal,Notice,setIcon} from 'obsidian';
import {PaperPreferences,cleanPaperPreferences,paperAppearanceStamp,paperBaseColor,paperPresets} from './paper-appearance';
import {themeSurface} from './ui-tokens';

export interface PaperSettingsHost {stamp?:()=>string;language?:'zh-CN'|'en';preferences:()=>PaperPreferences;save:(preferences:PaperPreferences)=>Promise<void>;}
const paperPresetEnglish:Record<PaperPreferences['paperPreset'],string>={cream:'Cream paper',white:'White paper',ivory:'Ivory paper',kraft:'Kraft paper',recycled:'Recycled paper',custom:'Custom'};
const previewInk=(color:string)=>{const channels=[1,3,5].map(at=>parseInt(color.slice(at,at+2),16)/255).map(value=>value<=.04045?value/12.92:Math.pow((value+.055)/1.055,2.4));return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722>.179?'#403b32':'#f4f0e6';};
/** Changes stay in this dialog until Apply; native Modal selection state is untouched. */
export class PaperSettingsModal extends Modal {
 private paperDraft:PaperPreferences=cleanPaperPreferences(undefined);private paperBaseline='';private paperBusy=false;private paperClosed=false;private paperInvalidColor=false;private paperConflict=false;private paperLoadFailed=false;private paperRun=0;
 private paperSwatches=new Map<PaperPreferences['paperPreset'],HTMLButtonElement>();private paperCustom!:HTMLButtonElement;private paperPicker!:HTMLInputElement;private paperHex!:HTMLInputElement;private paperSlider!:HTMLInputElement;private paperStrength!:HTMLOutputElement;private paperPreview!:HTMLElement;private paperStatus!:HTMLElement;private paperApply!:HTMLButtonElement;private paperReload!:HTMLButtonElement;
 constructor(app:App,private paperHost:PaperSettingsHost){super(app);}
 private paperText(zh:string,en:string){return this.paperHost.language==='en'?en:zh;}
 private paperButton(parent:HTMLElement,label:string,run:()=>void,cls=''){const button=parent.createEl('button',{text:label,cls,attr:{'aria-label':label}});button.onclick=()=>{if(!this.paperClosed&&!this.paperBusy)run();};return button;}
 onOpen(){const t=(zh:string,en:string)=>this.paperText(zh,en);this.paperRun++;this.paperClosed=false;this.paperBusy=false;this.paperInvalidColor=false;this.paperConflict=false;this.paperLoadFailed=false;this.paperSwatches.clear();this.contentEl.empty();themeSurface(this.modalEl);this.modalEl.addClass('ts-paper-settings');this.titleEl.setText(t('纸张与纹理','Paper and texture'));
  const body=this.contentEl.createDiv('ts-paper-settings-body'),controls=body.createDiv('ts-paper-controls');controls.createEl('h3',{text:t('纸张颜色','Paper color')});
  const swatches=controls.createDiv({cls:'ts-paper-swatches',attr:{role:'group','aria-label':t('纸张颜色预设','Paper color presets')}});
  for(const preset of Object.keys(paperPresets) as PaperPreferences['paperPreset'][]){if(preset==='custom')continue;const item=paperPresets[preset],button=this.paperButton(swatches,t(item.name,paperPresetEnglish[preset]),()=>{this.paperDraft.paperPreset=preset;this.paperInvalidColor=false;this.paperHex.value=this.paperDraft.paperColor;this.paperStatus.setText('');this.paperSync();},'ts-paper-swatch');button.style.setProperty('--ts-paper-swatch-color',item.color);button.setAttribute('data-paper-preset',preset);const chip=button.createSpan('ts-paper-swatch-chip');button.prepend(chip);this.paperSwatches.set(preset,button);}
  const custom=controls.createDiv('ts-paper-custom-row');this.paperCustom=this.paperButton(custom,t('自定义纸色','Custom color'),()=>{this.paperDraft.paperPreset='custom';this.paperSync();},'ts-paper-custom-label');this.paperPicker=custom.createEl('input',{type:'color',attr:{'aria-label':t('选择自定义纸张颜色','Choose a custom paper color')}});this.paperHex=custom.createEl('input',{type:'text',attr:{'aria-label':t('自定义纸色十六进制代码','Custom paper color hex code'),placeholder:'#f3e9d4',maxlength:'7',spellcheck:'false'}});
  this.paperPicker.oninput=()=>{if(this.paperClosed||this.paperBusy)return;this.paperDraft.paperColor=this.paperPicker.value.toLowerCase();this.paperDraft.paperPreset='custom';this.paperHex.value=this.paperDraft.paperColor;this.paperInvalidColor=false;this.paperStatus.setText('');this.paperSync();};
  this.paperHex.oninput=()=>{if(this.paperClosed||this.paperBusy)return;const value=this.paperHex.value.trim().toLowerCase();this.paperInvalidColor=!/^#[0-9a-f]{6}$/.test(value);if(!this.paperInvalidColor){this.paperDraft.paperColor=value;this.paperDraft.paperPreset='custom';this.paperStatus.setText('');}else this.paperStatus.setText(t('请填写完整的颜色代码，例如 #f3e9d4。','Enter a complete color code, such as #f3e9d4.'));this.paperSync();};
  const texture=controls.createDiv('ts-paper-texture-control'),label=texture.createEl('label');label.createSpan({text:t('纹理强度','Texture strength')});this.paperStrength=label.createEl('output',{attr:{'aria-live':'polite'}});this.paperSlider=texture.createEl('input',{type:'range',attr:{min:'0',max:'100',step:'1','aria-label':t('纸张纹理强度','Paper texture strength')}});this.paperSlider.oninput=()=>{if(this.paperClosed||this.paperBusy)return;this.paperDraft.paperTexture=cleanPaperPreferences({...this.paperDraft,paperTexture:Number(this.paperSlider.value)}).paperTexture;this.paperSync();};const limits=texture.createDiv('ts-paper-texture-limits');limits.createSpan({text:t('平滑纯色','Smooth')});limits.createSpan({text:t('明显纸纹','Textured')});
  const scene=body.createDiv('ts-paper-preview-pane');scene.createDiv({cls:'ts-paper-preview-heading',text:t('纸面预览','Paper preview')});this.paperPreview=scene.createDiv({cls:'ts-paper-preview',attr:{'aria-label':t('纸色与纹理预览','Paper color and texture preview')}});const content=this.paperPreview.createDiv('ts-paper-preview-content');content.createSpan({cls:'ts-paper-preview-caption',text:t('灵感手记','Ideas notebook')});content.createEl('h3',{text:t('从一个想法开始','Start with an idea')});content.createEl('p',{text:t('记录眼前的线索，留一点空白给接下来的思考。','Capture a few clues and leave room for the next thought.')});const note=content.createDiv('ts-paper-preview-note');setIcon(note.createSpan(),'sprout');note.createSpan({text:t('让思绪在纸上生长','Let ideas grow on paper')});
  this.paperStatus=this.contentEl.createDiv({cls:'ts-paper-settings-status',attr:{role:'status','aria-live':'polite'}});
  const footer=this.contentEl.createDiv('ts-paper-settings-footer');this.paperReload=this.paperButton(footer,t('载入当前设置','Reload current settings'),()=>this.paperLoad(),'ts-paper-reload');this.paperReload.hidden=true;const cancel=footer.createEl('button',{text:t('取消','Cancel')});cancel.onclick=()=>{if(!this.paperClosed)this.close();};this.paperApply=this.paperButton(footer,t('应用','Apply'),()=>{void this.paperSave();},'mod-cta');
  this.contentEl.onkeydown=event=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey)&&!event.altKey&&!event.shiftKey&&!event.isComposing&&event.keyCode!==229){event.preventDefault();if(!this.paperApply.disabled)void this.paperSave();}};
  this.paperLoad();
 }
 private paperStamp(preferences:PaperPreferences){return paperAppearanceStamp(preferences)+(this.paperHost.stamp?'|'+this.paperHost.stamp():'');}
 private paperLoad(){if(this.paperClosed||this.paperBusy)return;try{this.paperDraft=cleanPaperPreferences(this.paperHost.preferences());this.paperBaseline=this.paperStamp(this.paperDraft);this.paperConflict=false;this.paperLoadFailed=false;this.paperInvalidColor=false;this.paperHex.value=this.paperDraft.paperColor;this.paperStatus.setText('');this.paperSync();}catch(error){this.paperLoadFailed=true;this.paperStatus.setText(String(error).replace(/^Error: /,''));this.paperSync();}}
 private paperSync(){if(this.paperClosed)return;for(const[preset,button]of this.paperSwatches){button.setAttribute('aria-pressed',String(this.paperDraft.paperPreset===preset));button.disabled=this.paperBusy||this.paperLoadFailed;}this.paperCustom.setAttribute('aria-pressed',String(this.paperDraft.paperPreset==='custom'));this.paperCustom.disabled=this.paperPicker.disabled=this.paperHex.disabled=this.paperSlider.disabled=this.paperBusy||this.paperLoadFailed;
  this.paperPicker.value=this.paperDraft.paperColor;this.paperHex.setAttribute('aria-invalid',String(this.paperInvalidColor));this.paperSlider.value=String(this.paperDraft.paperTexture);this.paperStrength.setText(`${this.paperDraft.paperTexture}%`);const color=paperBaseColor(this.paperDraft);this.paperPreview.style.setProperty('--ts-paper-color',color);this.paperPreview.style.setProperty('--ts-paper-texture',String(this.paperDraft.paperTexture/100));this.paperPreview.style.setProperty('--ts-paper-preview-ink',previewInk(color));
  this.paperApply.disabled=this.paperBusy||this.paperInvalidColor||this.paperConflict||this.paperLoadFailed;this.paperApply.setText(this.paperBusy?this.paperText('正在应用…','Applying...'):this.paperText('应用','Apply'));this.paperReload.hidden=!this.paperConflict&&!this.paperLoadFailed;this.paperReload.disabled=this.paperBusy;
 }
 private async paperSave(){if(this.paperClosed||this.paperBusy||this.paperApply.disabled)return;
  try{const current=cleanPaperPreferences(this.paperHost.preferences());if(this.paperStamp(current)!==this.paperBaseline){this.paperConflict=true;this.paperStatus.setText(this.paperText('纸张设置已在其他窗口改变。请载入当前设置后重新调整。','Paper settings changed in another window. Reload current settings before making changes.'));this.paperSync();return;}}
  catch(error){this.paperStatus.setText(String(error).replace(/^Error: /,''));return;}
  const next=cleanPaperPreferences(this.paperDraft),run=this.paperRun;this.paperBusy=true;this.paperStatus.setText(this.paperText('正在保存纸张设置…','Saving paper settings...'));this.paperSync();
  try{await this.paperHost.save(next);if(this.paperClosed||run!==this.paperRun)return;this.paperBusy=false;this.close();}
  catch(error){const message=`${this.paperText('纸张设置保存失败：','Could not save paper settings: ')}${String(error).replace(/^Error: /,'')}`;if(this.paperClosed||run!==this.paperRun){new Notice(message);return;}this.paperBusy=false;this.paperStatus.setText(`${message}${this.paperText('。可以重试。','. You can retry.')}`);this.paperSync();}
 }
 onClose(){this.paperRun++;this.paperClosed=true;this.paperSwatches.clear();this.contentEl.onkeydown=null;this.contentEl.empty();}
}
