import {App,Modal,Notice,TFile,setIcon} from 'obsidian';
import {NoteSelection,selectionNoteTitle,sameNoteSelection} from './selection-note';
import {themeSurface} from './ui-tokens';
import {isWorkspaceFile} from './workspace';
import {resultPage} from './result-page';
import {canEnterReference} from './reference-keys';
import {referenceReading} from './reference-reading';
import {ReferenceReadingModal} from './reference-reading-view';
import {noteFragments,fragmentMatches,NoteFragment,fragmentSearchSelection,steppedIndex} from './note-fragments';
export interface NoteLinkTarget{file:TFile;read:()=>NoteSelection;replace:(expected:NoteSelection,link:string)=>void;}
export type CreateLinkedNote=(name:string,source:TFile)=>Promise<TFile>;
export class SelectionNoteModal extends Modal{
 private reader?:ReferenceReadingModal;
 private notePage=0;private partPage=0;private savedSearch={query:'',page:0,index:0};
 private matches:TFile[]=[];private resultIndex=0;private visiblePaths:string[]=[];private searchEmpty=false;
 private partFile?:TFile;private partPath='';private partText='';private parts:NoteFragment[]=[];private subpath='';private embed=false;
 private original:NoteSelection;private path:string;private query!:HTMLInputElement;private list!:HTMLElement;private error!:HTMLElement;private create!:HTMLButtonElement;private busy=false;private closed=false;private created?:TFile;
 constructor(app:App,private target:NoteLinkTarget,private make:CreateLinkedNote,private done=()=>{}){super(app);this.original=target.read();selectionNoteTitle(this.original);this.path=target.file.path;}
 onOpen(){themeSurface(this.modalEl);this.modalEl.addClass('ts-selection-note');this.titleEl.setText('创建或关联笔记');this.contentEl.createDiv({cls:'ts-selection-note-context',text:`选中文字：${this.original.text.slice(this.original.start,this.original.end)}`});
  const search=this.contentEl.createDiv('ts-selection-note-search');setIcon(search.createSpan(),'search');this.query=search.createEl('input',{type:'search',value:selectionNoteTitle(this.original),attr:{'aria-label':'搜索或命名关联笔记',maxlength:'100'}});this.query.oninput=()=>{this.resultIndex=0;this.notePage=0;this.partPage=0;if(this.partFile){const next=fragmentSearchSelection(this.parts,this.query.value,this.subpath);this.subpath=next.subpath;this.searchEmpty=next.empty;}this.render();};this.query.onkeydown=e=>this.searchKey(e);
  this.list=this.contentEl.createDiv('ts-selection-note-list');this.error=this.contentEl.createDiv({cls:'ts-selection-note-error',attr:{role:'alert'}});const footer=this.contentEl.createDiv('ts-selection-note-footer');footer.createSpan({text:'保留选中文字作为链接名称 · 原生双链与撤销'});this.create=footer.createEl('button',{cls:'mod-cta',text:'创建并关联',attr:{'aria-label':'创建并关联笔记'}});this.create.onclick=()=>void (this.partFile?this.choose(this.partFile,this.subpath,this.embed,this.partText):this.choose());this.query.title='↑ ↓ 选择 · Enter 插入 · Page Up / Down 翻页 · Alt + ← 返回';this.render();this.query.focus();this.query.select();
 }
 private validate(){if(this.closed)throw Error('关联窗口已关闭');if(this.app.vault.getAbstractFileByPath(this.path)!==this.target.file||this.target.file.path!==this.path||!sameNoteSelection(this.original,this.target.read()))throw Error('原笔记或选区已变化，未插入链接；请重新选择');}
 private render(){if(this.closed)return;this.list.classList.toggle('has-fragments',!!this.partFile);if(this.partFile){this.renderParts();return;}this.list.empty();this.create.setText('创建并关联');this.create.setAttribute('aria-label','创建并关联笔记');this.contentEl.querySelector('.ts-selection-note-footer>span')!.setText('保留选中文字作为链接名称 · 原生双链与撤销');const q=this.query.value.trim().toLocaleLowerCase(),words=q.split(/\s+/).filter(Boolean),files=this.app.vault.getMarkdownFiles().filter(isWorkspaceFile).filter(f=>f!==this.target.file),matches=files.filter(f=>words.every(w=>f.path.toLocaleLowerCase().includes(w))).sort((a,b)=>Number(b.basename.toLocaleLowerCase()===q)-Number(a.basename.toLocaleLowerCase()===q)||a.path.localeCompare(b.path,'zh-CN'));
  const page=resultPage(matches,this.notePage,30);this.notePage=page.page;this.matches=page.items;this.resultIndex=Math.max(0,Math.min(this.resultIndex,this.matches.length-1));for(const [index,f] of this.matches.entries()){const row=this.list.createDiv('ts-selection-note-row'+(index===this.resultIndex?' is-active':''));const b=row.createEl('button',{cls:'ts-selection-note-result',attr:{'aria-label':`关联 ${f.path}`}});b.disabled=this.busy;setIcon(b.createSpan(),'file-text');const labels=b.createDiv();labels.createEl('strong',{text:f.basename});labels.createEl('small',{text:f.path});if(f.basename.toLocaleLowerCase()===q)b.createEl('small',{text:'同名'});b.onclick=()=>void this.choose(f);const detail=row.createEl('button',{cls:'ts-selection-note-detail',attr:{'aria-label':`选择 ${f.basename} 中的标题或块`}});setIcon(detail,'text-select');detail.disabled=this.busy;detail.onclick=()=>void this.openParts(f);}
  if(!matches.length)this.list.createDiv({cls:'ts-selection-note-empty',text:'没有匹配笔记，可以用下面的按钮创建。'});this.renderPager(page,step=>{this.notePage+=step;this.resultIndex=0;this.render();this.query.focus({preventScroll:true});});
  const same=files.some(f=>f.basename.toLocaleLowerCase()===q);this.create.disabled=this.busy||!!this.created||!q||same;this.create.title=this.created?'已创建笔记，请从上方列表关联':same?'已有同名笔记，请从列表选择或换一个名称':'';this.query.disabled=this.busy;
 }
 private renderPager(page:{page:number;pages:number;total:number},move:(step:number)=>void){if(page.pages<=1)return;const nav=this.list.createDiv({cls:'ts-reference-pages',attr:{'aria-label':'引用结果分页'}});for(const [step,label,icon] of [[-1,'上一页','chevron-left'],[1,'下一页','chevron-right']] as const){if(step===1)nav.createSpan({text:`${page.page+1} / ${page.pages} · ${page.total} 项`});const b=nav.createEl('button',{attr:{'aria-label':label,title:label}});setIcon(b,icon);b.disabled=this.busy||(step<0?page.page===0:page.page===page.pages-1);b.onclick=()=>move(step);}}
 private searchKey(e:KeyboardEvent){if(e.isComposing||e.keyCode===229||this.busy||this.closed)return;
  if(e.altKey&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&e.key==='ArrowLeft'&&this.partFile){e.preventDefault();this.list.querySelector<HTMLButtonElement>('[aria-label="返回笔记搜索"]')?.click();return;}
  if(e.ctrlKey||e.metaKey||e.altKey||e.shiftKey)return;
  if(e.key==='PageDown'||e.key==='PageUp'){const button=this.list.querySelector<HTMLButtonElement>(`[aria-label="${e.key==='PageDown'?'下一页':'上一页'}"]`);if(button){e.preventDefault();if(!button.disabled)button.click();}return;}
  if(!['ArrowDown','ArrowUp','ArrowRight','Enter'].includes(e.key))return;
  if(e.key==='ArrowRight'){if(this.partFile||!canEnterReference(this.query.value,this.query.selectionStart,this.query.selectionEnd))return;const file=this.matches[this.resultIndex];if(file){e.preventDefault();void this.openParts(file);}return;}
  e.preventDefault();if(e.key==='Enter'){if(this.partFile){if(!this.create.disabled)this.create.click();}else{const file=this.matches[this.resultIndex];if(file)void this.choose(file);else if(!this.create.disabled)this.create.click();}return;}
  const delta=e.key==='ArrowDown'?1:-1;if(this.partFile){const index=steppedIndex(this.visiblePaths.indexOf(this.subpath),this.visiblePaths.length,delta);if(index>=0)this.subpath=this.visiblePaths[index];}else{this.resultIndex=steppedIndex(this.resultIndex,this.matches.length,delta);this.list.querySelectorAll('.ts-selection-note-row').forEach((row,i)=>row.classList.toggle('is-active',i===this.resultIndex));}if(this.partFile)this.updateFragmentChoice();this.list.querySelector(this.partFile?'.ts-fragment-option[aria-pressed=true]':'.ts-selection-note-row.is-active')?.scrollIntoView({block:'nearest'});
 }
 async openParts(file:TFile,refresh=false){if(this.busy||this.closed)return;if(!refresh)this.savedSearch={query:this.query.value,page:this.notePage,index:this.resultIndex};this.busy=true;this.error.empty();this.render();const path=file.path;
  try{if(file.stat.size>2000000)throw Error('笔记较大，请使用原生编辑器选择引用');const text=await this.app.vault.read(file);if(this.closed)return;if(this.app.vault.getAbstractFileByPath(path)!==file||file.path!==path)throw Error('笔记已变化，请重新选择');if(text.length>2000000)throw Error('笔记较大，请使用原生编辑器选择引用');this.partFile=file;this.partPath=path;this.partText=text;this.parts=noteFragments(text,this.app.metadataCache.getFileCache(file));if(!refresh){this.partPage=0;this.subpath='';this.embed=false;this.query.value='';this.searchEmpty=false;}else{this.searchEmpty=!!this.query.value.trim()&&!this.parts.some(p=>fragmentMatches(p,this.query.value));if(this.subpath&&!this.parts.some(p=>p.subpath===this.subpath))this.error.setText('原引用位置已移除，请重新选择标题或块');else{const next=fragmentSearchSelection(this.parts,this.query.value,this.subpath);this.subpath=next.subpath;this.searchEmpty=next.empty;}}this.query.placeholder='搜索标题或块内容';}
  catch(e){if(!this.closed)this.error.setText(String(e));}finally{this.busy=false;if(!this.closed){this.render();this.query.focus({preventScroll:true});}}
 }
 private renderParts(){this.list.empty();this.query.disabled=this.busy;this.create.disabled=this.busy||this.searchEmpty||!!this.subpath&&!this.parts.some(p=>p.subpath===this.subpath);this.create.title='';this.create.setText(this.embed?'嵌入正文':'插入链接');this.create.setAttribute('aria-label',this.embed?'嵌入所选正文':'插入所选位置链接');this.contentEl.querySelector('.ts-selection-note-footer>span')!.setText(this.embed?'用原生嵌入替换选区，内容随原笔记更新':'保留选中文字作为链接名称 · 原生双链与撤销');
  const header=this.list.createDiv('ts-fragment-header'),back=header.createEl('button',{text:'返回笔记',attr:{'aria-label':'返回笔记搜索'}});back.disabled=this.busy;back.onclick=()=>{this.partFile=undefined;this.partText='';this.parts=[];this.searchEmpty=false;this.query.value=this.savedSearch.query;this.notePage=this.savedSearch.page;this.resultIndex=this.savedSearch.index;this.query.placeholder='';this.error.empty();this.render();this.query.focus({preventScroll:true});this.list.querySelector('.is-active')?.scrollIntoView({block:'nearest'});};header.createEl('strong',{text:this.partFile!.basename});const refresh=header.createEl('button',{cls:'ts-fragment-refresh',attr:{'aria-label':'刷新引用内容',title:'刷新引用内容'}});setIcon(refresh,'refresh-cw');refresh.disabled=this.busy;refresh.onclick=()=>void this.openParts(this.partFile!,true);
  const modes=this.list.createDiv({cls:'ts-fragment-modes',attr:{'aria-label':'引用方式'}});for(const [value,label] of [[false,'链接'],[true,'嵌入正文']] as const){const b=modes.createEl('button',{text:label,attr:{'aria-pressed':String(this.embed===value)}});b.disabled=this.busy;b.onclick=()=>{this.embed=value;this.render();this.list.querySelector<HTMLButtonElement>('.ts-fragment-modes [aria-pressed=true]')?.focus({preventScroll:true});};}
  const rows=this.list.createDiv('ts-fragment-options'),options=[{subpath:'',title:'整篇笔记',kind:'heading' as const,preview:this.partText.slice(0,240)},...this.parts].filter(p=>!p.subpath||fragmentMatches(p,this.query.value));
  const chosenIndex=options.findIndex(p=>p.subpath===this.subpath);if(chosenIndex>=0)this.partPage=Math.floor(chosenIndex/60);const page=resultPage(options,this.partPage,60),shown=page.items;this.partPage=page.page;this.visiblePaths=shown.map(p=>p.subpath);for(const part of shown){const b=rows.createEl('button',{cls:'ts-fragment-option',attr:{'aria-pressed':String(this.subpath===part.subpath)}});b.disabled=this.busy;setIcon(b.createSpan(),part.subpath?(part.kind==='block'?'blocks':'heading'):'file-text');b.createSpan({text:part.title});b.onclick=()=>{this.subpath=part.subpath;this.searchEmpty=false;this.error.empty();this.updateFragmentChoice();};}
  if(!this.parts.length)this.list.createDiv({cls:'ts-selection-note-empty',text:'没有可用的标题或块标识。可引用整篇笔记；在原文段落末尾添加 ^标识 后可引用该段。'});
  else if(options.length===1&&this.query.value.trim())this.list.createDiv({cls:'ts-selection-note-empty',text:'没有匹配的标题或块。'});
  this.renderPager(page,step=>{const next=resultPage(options,this.partPage+step,60);this.partPage=next.page;this.subpath=next.items[0]?.subpath||'';this.searchEmpty=false;this.error.empty();this.render();this.query.focus({preventScroll:true});});
  this.list.createDiv('ts-fragment-preview');this.renderFragmentPreview();
 }
 private updateFragmentChoice(){this.list.querySelectorAll('.ts-fragment-option').forEach((button,index)=>button.setAttribute('aria-pressed',String(this.visiblePaths[index]===this.subpath)));this.create.disabled=this.busy||this.searchEmpty||!!this.subpath&&!this.parts.some(p=>p.subpath===this.subpath);this.renderFragmentPreview();}
 private renderFragmentPreview(){const part=this.parts.find(p=>p.subpath===this.subpath),preview=this.list.querySelector<HTMLElement>('.ts-fragment-preview');if(!preview)return;preview.empty();const read=preview.createEl('button',{cls:'ts-reference-read',attr:{'aria-label':'阅读引用原文',title:'阅读引用原文'}});setIcon(read,'book-open');read.disabled=this.create.disabled;read.onclick=()=>void this.readReference();preview.createEl('small',{text:part?part.title:'整篇笔记'});preview.createEl('p',{text:part?(part.preview||'此标题下暂无正文'):this.partText.slice(0,240)});const link=this.app.fileManager.generateMarkdownLink(this.partFile!,this.path,this.subpath||undefined,this.embed?undefined:this.original.text.slice(this.original.start,this.original.end));preview.createEl('code',{text:(this.embed?'!':'')+link});
 }
 async readReference(){if(this.closed||this.busy||!this.partFile||this.reader?.modalEl.isConnected)return;const file=this.partFile,path=this.partPath,subpath=this.subpath;this.busy=true;this.error.empty();this.render();try{if(file.stat.size>2000000)throw Error('笔记较大，请使用原生编辑器阅读');const raw=await this.app.vault.read(file);if(this.closed)return;if(file.path!==path||this.app.vault.getAbstractFileByPath(path)!==file||raw!==this.partText)throw Error('引用笔记已变化，请先刷新引用内容');const content=referenceReading(raw,this.app.metadataCache.getFileCache(file),subpath);this.reader=new ReferenceReadingModal(this.app,path,content,()=>{this.reader=undefined;if(!this.closed)this.query.focus({preventScroll:true});},async embed=>{const owner=this.reader;if(!await this.choose(file,subpath,embed,raw,()=>!!owner&&this.reader===owner&&owner.modalEl.isConnected))throw Error(this.error.textContent||'引用未插入，请返回重新选择');},this.embed);this.reader.open();}catch(e){if(!this.closed)this.error.setText(e instanceof Error?e.message:String(e));}finally{this.busy=false;if(!this.closed)this.render();}}
 async choose(file?:TFile,subpath='',embed=false,expectedText?:string,stillCurrent=()=>true):Promise<boolean>{if(this.closed||this.busy)return false;this.busy=true;this.error.empty();this.render();let created:TFile|undefined;
  try{this.validate();if(!file){const name=this.query.value.trim();if(!name||name.length>100)throw Error('请输入 1–100 字的笔记名称');if(this.created)throw Error('笔记已经创建，请从结果中选择');if(this.app.vault.getMarkdownFiles().some(f=>f.basename.toLocaleLowerCase()===name.toLocaleLowerCase()))throw Error('已有同名笔记，请从列表选择');created=this.created=await this.make(name,this.target.file);file=created;}
   this.validate();if(expectedText!==undefined){if(file.path!==this.partPath||await this.app.vault.read(file)!==expectedText)throw Error('引用笔记已变化，请返回重新选择段落');if(subpath&&!noteFragments(expectedText,this.app.metadataCache.getFileCache(file)).some(p=>p.subpath===subpath))throw Error('引用位置已变化，请返回重新选择段落');this.validate();}if(file===this.target.file||this.app.vault.getAbstractFileByPath(file.path)!==file)throw Error('关联目标已变化，请重新选择');if(!stillCurrent())throw Error('阅读窗口已关闭，未插入引用');const label=this.original.text.slice(this.original.start,this.original.end),link=this.app.fileManager.generateMarkdownLink(file,this.path,subpath||undefined,embed?undefined:label);this.target.replace(this.original,(embed?'!':'')+link);this.close();new Notice(created?'笔记已创建并关联':'已关联笔记');return true;
  }catch(e){const message=(e instanceof Error?e.message:String(e))+(created?`。新笔记已保留在 ${created.path}`:'');if(this.closed)new Notice(message);else this.error.setText(message);return false;}finally{this.busy=false;if(!this.closed)this.render();}
 }
 onClose(){this.closed=true;this.reader?.close();this.reader=undefined;this.savedSearch={query:'',page:0,index:0};this.matches=[];this.visiblePaths=[];this.parts=[];this.partText='';this.partFile=undefined;this.original={text:'',start:0,end:0};this.contentEl.empty();this.done();}
}
