import {App,Modal,Notice,TFile,setIcon,parseYaml} from 'obsidian';
import {themeSurface} from './ui-tokens';
import {videoSource,yingjianMoments,VideoMoment} from './yingjian';
import {isWorkspaceFile} from './workspace';
export interface YingjianHost {boardTitle?:string;chooseBoard?:(file?:TFile)=>unknown;play:(source:string,time:number,note:TFile)=>Promise<void>;open:(file:TFile)=>Promise<unknown>;addNote?:(file:TFile)=>Promise<unknown>;addMoments?:(file:TFile,raw:string,moments:VideoMoment[])=>Promise<unknown>;}
export class YingjianModal extends Modal {
 private query!:HTMLInputElement;private notes!:HTMLSelectElement;private list!:HTMLElement;private status!:HTMLElement;private error!:HTMLElement;private footer!:HTMLElement;
 private file?:TFile;private path='';private source='';private raw='';private moments:VideoMoment[]=[];private selected=new Set<string>();private closed=false;private loading=false;private busy=false;private generation=0;private limit=40;
 constructor(app:App,private host:YingjianHost,private done:()=>void){super(app);}
 private action(el:HTMLElement,title:string,icon:string,run:()=>unknown,disabled=false){const b=el.createEl('button',{attr:{'aria-label':title,title}});setIcon(b.createSpan(),icon);b.createSpan({text:title});b.disabled=disabled;b.onclick=()=>void this.run(run);return b;}
 private async run(action:()=>unknown){if(this.closed||this.busy||this.loading)return;this.busy=true;this.error.empty();this.render();try{await action();}catch(e){if(!this.closed)this.error.setText(e instanceof Error?e.message:String(e));}finally{this.busy=false;if(!this.closed)this.render();}}
 onOpen(){themeSurface(this.modalEl);this.modalEl.addClass('ts-yingjian');this.titleEl.setText('影笺 · 视频笔记');
  const fields=this.contentEl.createDiv('ts-yingjian-fields');this.notes=fields.createEl('select',{attr:{'aria-label':'选择影笺笔记'}});this.notes.createEl('option',{value:'',text:'选择已保存到本仓库的视频笔记'});
  const files=this.populateNotes();this.notes.onchange=()=>void this.load(this.notes.value);
  this.action(fields,'刷新笔记','refresh-cw',()=>{this.populateNotes();return this.load(this.notes.value);});
  this.query=this.contentEl.createEl('input',{type:'search',attr:{placeholder:'搜索时间或摘录内容…','aria-label':'搜索视频摘录'}});this.query.oninput=()=>{this.limit=40;this.render();};
  this.status=this.contentEl.createDiv({cls:'ts-yingjian-status',attr:{role:'status'}});this.list=this.contentEl.createDiv('ts-yingjian-list');this.error=this.contentEl.createDiv({cls:'ts-yingjian-error',attr:{role:'alert'}});this.footer=this.contentEl.createDiv('ts-yingjian-footer');
  this.contentEl.createDiv({cls:'ts-yingjian-hint',text:'先在影笺选择此 Obsidian 仓库并保存笔记。整篇卡片共用原文；时间点摘录为副本，保留播放器时间链接和笔记来源。'});this.render();if(files.length){this.notes.value=files[0].path;void this.load(files[0].path);}
 }
 private populateNotes(){const path=this.notes.value;this.notes.empty();this.notes.createEl('option',{value:'',text:'选择已保存到本仓库的视频笔记'});const files=this.app.vault.getMarkdownFiles().filter(isWorkspaceFile).filter(f=>{const m=this.app.metadataCache.getFileCache(f)?.frontmatter;return m&&videoSource(m.source)&&(m['video-note-id']||[m.tags].flat().some(t=>t==='影笺'));}).sort((a,b)=>b.stat.mtime-a.stat.mtime);for(const f of files)this.notes.createEl('option',{value:f.path,text:f.path});this.notes.value=files.some(f=>f.path===path)?path:files[0]?.path||'';return files;}
 async selectNote(path:string){if(this.closed||this.busy)throw Error('正在处理当前摘录，请稍后再打开笔记');this.populateNotes();await this.load(path);if(this.file?.path===path){if(!Array.from(this.notes.options).some(o=>o.value===path))this.notes.createEl('option',{value:path,text:path});this.notes.value=path;}}

 async load(path:string){if(this.closed)return;const generation=++this.generation;this.loading=true;this.selected.clear();this.file=undefined;this.raw='';this.moments=[];this.error.empty();this.render();try{if(!path)return;const file=this.app.vault.getAbstractFileByPath(path);if(!(file instanceof TFile)||file.extension!=='md'||!isWorkspaceFile(file))throw Error('视频笔记已移动或删除');if(file.stat.size>2000000)throw Error('笔记过大，请先在原笔记中选择章节');const raw=await this.app.vault.read(file);if(this.closed||generation!==this.generation)return;const header=/^---\r?\n([\s\S]*?)\r?\n(?:---|\.\.\.)(?:\r?\n|$)/.exec(raw),meta=header?parseYaml(header[1]):undefined,source=videoSource(meta?.source);if(!source||!(meta?.['video-note-id']||[meta?.tags].flat().includes('影笺'))||file.path!==path)throw Error('视频来源已变化，请重新选择');const parsed=yingjianMoments(raw,source);this.file=file;this.path=path;this.source=source;this.raw=raw;this.moments=parsed.moments;this.limit=40;if(parsed.truncated)this.error.setText('当前只展示前 500 个时间点，请分章节处理。');}catch(e){if(!this.closed&&generation===this.generation)this.error.setText(e instanceof Error?e.message:String(e));}finally{if(generation===this.generation){this.loading=false;if(!this.closed)this.render();}}}
 private async validate(){const file=this.file,path=this.path;if(this.closed||!file||file.path!==path||this.app.vault.getAbstractFileByPath(path)!==file)throw Error('来源笔记已变化，请刷新');const raw=await this.app.vault.read(file);if(this.closed||this.file!==file||file.path!==path||this.app.vault.getAbstractFileByPath(path)!==file||raw!==this.raw)throw Error('来源内容已变化，请刷新后重新选择');return file;}
 private render(){if(this.closed)return;this.notes.disabled=this.loading||this.busy;this.query.disabled=this.loading||this.busy;this.list.empty();this.footer.empty();const query=this.query.value.trim().toLocaleLowerCase(),visible=this.moments.filter(m=>!query||`${m.label}\n${m.fragment.body}`.toLocaleLowerCase().includes(query));this.status.setText(this.loading?'正在读取视频笔记…':`${visible.length} 个时间点 · 已选 ${this.selected.size} 项${this.host.boardTitle?' · '+this.host.boardTitle:' · 先打开白板可导入摘录'}`);
  if(!this.file&&!this.loading)this.list.createDiv({cls:'ts-yingjian-empty',text:'未选择可用视频笔记。请确认影笺已保存到同一仓库。'});
  if(this.file&&!visible.length)this.list.createDiv({cls:'ts-yingjian-empty',text:'没有匹配的时间点。仍可打开视频或加入整篇笔记。'});
  for(const m of visible.slice(0,this.limit)){const row=this.list.createDiv('ts-yingjian-row'),label=row.createEl('label'),check=label.createEl('input',{type:'checkbox',attr:{'aria-label':`选择 ${m.label} 第 ${m.fragment.start} 行`}});check.checked=this.selected.has(m.id);check.disabled=this.busy||this.loading;check.onchange=()=>{if(check.checked){if(this.selected.size>=50){check.checked=false;new Notice('一次最多选择 50 个时间点');return;}this.selected.add(m.id);}else this.selected.delete(m.id);this.render();};label.createEl('strong',{text:m.label});row.createDiv({cls:'ts-yingjian-preview',text:m.fragment.body.replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/\^video-t-[\w-]+/g,'').slice(0,400)});
   this.action(row,'回看此处','play',async()=>{const file=await this.validate();await this.host.play(this.source,m.time,file);},this.busy||this.loading);
  }
  if(visible.length>this.limit)this.action(this.list,'显示更多时间点','chevron-down',()=>{this.limit+=40;});
  this.action(this.footer,'选中当前结果','list-checks',()=>{this.selected=new Set(visible.slice(0,50).map(m=>m.id));},!visible.length||this.busy||this.loading);this.action(this.footer,'清空选择','x',()=>this.selected.clear(),!this.selected.size||this.busy||this.loading);
  if(this.host.chooseBoard)this.action(this.footer,'选择接收白板','panels-top-left',async()=>{const file=this.file?await this.validate():undefined;this.host.chooseBoard?.(file);},this.busy||this.loading);
  this.action(this.footer,'打开笔记','file-text',async()=>this.host.open(await this.validate()),!this.file||this.busy||this.loading);this.action(this.footer,'打开视频','clapperboard',async()=>{const file=await this.validate();await this.host.play(this.source,0,file);},!this.file||this.busy||this.loading);
  this.action(this.footer,'整篇加入白板','file-plus',async()=>{const count=await this.host.addNote?.(await this.validate());new Notice(count===0?'白板已有此笔记，无需重复添加':'视频笔记已加入白板，原文共用');},!this.file||!this.host.addNote||this.busy||this.loading);
  this.action(this.footer,'摘录加入白板','plus',async()=>{const file=await this.validate();await this.host.addMoments?.(file,this.raw,this.moments.filter(m=>this.selected.has(m.id)));this.selected.clear();new Notice('视频摘录已加入白板，可撤销');},!this.file||!this.selected.size||!this.host.addMoments||this.busy||this.loading).addClass('mod-cta');
 }
 onClose(){this.closed=true;this.generation++;this.raw='';this.file=undefined;this.moments=[];this.selected.clear();this.contentEl.empty();this.done();}
}
