const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.connectOverCDP('http://127.0.0.1:9237'),p=browser.contexts()[0].pages().find(p=>p.url()==='app://obsidian.md/index.html');assert.equal(await p.evaluate(()=>app.vault.adapter.basePath),path.resolve('../thoughtspace-qa-vault'));
 const out='dist/experience-native';fs.mkdirSync(out,{recursive:true});const results={checks:[],screenshots:[],ports:[]};const check=(name,value)=>{assert.ok(value,name);results.checks.push(name);console.log('PASS',name);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));};
 const fixture=await p.evaluate(async()=>{
  for(const leaf of app.workspace.getLeavesOfType('thoughtspace-board'))await leaf.detach();for(const type of ['thoughtspace-media-player','thoughtspace-online-player'])for(const leaf of app.workspace.getLeavesOfType(type))await leaf.detach();
  require('@electron/remote').getCurrentWindow().setSize(1440,900);app.workspace.leftSplit.collapse();app.workspace.rightSplit.collapse();
  const stamp=Date.now(),media=`media/体验 测试 + ${stamp}.mp4`,note=`qa-experience-${stamp}.md`,board=`qa-experience-${stamp}.thoughtspace`;await app.vault.createBinary(media,await app.vault.adapter.readBinary('media/fixture.mp4'));await app.vault.create(note,'# 原笔记\n\n只用于临时库测试。');
  const nodes=['a','b','c'].map((id,i)=>({id,kind:'text',text:`研究 ${id}`,x:i===2?1100:180+i*340,y:180,width:240,height:140,color:'slate',autoSize:false}));nodes.push({id:'player',kind:'video',file:media,x:180,y:750,width:400,height:300,color:'slate'});const f=await app.vault.create(board,JSON.stringify({version:3,nodes,edges:[],viewport:{x:0,y:0,zoom:1}}));await app.plugins.plugins.thoughtspace.openBoard(f);window.experience=app.workspace.getLeavesOfType('thoughtspace-board').find(l=>l.view.file?.path===board&&l.view.session).view;window.experienceOriginalGuides=app.plugins.plugins.thoughtspace.settings.alignmentGuides;app.plugins.plugins.thoughtspace.settings.alignmentGuides=true;return{media,note,board};
 });fs.writeFileSync(path.join(out,'fixture.json'),JSON.stringify(fixture,null,2));
 const shot=async name=>{const file=path.join(out,name);await p.locator('.ts-stage').screenshot({path:file});results.screenshots.push(file);};
 try{
  await p.evaluate(()=>{experience.findOnBoard();});const input=p.getByRole('searchbox',{name:'搜索白板内容',exact:true});await input.fill('研究');await p.waitForTimeout(160);await input.press('ArrowDown');await input.press('Enter');await p.waitForTimeout(160);check('search closes on locate',await input.count()===0);await p.evaluate(()=>{experience.findOnBoard();});check('search query restored',await input.inputValue()==='研究');check('search selected result restored',await p.locator('.ts-board-search-row.is-active').getAttribute('data-search-node')==='b');await p.keyboard.press('Escape');
  for(const zoom of [.25,.5,1]){
   await p.evaluate(zoom=>{experience.session.board.viewport={x:200,y:80,zoom};experience.selected=new Set(['a']);experience.renderBoard();experience.updateSelection();},zoom);await p.waitForTimeout(100);
   const port=p.locator('[data-id="a"] .ts-connect-port[data-side="right"]'),geometry=await port.evaluate((el,zoom)=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{zoom,width:r.width,height:r.height,hit:hit===el||el.contains(hit)};},zoom);results.ports.push(geometry);check(`port 30 screen pixels and hit at ${zoom}`,Math.abs(geometry.width-30)<.1&&geometry.hit);
   await port.focus();check(`port keyboard focus at ${zoom}`,await port.evaluate(el=>document.activeElement===el));
  }
  await p.evaluate(()=>{experience.session.board.viewport={x:0,y:0,zoom:1};experience.selected.clear();experience.renderBoard();});await p.waitForTimeout(150);
  for(const notice of await p.locator('.notice').all())await notice.click({position:{x:8,y:8},timeout:1000}).catch(()=>{});const c=await p.locator('[data-id="c"]').boundingBox();await p.mouse.move(c.x+120,c.y+90);await p.mouse.down();await p.mouse.move(c.x+120-245,c.y+90,{steps:10});await p.waitForTimeout(100);
  const gaps=await p.locator('.ts-alignment-guide[data-spacing]:not([data-spacing=""])').evaluateAll(els=>els.map(e=>e.dataset.spacing));check('drag exposes two equal gap labels',gaps.length===2&&gaps.every(g=>'100'===g));await shot('equal-spacing.png');await p.mouse.up();await p.waitForTimeout(180);check('equal gap landing committed',await p.evaluate(()=>experience.session.board.nodes.find(n=>n.id==='c').x===860));await p.evaluate(()=>experience.session.undo());check('spacing undo restores original geometry',await p.evaluate(()=>experience.session.board.nodes.find(n=>n.id==='c').x===1100));await p.evaluate(()=>experience.session.undo(true));
  const drop=async alt=>{await p.evaluate(()=>{experience.session.board.viewport={x:0,y:0,zoom:1};experience.selected=new Set(['a']);experience.renderBoard();experience.updateSelection();});const box=await p.locator('[data-id="a"] .ts-connect-port[data-side="right"]').boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();const extra=await p.evaluate(()=>experience.session.board.nodes.length>4?450:0);await p.mouse.move(box.x+220+extra,box.y+310,{steps:10});if(alt)await p.keyboard.down('Alt');await p.mouse.up();if(alt)await p.keyboard.up('Alt');await p.waitForTimeout(120);};
  const before=await p.evaluate(()=>({nodes:experience.session.board.nodes.length,edges:experience.session.board.edges.length}));await drop(true);check('Alt drop opens content type menu',await p.locator('.menu-item-title').filter({hasText:'关联已有笔记或 PDF'}).count()===1);await shot('connection-type-menu.png');await p.keyboard.press('Escape');check('menu cancel leaves no orphan',await p.evaluate(before=>experience.session.board.nodes.length===before.nodes&&experience.session.board.edges.length===before.edges,before));
  await drop(true);await p.locator('.menu-item-title').filter({hasText:'关联已有笔记或 PDF'}).click();await p.waitForTimeout(100);await p.keyboard.press('Escape');check('file picker cancel leaves no orphan',await p.evaluate(before=>experience.session.board.nodes.length===before.nodes&&experience.session.board.edges.length===before.edges,before));
  await drop(true);await p.locator('.menu-item-title').filter({hasText:'添加表格'}).click();await p.waitForFunction(()=>!!experience.inline);check('table choice creates one linked editable text',await p.evaluate(before=>experience.session.board.nodes.length===before.nodes+1&&experience.session.board.edges.length===before.edges+1&&/\|\s*项目\s*\|/.test(experience.inline.value),before));await p.keyboard.press('Escape');
  await drop(false);await p.waitForFunction(()=>!!experience.inline);check('ordinary drop retains immediate text editor',await p.evaluate(()=>experience.inline.value===''));await p.keyboard.press('Escape');
  await p.evaluate(({media,board})=>{const href='obsidian://thoughtspace-player?'+new URLSearchParams({vault:app.vault.getName(),file:media,t:'0.125'});experience.session.change(b=>{b.nodes.push({id:'excerpt',kind:'text',text:'一致的时间戳\n\n[0:00]('+href+')',x:690,y:750,width:340,height:200,color:'slate',autoSize:false});b.edges.push({id:'source-edge',from:'player',to:'excerpt',label:''});});experience.session.board.viewport={x:-100,y:-570,zoom:1};experience.renderBoard();},fixture);await p.waitForFunction(()=>experience.positions.get('excerpt')?.querySelector('.ts-media-reference-time'));
  await p.locator('[data-id="excerpt"] .ts-media-reference-time').click();await p.waitForFunction(()=>Math.abs(experience.mediaPlayers.get('player')?.getState().time-.125)<.01);check('unloaded player retains exact seek without autoplay',await p.evaluate(()=>!experience.positions.get('player').querySelector('video')||experience.positions.get('player').querySelector('video').paused));await p.evaluate(()=>experience.mediaPlayers.get('player').play());await p.waitForFunction(()=>experience.positions.get('player')?.querySelector('video')?.readyState>=1);await p.evaluate(()=>experience.mediaPlayers.get('player').pause());
  for(const time of [0,.5,999]){await p.evaluate(async({media,time})=>{await app.plugins.plugins.thoughtspace.openBoardMediaTimestamp('obsidian://thoughtspace-player?'+new URLSearchParams({vault:app.vault.getName(),file:media,t:String(time)}),experience,'excerpt');},{media:fixture.media,time});check(`board pending seek ${time} preserves time and stays suspended`,await p.evaluate(time=>{const v=experience.positions.get('player').querySelector('video');return (!v||v.paused)&&experience.mediaPlayers.get('player').getState().time===time;},time));await p.evaluate(()=>experience.mediaPlayers.get('player').play());await p.waitForFunction(()=>experience.positions.get('player')?.querySelector('video')?.readyState>=1);check(`explicit playback ${time} remains within duration`,await p.evaluate(time=>{const v=experience.positions.get('player').querySelector('video');v.pause();return v.currentTime>=0&&v.currentTime<=v.duration&&(time>v.duration||Math.abs(v.currentTime-time)<.2);},time));}
  await p.evaluate(()=>{experience.session.change(b=>{b.nodes=b.nodes.filter(n=>n.id!=='player');b.edges=b.edges.filter(e=>e.from!=='player'&&e.to!=='player');});});
  for(let i=0;i<2;i++)await p.evaluate(async media=>{await app.plugins.plugins.thoughtspace.openBoardMediaTimestamp('obsidian://thoughtspace-player?'+new URLSearchParams({vault:app.vault.getName(),file:media,t:'0.5'}),experience,'excerpt');},fixture.media);
  check('missing board player reuses one standalone workspace on repeated clicks',await p.evaluate(()=>app.workspace.getLeavesOfType('thoughtspace-media-player').length===1));
  const draft=p.getByRole('textbox',{name:'摘录 Markdown 正文',exact:true});await draft.fill('QA route draft must survive');
  const protectedResult=await p.evaluate(async()=>{const view=app.workspace.getLeavesOfType('thoughtspace-media-player')[0].view,before=view.currentFile();await app.plugins.plugins.thoughtspace.openBoardMediaTimestamp('obsidian://thoughtspace-player?'+new URLSearchParams({vault:app.vault.getName(),file:'media/fixture.mp4',t:'0'}),experience);return view.currentFile()===before;});check('fallback respects existing draft on source change',protectedResult&&await draft.inputValue()==='QA route draft must survive');
 }finally{await p.evaluate(()=>{app.plugins.plugins.thoughtspace.settings.alignmentGuides=experienceOriginalGuides;});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
